### ISSUE TITLE
催更~~~~~~~~~

### ISSUE THREAD

**Issue by starstarman** [zjunlp/deepke#10]

**Comment by yuwl798180** [comment]
这几天会上线新的版本，将会把可复用的nlp模块单独抽取出来。
同时会添加下三元组直接抽取的功能。

稍等哈

**Comment by starstarman** [comment]
前辈，我看预测的数据集里没有realtion小弟很迷茫，求指点



------------------ 原始邮件 ------------------
发件人: "yuwl798180"<notifications@github.com>; 
发送时间: 2019年10月11日(星期五) 晚上9:05
收件人: "zjunlp/deepke"<deepke@noreply.github.com>; 
抄送: "阔"<83170989@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zjunlp/deepke] 催更~~~~~~~~~ (#10)




这几天会上线新的版本，将会把可复用的nlp模块单独抽取出来。
 同时会添加下三元组直接抽取的功能。
 
稍等哈

**Comment by yuwl798180** [comment]
你好，relation文件有的呀，在data文件夹里面

**Comment by starstarman** [comment]
嗯~ o(*￣▽￣*)o，是生成的predict.csv里面
这个文件是不是应该有关系






------------------ 原始邮件 ------------------
发件人: "yuwl798180"<notifications@github.com>; 
发送时间: 2019年10月16日(星期三) 下午2:03
收件人: "zjunlp/deepke"<deepke@noreply.github.com>; 
抄送: "阔"<83170989@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zjunlp/deepke] 催更~~~~~~~~~ (#10)




你好，relation文件有的呀，在data文件夹里面

**Comment by yuwl798180** [comment]
嗯嗯，这个是用来做predict来预测关系是什么的数据，应该也是有relation的。

之所以没有，是因为那几条数据是我自己写的，想看下能预测成什么relation

**Comment by starstarman** [comment]
大佬，还有个问题需要请教一下，用预训练模型的话，大概需要迭代多少次，目前是13次用了4个小时，我看指标很高，还用迭代到程序停止吗？

**Comment by yuwl798180** [comment]
你好，现在迭代停止大多是使用早停的方式，即指标不再提升或者提升不明显时就停止迭代，此时泛化性能会更好些。

**Comment by starstarman** [comment]
好的谢谢


------------------ 原始邮件 ------------------
发件人: "yuwl798180"<notifications@github.com>;
发送时间: 2019年10月20日(星期天) 晚上9:23
收件人: "zjunlp/deepke"<deepke@noreply.github.com>;
抄送: "阔"<83170989@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zjunlp/deepke] 催更~~~~~~~~~ (#10)




你好，现在迭代停止大多是使用早停的方式，即指标不再提升或者提升不明显时就停止迭代，此时泛化性能会更好些。
