### ISSUE TITLE
做样本分析的输出端口

### ISSUE THREAD

**Issue by lelechallc** [zjunlp/DeepKE#101]
**Describe the question**
> A clear and concise description of what the question is.
请问我在使用re\standard中cnn做re任务时，想要做样本分析（badcase分析）的话，样本关系抽取预测的输出端口在哪里呢？

**Comment by tlk1997** [comment]
可在这https://github.com/zjunlp/DeepKE/blob/main/src/deepke/relation_extraction/standard/tools/trainer.py 添加相关代码

**Comment by zxlzr** [comment]
> 

您可以根据https://github.com/zjunlp/DeepKE/blob/main/src/deepke/relation_extraction/standard/tools/trainer.py  中的输入输出debug或者log 输出x y查看case
