### ISSUE TITLE
样本输出端口

### ISSUE THREAD

**Issue by lelechallc** [zjunlp/DeepKE#102]
**Describe the question**
[请问还是上一个问题，]https://github.com/zjunlp/DeepKE/issues/101
我在本地文件中修改
https://github.com/zjunlp/DeepKE/blob/main/src/deepke/relation_extraction/standard/tools/trainer.py的相应代码对run.py的输出没有影响，是不是因为run.py文件import的deepke库是pip导入所导致的，如果是这样的话，想看样本预测值的话有什么方法呢？

非常感谢博主的耐心解答！！

**Comment by tlk1997** [comment]
如果要修改后使用代码，不能使用pip包倒入。可换成python setup.py install方式导入
