### ISSUE TITLE
Where is the long-tailed RE models?

### ISSUE THREAD

**Issue by jc-ryan** [zjunlp/DeepKE#106]
**Describe the question**
> A clear and concise description of what the question is.
Excuse me, where is the code of paper _The Devil is the Classifier: Investigating Long Tail Relation Classification with Decoupling Analysis_?

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
Hi, the code is in the old version of DeepKE (https://github.com/zjunlp/DeepKE/tree/deepke-v1.0) and the developer have graduated. In this version the code is organized. You can find some 
legacy code in  the loss.py  in https://github.com/zjunlp/DeepKE/blob/main/src/deepke/relation_extraction/standard/tools/loss.py
