### ISSUE TITLE
windows10  python由3.8降级到3.6

### ISSUE THREAD

**Issue by liuxiaobei727** [zjunlp/DeepKE#108]
**Describe the bug**
> A clear and concise description of what the bug is.

各种bug,我刚开始创建了一个虚拟环境deepke，然后pip install deepke ，但是各种报错，我想问一下是不是windows下不行吖？有没有windows下的详细安装教程提供一下

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

windows   python3.6 

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by tlk1997** [comment]
python3.6下没测试过，但你可以试试通过python setup.py install的方式安装

**Comment by liuxiaobei727** [comment]
> 

python3.8 windows的环境下是可以实现的吧？

**Comment by tlk1997** [comment]
是的

**Comment by liuxiaobei727** [comment]
> 

我在windows新建了一个python3.8的环境，然后pip install deepke,这是系统给我报的错， from urllib3.util.ssl_ import (
ImportError: cannot import name 'ssl' from 'urllib3.util.ssl_' (D:\python\Anaconda\envs\deepke\lib\site-packages\urllib3\util\ssl_.py)
求解决
![image](https://user-images.githubusercontent.com/76939632/164888989-0571ff22-8b3d-4c05-a035-ab5114cbace2.png)

**Comment by tlk1997** [comment]
你可以试试通过python setup.py install的方式安装

**Comment by liuxiaobei727** [comment]
windows环境下这个在哪安装？在哪输入命令吖？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月23日(星期六) 下午5:40
收件人: ***@***.***&gt;; 
抄送: "电子信息工程 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zjunlp/DeepKE] windows10  python由3.8降级到3.6 (Issue #108)





 
你可以试试通过python setup.py install的方式安装

**Comment by tlk1997** [comment]
看一下readme，里面有详细介绍，

**Comment by QiaoShuofei** [comment]
windows下可以试试Anaconda提供的Prompt命令行窗口，在里面激活虚拟环境，进入setup.py的目录执行指令

**Comment by liuxiaobei727** [comment]
> windows下可以试试Anaconda提供的Prompt命令行窗口，在里面激活虚拟环境，进入 setup.py 的目录执行指令
在setup.py下试了一下还是不行，我还重新把环境删了，又重新建的python3.8的deepke的环境，然后执行的此命令，还是报错，
![image](https://user-images.githubusercontent.com/76939632/164890039-8f559374-ab3c-4883-81e7-fb702b03df8d.png)
望解决，非常感谢

**Comment by QiaoShuofei** [comment]
能否看一下您具体报错的代码

**Comment by QiaoShuofei** [comment]
> > windows下可以试试Anaconda提供的Prompt命令行窗口，在里面激活虚拟环境，进入 setup.py 的目录执行指令
> > 在setup.py下试了一下还是不行，我还重新把环境删了，又重新建的python3.8的deepke的环境，然后执行的此命令，还是报错，
> > ![image](https://user-images.githubusercontent.com/76939632/164890039-8f559374-ab3c-4883-81e7-fb702b03df8d.png)
> > 望解决，非常感谢

能否看一下您具体报错的代码和报错的完整信息

**Comment by liuxiaobei727** [comment]
D:\python\Anaconda\envs\deepke\python.exe D:/知识图谱/DeepKE-main/example/re/standard/run.py
wandb: WARNING W&amp;B installed but not logged in.&nbsp; Run `wandb login` or set the WANDB_API_KEY env variable.
04/23/2022 18:19:44 - INFO - deepke.relation_extraction.multimodal.models.clip.file_utils -&nbsp; &nbsp;PyTorch version 1.10.0 available.
Traceback (most recent call last):
&nbsp; File "D:/知识图谱/DeepKE-main/example/re/standard/run.py", line 14, in <module&gt;
&nbsp; &nbsp; import deepke.relation_extraction.standard.models as models
&nbsp; File "d:\知识图谱\deepke-main\src\deepke\__init__.py", line 3, in <module&gt;
&nbsp; &nbsp; from .name_entity_re import *
&nbsp; File "d:\知识图谱\deepke-main\src\deepke\name_entity_re\__init__.py", line 1, in <module&gt;
&nbsp; &nbsp; from .standard import *
&nbsp; File "d:\知识图谱\deepke-main\src\deepke\name_entity_re\standard\__init__.py", line 1, in <module&gt;
&nbsp; &nbsp; from .models import *
&nbsp; File "d:\知识图谱\deepke-main\src\deepke\name_entity_re\standard\models\__init__.py", line 1, in <module&gt;
&nbsp; &nbsp; from .InferBert import *
&nbsp; File "d:\知识图谱\deepke-main\src\deepke\name_entity_re\standard\models\InferBert.py", line 8, in <module&gt;
&nbsp; &nbsp; from pytorch_transformers import (BertConfig, BertForTokenClassification,
&nbsp; File "D:\python\Anaconda\envs\deepke\lib\site-packages\pytorch_transformers-1.2.0-py3.8.egg\pytorch_transformers\__init__.py", line 2, in <module&gt;
&nbsp; &nbsp; from .tokenization_auto import AutoTokenizer
&nbsp; File "D:\python\Anaconda\envs\deepke\lib\site-packages\pytorch_transformers-1.2.0-py3.8.egg\pytorch_transformers\tokenization_auto.py", line 21, in <module&gt;
&nbsp; &nbsp; from .tokenization_bert import BertTokenizer
&nbsp; File "D:\python\Anaconda\envs\deepke\lib\site-packages\pytorch_transformers-1.2.0-py3.8.egg\pytorch_transformers\tokenization_bert.py", line 25, in <module&gt;
&nbsp; &nbsp; from .tokenization_utils import PreTrainedTokenizer
&nbsp; File "D:\python\Anaconda\envs\deepke\lib\site-packages\pytorch_transformers-1.2.0-py3.8.egg\pytorch_transformers\tokenization_utils.py", line 26, in <module&gt;
&nbsp; &nbsp; from .file_utils import cached_path
&nbsp; File "D:\python\Anaconda\envs\deepke\lib\site-packages\pytorch_transformers-1.2.0-py3.8.egg\pytorch_transformers\file_utils.py", line 19, in <module&gt;
&nbsp; &nbsp; import boto3
&nbsp; File "D:\python\Anaconda\envs\deepke\lib\site-packages\boto3-1.21.46-py3.8.egg\boto3\__init__.py", line 17, in <module&gt;
&nbsp; &nbsp; from boto3.session import Session
&nbsp; File "D:\python\Anaconda\envs\deepke\lib\site-packages\boto3-1.21.46-py3.8.egg\boto3\session.py", line 17, in <module&gt;
&nbsp; &nbsp; import botocore.session
&nbsp; File "D:\python\Anaconda\envs\deepke\lib\site-packages\botocore-1.24.46-py3.8.egg\botocore\session.py", line 26, in <module&gt;
&nbsp; &nbsp; import botocore.client
&nbsp; File "D:\python\Anaconda\envs\deepke\lib\site-packages\botocore-1.24.46-py3.8.egg\botocore\client.py", line 15, in <module&gt;
&nbsp; &nbsp; from botocore import waiter, xform_name
&nbsp; File "D:\python\Anaconda\envs\deepke\lib\site-packages\botocore-1.24.46-py3.8.egg\botocore\waiter.py", line 18, in <module&gt;
&nbsp; &nbsp; from botocore.docs.docstring import WaiterDocstring
&nbsp; File "D:\python\Anaconda\envs\deepke\lib\site-packages\botocore-1.24.46-py3.8.egg\botocore\docs\__init__.py", line 15, in <module&gt;
&nbsp; &nbsp; from botocore.docs.service import ServiceDocumenter
&nbsp; File "D:\python\Anaconda\envs\deepke\lib\site-packages\botocore-1.24.46-py3.8.egg\botocore\docs\service.py", line 14, in <module&gt;
&nbsp; &nbsp; from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
&nbsp; File "D:\python\Anaconda\envs\deepke\lib\site-packages\botocore-1.24.46-py3.8.egg\botocore\docs\client.py", line 14, in <module&gt;
&nbsp; &nbsp; from botocore.docs.example import ResponseExampleDocumenter
&nbsp; File "D:\python\Anaconda\envs\deepke\lib\site-packages\botocore-1.24.46-py3.8.egg\botocore\docs\example.py", line 13, in <module&gt;
&nbsp; &nbsp; from botocore.docs.shape import ShapeDocumenter
&nbsp; File "D:\python\Anaconda\envs\deepke\lib\site-packages\botocore-1.24.46-py3.8.egg\botocore\docs\shape.py", line 19, in <module&gt;
&nbsp; &nbsp; from botocore.utils import is_json_value_header
&nbsp; File "D:\python\Anaconda\envs\deepke\lib\site-packages\botocore-1.24.46-py3.8.egg\botocore\utils.py", line 34, in <module&gt;
&nbsp; &nbsp; import botocore.httpsession
&nbsp; File "D:\python\Anaconda\envs\deepke\lib\site-packages\botocore-1.24.46-py3.8.egg\botocore\httpsession.py", line 21, in <module&gt;
&nbsp; &nbsp; from urllib3.util.ssl_ import (
ImportError: cannot import name 'ssl' from 'urllib3.util.ssl_' (D:\python\Anaconda\envs\deepke\lib\site-packages\urllib3-1.26.9-py3.8.egg\urllib3\util\ssl_.py)


进程已结束,退出代码1









------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月23日(星期六) 晚上6:19
收件人: ***@***.***&gt;; 
抄送: "电子信息工程 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zjunlp/DeepKE] windows10  python由3.8降级到3.6 (Issue #108)





   
windows下可以试试Anaconda提供的Prompt命令行窗口，在里面激活虚拟环境，进入 setup.py 的目录执行指令
 在setup.py下试了一下还是不行，我还重新把环境删了，又重新建的python3.8的deepke的环境，然后执行的此命令，还是报错，
 
 望解决，非常感谢
   
能否看一下您具体报错的代码和报错的完整信息

**Comment by QiaoShuofei** [comment]
![Snipaste_2022-04-23_18-42-47](https://user-images.githubusercontent.com/60096298/164891238-a70353f3-8180-4e67-87e6-d4823806c0ae.png)
您好，我们亲自尝试了windows10下安装python3.8的deepke虚拟环境，并通过pip install deepke方式安装deepke包，运行您的报错代码import deepke.relation_extraction.standard.models as models后并没有出现错误，请您仔细检查一下自己的环境是否存在问题，如实在不行可选择重装python等方式。
