### ISSUE TITLE
关于few-shot

### ISSUE THREAD

**Issue by Gavingx** [zjunlp/DeepKE#109]
你好，我看文档中，关于ner、re和ae这块，你们做实验都是在英文数据集上做的，请问有在中文上做过么？效果怎么样呀？或者说后续有没有这一块的计划呀？零样本或者少样本在中文上的实验

**Comment by tlk1997** [comment]
你好，关于中文数据集只在常规场景下做了实验，其他场景的话可以自行修改一下代码试一试

**Comment by Gavingx** [comment]
好的，谢谢
