### ISSUE TITLE
胶囊网络碰到一些问题 

### ISSUE THREAD

**Issue by nanciwan** [zjunlp/deepke#11]
你好，想请教一下一个问题：
当我用胶囊网络的时候，我发现损失在不断的下降，但是，精度却在不断的降低？这让我很疑惑。
==========  Start training  ==========
Train Epoch: 1 [640/4000 (16%)]	Loss: 0.808406
Train Epoch: 1 [1280/4000 (32%)]	Loss: 0.807249
Train Epoch: 1 [1920/4000 (48%)]	Loss: 0.805759
Train Epoch: 1 [2560/4000 (63%)]	Loss: 0.803572
Train Epoch: 1 [3200/4000 (79%)]	Loss: 0.800597
Train Epoch: 1 [3840/4000 (95%)]	Loss: 0.796495
Train Epoch: 1 [4000/4000 (100%)]	Loss: 0.795066
 macro metrics: [p: 0.4085, r:0.2570, f1:0.2254]
 micro metrics: [p: 0.2570, r:0.2570, f1:0.2570]
Train Epoch: 2 [640/4000 (16%)]	Loss: 0.789447
Train Epoch: 2 [1280/4000 (32%)]	Loss: 0.782183
Train Epoch: 2 [1920/4000 (48%)]	Loss: 0.773557
Train Epoch: 2 [2560/4000 (63%)]	Loss: 0.762742
Train Epoch: 2 [3200/4000 (79%)]	Loss: 0.750204
Train Epoch: 2 [3840/4000 (95%)]	Loss: 0.735720
Train Epoch: 2 [4000/4000 (100%)]	Loss: 0.731115
 macro metrics: [p: 0.1102, r:0.1210, f1:0.0532]
 micro metrics: [p: 0.1210, r:0.1210, f1:0.1210]
Train Epoch: 3 [640/4000 (16%)]	Loss: 0.714159
Train Epoch: 3 [1280/4000 (32%)]	Loss: 0.695173
Train Epoch: 3 [1920/4000 (48%)]	Loss: 0.674588
Train Epoch: 3 [2560/4000 (63%)]	Loss: 0.652236
Train Epoch: 3 [3200/4000 (79%)]	Loss: 0.628999
Train Epoch: 3 [3840/4000 (95%)]	Loss: 0.607024
Train Epoch: 3 [4000/4000 (100%)]	Loss: 0.601029
 macro metrics: [p: 0.0100, r:0.1000, f1:0.0182]
 micro metrics: [p: 0.1000, r:0.1000, f1:0.1000]
Train Epoch: 4 [640/4000 (16%)]	Loss: 0.581706
Train Epoch: 4 [1280/4000 (32%)]	Loss: 0.566093
Train Epoch: 4 [1920/4000 (48%)]	Loss: 0.553648
Train Epoch: 4 [2560/4000 (63%)]	Loss: 0.543705
Train Epoch: 4 [3200/4000 (79%)]	Loss: 0.536618
这是什么情况呢？

**Comment by yuwl798180** [comment]
你好，这是因为过拟合了。

你跑的是demo里采样数据吧，这个数据量太小了，很容易过拟合。
