### ISSUE TITLE
能不能写一个详细的中文文档啊，只有example的使用远远不够啊，最好能直接封装好接口，直接操作源代码实在太难受了

### ISSUE THREAD

**Issue by sl-w** [zjunlp/DeepKE#111]
**Describe the question**
> A clear and concise description of what the question is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
您好，这里有详细的模块函数介绍https://zjunlp.github.io/DeepKE/deepke.html 您可以查阅文档，接口都是封装好的。我们后续会增加中文的查阅文档。
