### ISSUE TITLE
关于LightNER论文中Prompt-guided Attention部分的疑问

### ISSUE THREAD

**Issue by cjj-sunshine** [zjunlp/DeepKE#113]
请问在LightNER这篇论文中，Prompt-guided Attention部分所采用的思想和p-tuning v2的思想是一样的吗，即在transformer的每一层前面加上soft prompt，冻结预训练语言模型的参数，只训练soft prompt部分的参数，不知道我这样理解对不对，希望能尽快得到您的回复！

**Comment by zxlzr** [comment]
您好，

思想上是一样的，在模型框架（主要面向生成）和任务场景（主要针对序列tagging任务）有略微区别，且在迁移场景soft prompt 可通过source domain 训练得到。我们论文在2021年8月底挂arxiv的略微早与p-tuning v2。

**Comment by cjj-sunshine** [comment]
> 您好，
> 
> 思想上是一样的，在模型框架（主要面向生成）和任务场景（主要针对序列tagging任务）有略微区别，且在迁移场景soft prompt 可通过source domain 训练得到。我们论文在2021年8月底挂arxiv的略微早与p-tuning v2。

好的，谢谢您的回复，我还有一个问题，模型训练的关键是要得到past_key_values，把past_key_values传入bart_encoder，计算attention得分时，是不是对BartEncoder的forward方法进行了修改

**Comment by Flow3rDown** [comment]
> > 您好，
> > 思想上是一样的，在模型框架（主要面向生成）和任务场景（主要针对序列tagging任务）有略微区别，且在迁移场景soft prompt 可通过source domain 训练得到。我们论文在2021年8月底挂arxiv的略微早与p-tuning v2。
> 
> 好的，谢谢您的回复，我还有一个问题，模型训练的关键是要得到past_key_values，把past_key_values传入bart_encoder，计算attention得分时，是不是对BartEncoder的forward方法进行了修改

是的，我们修改了Bart源码以支持past_key_values的使用，具体细节可查看代码。

**Comment by cjj-sunshine** [comment]
非常感谢您的回复！
