### ISSUE TITLE
pos_limit参数

### ISSUE THREAD

**Issue by hihihe** [zjunlp/DeepKE#114]
**Describe the question**
> A clear and concise description of what the question is.

https://github.com/zjunlp/DeepKE/blob/b9654082630361a7559dbd9018150eed7ddc3e7f/example/re/standard/conf/preprocess.yaml#L26
pos_limit参数是不是暂时没使用，没找到调用他的地方

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by tlk1997** [comment]
你好，这个参数的使用在https://github.com/zjunlp/DeepKE/blob/main/src/deepke/relation_extraction/standard/tools/preprocess.py#L42中

**Comment by tlk1997** [comment]
1.0.6
