### ISSUE TITLE
InferBert.py 推理有问题

### ISSUE THREAD

**Issue by kevinuserdd** [zjunlp/DeepKE#115]
InferBert.py最后推理部分有问题？ 不是PER、LOC这三个类别的，输出后处理就报错了

**Comment by tlk1997** [comment]
你好，训练的数据集只训练了这三类，所以无法预测其他类

**Comment by kevinuserdd** [comment]
> 

建议inferBert里面的推理部分写的通用一些，这样写的太死了； 而且文档里提到了开箱即用的模型，又写了很多类型，会让人分不清到底模型里有哪些类别

**Comment by kevinuserdd** [comment]
> 开箱即用的模型可参考https://github.com/zjunlp/DeepKE/blob/main/README_CNSCHEMA_CN.md 中的快速加载部分，并按照这个readme中流程修改代码使用即可进行多类型预测。 如果通过[https://github.com/zjunlp/DeepKE/tree/main/example/ner/standard中](https://github.com/zjunlp/DeepKE/tree/main/example/ner/standard%E4%B8%AD) 120.27.214.45/Data/ner/standard/data.tar.gz 下载的数据集，则只能预测那三类，使用这个数据集进行预测和训练无需修改代码。

懂你的意思，但是开箱即用的模型，按照README里面的方法，修改get_label也不行的；因为预测的时候会走InferBert.py里面的推理函数，那个函数你写的时候就限定了那三个类别； 除非自己还需要修改推理函数的后处理？

**Comment by tlk1997** [comment]
可以git pull最新代码，所给代码只是参考，具体输出可自行修改
