### ISSUE TITLE
ner-multimodal 模型无法训练

### ISSUE THREAD

**Issue by 3525355094** [zjunlp/DeepKE#122]
**Describe the question**
> A clear and concise description of what the question is.
训练时一直出现这样的错误：
OSError: Can't load config for 'openai/clip-vit-base-patch32'. Make sure that:

- 'openai/clip-vit-base-patch32' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'openai/clip-vit-base-patch32' is the correct path to a directory containing a config.json file

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by xxupiano** [comment]
1. 将transformers升级至4.11.3;
2. 下载模型https://huggingface.co/openai/clip-vit-base-patch32并以绝对路径导入的方式使用

**Comment by 3525355094** [comment]
> 1. 将transformers升级至4.11.3;
> 2. 下载模型https://huggingface.co/openai/clip-vit-base-patch32 并以绝对路径导入的方式使用

请问下载后把模型放在哪个文件夹下呢？

**Comment by tlk1997** [comment]
放在哪都行，只需要讲train.yaml中vit_name修改为模型绝对路径即可

**Comment by 3525355094** [comment]
> 放在哪都行，只需要讲train.yaml中vit_name修改为模型绝对路径即可

好的，谢谢，我试一试

**Comment by 3525355094** [comment]
> 放在哪都行，只需要将train.yaml和predict.yaml中vit_name修改为模型绝对路径即可

我已经将模型下载并将路径修改为绝对路径·，但我发现无论怎样修改路径、重启项目，代码的默认路径都是vit_name='[openai/clip-vit-base-patch32](https://huggingface.co/openai/clip-vit-base-patch32)'，都会报最上面的那个错误。

**Comment by GoooDte** [comment]
能否贴一下您具体的报错截图和vit模型文件夹下内容的截图

**Comment by 3525355094** [comment]
文件截图是这样的：
![image](https://user-images.githubusercontent.com/73507088/177981060-a014d596-d778-4427-b41a-fab2ff2ca8a6.png)
刚才那个报错截图没有了，因为我刚刚将train.yaml中的vit模型路径的参数名改为vit_name1，并将代码中出现它的地方也全部改了，然后运行没有了那个错误，不过现在又出现了这样的情况：
![image](https://user-images.githubusercontent.com/73507088/177981685-fb797cc5-f53f-4bb2-a3d0-fed9625c8b1d.png)
正在进一步观察中。

**Comment by tlk1997** [comment]
predict.yaml里也要改

**Comment by 3525355094** [comment]
请问有人见过这种问题吗？：
![image](https://user-images.githubusercontent.com/73507088/178014459-8244263c-04aa-48b5-ab6e-1a1509b3f221.png)

**Comment by tlk1997** [comment]
文件路径问题，可以修改文件内对应路径，可以先更新一下代码
