### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './meta/rel2id.json'

### ISSUE THREAD

**Issue by JxuHenry** [zjunlp/DeepKE#125]
当我跑ner任务的时候报错FileNotFoundError: [Errno 2] No such file or directory: './meta/rel2id.json'，请问怎么解决？

**Comment by xxupiano** [comment]
是standard NER？数据集应该放在data文件夹下，直接按README下载解压即可。

**Comment by JxuHenry** [comment]
是的，是standard NER，数据集也在data文件夹里面，运行Python run.py报错ileNotFoundError: [Errno 2] No such file or directory: './meta/rel2id.json'

**Comment by xxupiano** [comment]
data是放在standard下面，但是standard NER数据集里没有rel2id.json这个文件，这是用在关系抽取的。
可以截图报错信息发一下吗？

**Comment by JxuHenry** [comment]
您好，谢谢，这个问题解决了，出现了新的问题，是这个：ModuleNotFoundError: No module named 'transformers.configuration_bart'
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/48616523/179165395-a549fd95-fd32-4f12-afe5-599d84b8be81.png">
我已经安装了transformers的包了

**Comment by xxupiano** [comment]
transformers版本降到3.4.0

**Comment by JxuHenry** [comment]
好的谢谢，之前的报错是这样的，您可以看看
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/48616523/179166112-a9ec6867-ddbe-4263-89d0-eb977494ac79.png">

**Comment by JxuHenry** [comment]
> transformers版本降到3.4.0

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/48616523/179166352-5d2da5f3-e86e-4fd9-bfe1-4a1471270a03.png">
transformers的版本是3.4.0

**Comment by TimelordRi** [comment]
> > data是放在standard下面，但是standard NER数据集里没有rel2id.json这个文件，这是用在关系抽取的。 可以截图报错信息发一下吗？
> 
> 好的谢谢，之前的报错是这样的，您可以看看 <img alt="image" width="1504" src="https://user-images.githubusercontent.com/48616523/179166112-a9ec6867-ddbe-4263-89d0-eb977494ac79.png">

你好🙋‍♂️，你说的问题在之前版本的deepke包中存在，也就是https://github.com/zjunlp/DeepKE/commit/ab6b52c4733fc8b0a36bbb5944309f1b23ce9345 版本的`deepke/relation_extraction/document/evaluation.py`文件存在这样的问题。如果你需要保留你目前对deepke其他部分的修改，可以clone一下新版的DeepKE并替换一下`deepke/relation_extraction`或者`deepke/relation_extraction/document`目录来解决这个错误。

**Comment by JxuHenry** [comment]
> > > data是放在standard下面，但是standard NER数据集里没有rel2id.json这个文件，这是用在关系抽取的。 可以截图报错信息发一下吗？
> > 
> > 
> > 好的谢谢，之前的报错是这样的，您可以看看 <img alt="image" width="1504" src="https://user-images.githubusercontent.com/48616523/179166112-a9ec6867-ddbe-4263-89d0-eb977494ac79.png">
> 
> 你好🙋‍♂️，你说的问题在之前版本的deepke包中存在，也就是[ab6b52c](https://github.com/zjunlp/DeepKE/commit/ab6b52c4733fc8b0a36bbb5944309f1b23ce9345) 版本的`deepke/relation_extraction/document/evaluation.py`文件存在这样的问题。你可以把deepke更新到最新版本，如果你需要保留你目前对deepke其他部分的修改，可以clone一下新版的DeepKE并替换一下`deepke/relation_extraction`或者`deepke/relation_extraction/document`目录来解决这个错误。

好的，谢谢，麻烦您了，那我的另一个错误能帮忙看看么？

**Comment by xxupiano** [comment]
pip install deepke --upgrade试试

**Comment by xxupiano** [comment]
将deepke更新到最新版本试试

**Comment by JxuHenry** [comment]
> pip install deepke --upgrade

您好，我已经更新了deepke最新版本，然后出现了新的问题
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/48616523/179173735-ba04fbdd-4970-4eea-b287-0cbad5b282bb.png">
这个我应该选择什么呢？

**Comment by TimelordRi** [comment]
如果你不想可视化运行结果，就输入3并回车，这个是wandb包的用法，可以搜索一下一下

**Comment by JxuHenry** [comment]
> 如果你不想可视化运行结果，就输入3并回车，这个是wandb包的用法，可以搜索一下一下

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/48616523/179174338-1b7a18cb-7a9f-4a06-907c-45f37dc1c0dd.png">

**Comment by xxupiano** [comment]
> 

pytorch GPU没有安装成功，或者CUDA版本不对，检查一下

**Comment by xxupiano** [comment]
> > pip install deepke --upgrade
> 
> 您好，我已经更新了deepke最新版本，然后出现了新的问题 <img alt="image" width="1435" src="https://user-images.githubusercontent.com/48616523/179173735-ba04fbdd-4970-4eea-b287-0cbad5b282bb.png"> 这个我应该选择什么呢？

建议1，会有操作提示，按照提示操作即可。

**Comment by xxupiano** [comment]
> > 如果你不想可视化运行结果，就输入3并回车，这个是wandb包的用法，可以搜索一下一下
> 
> <img alt="image" width="1511" src="https://user-images.githubusercontent.com/48616523/179174338-1b7a18cb-7a9f-4a06-907c-45f37dc1c0dd.png">

pytorch GPU没有安装成功，或者CUDA版本不对，检查一下

**Comment by TimelordRi** [comment]
你或许没有安装pytorch配套的cuda，参考一下这个文档试试，https://blog.csdn.net/HPGaa/article/details/117230868 。

**Comment by xxupiano** [comment]
pytorch 1.11.0即可

**Comment by JxuHenry** [comment]
> pytorch 1.11.0即可

好的谢谢

**Comment by JxuHenry** [comment]
请问一下这个ner的基础模型就使用了bert直接做ner是么？

**Comment by xxupiano** [comment]
> 请问一下这个ner的基础模型就使用了bert直接做ner是么？

是

**Comment by JxuHenry** [comment]
> > 请问一下这个ner的基础模型就使用了bert直接做ner是么？
> 
> 是

<img width="1513" alt="image" src="https://user-images.githubusercontent.com/48616523/179177482-816e58f2-8319-4e62-a982-64a31591f717.png">
训练的时候如何看训练效果呢？

**Comment by xxupiano** [comment]
> 

训练后会显示eval的结果

**Comment by JxuHenry** [comment]
> > 
> 
> 训练后会显示eval的结果

那是只训练3个epoch就可以了么？还是说需要根据数据来增加epoch的数量？

**Comment by xxupiano** [comment]
> > > 
> > 
> > 
> > 训练后会显示eval的结果
> 
> 那是只训练3个epoch就可以了么？还是说需要根据数据来增加epoch的数量？

可以根据结果f1-score大小来调整epoch

**Comment by JxuHenry** [comment]
> > > > 
> > > 
> > > 
> > > 训练后会显示eval的结果
> > 
> > 
> > 那是只训练3个epoch就可以了么？还是说需要根据数据来增加epoch的数量？
> 
> 可以根据结果f1-score大小来调整epoch

OK，好的谢谢，非常感谢

**Comment by JxuHenry** [comment]
请问我如何修改batch size呢？在配置文件中没有看到batch size

**Comment by xxupiano** [comment]
> 请问我如何修改batch size呢？在配置文件中没有看到batch size

https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/conf/train.yaml 有的

**Comment by JxuHenry** [comment]
> https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/conf/train.yaml

eval_batch_size是这个值？

**Comment by xxupiano** [comment]
> > > 请问我如何修改batch size呢？在配置文件中没有看到batch size
> > 
> > 
> > https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/conf/train.yaml 有的
> 
> train_batch_size是这个值？

training时候的batch_size是train_batch_size，train之后eval的batch_size是eval_batch_size
