### ISSUE TITLE
requirements Conflict

### ISSUE THREAD

**Issue by lightbordwin** [zjunlp/DeepKE#131]
**Describe the bug**
> A clear and concise description of what the bug is.

using pip install deepke
get error from console: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 2.0.0 requires tqdm>=4.62.1, but you have tqdm 4.60.0 which is incompatible.
when I upgrade tqdm to 4.64.0 ,another error occured: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
deepke 2.0.5 requires tqdm==4.60.0, but you have tqdm 4.64.0 which is incompatible.
how to solve this?

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

windows 10
python 3.8.8

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by tlk1997** [comment]
以下几个方面检查并解决：
1、是否创建了新的虚拟环境，datasets包是从哪来的，因为3,.4.0的transformers并不依赖于datasets
2、卸载之前安装的依赖包，修改setup.py中的tqdm==4.64.0，再通过python setup.py install 的方式进行安装依赖包

**Comment by tlk1997** [comment]
Check as followings:
1. Whether a new virtual environment is created, and where does the datasets package come from, because 3,.4.0 transformers does not rely on datasets
2. Uninstall the previously installed deepke package, modify tqdm==4.64.0 in setup.py, and then use 'python setup.py install' to install dependent packages
