### ISSUE TITLE
label中英文对不上

### ISSUE THREAD

**Issue by changleilei** [zjunlp/DeepKE#132]
**Describe the question**
> A clear and concise description of what the question is.

    ner("6月5日是我的生日")   抽取结果: {'歌曲': ['6月5日']}

label_dict 如下：

label_dict = {'O': '其他', 'YAS': '人物', 'TOJ': '影视作品', 'NGS': '目', 'QCV': '生物', 'OKB': '数字', 'BQF': '日期', 'CAR': '国家',
              'ZFM': '网站', 'EMT': '网络小说', 'UER': '图书作品', 'QEE': '歌曲', 'UFT': '地点', 'GJS': '气候', 'SVA': '行政区',
              'ANO': 'TEXT', 'KEJ': '历史人物', 'ZDI': '学校', 'CAT': '企业', 'GCK': '出版社', 'FQK': '书籍', 'BAK': '音乐专辑',
              'RET': '城市', 'QZP': '景点', 'QAQ': '电视综艺', 'ZRE': '机构', 'TDZ': '作品', 'CVC': '语言', 'PMN': '学科专业'}

 https://github.com/zjunlp/DeepKE/blob/main/README_CNSCHEMA_CN.md 是对照着这个链接做的，还有 “目”代表的是什么意思？是“目 科 属 种” 中的“目”吗？

还有关系抽取的模型，连接点进去的模型只有90MB，是不是失效了。

感谢!
**Environment (please complete the following information):**
 - OS: [linux]
 - Python Version [3.8]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by tlk1997** [comment]
英文ID是随机产生出来的，目就是你理解的意思，关系抽取的模型是取了bert中的一层在连接lstm网络，所以只有90mb

**Comment by changleilei** [comment]
> 
所以把日期抽取成歌曲是抽取结果出错了，并不是label对照的错误

**Comment by tlk1997** [comment]
是的，也可以打印下label，但应该是预测错了

**Comment by changleilei** [comment]
> 

打印了，这个模型比较偏好预测成歌曲，因为也测试了其他的一些用例。感谢回复！

**Comment by zxlzr** [comment]
模型预测错误很难避免，我们会在未来不断更新模型改进并提升抽取性能
