### ISSUE TITLE
请问 中文事件抽取 工具

### ISSUE THREAD

**Issue by ping40** [zjunlp/DeepKE#138]
感谢 贡献了 优秀工具  deepke。

请教各位 nlp大咖，当下 有没有 类似 deepke的 deepee 工具？  

zjunlp/deepee 这个项目 感觉不够完备，**也不活跃**。数据dataset 不完备，也无predict.py。

**Comment by zxlzr** [comment]
您好， 感谢关注DeepKE，事件抽取正在开发中会在近期发布到DeepKE，deepee项目已停止维护，部分算法会集成进deepke。

**Comment by ping40** [comment]
您好，能否说下大概 进度安排吗 ？

**Comment by zxlzr** [comment]
计划2022年底会推送事件抽取。

**Comment by ping40** [comment]
谢谢。 期待......
