### ISSUE TITLE
在训练时会出现以下错误，请问是怎么回事？

### ISSUE THREAD

**Issue by swo026** [zjunlp/DeepKE#139]
File ".\example\ner\standard\run_lstmcrf.py", line 118, in main
    eval_f1 = f1_score([id2label[l] for l in y_true_list], [id2label[l] for l in y_pred_list],
  File ".\example\ner\standard\run_lstmcrf.py", line 118, in <listcomp>
    eval_f1 = f1_score([id2label[l] for l in y_true_list], [id2label[l] for l in y_pred_list],
KeyError: tensor([3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Comment by pengzju** [comment]
您好，这里的y_true_list和y_pred_list应该确保是一维的。从您的报错情况来看，应该是将一个Tensor当作key了。（后续会在代码中补充异常处理，感谢您的关注）

**Comment by swo026** [comment]
我尝试将y_pred_list转成一维进行输入，但是y_true_list和y_pred_list的长度不一致

**Comment by pengzju** [comment]
dataloader每次采样都会返回padding后的input, target以及mask。您应该将y_true_list中padding的部分去掉（通过读取mask是否为True），在代码中体现为
for y, m in zip(target, mask):
      y_true_list += y[m == True].tolist()
应该是没有利用mask导致的问题，祝好~

**Comment by swo026** [comment]
> dataloader每次采样都会返回padding后的input, target以及mask。您应该将y_true_list中padding的部分去掉（通过读取mask是否为True），在代码中体现为 for y, m in zip(target, mask): y_true_list += y[m == True].tolist() 应该是没有利用mask导致的问题，祝好~

好的，我试一下，十分感谢

**Comment by pengzju** [comment]
希望您告知一下修改后的结果，以便我能关闭这个issue

**Comment by swo026** [comment]
for lst, m in zip(y_pred[0], mask):
    y_pred_list += lst[m == True].tolist()
for y, m in zip(target, mask):
    y_true_list += y[m == True].tolist()
eval_loss += loss.item()


这里改成这样就没有问题了，看起来应该是把模型输出的结果y_pred中padding的地方去掉
