### ISSUE TITLE
特别版DeepKE-cnSchema,用关系抽取模型预训练模型，缺少relation.csv文件

### ISSUE THREAD

**Issue by sssss99999** [zjunlp/DeepKE#143]
**Describe the question**
> A clear and concise description of what the question is.

特别版DeepKE-cnSchema,用关系抽取模型预训练模型RoBERTa-wwm-ext进行测试时，缺少DeepKE/example/re/standard/data/origin/relation.csv文件。

如果用 https://github.com/zjunlp/DeepKE/blob/main/README_CNSCHEMA_CN.md#%E5%85%B3%E7%B3%BBschema里的关系类别，有些类别是重复的，如 33，45 都为   cns:人物 | cns:歌曲 | cns:作曲，不够50个类别

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by xxupiano** [comment]
relation.csv已提供https://drive.google.com/drive/folders/1UurqpjePe3zhXxbDDNwLAjVvt7UyUMuQ
