### ISSUE TITLE
Docker 环境下缓存工具版本错误

### ISSUE THREAD

**Issue by thredreams** [zjunlp/DeepKE#144]
**Describe the question**
> A clear and concise description of what the question is.

在Docker环境下，python setup.py install过程中失败，提示是 `cachetools 5.2.0 is installed but cachetools<5.0,>=2.0.0 is required by {'google-auth'}`

**Environment (please complete the following information):**
 - OS: window10、Dockers20.10。17
 - Python Version ： 3.8.13

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/44553414/191189324-d00ee13c-edd3-49c8-ba64-fd2311ced6f5.png)

**Additional context**
- 我觉得README里应该添加如何使用Docker的说明,属实是走了不少的弯路

**Comment by tlk1997** [comment]
推荐使用anaconda创建虚拟环境

**Comment by thredreams** [comment]
但是我看Dockerfile里不是也用的miniconda虚拟环境吗？
我试图更新`google-auth`包，但是结果不行，所以我回退了cachetools到5.0.0以前的最新版本4.2.4
```
pip install cachetools==4.2.4
```
在这个过程中pip提示我之前升级google-auth的操作破坏了tensorboard2.4.1的依赖
![image](https://user-images.githubusercontent.com/44553414/191203181-956c5df9-23dc-4a29-98e3-e11f3b2f3644.png)

**Comment by tlk1997** [comment]
直接用conda，没有碰到过cachetools和google-auth这两个包的问题，所以还得自行研究一下

**Comment by thredreams** [comment]
在Docker使用中确实出现了相当多的依赖问题，缺少一些包，我正在尝试缺啥装啥的策略，如果最后可行，我会试着再提一个issue将这些步骤分享出来。

**Comment by zxlzr** [comment]
手动点赞👍🏻非常感谢
