### ISSUE TITLE
sort没有正确排序

### ISSUE THREAD

**Issue by 1158593340** [zjunlp/DeepKE#146]
**Describe the bug**
> A clear and concise description of what the bug is.
![image](https://user-images.githubusercontent.com/72919715/191515100-661953cb-7b9e-4e3b-8934-b07939aace23.png)
![image](https://user-images.githubusercontent.com/72919715/191516402-b9fd7f17-b4ef-4c2a-9bf7-9fa74b14ebc7.png)
![image](https://user-images.githubusercontent.com/72919715/191517964-1d3c2d97-0678-4b6e-a864-741203e4bff2.png)
sort没有正确排序,max_len没有获取到最大长度,句子长度不同

**Environment (please complete the following information):**
 - OS: [e.g. linux]
 - Python Version [e.g. 3.8]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
您好，已安排同学检查和开发修复。

**Comment by xxupiano** [comment]
这个支持的是中文数据集

**Comment by 1158593340** [comment]
> 这个支持的是中文数据集

哦哦，好的
