### ISSUE TITLE
请问这样是怎么会回事？

### ISSUE THREAD

**Issue by yjc924-cc** [zjunlp/DeepKE#147]
![image](https://user-images.githubusercontent.com/74005132/192190166-b566335b-a604-4b0e-8914-1cfecc6d071b.png)

**Comment by xxupiano** [comment]
路径问题，最后一行路径中包含'/'，是Linux的路径格式，改为win格式即可

**Comment by yjc924-cc** [comment]
您好，能不能详细说一下改那个部分，没找到bug在哪

**Comment by pengzju** [comment]
你好，尝试更改一下train.yaml中的data_dir配置项（改为'data'而不是'data/'）
![image](https://user-images.githubusercontent.com/63391142/192192890-d0fb1b0e-9b0d-4354-9f36-da34ac6bf408.png)

**Comment by yjc924-cc** [comment]
谢谢您的帮助
