### ISSUE TITLE
_handle_relation_data()返回的关系字典是不可靠的

### ISSUE THREAD

**Issue by sunweishou** [zjunlp/DeepKE#148]
如下图，_handle_relation_data()返回的关系字典是不可靠的，会导致列表索引溢出。
因为存在不同类型的实体存在相同的关系，但关系索引不一样的情况。应该以关系索引为key。

如下面的“成立日期”，有两个来自于不同实体类型的定义。
Date,机构,成立日期,36
学校,人物,毕业院校,37
Number,机构,占地面积,38
语言,国家,官方语言,39
Text,行政区,邮政编码,40
Number,行政区,人口数量,41
城市,景点,所在城市,42
人物,图书作品,作者,43
Date,企业,成立日期,44
人物,歌曲,作曲,45
气候,行政区,气候,46

![捕获](https://user-images.githubusercontent.com/35616385/192410986-15bcd6ad-903f-4031-a61a-3c24bf199c04.PNG)
![捕获2](https://user-images.githubusercontent.com/35616385/192411014-b1a4f68b-3518-45c3-829d-edf26ad9e445.PNG)

**Comment by tlk1997** [comment]
感谢提问，我们会修改数据集中关系文件，将其命名为两种不同的关系类型
