### ISSUE TITLE
安装deepke遇到的问题，希望能收到您的回复

### ISSUE THREAD

**Issue by ufuiomm** [zjunlp/DeepKE#149]
您好，我对DeepKE非常感兴趣，因此下载了github上的代码学习，但在安装环境时遇到了问题
我使用pip install deepke命令安装deepke，安装程序报错说以下几个库版本太低：
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
text2vec 1.1.7 requires transformers>=4.6.0, but you have transformers 3.4.0 which is incompatible.
tensorflow 2.10.0 requires tensorboard<2.11,>=2.10, but you have tensorboard 2.4.1 which is incompatible.
tensorflow-gpu 2.10.0 requires tensorboard<2.11,>=2.10, but you have tensorboard 2.4.1 which is incompatible.
datasets 2.1.0 requires tqdm>=4.62.1, but you have tqdm 4.60.0 which is incompatible.
Successfully installed huggingface-hub-0.2.1 tensorboard-2.4.1 tokenizers-0.9.2 tqdm-4.60.0 transformers-3.4.0
我发现这几个库的版本是安装时替换的。我重新手动升级这几个库后，再次安装，依旧报这个异常，并且安装时将这几个库的版本重新修改为较低的版本。
因此希望能得到你的帮助解决这个问题，希望能收到您的回复。

**Comment by tlk1997** [comment]
创一个新的虚拟环境在安装

**Comment by zxlzr** [comment]
您好建议您使用虚拟环境安装。
