### ISSUE TITLE
NER got error :wandb: WARNING W&B installed but not logged in.  Run `wandb login` or set the WANDB_API_KEY env variable.

### ISSUE THREAD

**Issue by JxuHenry** [zjunlp/DeepKE#150]
**Describe the question**
wandb: WARNING W&B installed but not logged in.  Run `wandb login` or set the WANDB_API_KEY env variable.
09/30/2022 14:12:22 - INFO - deepke.relation_extraction.multimodal.models.clip.file_utils -   PyTorch version 1.11.0+cu113 available.
09/30/2022 14:12:22 - INFO - deepke.name_entity_re.multimodal.models.clip.file_utils -   PyTorch version 1.11.0+cu113 available.
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose 'Don't visualize my results'
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
/root/miniconda3/envs/deepke/lib/python3.8/site-packages/hydra_core-1.0.6-py3.8.egg/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive hydra/output/custom.yaml in file:///home/deploy/vte-nlp-ner/DeepKE/example/ner/standard/conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
/root/miniconda3/envs/deepke/lib/python3.8/site-packages/hydra_core-1.0.6-py3.8.egg/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive train.yaml in file:///home/deploy/vte-nlp-ner/DeepKE/example/ner/standard/conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
/root/miniconda3/envs/deepke/lib/python3.8/site-packages/hydra_core-1.0.6-py3.8.egg/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive predict.yaml in file:///home/deploy/vte-nlp-ner/DeepKE/example/ner/standard/conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
Traceback (most recent call last):
  File "run.py", line 83, in main
    raise ValueError("Output directory ({}) already exists and is not empty.".format(utils.get_original_cwd()+'/'+cfg.output_dir))
ValueError: Output directory (/home/deploy/vte-nlp-ner/DeepKE/example/ner/standard/checkpoints) already exists and is not empty.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

wandb: Waiting for W&B process to finish, PID 31359... (failed 1).
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /home/deploy/vte-nlp-ner/DeepKE/example/ner/standard/wandb/offline-run-20220930_141229-38pdrrq3
wandb: Find logs at: ./wandb/offline-run-20220930_141229-38pdrrq3/logs/debug.log
wandb: 

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by pangpangDD** [comment]
hello , how did you solve it?

**Comment by xxupiano** [comment]
You can choose one of the following solutions:
1. Please refer to the [doc of wandb](https://docs.wandb.ai/quickstart) to have a W&B account and login.
2. Do not use wandb (annotate code with wandb).
