### ISSUE TITLE
few shot NER 中文数据集缺失

### ISSUE THREAD

**Issue by RichardFans** [zjunlp/DeepKE#151]
example/ner/few-shot/run.py 源码中添加了对 cluener2020 的支持，但 ReadME中 wget 120.27.214.45/Data/ner/few_shot/data.tar.gz，中却没有这个数据集；请问如何获取这个数据集？是需要从 https://github.com/CLUEbenchmark/FewCLUE 中获取吗？可FewCLUE也不止一个任务数据集， 应该用哪个呢？

**Comment by pengzju** [comment]
您好，感谢您对此项目的关注。
我们从cluener2020中抽取了few-shot数据集（包括20shot、50shot、100shot、test集等），具体而言您可以通过如下的方式获得到数据：
`wget 120.27.214.45/Data/ner/few_shot/data_cn.tar.gz`
`tar -xvf data_cn.tar.gz`
并将这些数据放置在example\ner\few-shot\data\cluener2020目录中

**Comment by RichardFans** [comment]
Thanks♪(･ω･)ﾉ
