### ISSUE TITLE
NameError: name 'build_crflstm_corpus' is not defined 

### ISSUE THREAD

**Issue by JxuHenry** [zjunlp/DeepKE#152]
for ner, when I run "run_lstmcrf.py", get error "NameError: name 'build_crflstm_corpus' is not defined "

**Comment by pengzju** [comment]
您好，我重新运行了run_lstmcrf.py发现可以正常训练。函数build_crflstm_corpus的import逻辑是这样的：
1、在`run_lstmcrf.py`中
from deepke.name_entity_re.standard import *

2、在standar目录下的`init.py`中
from .models import *
from .tools import *

3、在tools目录下的`init.py`中
from .preprocess import *

4、函数build_crflstm_corpus存在于preproess.py中。

因此建议您按照这个逻辑进行debug，重点关注几个`init.py`

**Comment by JxuHenry** [comment]
> 您好，我重新运行了run_lstmcrf.py发现可以正常训练。函数build_crflstm_corpus的import逻辑是这样的： 1、在`run_lstmcrf.py`中 from deepke.name_entity_re.standard import *
> 
> 2、在standar目录下的`init.py`中 from .models import * from .tools import *
> 
> 3、在tools目录下的`init.py`中 from .preprocess import *
> 
> 4、函数build_crflstm_corpus存在于preproess.py中。
> 
> 因此建议您按照这个逻辑进行debug，重点关注几个`init.py`

再请问一下，为什么我程序跑起来之后，看GPU的使用率还是0呢？我怎么确认程序是否是使用的GPU训练的呢？

**Comment by pengzju** [comment]
若您没有其他问题，请允许我关闭此issue

**Comment by JxuHenry** [comment]
> torch.cuda.is_available()

torch.cuda.is_available()的结果打印为true，这个不是只能看我的服务器的GPU是否能够使用么？应该无法判断deepke的程序是否使用了GPU吧？

**Comment by pengzju** [comment]
`    if cfg.use_gpu and torch.cuda.is_available():`
`        device = torch.device('cuda', cfg.gpu_id)`
`    else:`
`        device = torch.device('cpu')`
deepke中也遵循这个逻辑啊，我建议您找一找其他原因

**Comment by JxuHenry** [comment]
> ` if cfg.use_gpu and torch.cuda.is_available():` ` device = torch.device('cuda', cfg.gpu_id)` ` else:` ` device = torch.device('cpu')` deepke中也遵循这个逻辑啊，我建议您找一找其他原因

OK好的谢谢
