### ISSUE TITLE
when run ner, i got error : Key 'bert_model' is not in struct

### ISSUE THREAD

**Issue by JxuHenry** [zjunlp/DeepKE#153]
Traceback (most recent call last):
  File "run_bert.py", line 93, in main
    tokenizer = BertTokenizer.from_pretrained(cfg.bert_model, do_lower_case=cfg.do_lower_case)
omegaconf.errors.ConfigAttributeError: Key 'bert_model' is not in struct
        full_key: bert_model
        reference_type=Optional[Dict[Union[str, Enum], Any]]
        object_type=dict

**Comment by pengzju** [comment]
When you use bert model, please set hydra/model in `config.yaml` to bert.
You can get more details on https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/conf/config.yaml

**Comment by JxuHenry** [comment]
> https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/conf/config.yaml

I got the following reslut:
precision    recall  f1-score   support                                                                                         
                                                                                                                                              
         DVT     0.0000    0.0000    0.0000       187                                                                                         
          PE     0.0000    0.0000    0.0000       113                                                                                         
        TIME     0.0000    0.0000    0.0000       155                                                                                         
                                                                                                                                              
   micro avg     0.0000    0.0000    0.0000       455                                                                                         
   macro avg     0.0000    0.0000    0.0000       455                                                                                         
weighted avg     0.0000    0.0000    0.0000       455                                                                                         
                                                                                                                                              
[2022-10-04 00:44:12,902][__main__][INFO] - ***** Eval results *****                                                                          
[2022-10-04 00:44:12,902][__main__][INFO] -                                                                                                   
              precision    recall  f1-score   support                                                                                         
                                                                                                                                              
         DVT     0.0000    0.0000    0.0000       187                                                                                         
          PE     0.0000    0.0000    0.0000       113                                                                                         
        TIME     0.0000    0.0000    0.0000       155                                                                                         
                                                                                                                                              
   micro avg     0.0000    0.0000    0.0000       455                                                                                         
   macro avg     0.0000    0.0000    0.0000       455                                                                                         
weighted avg     0.0000    0.0000    0.0000       455

Why my model resluts were all zero ?

**Comment by pengzju** [comment]
我建议您适当调整超参数，例如学习率learning rate，以及lstm的层数hidden_layer等等。重点关注loss是否为`nan`

**Comment by JxuHenry** [comment]
> 我建议您适当调整超参数，例如学习率learning rate，以及lstm的层数hidden_layer等等。重点关注loss是否为`nan`

您好我训练的是bert模型的ner，不是lstm的模型

**Comment by pengzju** [comment]
那就确保您的pretrain模型是正确的，并且调整超参。建议您先在deepke现成的数据集下运行

**Comment by JxuHenry** [comment]
> 那就确保您的pretrain模型是正确的，并且调整超参。建议您先在deepke现成的数据集下运行

那么我实在tran.yml中修改使用的预训练模型是么？

**Comment by JxuHenry** [comment]
> > 那就确保您的pretrain模型是正确的，并且调整超参。建议您先在deepke现成的数据集下运行
> 
> 那么我实在tran.yml中修改使用的预训练模型是么？

**Comment by pengzju** [comment]
micro avg表示微平均，表示不区分样本类别，计算整体的准确率、召回率和F1值
macro avg表示宏平均，表示所有类别对应指标的平均值。
weighted avg表示带权重平均，表示类别样本占总样本的比重与对应指标的乘积的累加和
具体可参考https://www.jianshu.com/p/757dfef76e13
