### ISSUE TITLE
意图识别

### ISSUE THREAD

**Issue by jiaolongxue** [zjunlp/DeepKE#154]
**Describe the feature**
知识图谱一个主要的应用场景是问答，是否可以考虑在套件中增加意图识别的功能

**Comment by zxlzr** [comment]
感谢您的建议，意图识别是一个分类问题，您可以通过去掉关系抽取任务的实体输入实现简单的支持意图识别。另外我们近期正在开发迭代工具promptkg https://github.com/zjunlp/PromptKG，该工具是支持基于kg的问答功能的。
