### ISSUE TITLE
网盘提取密码错误

### ISSUE THREAD

**Issue by lzw19910** [zjunlp/DeepKE#155]
“DeepKE(RE), RoBERTa-wwm-ext, Chinese	关系抽取	PyTorch	Pytorch（密码ggnu）” 中的百度网盘提取密码ggnu是错的，无法提取文件。谷歌云盘中的分享文件中也没有https://github.com/zjunlp/DeepKE/blob/main/README_CNSCHEMA_CN.md 中提到的zip文件。

**Comment by xxupiano** [comment]
已修复

**Comment by tlk1997** [comment]
链接: https://pan.baidu.com/s/1ozFsxExAQTBRs5NbJW7W5g  密码: 78pq
