### ISSUE TITLE
依赖torch版本不一致

### ISSUE THREAD

**Issue by jiaolongxue** [zjunlp/DeepKE#157]
**Describe the question**

setup.py中要求的torch版本是1.11
![image](https://user-images.githubusercontent.com/21324579/194739031-bc5d6510-3356-431d-a5ec-0e4d71d439e1.png)

但是example/ner/standard/requirements.txt中要求的torch版本是1.5.0
![image](https://user-images.githubusercontent.com/21324579/194739047-e7370059-2234-4ab2-b2f5-ccc2045bc45e.png)

最外层requirements.txt中要求的torch版本是torch>=1.5,<=1.10
![image](https://user-images.githubusercontent.com/21324579/194739060-5edce14b-7578-4419-98e0-2410971cc723.png)

这些地方的版本是否要统一一下，不然在执行example的requirements.txt会卸载python setup.py install安装好的torch，是否会导致软件不可用？
![image](https://user-images.githubusercontent.com/21324579/194739119-1be72b00-418f-4190-b91e-e75c41fab50e.png)
执行example的requirements.txt会卸载python setup.py install安装好的deepke，版本变为0.2.66
![image](https://user-images.githubusercontent.com/21324579/194739198-0e0e6b5e-5a9e-49e8-be0b-694e5b37f663.png)

**Comment by tlk1997** [comment]
1.5到1.11的版本都能用

**Comment by zxlzr** [comment]
您好，我们会在近期统一pytorch版本

**Comment by divingwolf** [comment]
> 您好，我们会在近期统一pytorch版本
pip install easyinstruct -i https://pypi.org/simple
你们这个要求torch>=1.13啊
还是不能统一版本吗
