### ISSUE TITLE
实体关系预测未使用实体类型信息吗？

### ISSUE THREAD

**Issue by sunweishou** [zjunlp/DeepKE#158]
实体关系预测未使用实体类型信息吗？

实例程序的实体关系预测代码，也没有进行实体类型信息的检验和过滤。
实践中出现，比如只定义了“人物-歌曲-作者“的关系，但是拿”地点-歌曲“去预测，也可以得到”作者“的关系，而且分值很高。

**Comment by sunweishou** [comment]
我查看训练数据，也只标记了头、尾实体，没有头尾实体的类型。

**Comment by zxlzr** [comment]
您好，目前训练的模型并未考虑实体类型信息，您可以通过加入特殊实体类型marker的方式加入实体类型信息在超参数中有# 是否需要使用实体类型替换实体词语
replace_entity_with_type: True
另一方面也是避免实体类型对关系类型出现偏差，比如实体类型直接对关系类型做出决策模型走了捷径没有考虑上下文。
