### ISSUE TITLE
命名实体识别的LSTM+CRF模型的model_vocab和label2id在哪下载？

### ISSUE THREAD

**Issue by swx-10** [zjunlp/DeepKE#159]
您好，请问命名实体识别的LSTM+CRF模型的model_vocab和label2id有提供下载吗？只看见了model.pth

**Comment by pengzju** [comment]
首先感谢您对此Repo的关注。
当您使用LSTM+CRF模型时由于没有Tokenizer，需要自行构造Vocabulary Set。其中(word2id, label2id)，id2label分别用于训练、解码；model_vacab是存储这些词典的文件路径。`run_lstmcrf.py`会根据您输入的数据自动构建这些pkl文件。

具体函数为`build_crflstm_corpus`，更多细节您可参考：
https://github.com/zjunlp/DeepKE/blob/main/src/deepke/name_entity_re/standard/tools/preprocess.py#L127

**Comment by pengzju** [comment]
首先感谢您对此Repo的关注。
当您使用LSTM+CRF模型时由于没有Tokenizer，需要自行构造Vocabulary Set。其中(word2id, label2id)，id2label分别用于训练、解码；model_vacab是存储这些词典的文件路径。`run_lstmcrf.py`会根据您输入的数据自动构建这些pkl文件。

具体函数为`build_crflstm_corpus`，更多细节您可参考：
https://github.com/zjunlp/DeepKE/blob/main/src/deepke/name_entity_re/standard/tools/preprocess.py#L127

**Comment by swx-10** [comment]
非常感谢您的回复！我是看到有提供训练好的lstm模型下载，但是没有发现Word2id等文件的下载，因此有这个疑问。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月11日 19:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [zjunlp/DeepKE] 命名实体识别的LSTM+CRF模型的model_vocab和label2id在哪下载？ (Issue #159) |

首先感谢您对此Repo的关注。
当您使用LSTM+CRF模型时由于没有Tokenizer，需要自行构造Vocabulary Set。其中(word2id, label2id)，id2label分别用于训练、解码；model_vacab是存储这些词典的文件路径。run_lstmcrf.py会根据您输入的数据自动构建这些pkl文件。

具体函数为build_crflstm_corpus，更多细节您可参考：
https://github.com/zjunlp/DeepKE/blob/main/src/deepke/name_entity_re/standard/tools/preprocess.py#L127

**Comment by pengzju** [comment]
中英文README_CNSCHEMA已更新，您可在Google Drive或者BaiduNetDisk上下载您需要的词典文件。
Google Drive: https://drive.google.com/drive/folders/1n1tzvl6hZYoUUFFWLfkuhkXPx5JB4XK_

可以使用如下代码获取具体的`word2id`、`label2id`、`id2label`:
with open('data_bilstm.pkl', 'rb') as inp:
    word2id = pickle.load(inp)
    label2id = pickle.load(inp)
    id2label = pickle.load(inp)

**Comment by speakstone** [comment]
Google Drive: https://drive.google.com/drive/folders/1n1tzvl6hZYoUUFFWLfkuhkXPx5JB4XK
Invalid
