### ISSUE TITLE
requirements 缺少依赖

### ISSUE THREAD

**Issue by 117v2** [zjunlp/DeepKE#161]
## 错误情况
通过 `pip install deepke`，下载解压完数据之后，运行 `example/re/standard` 下示例 `python run.py` 时报错，信息显示缺少依赖 `tensorboardX` 及 `ipdb` 。 

## 环境
- OS: Ubuntu 22.04
- Python 3.8

<img src="https://s3.bmp.ovh/imgs/2022/10/21/2bddb9a48811e4cf.png" width=756pt>

**Comment by zxlzr** [comment]
您好感谢关注，您可以pip 安装下缺失的依赖包，建议您直接通过虚拟环境下python setup.py install进行安装。
