### ISSUE TITLE
DeepKE v2.1新版特性（DeepKE v2.1 New Release Features）

### ISSUE THREAD

**Issue by xxupiano** [zjunlp/DeepKE#165]
- 新增支持多模态场景的[实体抽取](https://github.com/zjunlp/DeepKE/tree/main/example/ner/multimodal)、[关系抽取](https://github.com/zjunlp/DeepKE/tree/main/example/re/multimodal)功能
- 新增[DeepKE-cnschema](https://github.com/zjunlp/DeepKE/blob/main/README_CNSCHEMA_CN.md)特别版模型，支持基于cnSchema的开箱即用的中文实体识别和关系抽取
- 新增针对[低资源关系抽取](https://github.com/zjunlp/DeepKE/tree/main/example/re/few-shot)的[数据增强](https://github.com/zjunlp/DeepKE/tree/main/example/re/few-shot/DA) (中文、英文)功能

<br>

- Add multimodal supports for [entity](https://github.com/zjunlp/DeepKE/tree/main/example/ner/multimodal) and [relation extraction](https://github.com/zjunlp/DeepKE/tree/main/example/re/multimodal)
- Release [DeepKE-cnschema](https://github.com/zjunlp/DeepKE/blob/main/README_CNSCHEMA.md) with off-the-shelf knowledge extraction models
- Add [data augmentation](https://github.com/zjunlp/DeepKE/tree/main/example/re/few-shot/DA) (Chinese, English) supports for [low-resource relation extraction](https://github.com/zjunlp/DeepKE/tree/main/example/re/few-shot)

**Comment by gshzjzbb** [comment]
![Uploading mmexport1715844102433.jpg…]()

**Comment by gshzjzbb** [comment]
![mmexport1715844102433](https://github.com/zjunlp/DeepKE/assets/170032834/4b4bc9ea-0458-46e7-a744-594eacd38b30)
