### ISSUE TITLE
自己的数据

### ISSUE THREAD

**Issue by wangxinzhe123** [zjunlp/DeepKE#166]
我用自己的数据跑二分类的实验，准确率接近100%，用乱编的数据准确率仍是接近100%，我不清楚是哪里出了问题

**Comment by tlk1997** [comment]
哪个任务那个模型呢

**Comment by wangxinzhe123** [comment]
关系抽取，standard ,model选的lm

**Comment by wangxinzhe123** [comment]
> 哪个任务哪个模型呢
关系抽取，standard ,model选的lm

**Comment by tlk1997** [comment]
你那乱编的数据是啥意思呢

**Comment by wangxinzhe123** [comment]
[就是我想用这个模型训练一个区别上下位关系的模型，然后我发现训练之后准确率过高，我就用图二自动生成的语句想判断一下模型的效果是否真的那么好。
乱编的数据类似下面这种，完全看不出关系的数据，他仍能判断出他具有上下位关系：
螺杆泵 机械泵 上下位关系 自己出来到了阅读.螺杆泵欢迎机械泵具有服务投资其实学习控制国内

**Comment by zxlzr** [comment]
您好，感谢您使用deepke，可能的原因如下：

1.模型缺少高质量负样本，就是模型训练时候的正样本和负样本区分度不大；建议您收集更多高质量样本训练。
2.模型过拟合了导致泛化较差，建议您打印出类别的置信度修改阈值，这种情况的话目前传统模型也没法很好解决，建议结合一些规则来做决策比如关键词的匹配、ngram匹配等
