### ISSUE TITLE
运行example出错

### ISSUE THREAD

**Issue by CrawlingForward** [zjunlp/DeepKE#167]
**Describe the question**
> A clear and concise description of what the question is.
您好，非常感谢作者共享此项目。我按照`Quick Start`中描述的步骤配置环境，遇到如下问题：
   下载解压完数据之后，运行`example/re/standard` 下示例 `python run.py` 时报错，信息显示缺少依赖 `tensorboardX` 及 `ipdb`，分别安装依赖包又遇到新问题，请问是什么原因，应如何解决，谢谢！

**Screenshots**
![image](https://user-images.githubusercontent.com/5276761/199139965-5eb779f9-b979-4278-a26f-82e30479937a.png)

**Environment (please complete the following information):**
 - OS: [e.g.  window 10]
 - Python Version [e.g. 3.8]

**Additional context**
> Add any other context about the problem here.

**Comment by tlk1997** [comment]
如果是用pip install deepke方式安装依赖包，可以卸载后改用python setup.py install的方式试试

**Comment by CrawlingForward** [comment]
谢谢，我就是在虚拟环境中，运行`python setup.py install`安装的

**Comment by tlk1997** [comment]
看报错像是hydra包有问题，你可以升级一下这个包的版本试试

**Comment by CrawlingForward** [comment]
`hydra-core`升级有具体版本吗，我看依赖文件要求是`hydra-core == 1.0.6'，现在也是1.0.6，升级之后冲突了
![image](https://user-images.githubusercontent.com/5276761/199144138-071359d9-ec78-4d2f-b0d7-9300dc735f05.png)

**Comment by CrawlingForward** [comment]
我又重新安装回`hydra-core == 1.0.6`，可以跑了
