### ISSUE TITLE
文档级关系抽取可否提供中文示例

### ISSUE THREAD

**Issue by anning19890402** [zjunlp/DeepKE#168]
**Describe the question**
> A clear and concise description of what the question is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
您好，中文我们没找到公开的文档级关系抽取数据集，建议您根据英文的输入修改输入格式，模型替换成中文预训练模型就可以使用的。

**Comment by anning19890402** [comment]
> 您好，中文我们没找到公开的文档级关系抽取数据集，建议您根据英文的输入修改输入格式，模型替换成中文预训练模型就可以使用的。

您好，感谢回复，我研究下

**Comment by kongshengjie** [comment]
请问一下有试过用自己中文数据集做文档级关系抽取吗，模型训练效果（P、R、F1）如何呢？

**Comment by zxlzr** [comment]
您好，文档级抽取没有公开的中文数据，我们没试过。建议您使用大模型做抽取效果好很多。

**Comment by kongshengjie** [comment]
好的，谢谢您的解答
