### ISSUE TITLE
模型效果

### ISSUE THREAD

**Issue by Naplues** [zjunlp/deepke#17]
你好，结果跑出来bert模型的结果比CNN还要差，请问正常吗

**Comment by yuwl798180** [comment]
你好，请问你是在什么数据集上跑的结果对比呀？
如果是在包里的采样数据做的测试，那bert效果是不好的。一是因为数据量太小，二是这个采样数据集纯粹为了跑通，没有添加负样本。所以cnn之类的很容易过拟合，跑到99%都可以的。

另外，现在大家使用语言模型，往往会先使用对应领域的数据集上无监督训练一次，然后再针对特定任务做微调。
比如做金融领域的任务（不管是信息抽取，问答还是其他nlp任务），会先找下金融领域的语料在bert模型上继续无监督训练，这样预训练的模型针对特定领域效果才会更好。

**Comment by Naplues** [comment]
我使用的是包里的数据集，请问您这个项目什么时候公开预测部分的代码呢
