### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'xxx/checkpoints/2019-12-03_17-35-30/cnn_epoch21.pth'

### ISSUE THREAD

**Issue by phucthuan1st** [zjunlp/DeepKE#171]
**Describe the question**
HI team, 
I've install deepKE on my kali, after 11hours trained using run.py, then I run predict.py and got that error.
How can I change the path to other checkpoint file? Where is it locate?

**Environment (please complete the following information):**
 - OS: Kali Linux
 - Python Version Anaconda Environment, Python 3.8.15

**Screenshots**
![image](https://user-images.githubusercontent.com/57631474/202616690-8f2a9ea4-9d58-4bf9-9555-55f4d3850344.png)

Hope to see your respond soon. Thanks for advance

**Comment by xxupiano** [comment]
Hi,
Before prediction, please set the 'fp' in https://github.com/zjunlp/DeepKE/blob/main/example/re/standard/conf/predict.yaml as the path of the checkpoint obtained during training.
