### ISSUE TITLE
python setup.py install出错Could not find suitable distribution for Requirement.parse('pyld==2.0.3')

### ISSUE THREAD

**Issue by LittleZ2022** [zjunlp/DeepKE#172]
**Describe the question**
您好，在安装deepke时出错，执行conda activate deepke时报错，但是已进入虚拟环境？
之后执行python setup.py install时报错，Could not find suitable distribution for Requirement.parse('pyld==2.0.3')，请问如何解决呀？

**Environment (please complete the following information):**
 - OS: [window]
 - Python Version [3.8]

**Screenshots**
![image](https://user-images.githubusercontent.com/113521234/202852166-826a683f-105a-4f9c-bb69-6fe70c190dc5.png)

**Comment by tlk1997** [comment]
你好，可以将setup.py中的pyld==2.0.3换成PyLD试试，如果还是下载不了，删除这一行，这个包仅用于[三元组抽取预测函数](https://github.com/zjunlp/DeepKE/blob/main/example/triple/predict.py)中，不影响其余部分使用。

**Comment by LittleZ2022** [comment]
您好，删除后又提示倒数第二个包could not find了。我重新再试试，谢谢您的解答

**Comment by tlk1997** [comment]
也有可能是因为没有用国内镜像源，需要将conda和pip换成国内的源

**Comment by LittleZ2022** [comment]
您好，已更换国内镜像源。然后出现了issue里另一个问题cachetools 5.2.0 is installed but cachetools<5.0,>=2.0.0 is required by {'google-auth'}

**Comment by LittleZ2022** [comment]
我去那个issue再瞅一眼
