### ISSUE TITLE
训练时出现问题

### ISSUE THREAD

**Issue by zmt1002** [zjunlp/DeepKE#173]
你好，我在开始训练后出现 UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
请问这大概是什么原因呢？

**Comment by GoooDte** [comment]
请问是在训练哪个文件时出现的问题呢

**Comment by tlk1997** [comment]
这应该是使用某个工具时某个进程使用结束没被关闭，并不影响模型使用

**Comment by xxupiano** [comment]
你好，可参考
https://blog.csdn.net/weixin_40286308/article/details/124870766
https://stackoverflow.com/questions/64515797/there-appear-to-be-6-leaked-semaphore-objects-to-clean-up-at-shutdown-warnings-w
可能是wandb的warning，不影响使用
