### ISSUE TITLE
程序运行有2个bug

### ISSUE THREAD

**Issue by XxxAtlantis** [zjunlp/DeepKE#174]
**Describe the bug**
1.few_shot ner的model 文件  _beam_search_generate 函数，num_samples 应该要加括号。
https://github.com/zjunlp/DeepKE/blob/0b4430c7c1eaf09de38476a3e0bd3e8c56637a44/src/deepke/name_entity_re/few_shot/models/model.py#L503

https://github.com/zjunlp/DeepKE/blob/0b4430c7c1eaf09de38476a3e0bd3e8c56637a44/src/deepke/name_entity_re/few_shot/models/model.py#L509

2.这个地方也报bug，AttributeError: 'super' object has no attribute 'reorder_state'
https://github.com/zjunlp/DeepKE/blob/0b4430c7c1eaf09de38476a3e0bd3e8c56637a44/src/deepke/name_entity_re/few_shot/models/model.py#L318

**Comment by zxlzr** [comment]
感谢您指出bug，我们尽快修复

**Comment by Flow3rDown** [comment]
> **Describe the bug** 1.few_shot ner的model 文件 _beam_search_generate 函数，num_samples 应该要加括号。
> 
> https://github.com/zjunlp/DeepKE/blob/0b4430c7c1eaf09de38476a3e0bd3e8c56637a44/src/deepke/name_entity_re/few_shot/models/model.py#L503
> 
> https://github.com/zjunlp/DeepKE/blob/0b4430c7c1eaf09de38476a3e0bd3e8c56637a44/src/deepke/name_entity_re/few_shot/models/model.py#L509
> 
> 2.这个地方也报bug，AttributeError: 'super' object has no attribute 'reorder_state'
> 
> https://github.com/zjunlp/DeepKE/blob/0b4430c7c1eaf09de38476a3e0bd3e8c56637a44/src/deepke/name_entity_re/few_shot/models/model.py#L318

感谢指出bug，已修复。
