### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by qige96** [zjunlp/DeepKE#175]
**Describe the bug**
> A clear and concise description of what the bug is.

```
(deepke) ricky@remote:~/codespace/DeepKE/example/re/few-shot$ python run.py
  File "run.py", line 99
    for (index + 1) % cfg.gradient_accumulation_steps == 0  or (index + 1) == num_batch:
                                                      ^
SyntaxError: invalid syntax
```

Inspecting the [code](https://github.com/zjunlp/DeepKE/blob/main/example/re/few-shot/run.py#L99), simply change `for` to `if` can fix the bug

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python Version: 3.8

**Comment by xxupiano** [comment]
We have fixed it. Please try it again.
