### ISSUE TITLE
快速上手中python predict.py报错

### ISSUE THREAD

**Issue by LittleZ2022** [zjunlp/DeepKE#176]
**Describe the question**
您好，按照readme里快速上手，运行到python predict.py时报错。请问怎么解决呀？
`RuntimeError: The size of tensor a (48) must match the size of tensor b (512) at non-singleton dimension 3
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
`

**Environment (please complete the following information):**
 - OS: window
 - Python Version 3.8

**Screenshots**
![image](https://user-images.githubusercontent.com/113521234/204186403-e8f0f167-e730-4537-887b-df574a4c6cac.png)

**Comment by xxupiano** [comment]
请把报错截全一些，目前不确定是什么任务代码。请问您跑的是哪个代码？

**Comment by tlk1997** [comment]
更新下最新代码，这个bug已经修复

**Comment by LittleZ2022** [comment]
> 

您好，不好意思运行结果有些多就没有截全。是task\githubproject\DeepKE\example\re\standard>python predict.py

**Comment by LittleZ2022** [comment]
> 

好嘞谢谢，我试一下
