### ISSUE TITLE
实体识别更换数据集 lstmcrf训练时报找不到.pth错误

### ISSUE THREAD

**Issue by nTjing** [zjunlp/DeepKE#177]
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/113650779/204192787-3dfd3264-9d8e-4d6a-9963-a00ecb2ea315.png">
标签设置为：labels: ['LOC','ORG','PER', 'GPE']

**Comment by xxupiano** [comment]
可参考 #147

**Comment by nTjing** [comment]
> 可参考 #147

D:\software\anaconda3\envs\deepke\python.exe D:/postgraduate/Project/deepke-main/example/ner/standard/run_lstmcrf.py
11/28/2022 14:43:36 - INFO - deepke.relation_extraction.multimodal.models.clip.file_utils -   PyTorch version 1.11.0 available.
11/28/2022 14:43:36 - INFO - pytorch_transformers.modeling_bert -   Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
11/28/2022 14:43:36 - INFO - pytorch_transformers.modeling_xlnet -   Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
11/28/2022 14:43:37 - INFO - deepke.name_entity_re.multimodal.models.clip.file_utils -   PyTorch version 1.11.0 available.
D:\software\anaconda3\envs\deepke\lib\site-packages\hydra\plugins\config_source.py:190: UserWarning: 
Missing @package directive hydra/output/custom.yaml in file://D:\postgraduate\Project\deepke-main\example\ner\standard\conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
D:\software\anaconda3\envs\deepke\lib\site-packages\hydra\plugins\config_source.py:190: UserWarning: 
Missing @package directive train.yaml in file://D:\postgraduate\Project\deepke-main\example\ner\standard\conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
D:\software\anaconda3\envs\deepke\lib\site-packages\hydra\plugins\config_source.py:190: UserWarning: 
Missing @package directive predict.yaml in file://D:\postgraduate\Project\deepke-main\example\ner\standard\conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
D:\software\anaconda3\envs\deepke\lib\site-packages\hydra\plugins\config_source.py:190: UserWarning: 
Missing @package directive hydra/model/lstmcrf.yaml in file://D:\postgraduate\Project\deepke-main\example\ner\standard\conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
  0%|          | 0/22 [00:00<?, ?it/s]
100%|██████████| 22/22 [06:09<00:00, 16.81s/it]>>Epoch1: Loss:3299.385955810547

Epoch: 100%|██████████| 1/1 [06:21<00:00, 381.19s/it]
>> total: 10409 f1: 0.0 loss: 79.78196122305734
Traceback (most recent call last):
  File "D:/postgraduate/Project/deepke-main/example/ner/standard/run_lstmcrf.py", line 129, in main
    evaluation_model = torch.load(os.path.join(utils.get_original_cwd(), cfg.output_dir, cfg.model_save_name))
  File "D:\software\anaconda3\envs\deepke\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\software\anaconda3\envs\deepke\lib\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\software\anaconda3\envs\deepke\lib\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\postgraduate\\Project\\deepke-main\\example\\ner\\standard\\checkpoints\\model.pth'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
100%|██████████| 22/22 [06:21<00:00, 17.35s/it]

进程已结束,退出代码1
修改之后还是报错

**Comment by pengzju** [comment]
这是因为您的f1值为0，训练的第一个Epoch没有保存模型的权重。（我建议您调整超参，使得第一个Epoch的f1值大于0）
或者您可以将max_avg_f1改为-1，具体可见
https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/run_lstmcrf.py#L65

**Comment by nTjing** [comment]
> 这是因为您的f1值为0，训练的第一个Epoch没有保存模型的权重。（我建议您调整超参，使得第一个Epoch的f1值大于0） 或者您可以将max_avg_f1改为-1，具体可见 https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/run_lstmcrf.py#L65

谢谢您的解答！感谢
