### ISSUE TITLE
如果待识别的是问句呢？

### ISSUE THREAD

**Issue by MrRace** [zjunlp/deepke#18]
如果待抽取的句子是一个问句，比如"姚明的老婆是谁?"，此时是否支持抽取出 实体 “姚明” ，还有 关系属性 “老婆”？

**Comment by yuwl798180** [comment]
你好，你这是典型的KBQA问题，就是利用抽取后的三元组所构成的图谱数据来做问答。
可以搜索下基于知识图谱的问答系统，相关文章很多的。
