### ISSUE TITLE
NameError: name 'writer' is not defined

### ISSUE THREAD

**Issue by nTjing** [zjunlp/DeepKE#180]
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/113650779/204409242-25a81176-d848-4348-9b53-ab47f5e27156.png">
zjunlp/deepke/example/ner/few-shot 运行run.py时报NameError: name 'writer' is not defined
想问一下writer如何定义？

**Comment by Flow3rDown** [comment]
您好，请更新下deepke版本，现版本已有`writer`的定义，详见[DeepKE/example/ner/few-shot/run.py](https://github.com/zjunlp/DeepKE/blob/d5cc15e3de99e2b5eb532ffcae40ba89e1f8eae6/example/ner/few-shot/run.py#L24).
