### ISSUE TITLE
No module named 'deepke'

### ISSUE THREAD

**Issue by dptong** [zjunlp/DeepKE#181]
**Describe the question**
> A clear and concise description of what the question is.
我按照步骤执行re/documen/run.py时，报异常：
Traceback (most recent call last):
  File "run.py", line 13, in <module>
    from deepke.relation_extraction.document import *
ModuleNotFoundError: No module named 'deepke'

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]
OS: UBUNTU
Python：3.8.13（anaconda）

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/40054462/204414215-12141b3c-a228-4055-806a-ade2927b526d.png)

**Additional context**
> Add any other context about the problem here.

**Comment by xxupiano** [comment]
请安装deepke环境

**Comment by zxlzr** [comment]
麻烦您参考Quick Start按照下环境和相关包
