### ISSUE TITLE
在运行ner的few-shot的predict.py文件时出现问题：IndexError: list index out of range

### ISSUE THREAD

**Issue by zmt1002** [zjunlp/DeepKE#186]
**Describe the bug**
似乎是在运行deepke/name_entity_re/few_shot/module/train.py文件的这个语句出现的问题： line 155, in predict
    self.logger.info("Raw texts: " + " ".join(texts[idx]))
请问一下这个问题该怎么解决？谢谢！

**Environment (please complete the following information):**
 - OS: [e.g. mac ]
 - Python Version [3.8]

**Screenshots**
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/118165453/206203553-dce72f30-0c1a-4790-bc42-a606b590d68b.png">

**Comment by Flow3rDown** [comment]
请问运行的哪个数据集？

**Comment by zmt1002** [comment]
> 请问运行的哪个数据集？

是我自己建的一个数据集

**Comment by Flow3rDown** [comment]
那你的数据集包含`test_data`吗，`predict`函数是预测`test_data`的，目测是`test_data`为None导致`texts`为空，所以出现`list index out of range`错误。
