### ISSUE TITLE
运行DeepKE/example/ner/standard/predict.py对英文数据预测出错

### ISSUE THREAD

**Issue by qinglongheu** [zjunlp/DeepKE#189]
text: "The remarkable achievements attribute to the poverty eliminationproject by government。"
报错
 File "/home/qinglong/.conda/envs/deepke/lib/python3.8/site-packages/deepke-2.1.1-py3.8.egg/deepke/name_entity_re/standard/models/InferBert.py", line 77, in tokenize
    if self.cfg.lan == "en":
omegaconf.errors.ConfigAttributeError: Key 'lan' is not in struct
	full_key: lan
	reference_type=Optional[Dict[Union[str, Enum], Any]]
	object_type=dict

**Comment by xxupiano** [comment]
根据README，修改config.yaml中lan为en

**Comment by qinglongheu** [comment]
建议修改一下inferBert.py中151行words = list(text)
text为字符串‘'The remarkable achievements attribute to the poverty eliminationproject by government。’的话， words = ['T', 'h', 'e', ' ', 'r', 'e', 'm', 'a', 'r', 'k', 'a', 'b', 'l', 'e', ' ', 'a', 'c', 'h', 'i', 'e', 'v', 'e', 'm', 'e', 'n', 't', 's', ' ', 'a', 't', 't', 'r', 'i', 'b', 'u', 't', 'e', ' ', 't', 'o', ' ', 't', 'h', 'e', ' ', 'p', 'o', 'v', 'e', 'r', 't', 'y', ' ', 'e', 'l', 'i', 'm', 'i', 'n', 'a', 't', 'i', 'o', 'n', 'p', 'r', 'o', 'j', 'e', 'c', 't', ' ', 'b', 'y', ' ', 'g', 'o', 'v', 'e', 'r', 'n', 'm', 'e', 'n', 't', '。']
改成words = text.strip('.').split(' ')

**Comment by xxupiano** [comment]
英文使用nltk分词了，但是您目前使用的是中文分词，请使用英文版本。可能您没有更新代码，再次git pull一下
