### ISSUE TITLE
关于用deepke模型在NYT数据集上，使用GCN做关系抽取的问题

### ISSUE THREAD

**Issue by XuanFengWen** [zjunlp/deepke#19]
感谢您开源关系抽取套件，我想请问您如果我想使用NYT数据集，该怎么改动源代码呢？因为源代码中没有注释，还请您耐心回答下，非常感谢、

**Comment by yuwl798180** [comment]
你好，中文和英文最大的区别主要在于数据的预处理上。
中文主要考虑是否分词的问题，而英文则需要把预料中的各种标点处理掉。这一步骤成为序列化。
我在dev中重新修改了这块代码，稍后会整合到master里。

另外，使用gcn的问题，目前做gcn基本是将每个词当作node，然后parsing tree中相连的词语作为node相连的edge。这是一个非常强的先验信号，所以才会让gcn效果比一般cnn，rnn好很多。
英文parsing tree的工具，使用stanford nlp 工具就可以，但是他不能做简体中文的处理。
