### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by jiadiwu** [zjunlp/DeepKE#190]
**Describe the question**
> A clear and concise description of what the question is.
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Environment (please complete the following information):**
 - OS: mac
 - Python 3.8

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by GoooDte** [comment]
Thanks for your issue and we will fix this problem soon !

**Comment by GoooDte** [comment]
You can first downgrade protobuf to 3.20.1 for further use.

**Comment by zxlzr** [comment]
We will try to fix the version bug soon.

**Comment by tlk1997** [comment]
Hello, the dependent packages used in DeepKE have been updated. You can reinstall DeepKE now.
