### ISSUE TITLE
怎样调用GPU跑代码？

### ISSUE THREAD

**Issue by zmt1002** [zjunlp/DeepKE#191]
**Describe the question**
你好，在使用CPU跑deepke/example/re/few-shot的代码过程中，训练速度很慢，想请问一下在这个项目里如何调用GPU去跑代码？

**Comment by tlk1997** [comment]
https://github.com/zjunlp/DeepKE/blob/main/example/re/few-shot/run.py#L44      这一行如果cuda可用会用机器中第一张gpu卡跑
