### ISSUE TITLE
re的few-shot自备数据集

### ISSUE THREAD

**Issue by LittleZ2022** [zjunlp/DeepKE#192]
请问re的few-shot训练自定义数据集时有测试中文的经验吗，需要注意些什么问题？目前看到提供的数据集是英文的。

比如，如果可以训练中文数据集，请问怎么准备数据集的格式，是按照目前英文数据集的四个文件的格式来吗？现在已经用doccano标注好数据了。

**Comment by xxupiano** [comment]
改用中文LM和中文tokenizer，格式可参考目前的英文数据集。
建议可以直接使用中文版Knowprompt：https://github.com/zjunlp/LREBench，其中有中文数据集DuIE2.0和CMeIE示例，运行脚本见https://github.com/zjunlp/LREBench/tree/main/scripts
