### ISSUE TITLE
deepke这个框架是属于开放域信息抽取吗？？

### ISSUE THREAD

**Issue by qinglongheu** [zjunlp/DeepKE#198]
**Describe the question**
> A clear and concise description of what the question is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
您好，deepke 不属于开放域信息抽取，需要定义好实体和关系类型
