### ISSUE TITLE
re/few-shot/run.py文件读取train.yaml配置文件中accumulate_grad_batches配置项的类型和代码中用到类型不一致

### ISSUE THREAD

**Issue by yinxiaolog** [zjunlp/DeepKE#199]
**Describe the bug**
> A clear and concise description of what the bug is.

train.yaml中为accumulate_grad_batches: '1'，字符串类型，代码第99行当成int运算

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/43245392/208428141-e396c17c-6265-4f7a-8104-de7f7da547c5.png)
![image](https://user-images.githubusercontent.com/43245392/208428177-6ab0dee5-b8ce-400a-b614-40899e42f581.png)
![image](https://user-images.githubusercontent.com/43245392/208428216-f9cde1b9-84ea-49cc-a405-4d893a9e60c5.png)

**Additional context**
> Add any other context about the problem here.

**Comment by tlk1997** [comment]
感谢提issue，该问题已修复
