### ISSUE TITLE
ae/standard/run.py文件中会用到device_ids变量，但是当单卡训练时，这个变量不会被生命，后面又会用到，会报错。

### ISSUE THREAD

**Issue by yinxiaolog** [zjunlp/DeepKE#200]
![image](https://user-images.githubusercontent.com/43245392/208428410-6fab82d8-a4c3-4d7f-aa14-09a6313f9c45.png)
![image](https://user-images.githubusercontent.com/43245392/208428436-f047ccc6-4836-4495-a0f8-94dd669d4ab2.png)
![image](https://user-images.githubusercontent.com/43245392/208428462-2327d8a2-083b-463a-9f28-46b3cae01dab.png)

**Comment by tlk1997** [comment]
感谢提issue，该问题已修复
