### ISSUE TITLE
example中的三元组提取是联合提取吗？能否提供一个readme文件讲解一下如何提取的？

### ISSUE THREAD

**Issue by qinglongheu** [zjunlp/DeepKE#201]
**Describe the question**
> A clear and concise description of what the question is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
您好，三元组是由实体识别https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/README_CN.md 和关系抽取https://github.com/zjunlp/DeepKE/blob/main/example/re/standard/README_CN.md 两步完成的，目前deepke 没有提供端到端抽取的（后续会支持），您可以在这里https://github.com/zjunlp/DeepKE/blob/main/README_CNSCHEMA_CN.md 找到抽取三元组的方式
