### ISSUE TITLE
运行ner-standard的run_bert.py，wandb报错

### ISSUE THREAD

**Issue by Lpover** [zjunlp/DeepKE#202]
![image](https://user-images.githubusercontent.com/43440585/209162333-af43e26f-fd67-43dc-bfcb-80b4101befa2.png)

**Comment by zxlzr** [comment]
您好， 可能是包版本问题，建议您检查下是否是虚拟环境且本地包的版本和requirement一致的，您可以先关闭wandb再运行

**Comment by tlk1997** [comment]
您好，https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/conf/config.yaml#L13 这一行需要改为bert
