### ISSUE TITLE
运行ner-standard的run_lstmcrf.py，源码安装的，对照requirement换了版本

### ISSUE THREAD

**Issue by Lpover** [zjunlp/DeepKE#203]
![image](https://user-images.githubusercontent.com/43440585/209355825-e214c3ba-2654-43fc-9a72-d855e0e9b35a.png)
使用run_bert和run_lstmcrf都是这样报错，请问这是啥报错啊

**Comment by tlk1997** [comment]
可以更新下setuptools包版本 pip install --upgrade setuptools

**Comment by Lpover** [comment]
> 可以更新下setuptools包试试 pip install --upgrade setuptools

您好，第一个Traceback解决了，但是第二个“AttributeError: module 'numpy' has no attribute 'object'”仍然存在

**Comment by tlk1997** [comment]
> > 可以更新下setuptools包试试 pip install --upgrade setuptools
> 
> 您好，第一个Traceback解决了，但是第二个“AttributeError: module 'numpy' has no attribute 'object'”仍然存在

numpy包卸载了再安装试试

**Comment by Lpover** [comment]
> > > 可以更新下setuptools包试试 pip install --upgrade setuptools
> > 
> > 
> > 您好，第一个Traceback解决了，但是第二个“AttributeError: module 'numpy' has no attribute 'object'”仍然存在
> 
> numpy包卸载了再安装试试

尝试了，但是好像不是numpy包的问题

**Comment by Lpover** [comment]
> > > 可以更新下setuptools包试试 pip install --upgrade setuptools
> > 
> > 
> > 您好，第一个Traceback解决了，但是第二个“AttributeError: module 'numpy' has no attribute 'object'”仍然存在
> 
> numpy包卸载了再安装试试

![image](https://user-images.githubusercontent.com/43440585/209422450-b13f0c54-4adf-46e1-95c1-3eca020bc88e.png)
安装的1.24.0的numpy

**Comment by Lpover** [comment]
numpy降级到1.18.5就可以了
