### ISSUE TITLE
ner中few-shot的predict.py出错

### ISSUE THREAD

**Issue by Lpover** [zjunlp/DeepKE#205]
![image](https://user-images.githubusercontent.com/43440585/209514810-efc62f6a-6d4a-42f9-958f-3e3430ce513b.png)
load_path和write_path都设置好了

**Comment by Flow3rDown** [comment]
非常抱歉，已修复
[example/ner/few-shot/predict.py](https://github.com/zjunlp/DeepKE/blob/5f2fab1f74fb4f28a23f377c5865d5b4c445bd7d/example/ner/few-shot/predict.py#L48)
