### ISSUE TITLE
DeepKE/example/re/standard gives an Error.

### ISSUE THREAD

**Issue by Du-danger** [zjunlp/DeepKE#207]
DeepKE/example/re/standard gives an Error.

I follow the procedure step by step, but get an error which is:
/home/xxx/anaconda3/envs/deepke/lib/python3.8/site-packages/numpy-1.24.1-py3.8-linux-x86_64.egg/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'object'

Is this is a bug?

**Comment by yang-md** [comment]
The error is happened, when I execute ''python run.py'' in dir DeepKE/example/re/standard.

**Comment by xxupiano** [comment]
Please try to reinstall *numpy==1.18.5*.
And we have updated *setup.py*.

**Comment by Du-danger** [comment]
After ''reinstall numpy==1.18.5'', but get a new error:
File "/home/ymd/anaconda3/envs/deepke/lib/python3.8/site-packages/botocore-1.24.45-py3.8.egg/botocore/httpsession.py", line 21, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/home/ymd/anaconda3/envs/deepke/lib/python3.8/site-packages/urllib3-2.0.0a2-py3.8.egg/urllib3/util/ssl_.py)

HaoJiaHuo!

**Comment by xxupiano** [comment]
Maybe you can try ``pip install --upgrade urllib3``.

**Comment by tlk1997** [comment]
You can try to Install with the latest `setup.py` file
