### ISSUE TITLE
hydra-core 版本问题

### ISSUE THREAD

**Issue by EightMonth** [zjunlp/DeepKE#209]
我是今天拉的master代码，但我在conda里面是使用的pip install deepke。在运行/example/re/standard/run.py时，出现以下问题

需要安装以下依赖
pip install future
pip install numpy

另外hydra-core的版本始终存在问题，我先后做了如下操作：
1.卸载当前hydra-core， pip uninstall hydra-core
2.安装最新版hydra-core, pip install hydra-core --upgrade
此时会有提示，deepke引用的是hydra-core==1.0.6版本，但是这时没理会这个提示
4.我尝试py run.py，会报hydra 模块找不到
5.更新hydra-core版本为1.0.6后，还是报了同样的hydra 模块找不到

**Comment by zxlzr** [comment]
您好，建议您使用python setup.py install，pip 的包会因为缓存原因可能仍然是老版本，其他问题会有专门同学回复。

**Comment by xxupiano** [comment]
已更新*setup.py*，请使用``python setup.py install``再次安装

**Comment by tlk1997** [comment]
如果还是未能安装，可以将setup.py中的20行设置为空list后安装src中源码，并直接pip install -r requirements.txt

**Comment by EightMonth** [comment]
感谢各位，已成功安装。

**Comment by ZionDoki** [comment]
> 如果还是未能安装，可以将setup.py中的20行设置为空list后安装src中源码，再直接pip install -r requirements.txt

感谢，出现了各种问题，最后按这个成功安装了= =。
