### ISSUE TITLE
请教，为什么模型的最后一层都不是用softmax

### ISSUE THREAD

**Issue by rivenarchy** [zjunlp/deepke#21]
我想问一下LOSS用的交叉熵什么最后的激活函数用的relu,是为了可以发现多种关系的意思吗

**Comment by yuwl798180** [comment]
你好，pytorch中 CrossEntropyLoss 是 LogSoftmax 与 NLLLoss 的整合。
建议看下 [api](https://pytorch.org/docs/stable/nn.html#crossentropyloss)
