### ISSUE TITLE
deepke在知识图谱中的定位是什么

### ISSUE THREAD

**Issue by EightMonth** [zjunlp/DeepKE#211]
deepke团队，你们好：
想请问一下，deeepke在知识图谱中的流程定位是什么，可以去操作哪些流程

**Comment by zxlzr** [comment]
您好，deepke是一个知识抽取工具，可以进行实体识别、关系抽取和属性抽取，支持从文本等数据中获取事实三元组构建知识图谱，详情可以参见readme的使用说明。
