### ISSUE TITLE
 DeepKE-cnSchema-RE|修改关系数量为51后，读取的关系数量仍然为11

### ISSUE THREAD

**Issue by 480284856** [zjunlp/DeepKE#212]
作者你们好，我遇到的问题为：
**Describe the bug**

我按照[该链接](https://github.com/zjunlp/DeepKE/blob/main/README_CNSCHEMA_CN.md#%E5%85%B3%E7%B3%BB%E6%8A%BD%E5%8F%96re-1)修改了*embedding.yaml*中的*num_relations*为51，但是在跑预测时，example/re/standard/predict.py中的第142行
```python
prob_rel = list(rels.keys())[y_pred.argmax().item()]
```
还是会报错，说是index out of range，调试时，* list(rels.keys())*的长度为11，*y_pred.argmax().item()*为42.

**报错复现:**
1. 使用pycharm运行：example/re/standard/predict.py
2. 输入‘no’之后，
句子为：知识图谱已经在人工智能的各个领域发挥越来越重要的作用
头实体为：知识图谱
头实体类型为：学科专业
尾实体为：人工智能
尾实体类型为：学科专业

运行后，下图划红线的部分的结果为：
```
11
y_pred: 29
```
![image](https://user-images.githubusercontent.com/69774354/210539090-55b66333-3915-41c3-85af-023dc0a799ea.png)

**深入了解**
变量*rels*的值由如下代码给予：
![image](https://user-images.githubusercontent.com/69774354/210540063-199e0f45-d7a4-4950-985d-306176ea3b9f.png)
进入该函数，感觉是读取了一个csv文件：
![image](https://user-images.githubusercontent.com/69774354/210540257-505f6cb0-5f4f-4c1e-b4c0-ce9ebec78faa.png)
打开该csv文件后，发现刚好为11个关系：
![image](https://user-images.githubusercontent.com/69774354/210540467-0e879ece-adee-4f02-9911-e09ab55dd940.png)

**可能的解决方案**
函数```_preprocess_data```在代码```example/re/standard/predict.py```中貌似是必定执行的，而且在```embedding.yaml```中修改```num_relations```好像只修改了模型的架构，但是索引到标签的映射表的长度还是11.我想问的是：这个[【关系Schema】](https://github.com/zjunlp/DeepKE/blob/main/README_CNSCHEMA_CN.md#%E5%85%B3%E7%B3%BBschema)中，是否为训练时的“index to label”，就是说，模型的给出的probability vector的索引是否跟上述链接的数字 对应的标签是否一致？如果是的话，那么我就可以手动创建一个csv文件了。

**Comment by tlk1997** [comment]
你好，使用提到的[关系Schema](https://github.com/zjunlp/DeepKE/blob/main/README_CNSCHEMA_CN.md#%E5%85%B3%E7%B3%BBschema)所训练的模型，在进行预测的时候，需要将data中的relation.csv也替换成cnSchema所对应的关系类型文件

**Comment by tlk1997** [comment]
你好，使用提到的[关系Schema](https://github.com/zjunlp/DeepKE/blob/main/README_CNSCHEMA_CN.md#%E5%85%B3%E7%B3%BBschema)所训练的模型，在进行预测的时候，需要将data中的relation.csv也替换成cnSchema所对应的关系类型文件

**Comment by 480284856** [comment]
@tlk1997 就是[这个文件](https://github.com/zjunlp/DeepKE/blob/main/README_CNSCHEMA_CN.md#%E5%85%B3%E7%B3%BBschema)吗？

**Comment by 480284856** [comment]
好的，谢谢
