### ISSUE TITLE
标签集存在重复

### ISSUE THREAD

**Issue by 480284856** [zjunlp/DeepKE#213]
如下图所示，原本应该是长度为50的标签集，但实际长度为47：
![image](https://user-images.githubusercontent.com/69774354/210689054-bbb787f0-9e10-425b-b655-c1f8bcde441d.png)
原因：
下面的操作会使得关系名相同，但是头尾实体类型不同的三元组之间会相互覆盖：
![image](https://user-images.githubusercontent.com/69774354/210689178-9d5502be-c1f0-4c77-bd53-c78b2534c455.png)

**Comment by tlk1997** [comment]
感谢纠错，之后会将数据集标签区分开来后重新训练模型并上传

**Comment by 480284856** [comment]
好的，期待后面的工作结果：）

**Comment by tlk1997** [comment]
已上传colab，可直接使用
