### ISSUE TITLE
torch模块找不到

### ISSUE THREAD

**Issue by EightMonth** [zjunlp/DeepKE#214]
![image](https://user-images.githubusercontent.com/23272421/211276493-60bd5001-d12f-4946-a6f9-f261fbf92346.png)
请问这是什么问题，始终找不到这个包。提示的是大于等于1.5，小于等于1.10，但是已经特意安装到1.10版本还是不行

**Comment by tlk1997** [comment]
可以通过pip list命令查看一下当前环境中有没有安装torch包，有的话可以去pytorch官网按照对应命令来重新进行安装

**Comment by EightMonth** [comment]
![image](https://user-images.githubusercontent.com/23272421/211282096-5dbd6f8b-de7b-4b05-aedb-47fb4e5c5e29.png)
刚刚又换了1.7.1版本的试了，还是不行，在pip list中也是有的，可以看图

**Comment by EightMonth** [comment]
新写的python文件只写了一行import torch，运行起来也是找不到，这应该是我本地的问题了吧

**Comment by EightMonth** [comment]
![image](https://user-images.githubusercontent.com/23272421/211289327-24942100-de87-43d4-8b01-7d3f77e7af73.png)
在conda中的python交互环境还是可以导入的

**Comment by tlk1997** [comment]
要不重新安装环境试试？

**Comment by EightMonth** [comment]
重新安装环境后依旧有这个问题，步骤如下：
windows conda 创建 python 3.8.15 环境
根据源码安装，先后分别执行py setup.py install ; py setup.py develop(setup.py文件第20行被我设置成空字符串了)
pip install -r requirement.txt

再回来py predicate.py

报错如下：
![image](https://user-images.githubusercontent.com/23272421/211443176-3cd6ef2b-d7ee-45fc-8787-011b2b2b04c7.png)

**Comment by xxupiano** [comment]
从报错路径可以看出目前环境在\dev\source_code xxx，不是conda环境。
请用'python'而不是'py'执行python脚本，例如`python predict.py`

**Comment by EightMonth** [comment]
这个问题解决了，又跑出来下一个问题，算了
