### ISSUE TITLE
安装包版本错误导致无法运行快速上手例子

### ISSUE THREAD

**Issue by swang88** [zjunlp/DeepKE#217]
**Describe the bug**
> A clear and concise description of what the bug is.
似乎是transformers4.5对应的tokenizers 0.10.3在一个version.py文件中报错，又因为deepke对这些包版本有严格要求，无法更改版本，这个错误无法解决导致执行DeepKE\example\ner\standard\run_bert.py文件报错。

**Environment (please complete the following information):**
 - OS: [ window]
 - Python Version [e.g. 3.8]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/28115406/216196493-8bc1b8a7-ab9e-46e1-a085-f9074314649e.png)

**Additional context**
> Add any other context about the problem here.

**Comment by swang88** [comment]
错误显示为raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '0.10.1,<0.11'。 我理解这里应该是参数传入有问题，这个version应该是0.10.3吧

**Comment by GoooDte** [comment]
感谢您的issue，您可以将deepke的transformer版本降至3.4.0，先尝试忽略deepke对包版本的要求以保证运行畅通

**Comment by zxlzr** [comment]
非常抱歉这是python 库版本问题，建议您降低transformer 版本，我们将在近期重构和更新python库以彻底解决该问题。

**Comment by DeoooChen** [comment]
> 非常抱歉这是python 库版本问题，建议您降低transformer 版本，我们将在近期重构和更新python库以彻底解决该问题。

OS: [Windows]
Python Version: [3.8.16]
![image](https://user-images.githubusercontent.com/124671489/237047579-25d44786-76db-40a0-9912-4034661d0a96.png)


您好，现在我把transformers==4.5.0换成了3.4.0，运行DeepKE-main\example\re\standard\run.py时不会出现“
raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '0.10.1,<0.11
”该问题了，但是出现了新的问题：
“
Traceback (most recent call last):
  File "E:/python code/intership/DeepKE-main/example/re/standard/run.py", line 14, in <module>
    import deepke.relation_extraction.standard.models as models
  File "C:\Users\HUAWEI\anaconda3\envs\deepke\lib\site-packages\deepke-2.2.1-py3.8.egg\deepke\__init__.py", line 2, in <module>
    from .relation_extraction import *
  File "C:\Users\HUAWEI\anaconda3\envs\deepke\lib\site-packages\deepke-2.2.1-py3.8.egg\deepke\relation_extraction\__init__.py", line 4, in <module>
    from .multimodal import *
  File "C:\Users\HUAWEI\anaconda3\envs\deepke\lib\site-packages\deepke-2.2.1-py3.8.egg\deepke\relation_extraction\multimodal\__init__.py", line 1, in <module>
    from .models import *
  File "C:\Users\HUAWEI\anaconda3\envs\deepke\lib\site-packages\deepke-2.2.1-py3.8.egg\deepke\relation_extraction\multimodal\models\__init__.py", line 2, in <module>
    from .IFA_model import *
  File "C:\Users\HUAWEI\anaconda3\envs\deepke\lib\site-packages\deepke-2.2.1-py3.8.egg\deepke\relation_extraction\multimodal\models\IFA_model.py", line 6, in <module>
    from transformers import BertConfig, BertModel, CLIPConfig, CLIPModel
ImportError: cannot import name 'CLIPConfig' from 'transformers' (C:\Users\HUAWEI\anaconda3\envs\deepke\lib\site-packages\transformers\__init__.py)
”
上述问题截图如下：

![image](https://user-images.githubusercontent.com/124671489/237046753-120d8bfc-8325-487c-afa7-f4f4cd6a6f03.png)

原因应该是在anaconda3\envs\deepke\Lib\site-packages\deepke-2.2.1-py3.8.egg\deepke\relation_extraction\multimodal\models\IFA_model.py中的第6行：from transformers import BertConfig, BertModel, CLIPConfig, CLIPModel

![image](https://user-images.githubusercontent.com/124671489/237047183-21059d55-d238-4f44-968e-48777d83cbf5.png)


而CLIPConfig和CLIPModel在transformers/__init__.py中找不到，请问现在应该怎么办？感谢~

**Comment by xxupiano** [comment]
请运行pip install transformers==3.4.0

**Comment by xxupiano** [comment]
> [DeoooChen](/DeoooChen)

请运行pip install transformers==3.4.0

**Comment by DeoooChen** [comment]
> > [DeoooChen](/DeoooChen)
> 
> 请运行pip install transformers==3.4.0

您好，可能是我前面无关内容比较多了，现在我使用的deepke==2.2.1，也已经运行过了pip install transformers==3.4.0，但是还是出现了如下问题：

![image](https://github.com/zjunlp/DeepKE/assets/124671489/91db4eb6-7fb8-4eb2-854f-b89a68976e20)

**Comment by DeoooChen** [comment]
> > > [DeoooChen](/DeoooChen)
> > 
> > 
> > 请运行pip install transformers==3.4.0
> 
> 您好，可能是我前面无关内容比较多了，现在我使用的deepke==2.2.1，也已经运行过了pip install transformers==3.4.0，但是还是出现了如下问题：
> 
> ![image](https://user-images.githubusercontent.com/124671489/237256402-91db4eb6-7fb8-4eb2-854f-b89a68976e20.png)

您好，我已经解决了。可能是Ipython, gensim或者keras版本的问题。我是在安装完其他项目的环境依赖的时候，发现该问题已经被解决的。但是实际上是为什么，我也不知道...
