### ISSUE TITLE
特别版DeepKE-cnSchema训练

### ISSUE THREAD

**Issue by nTjing** [zjunlp/DeepKE#218]
您好  我想自己训练特别版DeepKE-cnSchema的模型  想问一下是数据集是在这里下载吗？https://drive.google.com/drive/folders/1zA8Ichx9nzU3GD92ptdyR_nmARB_7ovg

目前无法打开这个链接 可以有百度网盘的方式吗？谢谢

**Comment by GoooDte** [comment]
您好我们尝试链接是可以打开的 您可以尝试使用科学上网的方法进行下载
