### ISSUE TITLE
re/standard模型训练结果问题

### ISSUE THREAD

**Issue by zmt1002** [zjunlp/DeepKE#219]
**Describe the question**
你好，我在进行re/standard的模型训练后，没有模型结果存储下来，我想请问一下这是什么原因？是因为我的数据问题吗？
![image](https://user-images.githubusercontent.com/118165453/218056306-787d95d3-5c38-48a3-b310-3c3281e0e3b1.png)

**Comment by GoooDte** [comment]
您好，请您定义https://github.com/zjunlp/DeepKE/blob/66a6bc4e649725b000f5aea1e7391f7ec8460e39/example/re/standard/run.py#L97中的es_path和best_es_path参数为您想要保存模型的路径
