### ISSUE TITLE
关于自己标注数据集

### ISSUE THREAD

**Issue by tantingting1012** [zjunlp/deepke#22]
你好，请问demo内使用的数据集中各个字段详细的含义或者如何标注的能否简单告知吗，我想针对某一个领域自己标注数据集，但是不太理解demo使用的数据字段的含义，比如tail_offset，head_offset

**Comment by yuwl798180** [comment]
你好，关系抽取打标是一件很费时的事情。
demo的数据不是我自己打标的，是采样了百度的数据集的一部分，具体想使用他的数据集，可以见 [网址](https://ai.baidu.com/broad/introduction)

至于具体打标的过程：现在大家基本是采用远程监督的方式，先用已知的三元组与互联网中的语料对齐，得到粗糙的语料。比如想得到 school-isLocatedIn-place 这样的三元组语料，要先有relaton:isLocatedIn （head清华大学-tail北京) 这样的三元组。再用这个三元组到互联网中对齐相应的语句，比如一句话中出现了清华大学和北京，就默认这是一条符合要求的语料。
但是这样一定会存在误标的语句，原因是词语多义和句中head tail并不是描述相应关系。

远程监督得到的语料后，后面就只能用人工校验了。
打标的语句中不仅要标出 head,tail，最好还要标出head_offset, tail_offset，这两个值是为了找出正确的entity位置。比如：南京南站位于南京的东北处。此时想标记南京就要区分到底是哪个南京了。

**Comment by tantingting1012** [comment]
好的，谢谢，方便问一下您这个项目，预测部分代码什么时候公开呢
