### ISSUE TITLE
re/standard模型predict结果关系对应出错

### ISSUE THREAD

**Issue by zmt1002** [zjunlp/DeepKE#220]
**Describe the question**
你好，下面是我data/origin/relation.csv文件的数据，训练模型之后predict，原本应该是“牵头”关系的显示索引超出范围，而原本是”担任“的对应“牵头”，“设立”对应的却是“担任”，而且结果的置信度均为1，我想请问一下这是什么原因？
![image](https://user-images.githubusercontent.com/118165453/218267474-b017a426-6bd7-4829-98f7-a3e59982bfc0.png)

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by tlk1997** [comment]
embedding.yaml中的num-relations是否设置为5，还有置信度是代表模型对本次预测的概率，并不一定正确

**Comment by zmt1002** [comment]
> embedding.yaml中的num-relations是否设置为5，还有置信度是代表模型对本次预测的概率，并不一定正确

num-relations是设置的5

**Comment by zxlzr** [comment]
可能是模型预测错的
