### ISSUE TITLE
ner/standard中的bert和lstmcrf都运行不起来

### ISSUE THREAD

**Issue by xiaohou1112** [zjunlp/DeepKE#221]
您好！
我按照步骤安装好后，放上了自己的数据，执行python run_lstmcrf.py和python run_bert.py
出现以下问题：
![微信图片_20230214222416](https://user-images.githubusercontent.com/62997063/218766119-7f0ee0d8-f539-44cb-ac9d-2e169123a5f0.png)

![微信图png](https://user-images.githubusercontent.com/62997063/218766752-e28c76d2-68b2-4e39-8c9d-bf5a149eb49b.png)
好像地下file那一行有一点点不一样。
不过就是两个文件都运行不起来。
我在train.yaml中更改了labels为自己的标签，其他没有改动。
请问这是为什么运行不起来呢？

**Comment by xxupiano** [comment]
删掉checkpoints文件夹再运行即可

**Comment by xiaohou1112** [comment]
> 删掉checkpoints文件夹再运行即可

  你好！我删除了还是一样报错。
![1676425068499](https://user-images.githubusercontent.com/62997063/218905230-324598cf-eb4e-4fce-a4ec-5490c4ed787c.jpg)

**Comment by GoooDte** [comment]
请您设置
example/ner/standard/conf/hydra/model/bert.yaml
中的bert_model参数为正确的模型名

**Comment by xxupiano** [comment]
https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/conf/config.yaml 是否修改hydra/model为bert？

**Comment by xiaohou1112** [comment]
> 请您设置 example/ner/standard/conf/hydra/model/bert.yaml 中的bert_model参数为正确的模型名

这个文件里面没有改动过。
![1676426186858](https://user-images.githubusercontent.com/62997063/218907660-104fe739-f003-42cf-ab76-cea19ce602bb.jpg)

**Comment by xiaohou1112** [comment]
> https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/conf/config.yaml 是否修改hydra/model为bert？

这里没有修改。现在运行了一下lstmcrf的运行起来了！谢谢！

**Comment by xiaohou1112** [comment]
> https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/conf/config.yaml 是否修改hydra/model为bert？

![1676426561666](https://user-images.githubusercontent.com/62997063/218908460-fb40a112-f0af-491d-ad65-56cc33bead04.jpg)
这里gai'chen改成了bert还是会显示这些warning，请问这是没问题的吗？

**Comment by xiaohou1112** [comment]
> 能跑通就行

![1676427499686](https://user-images.githubusercontent.com/62997063/218910531-dac3c178-ff46-4f95-a3df-a6a6eb5f50d2.png)
然后在这里卡住了一直没下去
