### ISSUE TITLE
数据集来源问题

### ISSUE THREAD

**Issue by nTjing** [zjunlp/DeepKE#222]
您好，想问一下DeepKE-cnSchema的数据集（可抽取50种关系类型和28种实体类型）的来源是哪里？社交媒体？百度百科？还是？

**Comment by zxlzr** [comment]
您好主要是百科和一些网上公开的数据

**Comment by nTjing** [comment]
> 您好主要是百科和一些网上公开的数据

网上公开数据的具体类别是什么呢？社交媒体方面的？

**Comment by zxlzr** [comment]
没有社交媒体，是一些公开的中文新闻

**Comment by nTjing** [comment]
> 

好的 了解了 谢谢您

**Comment by ZZxZZ17** [comment]
您好，可以提供一下训练中文模型时用到的数据集吗？

**Comment by zxlzr** [comment]
您好非常抱歉，数据都是网上公开渠道收集的，暂时不会公开。
