### ISSUE TITLE
ner/standard进行lstmcrf，出现进程kill

### ISSUE THREAD

**Issue by KayleLong** [zjunlp/DeepKE#224]
![1](https://user-images.githubusercontent.com/28802610/220286502-905ddc5b-4cf6-40c2-89bc-58d3d4d32b7d.png)
![2](https://user-images.githubusercontent.com/28802610/220286548-29cf1aac-fc8e-4f1c-a71d-18bb8f5051b9.png)
![3](https://user-images.githubusercontent.com/28802610/220286567-3c190fff-a37b-464e-9661-d211493a066e.png)

图2是程序刚开始run，图3出现进程被kill（红色标出）

**Comment by pengzju** [comment]
从您的报错信息来看 “Missing @package directive hydra/model/lstmcrf.yaml”，我猜测是您丢失了`yaml`配置文件，请您检查一下。
以及检查一下在`config.yaml`中`hydra/model`这一列是否设置为`lstmcrf`

**Comment by luketong7** [comment]
我也遇到了相似的问题，显示出进度条之后就没有后续了。按照上述回复检查了配置文件，问题仍然没有解决。

**Comment by pengzju** [comment]
感谢二位对DeepKE工作的关注，我刚又测试了一遍代码，正常运行没问题的。
![image](https://user-images.githubusercontent.com/63391142/220297381-c4b90308-1b95-414c-8b03-a7d32a630bd8.png)

**Comment by pengzju** [comment]
我建议您在运行的过程中，新开一个shell窗口，检查内存(top命令)使用情况，有可能是Out of Memory导致的系统问题

**Comment by KayleLong** [comment]
第一次run的时候就出现这个问题，后续多次run，有成功运行一次并生成了模型。可是再次运行，就又出现了这个问题，查看了内存，直接满了。
现在回想起来，运行成功那一次是因为我修改了conf中的train.yaml文件中的train_batch_size参数，改小了4倍。
train_batch_size=32

> 我建议您在运行的过程中，新开一个shell窗口，检查内存(top命令)使用情况，有可能是Out of Memory导致的系统问题
