### ISSUE TITLE
官网知识图谱问题

### ISSUE THREAD

**Issue by nTjing** [zjunlp/DeepKE#225]
您好，想问一下您在官网呈现的这个知识图谱是用的neo4j图数据库吗？
<img width="762" alt="image" src="https://user-images.githubusercontent.com/113650779/220504528-fb359024-71d4-43fb-9bac-2d95d6fc00d7.png">

**Comment by GoooDte** [comment]
您好，这个图是我们用画图工具画的，并非来自Neo4j

**Comment by nTjing** [comment]
您好，想问一下，画图工具是哪一个呀？

**Comment by nTjing** [comment]
> html+javascript

好的 谢谢
