### ISSUE TITLE
特别版deepKE模型问题

### ISSUE THREAD

**Issue by nTjing** [zjunlp/DeepKE#229]
您好，基于实体抽取任务（NER）分别提供了基于RoBERTa-wwm-ext, Chinese和BERT-wwm, Chinese训练的模型，这两个模型都属于中文预训练模型，我想问一下是否是基于这两个预训练模型，然后再在数据集（28种实体）上微调训练出来的模型？这个模型的嵌入层是直接使用的预训练模型嘛？

**Comment by tlk1997** [comment]
是的

**Comment by nTjing** [comment]
> 是的

好的 谢谢！
