### ISSUE TITLE
基于cndeepke数据集，用bilstm-crf模型训练

### ISSUE THREAD

**Issue by nTjing** [zjunlp/DeepKE#231]
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/113650779/222950460-35a03b69-c45e-4092-b41c-b667c9b69534.png">
j将数据集换成了特别版deepke的数据集，也从训练集中又划分出了验证集，但是运行时报错，貌似是张量维度问题
但是我用人民日报的数据集运行是可以跑通的

**Comment by pengzju** [comment]
您好，感谢您对DeepKE工作的关注！这个错误来自于数据处理部分，目前已修复。
您可以将DeepKE更新到最新的版本，或者考虑手动修复，将`dataset.py`中第77行修改为：
`batch.sort(key=lambda x: len(x.text_a.split(' ')), reverse=True)`

**Comment by nTjing** [comment]
> 

好的 我尝试一下 谢谢你！
