### ISSUE TITLE
RE中使用GCN模型时邻接矩阵adj的处理

### ISSUE THREAD

**Issue by NEUtangyu** [zjunlp/DeepKE#237]
**Describe the question**
> A clear and concise description of what the question is.

1. 在数据处理完之后，train_dataloader中有'word'、'lens'、'head_pos'、'tail_pos'，还没有adj的值，为什么在train.py中
for batch_idx, (x, y) in enumerate(dataloader, 1):这句代码中，x中有adj的值。这个adj的值从哪里来，好像也没有代码进行处理呀。

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

1. run.py
![image](https://user-images.githubusercontent.com/103868373/223633104-5f16e481-639a-4dde-8c93-7ccca1f31db5.png)

2. train.py
![image](https://user-images.githubusercontent.com/103868373/223633251-f8566ced-16bf-478f-b6cc-eafcfa1ba06c.png)

**Additional context**
> Add any other context about the problem here.

**Comment by tlk1997** [comment]
上述GCN的模型是模仿早期一篇 GCN for RE 的 [文章：Graph Convolution over Pruned Dependency Trees Improves Relation Extraction](https://arxiv.org/abs/1809.10185) 源码构建的GCN架构，你可以参考下[原始代码](https://github.com/qipeng/gcn-over-pruned-trees/blob/db7c128e5c6fcccbe56c1358ba8f4fed30428678/model/gcn.py#L97)，adj可根据源代码生成，在deepke中adj为随机生成的

**Comment by zxlzr** [comment]
您也可以通过一些现成的parsing工具生成adj。

**Comment by NEUtangyu** [comment]
好的谢谢
