### ISSUE TITLE
RE训练自己的数据集，准确率100%，p、r、f1都是1.0

### ISSUE THREAD

**Issue by NEUtangyu** [zjunlp/DeepKE#239]
**Describe the question**
> A clear and concise description of what the question is.
改成自己的数据集，训练集7900条，验证集、测试集都是1500条，句子是疑问句，句子大部分较短，关系只有8种，
RE，模型使用的是GCN，准确率100%，p、r、f1都是1.0，请问一下，是不是自制的数据集出了问题，应该从哪些方面修改

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/103868373/224523296-4b28a6c9-1c13-47fd-a4d1-0e1046c2d10f.png)
![image](https://user-images.githubusercontent.com/103868373/224523235-5219c215-56cc-4550-8a17-17fc70542134.png)
![image](https://user-images.githubusercontent.com/103868373/224523251-6d6e58bd-52d5-48b7-b41c-2fe859c61554.png)

**Additional context**
> Add any other context about the problem here.

**Comment by GoooDte** [comment]
您好，您可以检查一下验证集、测试集是否与训练集存在重合

**Comment by NEUtangyu** [comment]
> 
嗯，我一共是有10900条数据，重复了大概有几十条数据，因为有一个类别数据太少了，就重复几次了。
然后，我训练完之后，发现最佳的轮数是第0轮。
![image](https://user-images.githubusercontent.com/103868373/224532310-46a8aed1-ac9d-41f9-84ab-e7b8f5712bfa.png)

**Comment by zxlzr** [comment]
请您检查训练、验证和测试数据之间的重复数据，不是某个类别重复数据，训练集过拟合了，如果测试验证和训练集有重复的可能会导致prf 1

**Comment by GoooDte** [comment]
您也可以人工看看测试集是否确实是预测正确了，也有可能是数据集句子太短且句式类似，导致训练效果较好

**Comment by NEUtangyu** [comment]
谢谢你们，我把重复的数据删除了，现在最佳轮数为43轮了，不过就是准确率还是100%,prf都还是1.0，应该是数据集句子太短，句式类似的原因吧。
