### ISSUE TITLE
目前有没有对“使用ChatGPT进行NER，RE，AE等任务的效果”方面的研究？

### ISSUE THREAD

**Issue by thredreams** [zjunlp/DeepKE#240]
**Describe the question**
> A clear and concise description of what the question is.

你们好，如题，我想知道用chatGPT进行这些任务与现有的模型之间效果有多大的差距。

以及DeepKE-GPT是否就是一个简单的对OpenAI提供的API的包装。从页面上来看，只能进行一些任务的demo，如果我要实际使用API进行文档级的NER，RE，AE任务，有什么需要注意的点吗？

希望得到一些帮助。谢谢。

**Comment by xxupiano** [comment]
https://arxiv.org/pdf/2302.10205v1.pdf
https://arxiv.org/pdf/2302.06476.pdf
一些论文可供参考

需要注意prompt设计的是否合理和有效，是否提供了与任务有关的信息，这些信息能否有效instruct GPT。

**Comment by thredreams** [comment]
非常感谢。
另外，你们的前端页面上似乎提供了默认的API-key，不知道你们是否注意到了，ChatGPT是收费的。只是每个账户有18$的使用额度。
> gpt-3.5-turbo 的收费是 $0.002 / 1K tokens

> Do not share your API key with others, or expose it in the browser or other client-side code. In order to protect the security of your account, OpenAI may also automatically rotate any API key that we've found has leaked publicly.

**Comment by zxlzr** [comment]
您好，感谢关注，那个key是个免费的仅供用户测试的（使用次数多了可能会失效），您可以直接使用自己的key。
