### ISSUE TITLE
模型运行问题请教

### ISSUE THREAD

**Issue by yaoyaowcs** [zjunlp/DeepKE#241]
**Describe the bug**
> A clear and concise description of what the bug is.
re任务中执行python run.py命令时，报：AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 网上搜了下看是说要把np.object改为object，但在对应报错文件里没有找到np.object，未能解决此问题，希望大佬给予帮助。

**Environment (please complete the following information):**
 - OS:  window
 - Python Version：3.8

**Screenshots**
> If applicable, add screenshots to help explain your problem.

<img width="948" alt="1678783591978" src="https://user-images.githubusercontent.com/61176136/224945647-6c9c782f-f3d5-4435-9188-a76d500407a8.png">

**Additional context**
> Add any other context about the problem here.

**Comment by GoooDte** [comment]
您好，您可以检查一下tensorboard和numpy的版本是否对应。可以参考这里https://blog.csdn.net/AliceH1226/article/details/128821182
