### ISSUE TITLE
Bert预测问题

### ISSUE THREAD

**Issue by JiaqiLin** [zjunlp/DeepKE#244]
你好，我未改动项目代码，使用项目下载的数据集训练完bert后，出现测试分数都为0，预测标签全部为O的情况。若将训练集改为只有几句时，可以预测出非O的标签。想请问一下，你们在训练Bert时有出现这样的问题吗？是因为O标签的比例过高问题吗？
![8c6954638c77203a3f45535f267b996](https://user-images.githubusercontent.com/87626816/228268908-6d112bdd-c9a1-4ef8-be06-653816202c4b.png)

**Comment by xxupiano** [comment]
源码训练、测试没有问题，可能是模型没有训练好，多训几个epoch试一下

**Comment by remosyao** [comment]
同问，用ner/standard/bert的时候出现了一样的问题，开始在自己电脑上因为显存不够，把batch_size调成4后才能正常运行，然后出现了一样的问题。后来在batchsize=128的时候成功的训练了两个模型（一个用的是自己的数据集）。后来我把自己的数据集扩大两倍后再次训练，又出现了这样的问题，然后把数据集缩小了一点，结果训练出的模型对一部分标签的识别是正常的，另一部分准确率和召回率都是0，不太清楚可能的原因，有没有大佬可以帮忙解答一下，谢谢

**Comment by xxupiano** [comment]
1. "出现了一样的问题"，和上述同样的解决方法，目前epoch默认是3，可以开大一点，先别担心过拟合，训久一点试试；
2. “训练出的模型对一部分标签的识别是正常的，另一部分准确率和召回率都是0”，可能你的数据存在长尾分布，准召是0的可能数据量太少， 也可以试着训久一点或者使用一些解决长尾的balanced loss试一下

**Comment by remosyao** [comment]
谢谢，还想问个问题，我之前在jupyterlab上run_bert是可以跑通的，过了两天我再尝试运行却发现终端会卡死，关都关不掉，我把run_bert.py换成几个月前下载的版本，发现可以运行，但是速度很慢，请问有没有什么建议ovo

**Comment by xxupiano** [comment]
个人PC的硬件条件比较简单，很容易内存、显存不够，导致卡死，建议使用服务器或者colab等在线jupyterlab跑实验
