### ISSUE TITLE
dockerfile部署后，训练和预测都会报错

### ISSUE THREAD

**Issue by 1023277973** [zjunlp/DeepKE#248]
**Describe the question**
> A clear and concise description of what the question is.

使用python setup install / develop 安装成功

![image](https://user-images.githubusercontent.com/50948975/230582644-6334a5f9-3887-40e4-ab1a-a30d76a273d6.png)
执行python run.py或者python predict.py都会报如下错误
![image](https://user-images.githubusercontent.com/50948975/230582793-ad04ac6d-a3a3-4589-95c2-dc9ffe5c72b2.png)
 
cannot import name 'CLIPConfig' from 'transformers' (/root/miniconda3/envs/deepke/lib/python3.8/site-packages/transformers/__init__.py)
![image](https://user-images.githubusercontent.com/50948975/230582385-186e8adf-8926-4f52-a530-1c9445ded9d0.png)

**Environment (please complete the following information):**
 - OS: [e.g.  window11 - docker]
 - Python Version [e.g. 3.8]
 - amd r7 5800u cpu+核显（不知道有没有影响）

**Comment by GoooDte** [comment]
感谢您的issue 我们已经更新了requirement，您可以重新下载代码用setup的方式安装

**Comment by 1023277973** [comment]
还是docker的形式来安装遇到的问题，我把我的完整步骤列出来，辛苦帮忙看一下。

1.在window机器上clone最新代码。进入到docker文件夹执行docker build . deepke
![image](https://user-images.githubusercontent.com/50948975/230700465-69eb2bc9-c6b4-421a-b19c-e37e289b4b95.png)
结果截图：
![image](https://user-images.githubusercontent.com/50948975/230700577-f052cfae-0513-42c2-a5dd-dbc5b3cc2dc9.png)
2.执行docker run -it deepke，启动构建好的镜像，并执行conda activate deepke 检查python版本。
![image](https://user-images.githubusercontent.com/50948975/230700631-d657c99e-98ba-4f1d-be1a-20c90111b8e1.png)
3.直接进入~/Deepke执行python setup.py install；结尾处报错：huggingface-hub 0.2.1 is installed but huggingface-hub<1.0,>=0.11.0 is required by {'transformers'}。
报错截图：
![image](https://user-images.githubusercontent.com/50948975/230700779-94bcb06b-e515-44d5-af85-d5905877c3be.png)
4.根据报错提示，修改requirements.txt,将huggingface-hub 0.2.1=》0.11.0
![image](https://user-images.githubusercontent.com/50948975/230700891-9aca831f-ab58-4f3e-a5f5-3f12839e30dd.png)
5.重新执行python setup.py install, 结尾处报错如下：Installed /root/miniconda3/envs/deepke/lib/python3.8/site-packages/gitdb-4.0.10-py3.8.egg
报错截图：
error: numpy 1.18.5 is installed but numpy<1.27.0,>=1.19.5 is required by {'scipy'}
![image](https://user-images.githubusercontent.com/50948975/230701030-00827ab4-f412-4d5a-b935-a04f9c62792b.png)
6.根据报错提示，修改requirements.txt,将huggingface-hub 1.18.5 =》1.24.1
![image](https://user-images.githubusercontent.com/50948975/230701065-3baf5073-e1bd-46b7-a6da-932b8a65c7f2.png)
7.重新执行python setup.py install, 顺利执行，没有报错。
![image](https://user-images.githubusercontent.com/50948975/230701104-266558cb-c0c9-45cd-b2a8-7bcc9a3a2ab3.png)
8.执行python setup.py develop,顺利执行，没有报错。
![image](https://user-images.githubusercontent.com/50948975/230701120-32d27f96-5540-486a-9f80-33db07e3ee5c.png)
9.进入DeepKE/example/re/standard，并下载训练集。
![image](https://user-images.githubusercontent.com/50948975/230701195-542b5be5-ceea-48d9-a76e-700cb96b51ad.png)
10.执行python run.py  或者 python predict.py
run.py报错截图
![image](https://user-images.githubusercontent.com/50948975/230701229-6a5c63af-daa6-48dd-a547-c873abde9b7c.png)
predict.py报错截图
![image](https://user-images.githubusercontent.com/50948975/230701261-8fa72543-8a2f-49c5-97de-f7d07db4a89b.png)
11.尝试修改numpy版本1.23.0，并重新install / develop
![image](https://user-images.githubusercontent.com/50948975/230701412-1082c5e8-d4ae-4c52-a6a6-45f79c3f6057.png)
12.重新执行run or predit，这回报错都变成了No module named 'deepke.name_entity_re.few_shot.models.util'
![image](https://user-images.githubusercontent.com/50948975/230701439-c967a854-f75e-4833-b73b-159ee523b4a2.png)
![image](https://user-images.githubusercontent.com/50948975/230701448-8fa5f0bc-7a67-473f-98ec-81b6c0f144ab.png)

如果可以希望能够本地验证一下，非常感谢~
（我这次的是另一个电脑，英特尔+nvidia平台。）

**Comment by GoooDte** [comment]
非常感谢您指出的问题，由于DeepKE新版本刚刚发布，可能存在一些bug，感谢您能帮我们耐心指出，我们已经修复了上述问题，如有其他问题欢迎您继续提出issue

**Comment by YeyRay** [comment]
更新代码重新setup后，可正常运行。但新代码更改路径后仍有模块无法加载，可在相应代码中调整import模块的路径以导入相应的模块。如在example/ner/standard的run_bert.py中：
![image](https://user-images.githubusercontent.com/128445855/230851460-855bce96-dd15-4edc-a00a-a53c7a17aff5.png)
将提示对应的model.py文件中的"`from utils.util import`"更改为"`form ..utils.util import`"即可。

**但在运行中，仍有无法导入的模块**。如在example/ner/standard的run_bert.py中：
![image](https://user-images.githubusercontent.com/128445855/230852579-bf34c42a-375c-4826-8e77-1ce62f47a8f5.png)
在对应文件中example/ner/corss文件夹下并**无datasets模块**可供程序导入

**Comment by 1023277973** [comment]
> 更新代码重新setup后，可正常运行。但新代码更改路径后仍有模块无法加载，可在相应代码中调整import模块的路径以导入相应的模块。如在example/ner/standard的run_bert.py中： ![image](https://user-images.githubusercontent.com/128445855/230851460-855bce96-dd15-4edc-a00a-a53c7a17aff5.png) 将提示对应的model.py文件中的"`from utils.util import`"更改为"`form ..utils.util import`"即可。
> 
> **但在运行中，仍有无法导入的模块**。如在example/ner/standard的run_bert.py中： ![image](https://user-images.githubusercontent.com/128445855/230852579-bf34c42a-375c-4826-8e77-1ce62f47a8f5.png) 在对应文件中example/ner/corss文件夹下并**无datasets模块**可供程序导入

这个好像可以直接pip install datasets，后面还有个pyhocon 也是同样的方式

**Comment by GoooDte** [comment]
感谢大家的issue
