### ISSUE TITLE
关于预测部分代码

### ISSUE THREAD

**Issue by tantingting1012** [zjunlp/deepke#25]
你好，请问您那边啥时候能更新一下预测代码呢

**Comment by yuwl798180** [comment]
你好，预测的代码，基本就是重新让输入的句子走一遍预处理，然后word2index，然后输入到训练后的模型中，这个可以很容易写出来。

我现在是把整个代码逻辑重构了一遍，可读性好很多。在dev分支中。
你可以看下dev里的predict.py文件。

由于重构使用了facebook的hydra包，而这个包有个很严重的bug，已经提交了修改的pr，等那边release新版本后，就会把dev整合到master里。

**Comment by tantingting1012** [comment]
你好，重构的代码就是这个项目吗，

**Comment by yuwl798180** [comment]
是的。主要是想把通用模块解耦，这样可以拿来复用到其他nlp任务中，也为了代码的可读性（python代码写起来很自由。。
会尽快更新到master中

**Comment by tantingting1012** [comment]
好的，感谢，期待更新到master





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yuwl798180"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月11日(星期一) 下午3:32
收件人:&nbsp;"zjunlp/deepke"<deepke@noreply.github.com&gt;;
抄送:&nbsp;"魔鬼中的天使"<1109773965@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zjunlp/deepke] 关于预测部分代码 (#25)




是的。主要是想把通用模块解耦，这样可以拿来复用到其他nlp任务中，也为了代码的可读性（python代码写起来很自由。。
 会尽快更新到master中
