### ISSUE TITLE
根据快速上手教程，源码安装报错

### ISSUE THREAD

**Issue by debrisvector** [zjunlp/DeepKE#253]
执行快速上手的python setup.py develop时，存在error。
请问该问题是否会影响deepke的使用

 - OS: windows
 - Python Version conda环境 3.6

**Screenshots**
![image](https://user-images.githubusercontent.com/36157282/231920990-810137b6-9a22-494e-b8e8-7dfd60204dd4.png)

**Comment by xxupiano** [comment]
可以更新下tqdm, pip install tqdm --upgrade

**Comment by debrisvector** [comment]
实际上我在此之前已经更新过tqdm，但是执行python setup.py develop时他的版本会check成4.60
![image](https://user-images.githubusercontent.com/36157282/231925889-2ee729d8-e74e-4a68-a08e-85060ce34f44.png)
在安装时
![image](https://user-images.githubusercontent.com/36157282/231926017-b7894151-f339-4d92-b559-f344a38cca38.png)

**Comment by debrisvector** [comment]
DeepKE-main路径和deepke.egg-info路径下的requirements.txt均已经修改，重启conda后仍旧出现该error，请问是否还有其他地方约束了安装版本

**Comment by xxupiano** [comment]
修改之后重新装deepke了吗？

**Comment by GoooDte** [comment]
新的requirement已经取消了对tqdm版本的限制，您可以重新下载deepke并安装

**Comment by debrisvector** [comment]
谢谢，源码安装后续还是有各种报错，
类似
```
raise InvalidRequirement(str(e)) from e 
pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected closing RIGHT_PARENTHESIS     PyYAML (>=5.1.*)
```
最后使用 pip install deepkg完成了安装
