### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by SuoFei01** [zjunlp/DeepKE#254]
![image](https://user-images.githubusercontent.com/126148490/231927142-aea870f9-eec3-4496-a39a-8e79c018a50d.png)
ImportError: cannot import name 'CLIPConfig' from 'transformers' (/root/anaconda3/envs/deepke/lib/python3.8/site-packages/transformers/__init__.py)

**Comment by Flow3rDown** [comment]
请您确认下`transformers`的版本是否是`4.26.0`，如果不是的话可以通过`python setup.py install`重新安装下DeepKE

**Comment by SuoFei01** [comment]
> 请您确认下的版本是否是，如果不是的话可以通过重新安装下DeepKE`transformers``4.26.0``python setup.py install`

安装4.26.0完成后提示
![Uploading image.png…]()
换成4.26.0后重新运行报错
![Uploading image.png…]()

**Comment by SuoFei01** [comment]
> 请您确认下`transformers`的版本是否是`4.26.0`，如果不是的话可以通过`python setup.py install`重新安装下DeepKE

安装4.26.0结束后提示
![image](https://user-images.githubusercontent.com/126148490/231928723-b44e39d9-399c-4ace-9fa1-d82c6bf0b65e.png)
重新运行后报错
![image](https://user-images.githubusercontent.com/126148490/231928760-93b23d2d-b3fa-45ad-b291-177d4129b3d5.png)

**Comment by Flow3rDown** [comment]
DeepKE的代码有过更新，您可以重新拉取一下DeepKE的代码并重新安装deepke

**Comment by SuoFei01** [comment]
> DeepKE的代码有过更新，您可以重新拉取一下DeepKE的代码并重新安装deepke

请问应该拉取那个版本的deepke，我尝试了2.2和2.1.3都存在以上问题

**Comment by GoooDte** [comment]
请您拉取新代码后运行python setup.py install重新安装deepke

**Comment by SuoFei01** [comment]
> 请您用git clone拉取新代码后运行python setup.py install重新安装deepke

已经可以了，非常感谢！！
