### ISSUE TITLE
运行run_bert.py时报错，说AttributeError: 'int' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by Miracle999-bit** [zjunlp/DeepKE#256]
**Describe the question**
> 我查看了报错的代码，发现是环境里Lib\site-packages\seqeval-1.2.2-py3.8\seqeval\metrics中的sequence_labeling.py出现的问题，尝试修改，但egg文件我改完他报错说ModuleNotFoundError: No module named 'seqeval'

**Environment (please complete the following information):**
 - OS: [ window]
 - Python Version [3.8]

**Screenshots**
>
<img width="849" alt="屏幕截图 2023-04-14 200729" src="https://user-images.githubusercontent.com/122346719/232272996-ad88662b-7658-419a-a688-049357f3e082.png">

**Additional context**
> Add any other context about the problem here.

**Comment by GoooDte** [comment]
可以尝试删掉seqeval库重新pip安装

**Comment by Miracle999-bit** [comment]
你好！是把site—package里的seqeval的egg文件删除吗

**Comment by GoooDte** [comment]
是的

**Comment by Miracle999-bit** [comment]
删除后安装报错 No module named '_distutils_hack

**Comment by GoooDte** [comment]
确认一下seqeval是不是1.2.2版本

**Comment by Miracle999-bit** [comment]
是1.2.2，依然报错AttributeError: 'int' object has no attribute 'startswith'
![Uploading 屏幕截图 2023-04-16 145322.png…]()

**Comment by xxupiano** [comment]
这不是包的问题，是因为训练数据太少了，模型没有训练好，预测出了如[SEP][CLS]等非NER的token label，建议使用few-shot NER

**Comment by Miracle999-bit** [comment]
你好！'int' object has no attribute 'startswith'这个问题 应该不是数据量的问题吧，感觉是chunk变量没有转换成str

**Comment by xxupiano** [comment]
这个报错是在seqeval.metrics.classification_report，因为模型没有学好才会预测出int，而不是str形式的NER label，比如B-PER，如上述回答，可以debug看一下y_pred就可以理解了。请问你的训练数据量是多少？

**Comment by Miracle999-bit** [comment]
想问下应该要多少数据量

**Comment by xxupiano** [comment]
比如CONLL 2003数据集，有1393 English news articles
