### ISSUE TITLE
想请问下如何进行多模态关系抽取预测？

### ISSUE THREAD

**Issue by 2466891502** [zjunlp/DeepKE#257]
**Describe the question**
> A clear and concise description of what the question is.
将MNRE数据集上训练好的模型放入 `predict.yaml`中的load_path进行预测，成功能运行并得到相应输出结果，想请问下该如何使用自己的文本和图片，设置相应的文件加载路径进行关系抽取，类似于模型接口化的工作
![image](https://user-images.githubusercontent.com/52395484/232412538-ddf6ddeb-c407-45c3-a7f8-4972ffeffa98.png)

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by Flow3rDown** [comment]
您好，多模态关系抽取使用的是[IFAformer](https://arxiv.org/pdf/2211.07504.pdf)方法，需要提前使用[visual grunding](https://github.com/zyang-ur/onestage_grounding)和[Faster RCNN](https://github.com/pytorch/vision/blob/main/torchvision/models/detection/faster_rcnn.py)工具从图片中抽取有关实体（如头实体和尾实体）的子图（请参考[README.md](https://github.com/zjunlp/DeepKE/blob/main/example/re/multimodal/README_CN.md)和原论文），所以没办法进行一键使用。

**Comment by 2466891502** [comment]
您好，我阅读了IFAformer方法和相应的子图抽取工具。
进一步想问下如果提供了原图和头实体尾实体的子图，是否能够实现官网示例中的关系抽取？
同时还想了解下文本组织的方式，官网中提到的{文本}*{头实体}*{尾实体}格式和测试数据中的txt文件格式是如何转化的？
![image](https://user-images.githubusercontent.com/52395484/232424581-fb23c57a-7502-49d1-a155-a1dbff579341.png)
如果提前明确了关系的类型，那关系抽取就没有了意义。

**Comment by GoooDte** [comment]
您好，官网中{文本}{头实体}{尾实体}的格式中头实体和尾实体不是必须的，在实际测试中只需要提供文本和实体对应的子图即可

**Comment by 2466891502** [comment]
您好，请问如果我要使用自定义的文本和图片，该如何设置predict.py中的数据读取路径。其中文本该按什么样的规则将字符串转成测试文本的格式？我在测试的时候如果文本中缺少关系这个属性就会报错，那如果已经明确了关系是什么不就不需要抽取了吗？感觉有点矛盾。
![image](https://user-images.githubusercontent.com/52395484/232482188-89097ce0-75eb-4964-99f5-91ab69617612.png)


此外，官网中的demo如果不按格式在文本中明确头尾实体的话抽取不出来二者的关系。
![image](https://user-images.githubusercontent.com/52395484/232482764-0e90df8f-83d8-47b6-91d4-56192f648f6d.png)
![image](https://user-images.githubusercontent.com/52395484/232482802-700907d9-7b39-46e1-9129-538a5e75afa1.png)

> 您好，官网中的demo仅仅是一个多模态关系抽取的示例，{文本}{头实体}{尾实体}的格式中头实体和尾实体不是必须的，在实际测试中只需要提供文本和实体对应的子图即可

**Comment by GoooDte** [comment]
测试时候具体的报错信息是什么

**Comment by 2466891502** [comment]
> 测试时候具体的报错信息是什么

我取出了测试文本中的一条文本，将其'relation'置空，希望能通过模型抽取出关系，可是并不行。如果按照您说的只需要一条文本不需要头尾实体的话，我应该只输入一个字符串就可以了。
![image](https://user-images.githubusercontent.com/52395484/232485370-02bd1ea3-dcc2-45df-935b-f1202961dd78.png)

**Comment by GoooDte** [comment]
这里的关系并不影响测试，测试的时候并不会看这个关系，predict的代码只是复用了训练时候的数据处理模块，并需要计算预测的正确率，因此需要传递关系值，如果不需要传递关系值的话，您可以将与之相关的代码注释掉即可。
