### ISSUE TITLE
如何把in-domainNER实验的各标签的F1值print出来

### ISSUE THREAD

**Issue by bwl666** [zjunlp/DeepKE#258]
你好，请问in-domain的命名实体识别任务中，如何实现print每个标签的F1值呢，是使用seqeval函数吗，希望能够得到解答，非常感谢！！！

**Comment by bwl666** [comment]
我的意思是如何在light-ner中将in-domain中各标签的F1print出来呢，作者们是怎么做到的呢，，，，seqeval的reference和predictions序列我有点做不出来

**Comment by Flow3rDown** [comment]
抱歉，目前LightNER暂不支持输出各个标签的F1，想要输出各标签F1需要修改[Seq2SeqSpanMetric](https://github.com/zjunlp/DeepKE/blob/3ea923d6b7d6e9c235f2688eb4397170ca4b9f6a/src/deepke/name_entity_re/few_shot/module/metrics.py#L17)中的评估函数，存储每个pair的类型，并在`_compute_tp_fn_fp`的计算过程中按标签类型计算p,r,f1。
