### ISSUE TITLE
error: aiohttp 4.0.0a1 is installed but aiohttp!=4.0.0a0,!=4.0.0a1 is required by {'fsspec'}

### ISSUE THREAD

**Issue by baicaiit** [zjunlp/DeepKE#260]
**Describe the bug**
> 下载源码, 运行 `python setup.py install`, 依赖包报错, 是依赖包那边出问题了么

**Environment (please complete the following information):**
 - OS: [mac]
 - Python Version [3.8.16]

**Screenshots**
```
Extracting deepke-2.2.1-py3.8.egg to /xxx/envs/deepke/lib/python3.8/site-packages
Adding deepke 2.2.1 to easy-install.pth file

Installed /xxx/envs/deepke/lib/python3.8/site-packages/deepke-2.2.1-py3.8.egg
Processing dependencies for deepke==2.2.1
error: aiohttp 4.0.0a1 is installed but aiohttp!=4.0.0a0,!=4.0.0a1 is required by {'fsspec'}
```

**Additional context**

**Comment by GoooDte** [comment]
您好 可以尝试一下pip的方式安装

**Comment by GoooDte** [comment]
您可以尝试建一个名为deepke的新环境试一下 注意python版本为3.8

**Comment by baicaiit** [comment]
> > 
> 
> 你好，我这个是在服务器上，Ubuntu20.04.6的环境中anaconda新建一个虚拟环境，但还是报了error: aiohttp 4.0.0a1 is installed but aiohttp!=4.0.0a0,!=4.0.0a1 is required by {'fsspec'}，你的这个错误，我想问一下，这个与创建的虚拟环境的名称什么的有关吗？
这个应该不影响使用的, 包都下载和编译成功的了, 但是看着error别扭
可以在运行完 `python setup.py install` 之后, 在运行一次 `pip install deepke==2.2.1`, 包的依赖出问题了, 暂时只能这样解决

**Comment by baicaiit** [comment]
> > 
> 
> 你好，我这个是在服务器上，Ubuntu20.04.6的环境中anaconda新建一个虚拟环境，但还是报了error: aiohttp 4.0.0a1 is installed but aiohttp!=4.0.0a0,!=4.0.0a1 is required by {'fsspec'}，你的这个错误，我想问一下，这个与创建的虚拟环境的名称什么的有关吗？
>
这个应该不影响使用的, 包都下载和编译成功的了, 但是看着error别扭
可以在运行完 python setup.py install 之后, 在运行一次 pip install deepke==2.2.1, 包的依赖出问题了, 暂时只能这样解决
