### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by Miracle999-bit** [zjunlp/DeepKE#262]
**Describe the question**
> 运行NER standard下的run_bert.py时报错如下：RuntimeError: CUDA error: invalid device ordinal，CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
尝试将train.yaml中use_multi_gpu按照README_CN修改为True，cuda:1修改为0，没有效果。

**Environment (please complete the following information):**
 - OS: [ window]
 - Python Version [3.8]
![Uploading 屏幕截图 2023-04-21 100835.png…]()

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by GoooDte** [comment]
可以尝试将CUDA_LAUNCH_BLOCKING设为1看进一步的报错信息
