### ISSUE TITLE
ner predict.py输出为空

### ISSUE THREAD

**Issue by Miracle999-bit** [zjunlp/DeepKE#263]
**Describe the question**
> D:\ProgramData\Anaconda3\envs\deepke_cuda\lib\site-packages\hydra_core-1.0.6-py3.8.egg\hydra\plugins\config_source.py:190: UserWarning: 
Missing @package directive hydra/output/custom.yaml in file://D:\Projects\Codes\DeepKE-main\DeepKE-main\example\ner\standard\conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
D:\ProgramData\Anaconda3\envs\deepke_cuda\lib\site-packages\hydra_core-1.0.6-py3.8.egg\hydra\plugins\config_source.py:190: UserWarning: 
Missing @package directive train.yaml in file://D:\Projects\Codes\DeepKE-main\DeepKE-main\example\ner\standard\conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
D:\ProgramData\Anaconda3\envs\deepke_cuda\lib\site-packages\hydra_core-1.0.6-py3.8.egg\hydra\plugins\config_source.py:190: UserWarning: 
Missing @package directive predict.yaml in file://D:\Projects\Codes\DeepKE-main\DeepKE-main\example\ner\standard\conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
D:\ProgramData\Anaconda3\envs\deepke_cuda\lib\site-packages\hydra_core-1.0.6-py3.8.egg\hydra\plugins\config_source.py:190: UserWarning: 
Missing @package directive hydra/model/bert.yaml in file://D:\Projects\Codes\DeepKE-main\DeepKE-main\example\ner\standard\conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)

报错说找不到yaml，但是工程里有

**Environment (please complete the following information):**
 - OS: [window]
 - Python Version [3.8]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by GoooDte** [comment]
尝试将hydra-core更新到1.3.1

**Comment by GoooDte** [comment]
查看一下路径是否有问题 两个斜杠 ‘/’ ‘\’不一致
