### ISSUE TITLE
Cross-Domain Few-Shot NER Question

### ISSUE THREAD

**Issue by bwl666** [zjunlp/DeepKE#265]
**Describe the question**
> A clear and concise description of what the question is.

您好，我对于《LightNER: A Lightweight Generative Framework with Prompt-guided Attention
for Low-resource NER》有两个问题

1.跨领域命名实体识别中您是如何避免因为训练集和测试集标签不一致而发生keyvalue的错误

2.可以将源域的标签标记方法改为和目标域一致吗，这样是可行的吗

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by Flow3rDown** [comment]
您好，感谢您的关注。
1. 首先，LightNER更关注的是低资源场景下的NER问题。我们论文中跨域迁移实验的源域数据集是CoNLL03，其实体类型在目标域数据集(Mit-Movie, Mit-Restaurant)中都有包含，这些共有的实体会从CoNLL03训练的模型中初始化，其他的用实体类型对应的标签词embedding进行初始化。为防止发生key value错误（模型加载时）可以自己编写加载模型权重的函数。
2. 不建议用此方法，不同的标签词会关注不同的实体类型，这样会造成混乱。

最近DeepKE还新增加了关于跨域NER的方法[CP-NER](https://github.com/zjunlp/DeepKE/blob/main/example/ner/cross/README.md)，更推荐您使用此方法进行跨域NER的实验。

**Comment by bwl666** [comment]
您好，首先非常感谢您及时且完整的回复，真的非常感谢，我学习到了很多，但还有几个问题可能需要提问：

1.conll03数据集的实体类型其实和如Mit-Movie的实体类型差很多，您说的共有实体类型是指conll03作为通用数据集，所以也包含很多Mit-Movie数据集中的实体吗，但如果不靠类似loc，per等的标签，怎么分别是不是共有的实体呢？

2.编写加载模型权重的函数可以防止key value吗，我以为是在dataloader阶段，将key由不同的数据集分别加载，我看您发的链接是将source和target的key相加除以2---model_dict[key] = (source_model_dict[key] + target_model_dict[key]) / 2，这是您在LightNER中所做的防止key value的行为吗？

3.您的cross-indomain ner的有源域实验中，是否是conll03的训练集作为train.txt，其他如Mit-Movie的测试集作为test.txt，请问其中有无验证集的参与，如果有，那是哪个作为验证集 ；      在无源域的实验中，Mit-Movie数据集中有10-500的训练集，也有测试集，其中有验证集的参与吗，您在run.py中的DATA_PATH又将mit-movie数据集的train和dev写作以下格式，让我对改数据集的dev数据集和test数据集有些搞混。
'mit-movie': {'train': 'data/mit-movie/20-shot-train.txt',
                  'dev': 'data/mit-movie/test.txt'}


最后的最后，我昨天写的评论不知为何没有发出去，您及时的回复了我，我也很想及时回复回去，真的很对不起，另外想说的就是，deepke是一个在NER领域做出杰出贡献的深度学习工具，构架清晰，操作方便，指导也很及时，由衷的感谢！！！希望有更多成果出来，身体健康。

**Comment by bwl666** [comment]
我知道您在LightNER中用的是BART生成模型，我用的是bert-softmax，不知道您在进行Sequence Labeling BERT是如何解决key-value问题的，非常期待您的回答。

**Comment by Flow3rDown** [comment]
1. 共有实体指的是标签词一致的实体，如loc, per, org, misc等。

2. 我不太理解您说的key,value具体指的哪一块，之前回答是在加载模型权重时由于实体标签发生变化可能会产生key,value error的问题，这时需要手动进行模型权重加载。DeepKE中的LightNER并不涉及跨域的实现，[CP-NER](https://github.com/zjunlp/DeepKE/blob/main/example/ner/cross/README.md)是专门做跨域NER的方法。

3. LightNER中的跨域实验是先使用源域数据（CoNLL03）训练模型，之后基于此模型在跨域数据上继续进行训练。mit-movie等数据并没有提供验证集，所以可以同样从full set中采样k-shot数据作为验证集。

**Comment by bwl666** [comment]
了解，非常感谢解答

**Comment by Flow3rDown** [comment]
> 我知道您在LightNER中用的是BART生成模型，我用的是bert-softmax，不知道您在进行Sequence Labeling BERT是如何解决key-value问题的，非常期待您的回答。

我们会在word embedding中新增一些实体token，在生成的时候会与word embedding中的这些实体token进行计算得到预测的实体标签。所以在跨域的时候相同的实体可以直接迁移这些embedding，新增的实体需要额外在word embedding中添加，添加的方法是用实体标签中的每个单词对应的word embedding向量进行平均初始化。

**Comment by bwl666** [comment]
1.因为我确实列了mit-movie和coll03的标签词，其实没有一样的，所以引发我的疑问，您说的新增的token是指关于目标域的词吗，比如conll03没有的而mit-movie有的，比如title，actor类别的实体。

2.您上个回复中说的我以为是在conll03上训练后保存该模型，再在mit-movie上训练得出有source的结果，但这个回答是在说您会在conll03训练的同时加入新增实体（可能是mit-movie中有，而conll03中没有的），是这样吗，如果是的话，您添加新增token的操作和计算得到预测实体的操作的代码在哪个.py文件中呢（这个问题有点麻烦，您如果觉得浪费时间可以忽略）

3.我想知道您在无source的cross-domain中是使用的dev数据集吗，如果有的话，您所说的k-shot中的k是多少呢

注：
mitmovie标签
names= ['O','B-ACTOR','B-GENRE','B-RATING','B-RATINGS_AVERAGE','B-YEAR','B-SONG','B-DIRECTOR','B-REVIEW','B-CHARACTER','B-TITLE',' B-TRAILER','B-PLOT','I-ACTOR','I-GENRE','I-RATING','I-RATINGS_AVERAGE','I-YEAR','I-SONG','I-DIRECTOR','I-REVIEW','I-CHARACTER','I-TITLE','I-TRAILER','I-PLOT']

coll03标签
'O', 'B-LOC', 'B-PER', 'B-ORG', 'B-MISC', 'I-LOC', 'I-PER', 'I-ORG', 'I-MISC'

**Comment by Flow3rDown** [comment]
1. 抱歉，mit-movie确实没有。您理解的是正确的。

2. 在conll03训练时不会增加实体，在新domain上继续训练时才会新增（这时候就会涉及到权重加载问题）。目前DeepKE里的LightNER方法是针对few-shot场景的，并不涉及跨域，不过实现也比较简单，自己写一个加载模型权重的函数就可以。

3. 验证集与训练集保持一致的采样策略即可，如训练集是10-shot，验证集也采集10-shot。测试是使用的是text.txt进行测试。

**Comment by bwl666** [comment]
那新增实体是哪些呢，可以在deepke的GitHub中找到吗

**Comment by Flow3rDown** [comment]
> 那新增实体是哪些呢，可以在deepke的GitHub中找到吗

新增实体就是目标域相比源域多出来的实体，通过[_add_tags_to_tokens](https://github.com/zjunlp/DeepKE/blob/dcbbb66a70b41e97cdcbfcc859be4e2c886291b3/src/deepke/name_entity_re/few_shot/module/datasets.py#L159)和[model.py](https://github.com/zjunlp/DeepKE/blob/dcbbb66a70b41e97cdcbfcc859be4e2c886291b3/src/deepke/name_entity_re/few_shot/models/model.py#L224-L225)可实现实体在模型word embedding layer的增加。

**Comment by bwl666** [comment]
也就是说您通过这个方式，将目标域的标签添加到embedding中，让模型能识别这个标签的实体。我改变run.py中的MAPPING是否也能实现这种目的呢（模型识别mit-movie中的实体）

还是说您是想在模型（经过coll03训练集训练过的模型）能识别conll03实体标签的基础上，让它再去识别mit-movie中的实体，但恕我直言，三个数据集和coll03数据集的共同实体都极少，直接用在conll03训练完的模型去识别mit-movie的实体效果可能也差不多？

**Comment by bwl666** [comment]
您一开始就是mapping实体和标签的方法在训练conll03数据集哈，我好像搞错了sorry
我是用在dataprocess下将实体和标签分开成value和key对应的字典，所以想问更改label中的列表，是不是也能实现用保存的模型训练其他三个数据集的效果（但因为更改了匹配的标签，所以这个模型不会识别之前conll03数据集的实体，如果添加也行，但感觉从效果上来说又没差）

def _info(self):
        return datasets.DatasetInfo(
            description=_DESCRIPTION,
            features=datasets.Features(
                {
                    "id": datasets.Value("string"),
                    "tokens": datasets.Sequence(datasets.Value("string")),
                    "ner_tags": datasets.Sequence(
                        datasets.features.ClassLabel(
                            names= ['O', 'B-LOC', 'B-PER', 'B-ORG', 'B-MISC', 'I-LOC', 'I-PER', 'I-ORG', 'I-MISC']
                        )
                    ),
                }
            ),
            supervised_keys=None,
            homepage="https://catalog.ldc.upenn.edu/LDC2013T19",
            citation=_CITATION,
        )
