### ISSUE TITLE
关系抽取GCN当中，使用的是有监督学习还是弱监督学习？？

### ISSUE THREAD

**Issue by NEUtangyu** [zjunlp/DeepKE#267]
**Describe the question**
> A clear and concise description of what the question is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by GoooDte** [comment]
是有监督学习

**Comment by NEUtangyu** [comment]
好的，谢谢
