### ISSUE TITLE
pip  install deepke的时候报找不到requirement.txt

### ISSUE THREAD

**Issue by beiTiaoLongJie** [zjunlp/DeepKE#269]
**Describe the bug**
> A clear and concise description of what the bug is.

![image](https://user-images.githubusercontent.com/32008840/236975481-e6cd8e40-d4a9-4f33-9f39-107aeffe0ccf.png)

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by GoooDte** [comment]
您好我们已在pypi上传了最新版的deepke，您可以重新通过pip install的方式安装

**Comment by kanswer** [comment]
现在下载还是这样啊
