### ISSUE TITLE
使用开源即用的模型，但是不起作用

### ISSUE THREAD

**Issue by zhang375765** [zjunlp/DeepKE#270]
参考实例代码，使用**开源即用的模型**做实体识别，识别结果都是这样的：
NER句子:
海钓比赛地点在厦门与金门之间的海域
NER结果:
[('海', '[CLS]'), ('钓', '[CLS]'), ('比', '[CLS]'), ('赛', '[CLS]'), ('地', '[CLS]'), ('点', '[CLS]'), ('在', '[CLS]'), ('厦', '[CLS]'), ('门', '[CLS]'), ('与', '[CLS]'), ('金', '[CLS]'), ('门', '[CLS]'), ('之', '[CLS]'), ('间', '[CLS]'), ('的', '[CLS]'), ('海', '[CLS]'), ('域', '[CLS]')]
模型训练过还是这样的输出，测试语句是从训练集里面截取的一句话

model = InferNer(os.path.join(os.getcwd(), "checkpoints"), cfg)
text='海钓比赛地点在厦门与金门之间的海域'
print("NER句子:")
print(text)
print('NER结果:')

result = model.predict(text)
print(result)

**Comment by xxupiano** [comment]
请问使用了多少数据训练？测试的f1是多少？

**Comment by tlk1997** [comment]
colab上模型已经更新，可以再下载试试，如果仍不佳，可自行训练一遍再进行预测

**Comment by zhang375765** [comment]
<img width="408" alt="1683877640265" src="https://github.com/zjunlp/DeepKE/assets/31236852/8fc7c01d-3828-46b8-b6f2-f9e270f000f4">
把模型训练了一下然后，用**训练数据**去识别实体结果就这样了，也下载的最新上传的模型识别结果在下面：
![image](https://github.com/zjunlp/DeepKE/assets/31236852/931d8e3d-27f2-4668-8e77-fe9d46ffa721)
用的项目里面example>ner>standard>predict.py 试验的，这是哪的问题呢

**Comment by zhang375765** [comment]
<img width="833" alt="1683889666001" src="https://github.com/zjunlp/DeepKE/assets/31236852/43b9088c-4176-40a2-a63e-603bb753a632">
找到原因了，这个代码的这两个参数写反了，调换一下位置就可以了。。是个bug，你们修复一下吧

**Comment by xxupiano** [comment]
已修复，非常感谢

**Comment by zhang375765** [comment]
还有一个问题，命名实体识别出来B-UER,B-ZFM,B-YAS等，这写实体分别指的什么类别呢，有没有完整的中文对照表
