### ISSUE TITLE
论文LightNER所说的附录没找到

### ISSUE THREAD

**Issue by bwl666** [zjunlp/DeepKE#273]
**Describe the question**
> A clear and concise description of what the question is.

LightNER: A Lightweight Generative Framework with Prompt-guided Attention for Low-resource NER论文中在5 Experiments开头说的Our experiments are evaluated in an exact match scenario and implementation details are presented in the appendix.“”，其中这个 appendix我在最后一节7 Conclusion and Future Work后没找到。

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by Flow3rDown** [comment]
https://arxiv.org/pdf/2109.00720.pdf 附录在第12页

**Comment by bwl666** [comment]
收到
