### ISSUE TITLE
llm中data中数据名称错误，对应的ee抽取数据处理部分代码报错

### ISSUE THREAD

**Issue by zhangnn520** [zjunlp/DeepKE#274]
**Describe the bug**
> A clear and concise description of what the bug is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zhangnn520** [comment]
![图片](https://github.com/zjunlp/DeepKE/assets/58899025/818abeda-22df-4c10-a0d2-638815a5a1e6)

**Comment by zhangnn520** [comment]
![图片](https://github.com/zjunlp/DeepKE/assets/58899025/c0a6aacf-7981-4ed9-be1a-2603088b1dd1)

**Comment by zxlzr** [comment]
您好请问您的错误解决了吗
