### ISSUE TITLE
请问本软件如何在离线环境下使用？

### ISSUE THREAD

**Issue by pangpangDD** [zjunlp/DeepKE#276]
需要在没有网络的环境下的电脑使用
我的方式是：
1.在外网利用anaconda配置好环境，运行成功。
2.移植anaconda到另外一个离线的电脑。

环境都是一样的，想请问以下网络问题如何避免：
1.按照要求将3个文件（config.json pytorch_model.bin vocab.txt）放到pretained文件夹下，但是仍然报错无法连接s3.amazonaws.com网络下载3个文件

2.wandb功能能够关闭吗？对应的需要做哪些操作？

**Comment by pangpangDD** [comment]
如能回复，万分感谢！！！！

**Comment by xxupiano** [comment]
1. 还需要tokenizer,.json，修改from_pretrained(放置模型的文件夹路径);
2. 可以关闭，把代码里有wandb的代码注释掉即可

**Comment by xxupiano** [comment]
如果需要离线使用wandb请设置环境变量
export WANDB_USER_EMAIL=账号邮箱
export WANDB_API_KEY=账号key

**Comment by pangpangDD** [comment]
> 1. 还需要tokenizer,.json，修改from_pretrained(放置模型的文件夹路径);
> 2. 可以关闭，把代码里有wandb的代码注释掉即可

1.还需要tokenizer.json文件具体位置在？
2.查看了下from_pretrained有很多位置，如果我需要用DeepKE-main\DeepKE-main\example\ner\standard 中应用bert模型，请问对应的修改路径在哪里？

鞠躬感谢！

**Comment by xxupiano** [comment]
1. 模型文件在https://huggingface.co/bert-base-chinese/tree/main，请下载到DeepKE-main\example\ner\standard\bert-base-chinese
2. 修改https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/conf/config.yaml#L13为bert
3. 直接python run_bert.py即可

**Comment by GoooDte** [comment]
您好 麻烦您把报错的截图截全一点

**Comment by pangpangDD** [comment]
> 您好 麻烦您把报错的截图截全一点

再次打扰您了！非常感谢！另外，只是新建了bert-base-chinese文件夹放了文件，没有修改from_pretrained(放置模型的文件夹路径)

![892f0f49baa23b268e98eba674ab16d](https://github.com/zjunlp/DeepKE/assets/58252967/4c12b681-b8b7-4611-9c69-f632cd39ada0)
![1b4d065e1f4394b249e8ae63ea22d00](https://github.com/zjunlp/DeepKE/assets/58252967/68eea0e7-f661-485b-b335-8f3c86ee62fa)

**Comment by GoooDte** [comment]
试一下改model.yaml中的bert-base-chinese为模型文件夹绝对路径

**Comment by pangpangDD** [comment]
> 试一下改model.yaml中的bert-base-chinese为模型文件夹绝对路径

非常非常感谢您！已经可以运行通过了！但是DeepKE-main\DeepKE-main\example\re\standard 下运行run.py 报错如下，如能方便看一下，万分感谢！
![40038ea52671de19816457ef6889be8](https://github.com/zjunlp/DeepKE/assets/58252967/f54a015b-3874-4bb8-8384-b71dc76645a0)

**Comment by xxupiano** [comment]
可以使用和之前同样的方法，修改https://github.com/zjunlp/DeepKE/blob/main/example/re/standard/conf/model/lm.yaml 中的lm_file为模型文件夹的绝对路径

**Comment by pangpangDD** [comment]
感谢感谢！问题都解决了！
