### ISSUE TITLE
类似Fewrel这种最常见的小样本设置的关系抽取测试标准应该是怎样的呢

### ISSUE THREAD

**Issue by kanswer** [zjunlp/DeepKE#278]
**Describe the question**
> 在论文《How to Unleash the Power of Large Language Models for Few-shot Relation Extraction?》中使用了四个数据集，但其实都是自己设置的小样本场景，但提到小样本关系分类，最切合的数据集是FewRel，同时FewRel的小样本设置和In-context learning很类似，面对这种任务设置时，该如何进行测试呢？期待您的回答。

**Comment by xxupiano** [comment]
FewRel是一个较早的少样本RE数据集，目前普遍使用它的最新版本wiki80，同时FewRel的训练集有64种关系，GPT-3.5的最大输入长度无法容纳1-shot的数据，所以我们没有使用它。

**Comment by kanswer** [comment]
我比较好奇的是您这里讲的1-shot的输入形式是什么，按照FewRel论文的设置是采用N-way-K-shot的，那么也就是标签域包含的标签种类是N（以训练集为例，就是从64种关系中选N种关系，然后这N种关系每种选K个实例来输入模型）个，那么对于这种情况，感觉您说的针对FewRel的1-shot还是没把它的N-way-K-shot设置考虑进去，而是用对应的分割数据集中所有的标签（64/16/16）的一个实例作为指令中的内容？

我感觉如果使用N-way-K-shot设置的话，1-shot应该是能输入的吧，N一般就设置为5或者10，K设置为1或者5.当然这样做其实混淆了ICL和N-way-K-shot设置，按照我的理解，针对FewRel这种N-way-K-shot设置的，context应该是多个场景，1-shot就是另一个N-way-K-shot的场景（关系标签随机选）。

如2-way-1-shot设置下：
instruction：
  略
context：
  Support1：A is the capital of B. [capital]
  Support2：A is the mother of B. [mother]
  Relation list: [capital, mother]
  Query1：C has a mother D. [mother]
真正待预测的场景:
  Support1：A was born in B. [place of birth]
  Support2：A was the son of B. [child]
  Query2：C was born in D. [?]
输出Query2的句子包含的关系类别

而如果按论文中的小样本1-shot设置就是
Context:
  A is the mother of B. [mother]
Query:
  C was born in D. [?]
输出Query的句子包含的关系类别
哪种设置在引入大模型后的小样本关系分类任务中更加正确呢？

**Comment by xxupiano** [comment]
您好，n-way-k-shot是meta learning，我们这里只研究整个数据集label的few-shot设定，比如TACRED一共有41种关系，那么1-shot的TACRED就一共有41个instance，每个instance表示一种关系，谢谢
