### ISSUE TITLE
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.  The tokenizer class you load from this checkpoint is 'BartTokenizer'.  The class this function is called from is 'BertTokenizer'. The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.  The tokenizer class you load from this checkpoint is 'BartTokenizer'.  The class this function is called from is 'BertTokenizer'.

### ISSUE THREAD

**Issue by zhangnn520** [zjunlp/DeepKE#279]
**Describe the bug**
> A clear and concise description of what the bug is.

        self.tokenizer = BertTokenizer.from_pretrained(self.bart_name) if 'chinese' in self.bart_name \
            else BartTokenizer.from_pretrained(self.bart_name)

会出现下面的警告：
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'BartTokenizer'. 
The class this function is called from is 'BertTokenizer'.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'BartTokenizer'. 
The class this function is called from is 'BertTokenizer'.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by pengzju** [comment]
您可以忽略此warning，详情请看：https://huggingface.co/fnlp/bart-large-chinese，在bart-xxx-chinese中，使用的tokenizer确实是BertTokenizer
