### ISSUE TITLE
咨询实现细节

### ISSUE THREAD

**Issue by tantingting1012** [zjunlp/deepke#28]
你好，请问您用的什么方法替换wordpiece处理输入呢

**Comment by tantingting1012** [comment]
bert模型那部分

**Comment by yuwl798180** [comment]
因为这个仓库主要用来做中文，bert里中文是使用字token。
对于英文来说，bert处理方式是，字符按照贪心方式与vocab里对齐，这样就把过长的英文词分隔开。

**Comment by tantingting1012** [comment]
哦哦，好的，谢谢诶，关于bert部分wiki内提供的参考论文里对关系抽取部分写得特别少，emm，请问您这个项目里使用bert做关系抽取的模型与基于bert做联合关系抽取的模型的详细差别有哪些呢，能详细请教一下吗？

**Comment by yuwl798180** [comment]
首先说一点，使用pre-train的language model做下游任务时，plm的作用类似于之前的在大规模语料上学习出比较的word embeding。
使用bert除了直接用这个word embeding，可以提升下游任务效果，还自带了12层的transformer(bert-base)。
所以使不使用bert和做什么任务，是不是联合抽取没有关系。

bert原文中，bert后面可以做任意的nlp task，只需要在不用的位置接上不同的mlp。
nlp task基本分类两大类，一类是分类标注任务。transformer encoder后不改变句子的长度，可以对应的每个token位置可以直接用来做标注任务。
另一类任务就是分类任务，典型的就是利用整个句子信息做文本分类任务。当然关系抽取也可以看到是文本分类任务，只是添加了限定条件，限定了除了利用句子信息外还要利用句子标注出来的两个实体。所以如何取巧的同时利用上这两部分语义信息，就是联合抽取上可以设计的点。当然你也可以说句子信息包括了head和tail的信息，并不需要额外再冗余的指出这两个实体，这也是研究的点。

目前联合抽取有
1. pipeline方式：bert的结果分开接两部分，一部分是找关系，一部分找实体；
2. encoder-decoder方式生成三元组；
3. 语料处理上novel-tagging，比如head不仅仅标注为B-PER，还带上关系信息，标记为B-PER-birth-date。
当然还有其他很多方法，具体看论文。

**Comment by tantingting1012** [comment]
哦哦，感谢

**Comment by tantingting1012** [comment]
请问能向你咨询一下config中配置的参数含义吗，因为没有备注，其中部分参数含义无法理解

**Comment by tantingting1012** [comment]
比如ModelConfig类里面的pos size和pos dim，hidden dim，LMconfig类里面的num hidden dim，Config类里面的pos limit ，感谢

**Comment by yuwl798180** [comment]
pos是position的简称，所以pos size和pos dim分别是position embedding处理前句子最大的长度和embedding后嵌入的长度。
pos limit是为了预处理把过长的句子位置信息抛去。

举个栗子：
pos limit 为50 时：表示句中每个词语相对标记的实体（head/tail）最远只能是50。
如： [xxxxxx                        xxx 北京  xxxxxx             xxx]
pos: [-50,-50,...-50,-49,...0, 1, 2, ...,49,50,50,..50]
这样做是为了让postion不过于稀疏，距离太远时就取到上下限。

此时pos size就是：50 *2 + 1 + 1 = 102
因为pos limit是：[-50,50]一共101个，再加上pad时需要1个，一共102个pos one hot。
pos dim是 embedding的维度，比如设为10，就是102映射到10维度，此时embedding matrix就是102*10。

LMconfig类里面的num hidden dim，这个是因为使用的是bert预训练语言模型，默认的是12层，我们使用时当然可以只使用前2/3/4/5等层（<=12即可）。

**Comment by tantingting1012** [comment]
明白，我在bert实现的关系抽取的论文中看到需要将subject和object进行mask，所以您这里的代码实现时，包含三部分（Token，Segment，Position）的词向量输入后，也是按照原论文的思路，通过单层的BiLSTM的每个方向上的隐藏状态，用一个隐藏层MLP进行两个技术实体的关系预测的吗

**Comment by yuwl798180** [comment]
是的。
另外建议再认真看下论文细节。

**Comment by tantingting1012** [comment]
嗯嗯，好的，谢谢诶，就是推荐的关于bert关系预测这篇论文讲的很少也不是太详细，具体的实现还是不太理解

**Comment by sumor199** [comment]
请问是有相关论文吗？可以给个链接看一看吗？
