### ISSUE TITLE
在re/standard任务中，训练时P、R、F1怎么计算的，感觉最终得到的F1的值不等于2*P*R/（P+R）？？例如p: 0.9771, r:0.9730, f1:0.9726

### ISSUE THREAD

**Issue by NEUtangyu** [zjunlp/DeepKE#281]
**Describe the question**
> A clear and concise description of what the question is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by xxupiano** [comment]
https://github.com/zjunlp/DeepKE/blob/0edfe19074a1b77ed15ea571cf9ae240657f54d8/src/deepke/relation_extraction/standard/tools/metrics.py#L68

**Comment by NEUtangyu** [comment]
你好，请问一下，那个F1=2*P*R/（P+R），是不是应该处于P值和R值之间呢，怎么我得到的结果都是F1值是最少的？

**Comment by xxupiano** [comment]
Sklearn里的Macro-F1
Macro-F1在sklearn里的计算方法就是计算每个类的F1-score的算数平均值：
这种情况下，F1-score的确不在精确度和召回率之间，因为已经这个时候的F1分数已经不是精确度和召回率的调和平均数了。

**Comment by NEUtangyu** [comment]
感谢你的耐心讲解。
