### ISSUE TITLE
example/llm/InstructKGC下进行推理inference，似乎有报错

### ISSUE THREAD

**Issue by leehommlee** [zjunlp/DeepKE#282]
我已经通过运行 bash scripts/run_finetune.bash 训练了一个模型，现在要进行推理，在我运行bash scripts/run_inference.bash后，出现了报错：
AttributeError: 'NoneType' object has no attribute 'config'
是否有人也遇到了相同问题

**Comment by guihonghao** [comment]
你可以试试按照alpaca-lora原始代码运行试试
```python
    if device == "cuda":
        model = LlamaForCausalLM.from_pretrained(
            base_model,
            load_in_8bit=load_8bit,
            torch_dtype=torch.float16,
            device_map="auto",
        )
        model = PeftModel.from_pretrained(
            model,
            lora_weights,
            torch_dtype=torch.float16,
        )
```

**Comment by guihonghao** [comment]
你也可以修改model = set_peft_model_state_dict(model, adapters_weights)为set_peft_model_state_dict(model, adapters_weights)来解决，我们已经在源码中更新

**Comment by leehommlee** [comment]
非常感谢，已解决了

**Comment by guihonghao** [comment]
close
