### ISSUE TITLE
关于如何调试deepspeed那种bash启动的代码

### ISSUE THREAD

**Issue by leehommlee** [zjunlp/DeepKE#283]
关于baseline mt5的那个项目代码，它用的是deepspeed训练，且使用‘run_finetune_ds.bash’启动代码。
想请教您一个问题，这种bash启动的项目代码，如何在编译器中进行断点调试呢？
感谢！

**Comment by guihonghao** [comment]
你好，你可以参考https://github.com/microsoft/DeepSpeed/issues/938、https://zhuanlan.zhihu.com/p/624518949

**Comment by leehommlee** [comment]
感谢

**Comment by guihonghao** [comment]
close
