### ISSUE TITLE
torch版本依赖问题

### ISSUE THREAD

**Issue by divingwolf** [zjunlp/DeepKE#284]
pip install easyinstruct -i https://pypi.org/simple
这个库要求torch >=1.13
你们其他的是 1.5-1.11
依赖有问题啊

**Comment by zxlzr** [comment]
您好，非常抱歉DeepKE里支持的很多早期的模型（目前实际使用量较小）不支持高版本的torch，建议您在使用最新的如llama等llm时直接使用高版本torch，我们会近期快速更新下版本的依赖把老模型的依赖版本做一些说明。

**Comment by divingwolf** [comment]
> 

llm那部分使用的话，并不需要example里面re ee ae 这些是吧？
就直接>=1.13版本就行？

**Comment by zxlzr** [comment]
不需要的，我们会马上更新readme，您可以直接使用更高版本的torch，目前我们建议torch>=1.9 transformer 4.28.0 可以参考https://github.com/zjunlp/CaMA 配置，llm部分和CaMA这两者的配置我们会保持一致

**Comment by zxlzr** [comment]
您好，我们已在readme更新了2个不同版本的说明，如果使用大模型您可以进入deepke-llm 目录，创建虚拟环境，根据https://github.com/zjunlp/DeepKE/blob/main/example/llm/requirements.txt 安装依赖包，如果使用老模型则使用根目录下默认的requirements.txt 安装依赖包。目前大模型版本 torch==1.13.0 transformers==4.28.1, 如有任何问题欢迎提问。
