### ISSUE TITLE
KeyError: 'HF_DATASETS_CACHE'

### ISSUE THREAD

**Issue by cccusername** [zjunlp/DeepKE#285]
执行‘’‘example/llm/InstructKGC/scripts/run_finetune.bash’‘’时报错```KeyError: 'HF_DATASETS_CACHE'```，请问应该怎么解决呢

**Comment by guihonghao** [comment]
你可将cache_dir=os.environ["HF_DATASETS_CACHE"]去掉，或者这样os.environ["HF_DATASETS_CACHE"] = "/***/.cache/huggingface/datasets"指定一个

**Comment by cccusername** [comment]
> 你可将cache_dir=os.environ["HF_DATASETS_CACHE"]去掉，或者这样os.environ["HF_DATASETS_CACHE"] = "/***/.cache/huggingface/datasets"指定一个

嗯嗯，刚刚去掉发现可以跑了，想问一下这个os.environ["HF_DATASETS_CACHE"] = "/***/.cache/huggingface/datasets"指定一个是随便指定一个路径就行吗

**Comment by guihonghao** [comment]
HF_DATASETS_CACHE是数据集缓存位置，默认在/home/用户/.cache目录下，可以任意指定。

**Comment by cccusername** [comment]
> HF_DATASETS_CACHE是数据集缓存位置，默认在/home/用户/.cache目录下，可以任意指定。

好的谢谢
