### ISSUE TITLE
There are empty lines in the output csv file when use src/deepke/transform_data.py

### ISSUE THREAD

**Issue by JJJYmmm** [zjunlp/DeepKE#286]
when using **src/deepke/transform_data.py** to convert a json file to a csv file,there is some empty lines between datas.

![image](https://github.com/zjunlp/DeepKE/assets/92386084/fc7f0273-abd0-414c-afb2-19f9a867d58f)

one method is to change the code on line 14
```
with open(fp_csv, 'w', encoding='utf-8') as f2:
```
to
```
with open(fp_csv, 'w', encoding='utf-8',newline='') as f2:
```

**Comment by tlk1997** [comment]
Can you provide data so that we can reproduce this problem?

**Comment by zxlzr** [comment]
Could you please provide more details so we can address the problem ASAP?

**Comment by JJJYmmm** [comment]
Sorry for replying now


When I use src/deep/transform_data.py to convert my own jsondata into csv data, I found that the final csv file had meaningless blank line breaks between each sample, although it did not affect the training of the model.


The attachment is a json file and the transform script you provided, I add a json2csv_new function in the script to remove the the blank lines between samples.



This is a very small issue that does not affect the use of deepke,perhaps I shouldn't consider it a bug


I'm sorry again for replying so late







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjunlp/DeepKE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月11日(星期天) 上午10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjunlp/DeepKE] There are empty lines in the output csv file when use src/deepke/transform_data.py (Issue #286)





 
Could you please provide more details so we can address the problem ASAP?
