### ISSUE TITLE
请问有大佬知道这个怎么解决么 我在加载这个已经预训练好的模型时失败了

### ISSUE THREAD

**Issue by zhengqianmaifang** [zjunlp/DeepKE#288]
OSError: Can't load tokenizer for 'zjunlp/llama-7b-lora-ie'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'zjunlp/llama-7b-lora-ie' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.
<img width="844" alt="image" src="https://github.com/zjunlp/DeepKE/assets/107344218/85579652-dc26-45dc-bca7-a4e17b146895">

**Comment by zxlzr** [comment]
请问您问题是否已解决？
