### ISSUE TITLE
如何获取训练数据

### ISSUE THREAD

**Issue by lylcst** [zjunlp/DeepKE#289]
**Describe the question**
> A clear and concise description of what the question is.
您好请问这个链接https://tianchi.aliyun.com/competition/entrance/，如何获取train.json数据，是哪个比赛的数据？

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
您好，是这个比赛的数据，https://tianchi.aliyun.com/competition/entrance/532080/information

**Comment by zxlzr** [comment]
抱歉我们已修正链接

**Comment by lylcst** [comment]
好的谢谢～
