### ISSUE TITLE
关于预测

### ISSUE THREAD

**Issue by RamonaLea** [zjunlp/deepke#29]
你好~如果是想通过输入句子，然后输出类似{实体A，实体B，关系}的话， 是否需要在相应的模型中加入predict的代码？然后通过model.load_state_dict(torch.load('./checkpoints/xx.pth'))，然后再去用model.predict()来输出结果？

**Comment by yuwl798180** [comment]
predict时不仅要输入句子，还要按照预处理语料的方式指出head和tail，然后将句子对照vocab转换为index，再输入到模型。
模型就是predict的过程和训练过程中的test的过程一模一样的，你可以把这块代码复用下就行。

**Comment by RamonaLea** [comment]
好的~谢谢~我去试试~

**Comment by RamonaLea** [comment]
预处理语料处理的方式就是您predict.py里面直接输出的 sentence的那个格式吧

**Comment by yuwl798180** [comment]
是的

**Comment by tantingting1012** [comment]
请问做预测只需要修改def validate(dataloader, model, device, config):函数吗

**Comment by RamonaLea** [comment]
> 请问做预测只需要修改def validate(dataloader, model, device, config):函数吗

好像不是 数据格式也有点不同 你可以看看 我前几天一直在看别的 也没来得及改
