### ISSUE TITLE
实体抽取标签类型-自定义数据

### ISSUE THREAD

**Issue by missyoudaisy** [zjunlp/DeepKE#290]
**Describe the question**
> A clear and concise description of what the question is.
你好，我看官方提供的数据中包含ORG、LOC、PER等实体类型，我想在我自定义的领域数据集上运行deepke的实体识别算法，想问一下标签是需要自己定义吗？（我的领域数据集里的物品的类型和官方数据中的类型不同）

如果我把所有的实体都定义成ORG类型，会对实验结果有所影响吗？

**Comment by xxupiano** [comment]
可以修改https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/conf/train.yaml#L23 为自定义的label然后重新训模型。“如果我把所有的实体都定义成ORG类型”相当于只有2个类？应该不会有影响，甚至效果好更好，

**Comment by zxlzr** [comment]
您好，如果您自定义实体标签（领域数据集里的物品的类型和官方数据中的类型不同）的话，需要收集标注数据训练模型，在有限资源内您可以使用几千-几万标注数据进行训练。

数据标注见https://github.com/zjunlp/DeepKE/blob/main/README_TAG_CN.md

训练模型见https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/README_CN.md 您可以有多种模型选择

如果我把所有的实体都定义成ORG类型，会对实验结果有所影响吗？如果是您自己训的模型结果是影响不大的，**如果您直接使用我们提供的模型是无法识别出来您领域的标签的。**

另外，如果您想进一步提高抽取的泛化性，且有足够算力的话也可以使用https://github.com/zjunlp/KnowLM 项目中智析抽取大模型。

**Comment by missyoudaisy** [comment]
> 可以修改https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/conf/train.yaml#L23 为自定义的label然后重新训模型。“如果我把所有的实体都定义成ORG类型”相当于只有2个类？应该不会有影响，甚至效果好更好

谢谢!

**Comment by missyoudaisy** [comment]
> 您好，如果您自定义实体标签（领域数据集里的物品的类型和官方数据中的类型不同）的话，需要收集标注数据训练模型，在有限资源内您可以使用几千-几万标注数据进行训练。
> 
> 数据标注见https://github.com/zjunlp/DeepKE/blob/main/README_TAG_CN.md
> 
> 训练模型见https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/README_CN.md 您可以有多种模型选择
> 
> 如果我把所有的实体都定义成ORG类型，会对实验结果有所影响吗？如果是您自己训的模型结果是影响不大的，**如果您直接使用我们提供的模型是无法识别出来您领域的标签的。**
> 
> 另外，如果您想进一步提高抽取的泛化性，且有足够算力的话也可以使用https://github.com/zjunlp/KnowLM 项目中智析抽取大模型。

谢谢解答！
