### ISSUE TITLE
使用alpaca-7b-lora-ie权重时的base_model是什么

### ISSUE THREAD

**Issue by nanoponge** [zjunlp/DeepKE#294]
请问在使用[alpaca-7b-lora-ie](https://huggingface.co/zjunlp/alpaca-7b-lora-ie)的权重进行测试时，base_model应该是什么，还是使用llama-7b-hf吗

**Comment by guihonghao** [comment]
https://huggingface.co/circulus/alpaca-7b/tree/main

**Comment by nanoponge** [comment]
可以直接使用finetune_llama.py将base_mode修改为alpaca-7b模型进行微调吗

**Comment by guihonghao** [comment]
可以，finetune_llama中的llama表示的是llama系列模型llama、alpaca、zhixi等，不仅仅表示LLaMA
