### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/huggingface/hub/models--bert-base-chinese/refs/main'

### ISSUE THREAD

**Issue by zx0327** [zjunlp/DeepKE#295]
我在尝试ner的标准任务时，一直报该错误。我看其他的开源项目都会自动去下载相关的预训练文件的

**Comment by xxupiano** [comment]
您好，是否没有联网，联网会自动下载bert-base-chinese。如果无法联网请下载https://huggingface.co/bert-base-chinese 模型到本地，修改此处为下载的模型路径 https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/conf/hydra/model/bert.yaml#L2

**Comment by zx0327** [comment]
唉，联网了。但是github huggingface，10次能断9次。ner的标准任务就成了这样子。

我又从百度网盘下载了你们开箱即用的版本，然后你们的pytorch版本比较低，把pytorch版本去掉之后，可以运行了，又一直报

Missing @package directive hydra/output/custom.yaml

**Comment by xxupiano** [comment]
hydra-core版本是1.0.6吗？

**Comment by zx0327** [comment]
![snapshot](https://github.com/zjunlp/DeepKE/assets/115991572/bf4acd1a-a8ff-49cf-bc19-59b13f8b29c8)
是的，是1.0.6，现在效果是这样的。

还想多问一句，为什么国内的ner的研究多只研究中文，而不是多语种的呢。按道理bert是支持多语种训练的，但是我看大部分模型都只支持中文
