### ISSUE TITLE
llm InstructKGC inference_llama.py

### ISSUE THREAD

**Issue by havocio** [zjunlp/DeepKE#296]
运行inference_llama.py，预测结果中文乱码。
例如 ？？？？位于？？？？？？？？？？？？？？？？？？

还有最新的inference_llama.py运行 报错 Tockenizer class LLaMATokenizer does not exist or is not currently imported

**Comment by guihonghao** [comment]
你可以把AutoTokenizer改成LlamaTokenizer

**Comment by havocio** [comment]
那预测的结果乱码 ，是如何解决的？

**Comment by guihonghao** [comment]
我用llama-7b、zjunlp/llama-7b-lora-ie跑inference_llama.py没有出现乱码现象。请提供更详细的信息。

**Comment by havocio** [comment]
python版本必须是3.9吗，试了3.7和3.10版本结果全为乱码。
命令：
CUDA_VISIBLE_DEVICES="0" python inference_llama.py \
    --base_model 'decapoda-research/llama-7b-hf' \
    --lora_weights 'lora/llama-7b-e3-r8' \
    --input_file 'data/valid.json' \
    --output_file 'result/output_llama_7b_e3_r8.json' \
    --load_8bit \

**Comment by guihonghao** [comment]
你先试试把--load_8bit去掉吧。
或者你训练的lora还没有收敛，建议增加训练epoch，lora_r、lora_alpha

**Comment by havocio** [comment]
是用的llama-7b、zjunlp/llama-7b-lora-ie跑inference_llama.py，去掉--load_8bit还是乱码

**Comment by guihonghao** [comment]
有乱码的截图吗。是输出的全乱码还是部分乱码部分中文？

**Comment by havocio** [comment]
![image](https://github.com/zjunlp/DeepKE/assets/49666447/03035ac0-7838-4526-ae23-3b9b31290305)

**Comment by guihonghao** [comment]
<img width="888" alt="image" src="https://github.com/zjunlp/DeepKE/assets/53286894/8a0c407a-c2f3-49eb-a8d4-21697bd7a396">
with open(input_file, "r", encoding="utf-8") as reader:建议添加encoding="utf-8"，试试zjunlp/alpaca-7b-lora-ie

**Comment by havocio** [comment]
你们出现过这个问题吗？又是如何解决的呢？

**Comment by guihonghao** [comment]
CUDA_VISIBLE_DEVICES="0" python src/inference_llama.py \
    --base_model 'models/alpaca-7b' \
    --lora_weights 'lora/alpaca-7b-lora-ie' \
    --input_file 'data/valid.json' \
    --output_file 'results/alpaca-7b-valid.json' 
以下分别是llama、alpaca输出的结果
![1](https://github.com/zjunlp/DeepKE/assets/53286894/5c78116e-c69d-454c-904a-5775e866c307)
![3](https://github.com/zjunlp/DeepKE/assets/53286894/1c07eb8a-7f3f-4c7a-a0fd-a2b2fc548edf)

**Comment by guihonghao** [comment]
CUDA_VISIBLE_DEVICES="0" python src/inference_llama.py \
    --base_model 'models/alpaca-7b' \
    --lora_weights 'lora/alpaca-7b-lora-ie' \
    --input_file 'data/valid.json' \
    --output_file 'results/alpaca-7b-valid.json' 
以下分别是llama、alpaca输出的结果
![1](https://github.com/zjunlp/DeepKE/assets/53286894/5c78116e-c69d-454c-904a-5775e866c307)
![3](https://github.com/zjunlp/DeepKE/assets/53286894/1c07eb8a-7f3f-4c7a-a0fd-a2b2fc548edf)

**Comment by havocio** [comment]
已经没有乱码了，确定是python版本问题
