### ISSUE TITLE
使用inference_llama.py调用Linly-AI/Chinese-LLaMA-7B模型，报错，没有config.json文件

### ISSUE THREAD

**Issue by wangcyak** [zjunlp/DeepKE#299]
**Describe the question**
> A clear and concise description of what the question is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Comment by guihonghao** [comment]
<img width="1245" alt="image" src="https://github.com/zjunlp/DeepKE/assets/53286894/57084040-7532-4ea6-8f5d-ad8b2cfbf77a">
该路径下没有config.json文件，解决方法参考https://github.com/CVI-SZU/Linly/issues/56、https://github.com/CVI-SZU/Linly/issues/67

**Comment by zxlzr** [comment]
请问您的问题解决了吗
