### ISSUE TITLE
dev branch下predict文件中的serializer

### ISSUE THREAD

**Issue by ywwhxxtw** [zjunlp/deepke#30]
你好，我目前在尝试改写predict部分的代码，看到predict.py中引入了一个serializer库，pip安装之后无法导入，并且看到有一些比较个性化的参数，想问一下这个库是哪里来的？

**Comment by yuwl798180** [comment]
dev仓库的代码还没有更新好。
主要是使用facebook的hydra做定制化的config，可以更方便的测试代码。
serializer是我自己写的代码，有serializer.py文件，这个文件是用来将输入句子序列化的，比如是否需要分词是否需要大小写更改。

hydra代码有个很严重的bug，我已提交了pr，作者说稍后会在0.11.0版本中更新上。
等hydra release 0.11 版本就会把整个代码重构下，增加可读性。

**Comment by ywwhxxtw** [comment]
好的，多谢，我已经实现了master代码的预测，不过你后面要重构的话就不提pull了

**Comment by RamonaLea** [comment]
你好~predict部分的代码可以参考一下吗 因为我改的时候发现好像因为输入数据格式不同，所以好像不能直接套用validation部分的代码？

**Comment by RamonaLea** [comment]
~我改好了~我发现是我自己修改出了问题~
