### ISSUE TITLE
运行pip install deepke报错

### ISSUE THREAD

**Issue by RenDengran** [zjunlp/DeepKE#300]
**Describe the question**
> A clear and concise description of what the question is.
在Python3.8的环境里面
当使用镜像源为阿里、清华、pip官方时候，会报错
使用豆瓣和中科大的时候不会报错。

**Environment (please complete the following information):**
 - OS: [window]
 - Python Version [3.8]

**Screenshots**
> If applicable, add screenshots to help explain your problem.
报错信息如下：

![1](https://github.com/zjunlp/DeepKE/assets/115343531/b71d3ea4-ed00-4f62-8429-d8f20f7ed3ae)

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
请问您的问题解决了吗

**Comment by RenDengran** [comment]
可以直接运行这两个命令之中的一个
pip install -i https://pypi.mirrors.ustc.edu.cn/simple/ --trusted-host pypi.mirrors.ustc.edu.cn deepke pip install -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com deepke
&nbsp;


任登燃
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月8日(星期六) 晚上11:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zjunlp/DeepKE] 运行pip install deepke报错 (Issue #300)





 
请问您的问题解决了吗

**Comment by RenDengran** [comment]
Run one of the following two commands in a terminal：
pip install -i https://pypi.mirrors.ustc.edu.cn/simple/ --trusted-host pypi.mirrors.ustc.edu.cn deepke pip install -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com deepke
&nbsp;


任登燃
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月11日(星期二) 中午11:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zjunlp/DeepKE] 运行pip install deepke报错 (Issue #300)





 
Closed #300 as completed.
