### ISSUE TITLE
w2ner运行报错

### ISSUE THREAD

**Issue by liujc196** [zjunlp/DeepKE#303]
![QQ图片20230711150834](https://github.com/zjunlp/DeepKE/assets/10265724/03bcece0-3ade-4940-8f71-72b1bdd71406)
如图所示，之前提示output中没有bert模型，我放进去了，放进去以后又报了这个错，实在是不会改了。。

还有另外一个问题，就是w2ner中有bert模型，单独的还有bert模型进行训练，为什么同样是用的给的少量数据进行测试，我的bert一个epoch就要8个小时，而w2ner就很快，是我的bert没设置好吗
![QQ图片20230711150900](https://github.com/zjunlp/DeepKE/assets/10265724/99b6d6e6-e341-46cc-98b8-1d2d8e3eaa36)

**Comment by pengzju** [comment]
问题一：似乎是您预训练模型的权重有问题，请您选择此模型：https://huggingface.co/bert-base-chinese
问题二：原因是您自己的bert训练并没有使用GPU，可以从右图看出GPU的使用率为10%，您可以尝试加载bert模型后，model.to('cuda')，即可启动GPU训练（注意相应的数据也要放到cuda上）

感谢您对DeepKE工作的支持，如果解决了您的问题，请帮忙关闭issue！

**Comment by liujc196** [comment]
我选择的确实是这个模型，在bert模型和w2ner里面放的都是这个，pytorch_model.bin将这个文件放入指定位置，虽然右侧显示的是10%，但是我用nvidia-smi查看，确实一共6g显存用了5G多，将近99%，怎么算把数据放到cuda上？就是解压咱们给的数据以后放到data文件夹里了

**Comment by pengzju** [comment]
您好，问题一是这样的。您在使用w2ner前需要先训练模型，需要将
`do_train`改为True
`do_eval`改为False
等训练完之后才能进行评估，对应的state_dict就是正确了的

**Comment by liujc196** [comment]
好的我已经找到地方修改，我先试试，或许我修改完了同样w2ner也得需要8小时的训练了，感谢您的回答
