### ISSUE TITLE
JSON数据变txt

### ISSUE THREAD

**Issue by liujc196** [zjunlp/DeepKE#304]
![~F YS6}OMQ}FRIMAYOL6Z_V](https://github.com/zjunlp/DeepKE/assets/10265724/965516ee-060f-42e5-beda-833d0da13088)

您好，我根据咱们提供标注工具标注以后是json格式的，我没看到文档里哪里说可以将json分成train，dev，test的txt格式，想问一下如何将数据变成咱们程序所需的标准格式。
第二个问题就是，这个LOC,NAM这些标签，是不是必须是英文，大写的，像我图片中“小米”这样是不行的

**Comment by pengzju** [comment]
问题一：这个标注后的数据可能需要您自行处理，我能提供的建议是您可以处理`doc_content`字段，根据`start_offset`设置B-Label，I-Label等，例如对于“小米Civi 1S“
- 小：B-小米
- 米：I-小米
- Civi：I-小米
- 1S：I-小米
来获取相应的标签，其他位置设为O即可。若您没有办法理解，可以搜索并学习ner任务中的B-I-O标签。
train，dev，test我建议您shuffle之后按照8:1:1的比例拆分即可

问题二：如果是standard NER，不涉及利用label信息的情况下，label什么样的字符串都是可以的（所以图中的“小米”没有问题）

**Comment by tianchiguaixia** [comment]
难道不支持json格式里面的start和end？
