### ISSUE TITLE
您好，用自己数据出现的问题

### ISSUE THREAD

**Issue by liujc196** [zjunlp/DeepKE#305]
![2$CR%GQV~GC35Z}J9E8OW](https://github.com/zjunlp/DeepKE/assets/10265724/f6f9b9d8-3096-4429-bd11-3ac2309fe94e)
您好，我用自己的数据，用bilstmcrf已经跑完一遍ner了，但是呢，我用换成bert，就报错了
![H49G%KDLN9WPF9}OPXXZUEU](https://github.com/zjunlp/DeepKE/assets/10265724/d26f747d-0f98-4fc7-b9ce-e1f6be28f2fb)
是不是因为模型没训练过我这个标签
后来我又换成了w2ner试试，用给的数据，能跑
![HP(TC02MQLAE~F9Z8YK3 HU](https://github.com/zjunlp/DeepKE/assets/10265724/9828d211-cf9d-4792-bd6d-ac564484c627)
但是用我自己的数据就不行
![UUAC7~MQ)1VG8%4}H9$8UMT](https://github.com/zjunlp/DeepKE/assets/10265724/e65f7a0e-8ff5-4d59-a16c-6797963154f1)
我怀疑是没有我数据的标签
lstmcrf的我会改，在conf的train里，但是w2ner的我找了好久没找到地方
![GPRY35C}EB(BO 3$X PIJJ0](https://github.com/zjunlp/DeepKE/assets/10265724/cc565055-bcfd-4e71-9619-74de8a5fe443)

**Comment by pengzju** [comment]
您好，w2ner不需要您显示的输入label，**您只需要确保数据的形式是B-I-O即可**（以空格分开数据和标签，就像示例的数据格式），w2ner会自动加载train和eval数据集，遍历获取所有的标签。

**Comment by xxupiano** [comment]
您好，需要修改https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/conf/train.yaml#L23 为自己的标签

**Comment by liujc196** [comment]
> 您好，w2ner不需要您显示的输入label，**您只需要确保数据的形式是B-I-O即可**（以空格分开数据和标签，就像示例的数据格式），w2ner会自动加载train和eval数据集，遍历获取所有的标签。

您好，您看一下我的数据格式，我是用咱们代码中src-transform_data.py生成的自己的数据
![1689497779368](https://github.com/zjunlp/DeepKE/assets/10265724/d0d00b59-d5e2-45cd-89df-dc843e54d7d4)
格式也对啊，lstmcrf都跑过去了，为什么会报错呢5555

**Comment by liujc196** [comment]
> 您好，需要修改https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/conf/train.yaml#L23 为自己的标签

您看我的图片，我已经把标签改成了自己的了，lstmcrf都跑过去了
![image](https://github.com/zjunlp/DeepKE/assets/10265724/b8980c01-8c44-4a3a-a805-61eae5448053)
可是bert和w2ner都报错了

**Comment by liujc196** [comment]
> 您好，需要修改https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/conf/train.yaml#L23 为自己的标签

您好，bert的我发现了，确实有一个标签我临时给改了，导致出错了，已经跑通了，但是我感觉没用到训练数据，速度超快就完成了，也就1,2分钟
![1689500339704](https://github.com/zjunlp/DeepKE/assets/10265724/7cd0029b-a8bf-4ee7-aa15-ce5dfeb647d9)

**Comment by liujc196** [comment]
> 您好，w2ner不需要您显示的输入label，**您只需要确保数据的形式是B-I-O即可**（以空格分开数据和标签，就像示例的数据格式），w2ner会自动加载train和eval数据集，遍历获取所有的标签。

已经跑起来了，原来是把空格也O了导致的，谢谢
