### ISSUE TITLE
模型转换出错

### ISSUE THREAD

**Issue by hongshaodong** [zjunlp/DeepKE#307]
**Describe the bug**
> A clear and concise description of what the bug is.
使用脚本恢复ZhiXi 13B过程中，

OSError: ./converted does not appear to have a file named config.json. Checkout 'https://huggingface.co/./converted/None' for available files.

一开始提升没有converted文件夹，我创建之后再次运行提示我缺少config.json文件，导致无法转换

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python 3.9
 - fire 0.5.0
 - transformers 4.28.1

**Screenshots**
> If applicable, add screenshots to help explain your problem.

``

**Additional context**
> Add any other context about the problem here.

**Comment by hongshaodong** [comment]
希望能够获得帮助，非常感谢！

**Comment by hongshaodong** [comment]
转换命令：  python tools/download.py --download_path ./zhixi-diff-fp16 --only_base --fp16

**Comment by hongshaodong** [comment]
转换命令：python tools/weight_diff.py recover --path_raw ./converted --path_diff ./zhixi-diff-fp16 --path_tuned ./zhixi --is_fp16 True

**Comment by MikeDean2367** [comment]
您好，根据您的描述，我猜测您应该是没有下载原始的llama13b的模型权重，导致的，您可以阅读[此处](https://github.com/zjunlp/KnowLM/blob/main/README_ZH.md#22-%E9%A2%84%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%E6%9D%83%E9%87%8D%E8%8E%B7%E5%8F%96%E4%B8%8E%E6%81%A2%E5%A4%8D)的步骤进行。下面是一种解决方法

如果您没有申请到llama13b的原始权限，您可以使用下面的命令直接下载得到转换好的llama13b模型：
```shell
python tools/download.py --specify --download_path ./converted
```

然后您再执行：
```shell
python tools/weight_diff.py recover --path_raw ./converted --path_diff ./zhixi-diff-fp16 --path_tuned ./zhixi --is_fp16 True
````

如果仍有问题，请告知我 :)

**Comment by hongshaodong** [comment]
很遗憾应该是网络的原因一直卡在下载

**Comment by hongshaodong** [comment]
非常感谢您的帮助

**Comment by zxlzr** [comment]
好的，下一代版本我们会直接提供合并后的权重和多种渠道下载。
