### ISSUE TITLE
您好，天池官网CCKS2023比赛已经关闭了，请问能否提供另外获取数据集的渠道呢？

### ISSUE THREAD

**Issue by RuSignalFlag** [zjunlp/DeepKE#308]
**Describe the question**
> A clear and concise description of what the question is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
您好，近期会公开数据。

**Comment by zxlzr** [comment]
您好数据将在近期更新到readme上

**Comment by zxlzr** [comment]
您好，比赛数据已开源在https://github.com/zjunlp/DeepKE/blob/main/example/llm/InstructKGC/README_CN.md
