### ISSUE TITLE
120.27.214.45 404 Not Found

### ISSUE THREAD

**Issue by luminous11** [zjunlp/DeepKE#309]
I tried to download the PRGC  dataset for entity and relation extraction. However, the dataset download failed. Is the URL changed or the server offline now?

The info is as below:

```
~/2023/DeepKE/example/triple/PRGC$ wget 120.27.214.45/Data/triple/PRGC/data.tar.gz
--2023-07-23 20:35:43--  http://120.27.214.45/Data/triple/PRGC/data.tar.gz
Connecting to 120.27.214.45:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-07-23 20:35:43 ERROR 404: Not Found.
```

**Comment by GoooDte** [comment]
Hello, try `wget 120.27.214.45/Data/triple/PRGC/CMeIE.zip`

**Comment by luminous11** [comment]
> Hello, try `wget 120.27.214.45/Data/triple/PRGC/CMeIE.zip`

Thank you for your reply. It succeeds. 
The download URL should be edited in "https://github.com/zjunlp/DeepKE/blob/dev/example/triple/PRGC/README.md".
