### ISSUE TITLE
bert-base-chinese

### ISSUE THREAD

**Issue by longcheng-wangxj** [zjunlp/DeepKE#310]
**Describe the question**
> A clear and concise description of what the question is.
本地如何加载  

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by GoooDte** [comment]
您好，本地加载模型需要把huggingface上的模型文件下载到本地，并将代码中from_pretrained中的路径更改为本地模型文件夹的路径
