### ISSUE TITLE
File "pytorch_model.bin" not generated after training W2NER model

### ISSUE THREAD

**Issue by YujiUgaki** [zjunlp/DeepKE#311]
**Describe the question**

I trained the W<sup>2</sup>NER model with my own dataset, but no "pytorch_model.bin" file was created in w2ner/output dir. The prediction results also seem missing. Could you help me fix this problem?

**Environment (please complete the following information):**
 - OS: Windows 11 Pro for Workstations 22H2 22621.1992
 - Python 3.8, DeepKE 2.2.1 (built from source)

**Screenshots**

 - w2ner/logs/datetime/run.log
![image](https://github.com/zjunlp/DeepKE/assets/59078662/5d5e352a-d3fe-4c1e-abbe-3684dd11c399)

 - w2ner/conf/train.yaml
![image](https://github.com/zjunlp/DeepKE/assets/59078662/cfaa609f-64f9-40b7-a1fa-59dc145123ae)

 - w2ner/output (EMPTY)
![image](https://github.com/zjunlp/DeepKE/assets/59078662/fc795955-a7c4-4b78-bd88-1d9b2cfa6227)

**Comment by pengzju** [comment]
你好，这是因为图中的F1为0，DeepKE并没有保存权重（保存权重的前提是F1值大于0），具体可见
https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/w2ner/run.py#L279

至于为什么是0？您可以检查下数据，或者也有可能模型训练时间太短欠拟合

**Comment by YujiUgaki** [comment]
非常感谢您的快速答复！ 这是另一次训练的日志：F1 非零，但没有生成文件。train.yaml 中除了“epochs”之外的所有内容都保持不变。

![image](https://github.com/zjunlp/DeepKE/assets/59078662/5d32481c-519c-42d3-a316-f5e9a235e2b8)

**Comment by YujiUgaki** [comment]
这很奇怪。我会再试一次看看结果。

**Comment by pengzju** [comment]
https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/w2ner/run.py#L288，或许您可以在这里打一下断点？

**Comment by YujiUgaki** [comment]
最近一次尝试：3个epoch后，F1非零，模型文件已生成。 非常感谢您的支持！
