### ISSUE TITLE
用于关系提取的数据集采用不同的标记化方法

### ISSUE THREAD

**Issue by YujiUgaki** [zjunlp/DeepKE#312]
我正在尝试用我自己的数据集训练标准 RE 模型。 不幸的是，示例数据集和我的数据集之间的不同标记化方法是不同的。

连续的半角字符在我的数据集中被视为单个标记，而在示例中它们被分开标记。 它会产生不同的“head_offset”和“tail_offset”值：

 - 我的数据集：
 <code>{'sentence': '魔影再现：“魔罗桫”组织以巴基斯坦空间科学委员会招聘为诱饵的攻击活动分析', 'relation': 'target_at', 'head': '魔罗桫', 'head_offest': <font color="red"><strong>5</strong></font>, 'tail': '巴基斯坦', 'tail_offset': <font color="red"><strong>12</strong></font>}</code>
标记化：['魔', '影', '再', '现', <font color="red"><strong>'：“'</strong></font>, '魔', '罗', '桫', '”', '组', '织', '以', '巴', '基', '斯', '坦', '空', '间', '科', '学', '委', '员', '会', '招', '聘', '为', '诱', '饵', '的', '攻', '击', '活', '动', '分', '析']

 - 如果像示例数据集那样进行标记：
 <code>{'sentence': '魔影再现：“魔罗桫”组织以巴基斯坦空间科学委员会招聘为诱饵的攻击活动分析', 'relation': 'target_at', 'head': '魔罗桫', 'head_offest': <font color="red"><strong>6</strong></font>, 'tail': '巴基斯坦', 'tail_offset': <font color="red"><strong>13</strong></font>}</code>
标记化：['魔', '影', '再', '现', <font color="red"><strong>'：', '“'</strong></font>, '魔', '罗', '桫', '”', '组', '织', '以', '巴', '基', '斯', '坦', '空', '间', '科', '学', '委', '员', '会', '招', '聘', '为', '诱', '饵', '的', '攻', '击', '活', '动', '分', '析']

我是否必须更正我的数据集中的标记化方法，以防得到错误模型？

**Comment by zxlzr** [comment]
您好这个和您使用模型的tokenizer有关，您直接使用llama等模型的tokenizer即可

**Comment by YujiUgaki** [comment]
感谢您的答复！ 我先去试一试。

**Comment by YujiUgaki** [comment]
这意味着，我只需要修改 preprocess.py 中的[第 120 行](https://github.com/zjunlp/DeepKE/blob/7d44ddfefe83748cafe8871639fcc8fe7ab3e5e6/src/deepke/relation_extraction/standard/tools/preprocess.py#L120)？将 <code>BertTokenizer</code> 改为 <code>LlamaTokenizer</code>？

我在 [general_utils.py](https://github.com/zjunlp/DeepKE/blob/7d44ddfefe83748cafe8871639fcc8fe7ab3e5e6/example/llm/InstructKGC/src/utils/general_utils.py#L11) 中注意到从 <code>transformer</code> 导入 <code>LlamaTokenizer</code>，但是 <code>transformer</code> 的“__init.py__”文件中缺少 <code>LlamaTokenizer</code>。而且 DeepKE-LLM 还需要不同环境。因此，我需要什么操作才能切换到 <code>LlamaTokenizer</code>？

**Comment by xxupiano** [comment]
transformers需要更新到最新版

**Comment by YujiUgaki** [comment]
已更新，我准备再次尝试。

**Comment by YujiUgaki** [comment]
另外我没有找到 <code>DeepKE/example/re/standard/data/origin/relation.csv</code> 的示例文件。 您能提供一下这个文件的格式吗？

**Comment by YujiUgaki** [comment]
我修改了 <code>deepke.relation_extraction.standard.tools.preprocess.py</code> 文件中的 <code>_lm_serialize</code> 函数，如下所示：

![image](https://github.com/zjunlp/DeepKE/assets/59078662/7fac5331-a0fa-4b17-98fe-6b161f637763)

这是我的“lm.yaml”配置文件。 预训练的模型已经按要求置于需要的目录中。

![image](https://github.com/zjunlp/DeepKE/assets/59078662/55e83747-ea8a-4994-a16f-1d4f22a55785)

但无法加载 <code>LlamaTokenizer</code>，报错如下：

![image](https://github.com/zjunlp/DeepKE/assets/59078662/4036e48a-e033-48f2-9cd7-ee05386dd30b)

**Comment by YujiUgaki** [comment]
当我切换到 <code>BertTokenizer</code> 时，标记生成器似乎已成功加载，尽管 CUDA 存在另一个错误。加载预训练的 <code>BertTokenizer</code> 和 <code>LlamaTokenizer</code> 之间有什么区别吗？

![image](https://github.com/zjunlp/DeepKE/assets/59078662/a6726fe0-4140-4812-a45f-cbd656e5be6d)

![image](https://github.com/zjunlp/DeepKE/assets/59078662/43d82ee2-6843-4999-8b0c-35233e5f13e3)

**Comment by xxupiano** [comment]
您好，可以先不用改并且使用您的数据集尝试一下

**Comment by YujiUgaki** [comment]
谢谢，我尝试了 BertTokenizer。 训练进展顺利，直到在第 42 轮（第 15 轮之后收敛）卡住。 我停止了训练并选择了一个 pth 文件进行三次预测。 预测全部正确，但置信度均为 1.00。 这是否表明存在过度拟合或一些更令人担忧的问题？

**Comment by zxlzr** [comment]
您好，建议您在测试集测试一下，可能过拟合了

**Comment by YujiUgaki** [comment]
感谢您的答复！目前训练集损失 0.007，验证集损失 0.171，测试集损失 0.202，结合曲线图可以判断发生了过拟合。我正在尝试超参数优化。如果您有更好的建议，请与我分享，谢谢！

**Comment by zxlzr** [comment]
您可以使用早停，观察测试集性能没有提升了就停止训练

**Comment by YujiUgaki** [comment]
谢谢你！ 这有效！
