### ISSUE TITLE
python run.py运行时提示No module named 'hydra'

### ISSUE THREAD

**Issue by EviraXu** [zjunlp/DeepKE#313]
环境：win10，python3.8
上述步骤使用源码安装
运行python run.py时提示缺少包
pip install hydra时会报错
 Building wheel for hydra (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      copying src\hydra.py -> build\lib.win-amd64-cpython-38
      running build_ext
      building '_hydra' extension
      creating build\temp.win-amd64-cpython-38
      creating build\temp.win-amd64-cpython-38\Release
      creating build\temp.win-amd64-cpython-38\Release\src
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\xulai\AppData\Local\Temp\pip-install-9jgo21fz\hydra_259f78fedc2f45539b5269b577b755c4\src -IC:\Users\xulai\.conda\envs\deepkedemo\include -IC:\Users\xulai\.conda\envs\deepkedemo\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /Tcsrc/MurmurHash3.c /Fobuild\temp.win-amd64-cpython-38\Release\src/MurmurHash3.obj -std=gnu99 -O2 -D_LARGEFILE64_SOURCE
      cl: 命令行 warning D9002 :忽略未知选项“-std=gnu99”
      MurmurHash3.c
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\xulai\AppData\Local\Temp\pip-install-9jgo21fz\hydra_259f78fedc2f45539b5269b577b755c4\src -IC:\Users\xulai\.conda\envs\deepkedemo\include -IC:\Users\xulai\.conda\envs\deepkedemo\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /Tcsrc/_hydra.c /Fobuild\temp.win-amd64-cpython-38\Release\src/_hydra.obj -std=gnu99 -O2 -D_LARGEFILE64_SOURCE
      cl: 命令行 warning D9002 :忽略未知选项“-std=gnu99”
      _hydra.c
      src/_hydra.c(1621): warning C4244: “函数”: 从“Py_ssize_t”转换到“int”，可能丢失数据
      src/_hydra.c(2668): warning C4267: “=”: 从“size_t”转换到“char”，可能丢失数据
      src/_hydra.c(3377): warning C4018: “<”: 有符号/无符号不匹配
      src/_hydra.c(6964): warning C4244: “函数”: 从“unsigned __int64”转换到“unsigned long”，可能丢失数据
      src/_hydra.c(7072): warning C4244: “函数”: 从“Py_ssize_t”转换到“int”，可能丢失数据
      src/_hydra.c(7103): warning C4244: “函数”: 从“Py_ssize_t”转换到“int”，可能丢失数据
      src/_hydra.c(7316): warning C4267: “函数”: 从“size_t”转换到“unsigned int”，可能丢失数据
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\xulai\AppData\Local\Temp\pip-install-9jgo21fz\hydra_259f78fedc2f45539b5269b577b755c4\src -IC:\Users\xulai\.conda\envs\deepkedemo\include -IC:\Users\xulai\.conda\envs\deepkedemo\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /Tcsrc/mmap_writer.c /Fobuild\temp.win-amd64-cpython-38\Release\src/mmap_writer.obj -std=gnu99 -O2 -D_LARGEFILE64_SOURCE
      cl: 命令行 warning D9002 :忽略未知选项“-std=gnu99”
      mmap_writer.c
      src/mmap_writer.c(5): fatal error C1083: 无法打开包括文件: “unistd.h”: No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hydra
  Running setup.py clean for hydra
Failed to build hydra
ERROR: Could not build wheels for hydra, which is required to install pyproject.toml-based projects

**Comment by GoooDte** [comment]
你好，可以尝试`pip install hydra-core==1.0.6`或者重新按源码安装

**Comment by zxlzr** [comment]
请问您问题解决了吗
