### ISSUE TITLE
unable to install using pip

### ISSUE THREAD

**Issue by pavanbaswani** [zjunlp/DeepKE#314]
**Describe the bug**
> I am facing an issue with installing the package through pip command. I have attached the complete log below.

`Collecting deepke
  Downloading deepke-2.2.4.tar.gz (256 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 257.0/257.0 kB 5.2 MB/s eta 0:00:00a 0:00:01
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-jwbbat15/deepke_027927e9df694ceb84f8d926f69150a1/setup.py", line 4, in <module>
          with open("requirements.txt") as requirements_file:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by GoooDte** [comment]
Hello, please refer to https://github.com/zjunlp/DeepKE/issues/300

**Comment by GoooDte** [comment]
Sorry, we have fixed this bug. Please try `pip install deepke==2.2.5`.

**Comment by GoooDte** [comment]
You can try to download the code and install it by `python setup.py install`

**Comment by zxlzr** [comment]
Hi, have you solved your issue?
