### ISSUE TITLE
使用ChatGLM6B微调时，模型加载出现问题

### ISSUE THREAD

**Issue by liiuzq-xiaobai** [zjunlp/DeepKE#315]
如果ChatGLM6B lora微调时，已经将chatglm6b模型下载到本地，通过本地加载出现如下错误？请问是什么原因。script脚本如下所示
![image](https://github.com/zjunlp/DeepKE/assets/70749713/b14e3bf5-5722-40df-9fba-909d414c7223)
`output_dir='/home/lzq/projects/LLM/DeepKE/example/llm/InstructKGC/Chatglm_train'
mkdir -p ${output_dir}
CUDA_VISIBLE_DEVICES="0,1,2,3" torchrun --nproc_per_node=2 --master_port=1331 src/finetune.py \
    --do_train --do_eval \
    --model_name_or_path '/home/lzq/projects/LLM/chatglm-6b' \
    --model_name 'chatglm' \
    --train_file '../datasets/train.json' \
    --output_dir=${output_dir}  \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --preprocessing_num_workers 8 \
    --num_train_epochs 10 \
    --learning_rate 1e-5 \
    --weight_decay 5e-4 \
    --adam_beta2 0.95 \
    --optim "adamw_torch" \
    --max_source_length 512 \
    --max_target_length 256 \
    --val_set_size 1000 \
    --evaluation_strategy "epoch" \
    --save_strategy "epoch" \
    --save_total_limit 10 \
    --lora_r 8 \
    --lora_alpha 32 \
    --lora_dropout 0.1 \
    --max_memory_MB 24000 \
    --fp16 \
    | tee ${output_dir}/train.log \
    2> ${output_dir}/train.err`

**Comment by pillow-xi** [comment]
您好，麻烦您确认一下，您的环境是否按照DeepKE/example/llm/requirements.txt中环境所配置，此外请您确认下脚本修改后是否进行了保存

**Comment by zxlzr** [comment]
请问您问题解决了吗，您能详细描述下问题吗？
