### ISSUE TITLE
同名关系

### ISSUE THREAD

**Issue by CoolYutaka** [zjunlp/DeepKE#316]
您好, 在训练关系抽取的数据集中, 同名但头尾实体不同类的关系是否需要重新命名以区分? 谢谢!

**Comment by CoolYutaka** [comment]
谢谢您的回复! 按照我的需求, 确实无需重命名. 所以我只需要象 #148 这样在 <code>relation.csv</code> 中保留同名异实体关系, 对吗?
<strong>Date,机构,成立日期,36</strong>
学校,人物,毕业院校,37
Number,机构,占地面积,38
语言,国家,官方语言,39
Text,行政区,邮政编码,40
Number,行政区,人口数量,41
城市,景点,所在城市,42
人物,图书作品,作者,43
<strong>Date,企业,成立日期,44</strong>
人物,歌曲,作曲,45
气候,行政区,气候,46

**Comment by CoolYutaka** [comment]
这样做可以正常训练模型.

但是, 如果 <code>relation.csv</code> 中存在同名异实体关系, 那么在经过函数 <code>_handle_relation_data()</code> 处理后返回的 <code>rels</code> 是一个去重字典, 同名关系只保留一个. 这样 <code>predict.py</code> 就会出问题, 因为 <code>rels</code> 的长度短于 <code>predict.py</code> [第 142 行](https://github.com/zjunlp/DeepKE/blob/main/example/re/standard/predict.py#L142) 得到的张量 <code>y_pred</code>, 所以145 行的代码就会出现索引错误. 不过, 这时我若直接取 <code>y_pred</code> 最大值的 index, 在 <code>relation.csv</code> 对应得到最可能存在关系, 这样做有问题吗?

**Comment by xxupiano** [comment]
关系名用作key来区分label，建议不要使用同名关系

**Comment by YujiUgaki** [comment]
数据集使用了同名关系, 我需要逐个判断手动修改... 请问还有更好的解决办法吗?

**Comment by CoolYutaka** [comment]
数据集使用了同名关系, 我需要逐条判断手动改关系名... 请问还有更好的解决方法吗?

**Comment by xxupiano** [comment]
建议写个代码按照“企业”和“机构”区别，自动改

**Comment by Danmo121** [comment]
有一个问题不是很理解，想咨询一下。如果所有的关系都是特定的，没有同名关系，这意味着任何两个实体类型之间的关系是确定的，例如 学校,和人物之间的关系就是毕业院校。而在预测的时候则需要提供实体类型，这样无论你提供的具体实体名称是什么，只要提供的实体类型，如果提供的实体类型是学校,和人物，那么必然能够得到关系是毕业院校。
