### ISSUE TITLE
请问多模态命名实体识别论文中的效果是在哪个数据集上的

### ISSUE THREAD

**Issue by meareabc** [zjunlp/DeepKE#318]
我想进行和多模态命名实体识别的对比实验，请问论文中的实验结果是否是在twitter17的数据集上进行的，我观察到readme中提供的预训练模型的f1效果和论文中接近，而且比论文中稍微高一点。

**Comment by flow3rdown** [comment]
您好，多模态命名实体识别的模型为IFAformer，来自于这篇[论文](https://arxiv.org/pdf/2211.07504.pdf)，但论文中仅在多模态关系抽取任务上进行了实验，并不包含命名实体识别的结果。IFAformer在Twitter17上的结果可以参考[README](https://github.com/zjunlp/DeepKE/blob/main/example/ner/multimodal/README.md).
