### ISSUE TITLE
调用 W2NER 和 RE 的 predict 函数

### ISSUE THREAD

**Issue by CoolYutaka** [zjunlp/DeepKE#319]
您好!

我想在其他脚本中先调用 <code>w2ner/predict.py</code> 抽取出句中实体; 再将抽取结果作为 RE 的输入, 调用 <code>re/standard/predict.py</code> 得到关系抽取结果, 请问应该如何操作呢? 我尝试过 <code>import</code>, 但总会报错: 找不到配置文件.

恳请您提供宝贵建议, 谢谢!

**Comment by xxupiano** [comment]
请问可以详细描述下w2ner抽出实体如何输入RE代码的吗？不是很懂您说的import是指？

**Comment by CoolYutaka** [comment]
抱歉没讲清楚.

我的项目文件夹结构如下:
kg
|____scripts
|          |
|          |____triple_extraction.py
|
|____DeepKE (从 GitHub 克隆)

我想在 triple_extraction.py 脚本中调用 w2ner/predict.py 和 re/standard/predict.py 的主函数, 于是就写 <code>import DeepKE.example.re.standard.predict as predict_re</code>, 然后运行 <code>predict_re.main()</code>, 结果报错找不到配置文件.

至于 "w2ner抽出实体如何输入RE代码" 的过程, 我又进行了考虑, 发现好像也不容易. 因为主函数不能返回 NER 或 RE 结果.

所以, 对于怎样<strong>在一个脚本中</strong>联合使用 NER 和 RE, 请问您有何建议呢? 非常感谢您的回答!

**Comment by GoooDte** [comment]
您好目前没有比较方便的端到端的同时运行NER和RE的方法，您可以将NER的输出结果保存在文件中然后在运行RE的时候读取该文件
