### ISSUE TITLE
新版本Docker部署指南

### ISSUE THREAD

**Issue by GoooDte** [zjunlp/DeepKE#320]
Download Docker from this [link](https://docs.docker.com/get-docker/).
Pull the Docker image from Docker Hub:
```bash
docker pull zjunlp/deepke
```
If you want to build the Docker image locally, you can clone the project to your local machine and build the Docker image:
```bash
git clone https://github.com/zjunlp/DeepKE.git
cd DeepKE/new_docker
docker build -t deepke .
```
Then run the Docker image as a container:
```bash
docker run -p 8080:80 deepke
```

**Comment by 1ess** [comment]
docker run 运行不起来呢，运行环境 Windows

**Comment by GoooDte** [comment]
您好，我们的docker环境主要面向的是linux环境，推荐您采用`pip`或源码的方式安装

**Comment by hanqiang728** [comment]
在Linux中执行 docker run -p 8080:80 zjunlp/deepke

**Comment by moxiaoyu925** [comment]
使用pip 安装，按照指令，连 requistments.txt 都安装不上去，各种版本不兼容，严格按照操作流程来操作的

**Comment by zxlzr** [comment]
您好，建议您直接使用git clone 的pip  requistments.txt 安装而非docker （大模型时代很多库更新太快了来不及更新兼容支持） 请问您使用的是deepk 还是deepke-llm，如有任何问题您可以新开一个issue
