### ISSUE TITLE
How to inference on vicuna? There is 'adapter_config.json' at ' /home/hw/DeepKE/example/llm/InstructKGC/lora/vicuna-7b-Lora/checkpoint-640'

### ISSUE THREAD

**Issue by Hubotcoder** [zjunlp/DeepKE#321]
[root@localhost InstructKGC]# CUDA_VISIBLE_DEVICES="0" python src/inference.py \
>     --model_name_or_path 'lmsys/vicuna-7b-delta-v1.1' \
>     --model_name 'llama' \
>     --lora_weights ' /home/hw/DeepKE/example/llm/InstructKGC/lora/vicuna-7b-Lora/checkpoint-640' \
>     --input_file 'data/valid.json' \
>     --output_file 'results/results_valid.json' \
>     --fp16 \
>     --bits 8

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /usr/local/anaconda3/envs/deepke-llm/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
CUDA SETUP: CUDA runtime path found: /usr/local/anaconda3/envs/deepke-llm/lib/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /usr/local/anaconda3/envs/deepke-llm/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
InferArguments(model_name_or_path='lmsys/vicuna-7b-delta-v1.1', model_name='llama', lora_weights=' /home/hw/DeepKE/example/llm/InstructKGC/lora/vicuna-7b-Lora/checkpoint-640', input_file='data/valid.json', output_file='results/results_valid.json', prompt_template_name='alpaca', max_source_length=512, max_target_length=256, cutoff_len=512, trust_remote_code=True, train_on_inputs=False, bits=8, double_quant=True, quant_type='nf4', bf16=False, fp16=True)
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:04<00:00,  2.18s/it]
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/deepke-llm/lib/python3.9/site-packages/peft/utils/config.py", line 117, in from_pretrained
    config_file = hf_hub_download(
  File "/usr/local/anaconda3/envs/deepke-llm/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/anaconda3/envs/deepke-llm/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': ' /home/hw/DeepKE/example/llm/InstructKGC/lora/vicuna-7b-Lora/checkpoint-640'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hw/DeepKE/example/llm/InstructKGC/src/inference.py", line 191, in <module>
    main()
  File "/home/hw/DeepKE/example/llm/InstructKGC/src/inference.py", line 186, in main
    inference(options)
  File "/home/hw/DeepKE/example/llm/InstructKGC/src/inference.py", line 92, in inference
    config = LoraConfig.from_pretrained(options.lora_weights)
  File "/usr/local/anaconda3/envs/deepke-llm/lib/python3.9/site-packages/peft/utils/config.py", line 121, in from_pretrained
    raise ValueError(f"Can't find '{CONFIG_NAME}' at '{pretrained_model_name_or_path}'")
ValueError: Can't find 'adapter_config.json' at ' /home/hw/DeepKE/example/llm/InstructKGC/lora/vicuna-7b-Lora/checkpoint-640'

**Comment by guihonghao** [comment]
请确保在/home/hw/DeepKE/example/llm/InstructKGC/lora/vicuna-7b-Lora/checkpoint-640'路径下存在adapter_config.json文件

**Comment by guihonghao** [comment]
Please make sure the file “adapter_config.json” exists in the path of ‘/home/hw/DeepKE/example/llm/InstructKGC/lora/vicuna-7b-Lora/checkpoint-640'

**Comment by guihonghao** [comment]
—model_name_or_path is the path to model weights such as the local path ‘models/vicuna’ and the —lora_weights is the path to Lora weights such as the local path ‘Lora/vicuna-r16’

**Comment by Hubotcoder** [comment]
> Please make sure the file “adapter_config.json” exists in the path of ‘/home/hw/DeepKE/example/llm/InstructKGC/lora/vicuna-7b-Lora/checkpoint-640'

Thank you! I found a redundant space at the beginning of the lora path. Problem solved!
