### ISSUE TITLE
NER/standard/run_lstmcrf.py异常

### ISSUE THREAD

**Issue by gitlihua** [zjunlp/DeepKE#322]
Describe 
数据情况：
通过DeepKE自带的[弱监督功能](https://github.com/zjunlp/DeepKE/blob/main/example/ner/prepare-data/README_CN.md)得到数据
![图片](https://github.com/zjunlp/DeepKE/assets/23493734/a3f366be-2ece-4c39-9f6b-72a6f6960725)

在将这三个文件移动到example/ner/standard/data目录下并一一改名为valid.txt、train.txt、test.txt
![图片](https://github.com/zjunlp/DeepKE/assets/23493734/e57e3adb-9114-4a3f-8b73-34d6d1f4a607)

然后在执行训练时报错，不知道什么原因？报错信息如下：
![图片](https://github.com/zjunlp/DeepKE/assets/23493734/d3962784-971f-4d3b-842c-824703cdc3bc)

**Comment by xxupiano** [comment]
根据报错像是len(eval_dataloader)是0，可以check一下valid.txt是否为空

**Comment by gitlihua** [comment]
我们检查valid.txt确实为空，然后重新加入一些数据让valid.txt不在为空，再次进行训练时还是报错，不知道什么原因？
![图片](https://github.com/zjunlp/DeepKE/assets/23493734/dc647aa4-9a3e-4dee-aed6-76d20d255111)

**Comment by xxupiano** [comment]
/usr/local可能需要管理员写权限，模型没法保存到这里

**Comment by gitlihua** [comment]
我是直接用的root账号  权限问题应该不存在的 而且产生的目录也是755的权限
![图片](https://github.com/zjunlp/DeepKE/assets/23493734/9e15cbac-59d1-4545-aff6-697728b00c2e)

**Comment by zxlzr** [comment]
您好，您可以检查下数据，一般模型至少要几千到几万条训练样本

**Comment by gitlihua** [comment]
好的 我们将验证集增加到几千个已经可以了，我们在进行关系抽取re时，又遇到如下问题，不知道什么原因？
DeepKE自带的[弱监督功能](https://github.com/zjunlp/DeepKE/blob/main/example/re/prepare-data/README_CN.md)自动得到数据

json文件：
![图片](https://github.com/zjunlp/DeepKE/assets/23493734/e8e84eb4-a29e-40e9-b87c-efb04503493f)
triple_file.csv 文件：
![图片](https://github.com/zjunlp/DeepKE/assets/23493734/709ab96b-5737-453e-be0b-81296266e3b8)

在执行命令时报错，不知道什么原因导致的
![图片](https://github.com/zjunlp/DeepKE/assets/23493734/4ba212d2-4f97-4470-8895-ce631b0c79b8)

**Comment by GoooDte** [comment]
您好，注意参数里没有triple_file，与之对应的应该是--dict_file

**Comment by gitlihua** [comment]
你们文档里面写的是用这个参数
![图片](https://github.com/zjunlp/DeepKE/assets/23493734/d817028f-8e31-4eb9-8037-e82f8022003c)

**Comment by gitlihua** [comment]
我将命令换成这个还是报错
![图片](https://github.com/zjunlp/DeepKE/assets/23493734/5540c52d-e995-4db9-9828-bd68385ebbe1)

**Comment by GoooDte** [comment]
感谢您的指正 我们会尽快修改这些bug

**Comment by GoooDte** [comment]
bug已修复 可以按照readme里的方式运行代码

**Comment by gitlihua** [comment]
还是报错
![图片](https://github.com/zjunlp/DeepKE/assets/23493734/a793ac86-343f-4f22-9eca-456f8eeb8201)

**Comment by gitlihua** [comment]
还是报错
![图片](https://github.com/zjunlp/DeepKE/assets/23493734/dc72aa19-055a-4d6d-861f-63a847c7fd5b)

**Comment by gitlihua** [comment]
感谢 已成功转出文件
