### ISSUE TITLE
在使用源码安装DeepKE时报错，想请问怎么解决

### ISSUE THREAD

**Issue by HooRin** [zjunlp/DeepKE#323]
使用
python setup.py install
python setup.py develop
均会报相似的错误：
Installed c:\anaconda3\lib\site-packages\deepke-2.2.6-py3.9.egg
Processing dependencies for deepke==2.2.6
Searching for yaml~=0.2.5
Reading https://pypi.org/simple/yaml/
Download error on https://pypi.org/simple/yaml/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificat
e (_ssl.c:1129) -- Some packages may not be found!
Couldn't find index page for 'yaml' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_s
sl.c:1129) -- Some packages may not be found!
No local packages or working download links found for yaml~=0.2.5
error: Could not find suitable distribution for Requirement.parse('yaml~=0.2.5')

![错误](https://github.com/zjunlp/DeepKE/assets/74388365/bb06a27d-4f69-4c69-b900-3b68dcb82a6d)

**Comment by zxlzr** [comment]
您的问题是否已解决？

**Comment by HooRin** [comment]
还没有，搞了好几天了，用Anaconda虚拟环境也不行，因为我之前用的虚拟机搞得，然后我现在不用虚拟机直接用本机在搞
，到pip install deepke了，目前还在下包。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjunlp/DeepKE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月16日(星期三) 中午11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjunlp/DeepKE] 在使用源码安装DeepKE时报错，想请问怎么解决 (Issue #323)





 
您的问题是否已解决？

**Comment by zxlzr** [comment]
建议您尽量用git clone 源码安装不要使用pip

您这个报错应该就是某个python包没装上（看起来是yaml），这里也建议您手动装这个包就行。

**Comment by HooRin** [comment]
好的谢谢，我再试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月16日(星期三) 中午11:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zjunlp/DeepKE] 在使用源码安装DeepKE时报错，想请问怎么解决 (Issue #323)





 
建议您尽量用git clone 源码安装不要使用pip
 
您这个报错应该就是某个python包没装上（看起来是yaml），这里也建议您手动装这个包就行。

**Comment by zxlzr** [comment]
您可以按https://github.com/zjunlp/DeepKE#manual-environment-configuration 安装，我们测试了好几次各种操作系统均未出现问题

**Comment by HooRin** [comment]
老师，在这个upload界面好长时间了，什么情况
![1692324586716](https://github.com/zjunlp/DeepKE/assets/74388365/d5d086ac-d70f-45f9-8f8e-3d294c934760)

**Comment by xxupiano** [comment]
可参考
https://github.com/wandb/wandb/issues/923
https://community.wandb.ai/t/taking-forever-to-finish-after-waiting-for-w-b-process-to-finish-success/4641/7

**Comment by zxlzr** [comment]
请问您的问题是否已解决？

**Comment by HooRin** [comment]
解决了，可以实现预测了，就是训练模型时间太长了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月20日(星期天) 上午10:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zjunlp/DeepKE] 在使用源码安装DeepKE时报错，想请问怎么解决 (Issue #323)





 
请问您的问题是否已解决？

**Comment by zxlzr** [comment]
请问您是否使用gpu预测，一般对于非大模型建议您使用gpu预测，速度还是可以的，cpu速度慢一些
