### ISSUE TITLE
开箱即用DeepKE-cnSchema运行出错

### ISSUE THREAD

**Issue by BDragon723** [zjunlp/DeepKE#324]
**Describe the bug**
作者大大您好，我最近在学习如何构建知识图谱的时候看见了此项目
发现其中cnSchema竟然可以开箱即用很兴奋，于是学着README中的步骤试着运行了DeepKE-main\example\triple\cnschema中的
predict.py文件，但是却一直报错。
因为是初学所以怕是低级错误一直没敢问，全靠百度必应，但是折磨了我几天后问题依旧没解决
conf\predict.yaml中的内容我更改如下（感觉应该没错...）：
text: '《星空黑夜传奇》是连载于起点中文网的网络小说，作者是啤酒的罪孽'
nerfp: 'D:\technology\DataSet\checkpoints_robert'
refp: 'D:\technology\DataSet\checkpoints_robert\re_robert.pth'
（下载的模型分别是DeepKE(NER), RoBERTa-wwm-ext, Chinese和DeepKE(RE), RoBERTa-wwm-ext, Chinese）
报错图片如下：

**Environment (please complete the following information):**
 - OS: [window]
 - Python Version [3.8.17]

**Screenshots**
> If applicable, add screenshots to help explain your problem.
<img width="876" alt="1" src="https://github.com/zjunlp/DeepKE/assets/107345290/096df6bd-05fc-4b10-80df-1afd136d01b3">
<img width="876" alt="2" src="https://github.com/zjunlp/DeepKE/assets/107345290/6dd04a9a-cc7e-451c-9013-effdc2027c00">

**Additional context**
其实不止这些bug，期间通过百度或者问ChatGPT解决了几个bug，但是解决了一个又出来一个，我实在没招了555，求大大解答！

**Comment by tlk1997** [comment]
修改处理逻辑即可

**Comment by zxlzr** [comment]
您好，您用的代码不是最新的吧，我看了71行predict 没这行，建议您重新pull下代码运行

**Comment by zxlzr** [comment]
https://github.com/zjunlp/DeepKE/blob/fabe6189276cf65ec3ce24211ec689c94c11064c/example/triple/cnschema/predict.py#L70 您可以修改下处理逻辑，这个是模型预测出了实体标签之外的token 导致dict key error

**Comment by BDragon723** [comment]
感谢大大们的回答，我中午又仔细看了一下这个范围内的代码，已经理解了这段代码所要处理的是什么事了，正如大大们所说这段代码是因为模型预测出实体标签外的token导致出错。。我目前还不知道怎么处理所以打算直接pass掉标签外的token
我把68-75行代码改成了：
        if v[0] == 'B':
            if temp != '':
                if result[i-1][1][-1:] != ']':
                    res[temp] =  label2word[result[i - 1][1][2:]]
                else:
                    pass
            temp = k
            last_type = result[i][1][2:]
        elif v[0] == 'I':
            if last_type == result[i][1][2:]:
                temp += k
           
<img width="472" alt="4" src="https://github.com/zjunlp/DeepKE/assets/107345290/aaf2c9e1-47c6-4975-9c70-28813518bb92">


好像暂时是没报错KeyError了！但是在刚刚试错的途中又出现了新的问题。。
<img width="852" alt="3" src="https://github.com/zjunlp/DeepKE/assets/107345290/bbdf7687-088a-4f03-b5cf-9ddfb38dd872">
正如上面的图片所示，有时候甚至在第57行执行代码result = model.predict(text)的时候就会报错（10%的几率会报这个错）。。很神奇
然后就是执行104行的代码model.load(cfg.refp, device=device)时基本都会报错RuntimeError，看报错好像是因为模型对不上？
辛苦大大解答了_(:з」∠)_

**Comment by tlk1997** [comment]
真正报错的为Inferbert的108行label_map，该字典从1开始做标签，不存在0值，这是因为原模型对于你输入文本训练不充分导致，可修改那部分代码去除0值，但最好的方法还是用自己的数据充分训练后再使用

**Comment by BDragon723** [comment]
感谢解答！我也发现了没有用数据训练效果真是一言难尽。。每次输出的标签都是随机的一样。看来还是得训练后才能应用啊，我自己再去研究一下！
