### ISSUE TITLE
在安装包时出现了一些问题

### ISSUE THREAD

**Issue by ppppls115** [zjunlp/DeepKE#325]
**Describe the question**
> A clear and concise description of what the question is.
１.我照着说明创建了一个python3.8的环境，然后开始安装requirements中的包，但是re/standard中的requirements，有个包是torch1.5，pip安装提示没有这个版本的torch。
２.我直接使用pip install deepke，出现了下面的提示：DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063 
都是环境配置方面的问题，这个问题在AI方面应该是很小白的问题，但是我刚入门，还不知道怎么解决，希望作者能帮忙解答一下，谢谢！
*Environment (please complete the following information):**
 - OS: [window]
 - Python Version [3.８]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
如果是传统抽取模型，请参考https://github.com/zjunlp/DeepKE#deepke 里的步骤安装

如果是大模型，请参考https://github.com/zjunlp/DeepKE#deepke-llm 安装

不建议使用pip install 安装

**Comment by ppppls115** [comment]
谢谢解答，环境好像没问题了，但是运行run.py来训练的时候，报错：wandb.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])

**Comment by zxlzr** [comment]
您需要填wandb的key，如果不使用自动调参这行注释掉即可。
