### ISSUE TITLE
使用自己数据集做常规全监督关系提取任务

### ISSUE THREAD

**Issue by kongshengjie** [zjunlp/DeepKE#326]
最近在看关系提取任务，发现example/re/standard中的数据集为句子级关系提取，下载的数据集中一个句子仅对应一个三元组，如下图所示。
![image](https://github.com/zjunlp/DeepKE/assets/119177939/f84a16dc-e619-4b36-a102-af15dd077a36)
如果需要构建自己的数据集，一个句子中会包含1~3个三元组，那么该如何实现呢？

**Comment by zxlzr** [comment]
您好：
1. 您可以把多三元组做成多次关系抽取，如句子有3个三元组，抽取3次即可
2. 您可以使用端到端三元组抽取参见
https://github.com/zjunlp/DeepKE/tree/main/example/triple 这里的方法
3. 您可以使用大模型抽取参见
https://github.com/zjunlp/DeepKE/tree/main/example/llm
有任何问题可以继续交流

**Comment by kongshengjie** [comment]
您好，我还有以下两点疑问：

1. 多三元组做成多次关系抽取：如果一个句子同时存在关系ABC，执行3次关系抽取，抽取结果会不会都是关系A，从而忽略了关系B和C？

1. 端到端三元组抽取：貌似只有ASP支持中文数据集，ASP论文中的关系提取F1只有75%左右，好像没有常规全监督的效果好？

**Comment by zxlzr** [comment]
1. 关系抽取是给定实体的，所以不会
2.端到端的都可以改造支持中文但需要改代码比较麻烦，效果和调参及数据质量有关，但目前效果不如大模型的建议直接使用大模型做端到端抽取

**Comment by kongshengjie** [comment]
好的谢谢

**Comment by kongshengjie** [comment]
您好，在做句子级全监督关系抽取的时候有一些小疑惑，下图是relation.csv文件，里面包含了数据集的所有关系。关系提取的输入是头尾实体名和头尾实体类型，我发现数据集中的头尾实体类型对应着唯一的关系，如头实体“影视作品”和尾实体“人物”对应着唯一的关系“导演”。
![image](https://github.com/zjunlp/DeepKE/assets/119177939/23accf05-7692-466d-969c-c604f94c543e)
