### ISSUE TITLE
源码部署报错包冲突

### ISSUE THREAD

**Issue by lixiaoxiangzhi** [zjunlp/DeepKE#328]
windows环境下python3.9
Installed e:\deepke-main\venv\lib\site-packages\packaging-23.1-py3.9.egg
error: huggingface-hub 0.11.0 is installed but huggingface-hub<1.0.0,>=0.14.0 is required by {'datasets'}

**Comment by GoooDte** [comment]
您好，建议使用python3.8进行安装。
如实在不能解决包冲突，可以单独安装huggingface-hub (0.14-1.0)，能正常使用即可。

**Comment by lixiaoxiangzhi** [comment]
您的来信已收到，祝您每天有个好心情。

**Comment by zxlzr** [comment]
请问您问题是否已解决？
