### ISSUE TITLE
Does this tool support NER?

### ISSUE THREAD

**Issue by xijiz** [zjunlp/deepke#33]
**Describe the question**
> A clear and concise description of what the question is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by yuwl798180** [comment]
sorry, this tool only supports relation extraction currently, so entity mentions(head and tail entities) are the input data, not output data.

Consider adding joint extraction(entity and relation) in next release.
