### ISSUE TITLE
请问 KnowLM-IE 对应的 NER 数据集怎么转换，或者有下载地址吗

### ISSUE THREAD

**Issue by suncheng-s** [zjunlp/DeepKE#330]
**Describe the question**
请问 KnowLM-IE 对应的 NER 数据集怎么转换，或者有下载地址吗

**Comment by guihonghao** [comment]
https://huggingface.co/datasets/zjunlp/knowlm-ke/resolve/main/ner_train.json 这个是KnowLM-13b-IE训练用到的NER数据集

**Comment by suncheng-s** [comment]
> https://huggingface.co/datasets/zjunlp/knowlm-ke/resolve/main/ner_train.json 这个是KnowLM-13b-IE训练用到的中文NER数据集，你可以通过改写 https://github.com/zjunlp/DeepKE/blob/main/example/llm/InstructKGC/kg2instruction/evaluate.py 脚本，将输出字符串转换为列表。

谢谢啦，7 万数据也挺多的。
