### ISSUE TITLE
事件抽取（standard）报错：RuntimeError: index 242 is out of bounds for dimension 1 with size 133

### ISSUE THREAD

**Issue by vladdie** [zjunlp/DeepKE#331]
**Describe the bug**
> A clear and concise description of what the bug is.

运行predict.py的时候报如下错误：
RuntimeError: index 242 is out of bounds for dimension 1 with size 133

此外，predict.yaml中设置了DuEE数据集test_trigger_pred_file的地址，但这个文件并未在上一步中生成，不知是否为必须？可否提供一个更为详尽的说明文档？谢谢。

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by shengyumao** [comment]
您好，请问您是训练了trigger模型以及role模型后运行的predict.py吗，另外DuEE数据集是不需要test_trigger_pred_file的，因为DuEE并没有公开的测试集，因此在训练和预测的时候需要将下面配置文件中的下面两行改为False
https://github.com/zjunlp/DeepKE/blob/main/example/ee/standard/conf/predict.yaml#L9
https://github.com/zjunlp/DeepKE/blob/main/example/ee/standard/conf/train.yaml#L7
如果仍然有错的话，麻烦您提供一下您具体的代码运行流程，我再帮您排查问题

**Comment by zxlzr** [comment]
请问您问题是否已解决？

**Comment by vladdie** [comment]
> 您好，请问您是训练了trigger模型以及role模型后运行的predict.py吗，另外DuEE数据集是不需要test_trigger_pred_file的，因为DuEE并没有公开的测试集，因此在训练和预测的时候需要将下面配置文件中的下面两行改为False https://github.com/zjunlp/DeepKE/blob/main/example/ee/standard/conf/predict.yaml#L9 https://github.com/zjunlp/DeepKE/blob/main/example/ee/standard/conf/train.yaml#L7 如果仍然有错的话，麻烦您提供一下您具体的代码运行流程，我再帮您排查问题

您好，谢谢您的回复。我的问题目前还没解决，因为EE的说明比较少，我还没弄懂是什么一回事，暂时放弃使用这个模型了。
