### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by ilovecomet** [zjunlp/DeepKE#333]
Lora微调LLaMa
环境按https://github.com/zjunlp/DeepKE/blob/main/example/llm/InstructKGC/README_CN.md#4lora%E5%BE%AE%E8%B0%83这个准备
报错如标题所示

LLama使用 https://huggingface.co/decapoda-research/llama-7b-hf
参数使用了--fp16 --bits 8

**Comment by guihonghao** [comment]
建议使用--bits 4，或者修改调整下面几行
'''
    for name, module in model.named_modules():
        if isinstance(module, LoraLayer):
            if args.bf16:
                module = module.to(torch.bfloat16)
        if 'norm' in name:
            module = module.to(torch.float32)
        if 'lm_head' in name or 'embed_tokens' in name:
            if hasattr(module, 'weight'):
                if args.bf16 and module.weight.dtype == torch.float32:
                    module = module.to(torch.bfloat16)
    '''

**Comment by zxlzr** [comment]
请问您问题是否已解决

**Comment by ilovecomet** [comment]
问题已解决，使用--bits 4 或者--bits 16 都可以，调整了几次上面几行代码，都没有成功。
