### ISSUE TITLE
chatglm微调环境问题

### ISSUE THREAD

**Issue by ilovecomet** [zjunlp/DeepKE#335]
安装example下的requirements.txt安装好环境后可以微调llama，在微调chatglm加载模型的时候提示import error（icetk），安装icetk==0.0.7版本的时候需要把protobuf降级到3.19以下，然后再运行的时候就一直报protobuf的错误。
请问下可以提供下chatgml微调的环境版本吗？
我的版本torch==1.13.0 protobuf==3.20.1/3.18，icetk 0.0.7 都不可以。
谢谢

**Comment by pillow-xi** [comment]
您好，谢谢您的提醒，peft包在近期进行了几次大的更新，导致某些情况下出现了bug，我们已经在requirements文件中将peft版本固定在了0.4.0。此外，在example文件下的环境是不需要icetk包的，如果在将peft包换成0.4.0版本没有解决您的问题，您可以重新新建一个环境，按照requirement文件配置环境。

**Comment by ilovecomet** [comment]
> 您好，谢谢您的提醒，peft包在近期进行了几次大的更新，导致某些情况下出现了bug，我们已经在requirements文件中将peft版本固定在了0.4.0。此外，在example文件下的环境是不需要icetk包的，如果在将peft包换成0.4.0版本没有解决您的问题，您可以重新新建一个环境，按照requirement文件配置环境。

感谢您的回复，我peft版本之前装的也是0.4.0版本的，现在又重新建了一个环境，chatglm仍然需要icetk包，麻烦可以确认下icetk的版本吗？
<img width="1225" alt="image" src="https://github.com/zjunlp/DeepKE/assets/48755126/9a0acbad-e4fd-4958-bf0a-353dfc44b6cf">

**Comment by pillow-xi** [comment]
您好，我们的icetk版本是0.0.7, protobuf版本为3.20.0

**Comment by ilovecomet** [comment]
目前已正常，非常感谢！
我查了下chatglm的更新日志，在4月份的一个版本里去掉了对icetk的依赖，我之前下载的chatglm一直没更新，重新下载后就不依赖icetk了，icetk最新版本要求protobuf版本偏低，和很多库不兼容。

**Comment by zxlzr** [comment]
我们会更新下依赖和readme，您后续如果有问题可以随时联系。
