### ISSUE TITLE
关于cross-ner的几个问题

### ISSUE THREAD

**Issue by wl1320310292** [zjunlp/DeepKE#337]
**Describe the question**
> A clear and concise description of what the question is.
你好，有几个问题想要请教下。
1.训练时使用的t-5模型是hf上的google/flan-t5-base吗？
2.请问在做领域迁移的时候，model_name_or_path，targets_prefix_path对应的目标域权重是不是和源域同样的训练方式得到的;
3.训练好的模型进行predict该如何使用呢？是直接使用transformers的T5模型的from_pretrained方法加载吗？

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by flow3rdown** [comment]
1. 使用的t5模型为[t5-base](https://huggingface.co/t5-base/tree/main)
2. 是的
3. 可以借鉴[此处](https://github.com/zjunlp/DeepKE/blob/c3158200453dbf5468e14c423612c72faa5ca285/example/ner/cross/run.py#L521)的代码， 使用的模型是[T5Prompt](https://github.com/zjunlp/DeepKE/blob/c3158200453dbf5468e14c423612c72faa5ca285/src/deepke/name_entity_re/cross/seq2seq/models.py#L7)
