### ISSUE TITLE
源码安装一堆报错，python包兼容性问题（已解决）

### ISSUE THREAD

**Issue by wpfnlp** [zjunlp/DeepKE#338]
源码安装浪费了一天时间，还是报错。
最后选用你们dockfile里的配置。
1. 下载 https://repo.anaconda.com/miniconda/Miniconda3-4.7.12-Linux-x86_64.sh 安装；
2. conda create -y --name deepke python=3.8
3. conda activate deepke
4. python setup.py install

一堆问题；
1. Installed /home/wpf/miniconda3/envs/deepke/lib/python3.8/site-packages/packaging-23.1-py3.8.egg
error: huggingface-hub 0.11.0 is installed but huggingface-hub<1.0.0,>=0.14.0 is required by {'datasets'}

然后设置huggingface_hub==0.14.0进行安装。

2. Downloading https://files.pythonhosted.org/packages/6f/31/a4a8e7367856d9584d0332793edfe631182a9cca885f12dbe2dd77c10c4a/pandas-2.1.0.tar.gz#sha256=62c24c7fc59e42b775ce0679cfa7b14a5f9bfb7643cfbe708c960699e05fb918
Best match: pandas 2.1.0
Processing pandas-2.1.0.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-agatp6ef/pandas-2.1.0.tar.gz

然后单独pip install pandas。

3. Best match: scipy 1.11.2
Processing scipy-1.11.2.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-s4exnlsv/scipy-1.11.2.tar.gz

然后单独pip install scipy。

4. python setup.py install

  raise InvalidRequirement(str(e)) from e
pkg_resources.extern.packaging.requirements.InvalidRequirement: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
5. 最后实在没办法了，单独执行`pip install -r requirements.txt ` ，注释掉setup.py里的`  install_requires=requirements,` 执行  `python setup.py install`

6. python run.py
报错：Could not load override hydra/output/custom

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.



希望国内开源一个框架，多测试下，很多人都安装不了，还不如不开源，浪费大家时间。

希望你们找台干净的系统 git clone从头到尾执行下，试一下。

**Comment by zxlzr** [comment]
> 源码安装浪费了一天时间，还是报错。 最后选用你们dockfile里的配置。
> 
> 1. 下载 https://repo.anaconda.com/miniconda/Miniconda3-4.7.12-Linux-x86_64.sh 安装；
> 2. conda create -y --name deepke python=3.8
> 3. conda activate deepke
> 4. python setup.py install
> 
> 一堆问题；
> 
> 1. Installed /home/wpf/miniconda3/envs/deepke/lib/python3.8/site-packages/packaging-23.1-py3.8.egg
>    error: huggingface-hub 0.11.0 is installed but huggingface-hub<1.0.0,>=0.14.0 is required by {'datasets'}
> 
> 然后设置huggingface_hub==0.14.0进行安装。
> 
> 2. Downloading https://files.pythonhosted.org/packages/6f/31/a4a8e7367856d9584d0332793edfe631182a9cca885f12dbe2dd77c10c4a/pandas-2.1.0.tar.gz#sha256=62c24c7fc59e42b775ce0679cfa7b14a5f9bfb7643cfbe708c960699e05fb918
>    Best match: pandas 2.1.0
>    Processing pandas-2.1.0.tar.gz
>    error: Couldn't find a setup script in /tmp/easy_install-agatp6ef/pandas-2.1.0.tar.gz
> 
> 然后单独pip install pandas。
> 
> 3. Best match: scipy 1.11.2
>    Processing scipy-1.11.2.tar.gz
>    error: Couldn't find a setup script in /tmp/easy_install-s4exnlsv/scipy-1.11.2.tar.gz
> 
> 然后单独pip install scipy。
> 
> 4. python setup.py install
> 
> raise InvalidRequirement(str(e)) from e pkg_resources.extern.packaging.requirements.InvalidRequirement: .* suffix can only be used with `==` or `!=` operators PyYAML (>=5.1.*) ~~~~~~^ 5. 最后实在没办法了，单独执行`pip install -r requirements.txt ` ，注释掉setup.py里的` install_requires=requirements,` 执行 `python setup.py install`
> 
> 6. python run.py
>    报错：Could not load override hydra/output/custom
> 
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
> 
> 希望国内开源一个框架，多测试下，很多人都安装不了，还不如不开源，浪费大家时间。
> 
> 希望你们找台干净的系统 git clone从头到尾执行下，试一下。

您好，非常抱歉，请问 您使用的是大模型版本还是传统版本，因为huggingface库经常更新如果您使用大模型版本请参见https://github.com/zjunlp/DeepKE/tree/main/example/llm#requirements  进行安装， 如果您使用传统模型版本，您使用的方式方式是对的, 我们之前经过多次测试和多位用户反馈是可以正常安装的，我们会马上排查问题，请您谅解。

**Comment by wpfnlp** [comment]
> 使用传统模型版本

但是安装了是了很多三种版本的miniconda，包括你们的dockerfile那个都不行，其实操作步骤都是很简单的，就三个命令。但是安装过程中确实是一堆报错。麻烦协助解决下，谢谢。

**Comment by wpfnlp** [comment]
> > 源码安装浪费了一天时间，还是报错。 最后选用你们dockfile里的配置。
> > 
> > 1. 下载 https://repo.anaconda.com/miniconda/Miniconda3-4.7.12-Linux-x86_64.sh 安装；
> > 2. conda create -y --name deepke python=3.8
> > 3. conda activate deepke
> > 4. python setup.py install
> > 
> > 一堆问题；
> > 
> > 1. Installed /home/wpf/miniconda3/envs/deepke/lib/python3.8/site-packages/packaging-23.1-py3.8.egg
> >    error: huggingface-hub 0.11.0 is installed but huggingface-hub<1.0.0,>=0.14.0 is required by {'datasets'}
> > 
> > 然后设置huggingface_hub==0.14.0进行安装。
> > 
> > 2. Downloading https://files.pythonhosted.org/packages/6f/31/a4a8e7367856d9584d0332793edfe631182a9cca885f12dbe2dd77c10c4a/pandas-2.1.0.tar.gz#sha256=62c24c7fc59e42b775ce0679cfa7b14a5f9bfb7643cfbe708c960699e05fb918
> >    Best match: pandas 2.1.0
> >    Processing pandas-2.1.0.tar.gz
> >    error: Couldn't find a setup script in /tmp/easy_install-agatp6ef/pandas-2.1.0.tar.gz
> > 
> > 然后单独pip install pandas。
> > 
> > 3. Best match: scipy 1.11.2
> >    Processing scipy-1.11.2.tar.gz
> >    error: Couldn't find a setup script in /tmp/easy_install-s4exnlsv/scipy-1.11.2.tar.gz
> > 
> > 然后单独pip install scipy。
> > 
> > 4. python setup.py install
> > 
> > raise InvalidRequirement(str(e)) from e pkg_resources.extern.packaging.requirements.InvalidRequirement: .* suffix can only be used with `==` or `!=` operators PyYAML (>=5.1.*) ~~~~~~^ 5. 最后实在没办法了，单独执行`pip install -r requirements.txt ` ，注释掉setup.py里的` install_requires=requirements,` 执行 `python setup.py install`
> > 
> > 6. python run.py
> >    报错：Could not load override hydra/output/custom
> > 
> > Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
> > 希望国内开源一个框架，多测试下，很多人都安装不了，还不如不开源，浪费大家时间。
> > 希望你们找台干净的系统 git clone从头到尾执行下，试一下。
> 
> 您好，非常抱歉，请问 您使用的是大模型版本还是传统版本，因为huggingface库经常更新如果您使用大模型版本请参见https://github.com/zjunlp/DeepKE/tree/main/example/llm#requirements 进行安装， 如果您使用传统模型版本，您使用的方式方式是对的, 我们之前经过多次测试和多位用户反馈是可以正常安装的，我们会马上排查问题，请您谅解。



    使用传统模型版本

但是安装了是了很多三种版本的miniconda，包括你们的dockerfile那个都不行，其实操作步骤都是很简单的，就三个命令。但是安装过程中确实是一堆报错。麻烦协助解决下，谢谢。

**Comment by zxlzr** [comment]
您好，从您的报错情况看可能是datasets包自己升级了导致兼容性错误，我们会尽快更新requirement并指定版本，在这个包更新前是可以正常安装的。huggingface的python包更新频率非常高，我们没来得及修改兼容配置非常抱歉。

如果您急用的话可以直接使用已经安装好的docker镜像
docker pull zjunlp/deepke:v1
docker run -it zjunlp/deepke:v1 /bin/bash

**Comment by wpfnlp** [comment]
> 您好，从您的报错情况看可能是datasets包自己升级了导致兼容性错误，我们会尽快更新requirement并指定版本，在这个包更新前是可以正常安装的。huggingface的python包更新频率非常高，我们没来得及修改兼容配置非常抱歉。
> 
> 如果您急用的话可以直接使用已经安装好的docker镜像 docker pull zjunlp/deepke:v1 docker run -it zjunlp/deepke:v1 /bin/bash

好的，谢谢您。请抽空尽快更新，谢谢您。我先用docker试一下。

**Comment by wpfnlp** [comment]
![2023-09-18 17-52-42 的屏幕截图](https://github.com/zjunlp/DeepKE/assets/47095734/47c7059b-c5e5-4513-b625-59ce5eeb632f)

docker环境下运行ner/multimodel下的python run.py报错。

**Comment by GoooDte** [comment]
您好 麻烦您按照他的提示运行一下

HYDRA_FULL_ERROR=1 python run.py

我们想看看您的具体报错原因

**Comment by wpfnlp** [comment]
> HYDRA_FULL_ERROR=1 python run.py

(base) root@526379ebe870:~/DeepKE/example/ner/multimodal# HYDRA_FULL_ERROR=1 python run.py
Traceback (most recent call last):
  File "run.py", line 102, in <module>
    main()
  File "/root/miniconda3/lib/python3.7/site-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra
    lambda: hydra.run(
  File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 350, in <lambda>
    overrides=args.overrides,
  File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 104, in run
    run_mode=RunMode.RUN,
  File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 512, in compose_config
    from_shell=from_shell,
  File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 156, in load_configuration
    from_shell=from_shell,
  File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 262, in _load_configuration
    run_mode=run_mode,
  File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 805, in _merge_defaults_into_config
    hydra_cfg = merge_defaults_list_into_config(hydra_cfg, user_list)
  File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 783, in merge_defaults_list_into_config
    package_override=default1.package,
  File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 715, in _merge_config
    raise MissingConfigException(msg, new_cfg, options)
hydra.errors.MissingConfigException: Could not load override hydra/output/custom

**Comment by zxlzr** [comment]
> > HYDRA_FULL_ERROR=1 python run.py
> 
> (base) root@526379ebe870:~/DeepKE/example/ner/multimodal# HYDRA_FULL_ERROR=1 python run.py Traceback (most recent call last): File "run.py", line 102, in main() File "/root/miniconda3/lib/python3.7/site-packages/hydra/main.py", line 37, in decorated_main strict=strict, File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra lambda: hydra.run( File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 201, in run_and_report raise ex File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 198, in run_and_report return func() File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 350, in overrides=args.overrides, File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 104, in run run_mode=RunMode.RUN, File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 512, in compose_config from_shell=from_shell, File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 156, in load_configuration from_shell=from_shell, File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 262, in _load_configuration run_mode=run_mode, File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 805, in _merge_defaults_into_config hydra_cfg = merge_defaults_list_into_config(hydra_cfg, user_list) File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 783, in merge_defaults_list_into_config package_override=default1.package, File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 715, in _merge_config raise MissingConfigException(msg, new_cfg, options) hydra.errors.MissingConfigException: Could not load override hydra/output/custom

您好问题开发同学正在复现中，多模态部分负责同学正在路上将尽快解决您的问题。

**Comment by flow3rdown** [comment]
> > HYDRA_FULL_ERROR=1 python run.py
> 
> (base) root@526379ebe870:~/DeepKE/example/ner/multimodal# HYDRA_FULL_ERROR=1 python run.py Traceback (most recent call last): File "run.py", line 102, in main() File "/root/miniconda3/lib/python3.7/site-packages/hydra/main.py", line 37, in decorated_main strict=strict, File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra lambda: hydra.run( File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 201, in run_and_report raise ex File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 198, in run_and_report return func() File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 350, in overrides=args.overrides, File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 104, in run run_mode=RunMode.RUN, File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 512, in compose_config from_shell=from_shell, File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 156, in load_configuration from_shell=from_shell, File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 262, in _load_configuration run_mode=run_mode, File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 805, in _merge_defaults_into_config hydra_cfg = merge_defaults_list_into_config(hydra_cfg, user_list) File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 783, in merge_defaults_list_into_config package_override=default1.package, File "/root/miniconda3/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 715, in _merge_config raise MissingConfigException(msg, new_cfg, options) hydra.errors.MissingConfigException: Could not load override hydra/output/custom

好像是`importlib-resources`版本的问题，麻烦您看下这个[issue](https://github.com/facebookresearch/hydra/issues/1192)是否能解决您的问题

**Comment by wpfnlp** [comment]
![2023-09-18 21-14-16屏幕截图](https://github.com/zjunlp/DeepKE/assets/47095734/283c5392-8e76-4c70-b9ce-fc262b9dcff5)

已经是最新版本了，换成5.4.0也是一样报错。

**Comment by flow3rdown** [comment]
> ![2023-09-18 21-14-16屏幕截图](https://user-images.githubusercontent.com/47095734/268655265-283c5392-8e76-4c70-b9ce-fc262b9dcff5.png)
> 
> 已经是最新版本了，换成5.4.0也是一样报错。

抱歉，是配置文件的问题，您可以拉取一下最新代码或者手动把`DeepKE/example/ner/multimodal/conf/config.yaml`改为：

```
cwd: ???


defaults:
  - override hydra/output: custom
  - train
  - predict
```

**Comment by zxlzr** [comment]
> > > ![2023-09-18 21-14-16屏幕截图](https://user-images.githubusercontent.com/47095734/268655265-283c5392-8e76-4c70-b9ce-fc262b9dcff5.png)
> > > 已经是最新版本了，换成5.4.0也是一样报错。
> > 
> > 
> > 抱歉，是配置文件的问题，您可以拉取一下最新代码或者手动把`DeepKE/example/ner/multimodal/conf/config.yaml`改为：
> > ```
> > cwd: ???
> > 
> > 
> > defaults:
> >   - hydra/output: custom
> >   - train
> >   - predict
> > ```
> 
> 如果您仍有问题请随时联系我们。

请问您的问题有解决吗？

**Comment by wpfnlp** [comment]
谢谢，已解决。非常感谢。
