### ISSUE TITLE
在执行时报告cannot import name utils

### ISSUE THREAD

**Issue by StCross** [zjunlp/deepke#34]
File main.py ,line 7 in<model>
from hydra import utils
ImportError: cannot import name 'utils'

**Comment by yuwl798180** [comment]
你好，更新后使用的hydra作为配置工具包，这个包版本必须>=0.11才有cwd的功能。
可以查看下hydra的版本吗？ `pip list | grep hydra-core`

**Comment by Arinlzy** [comment]
是不是只 install 了 hydra ？  其实还要 install hydra-core
