### ISSUE TITLE
mt5 安装无法正常运行

### ISSUE THREAD

**Issue by aleversn** [zjunlp/DeepKE#340]
参考[文档](https://github.com/zjunlp/DeepKE/blob/main/example/triple/mt5/README_ZH.md)安装后，
运行先是提示@root_validator问题，
在deepspeed/monitor/config.py下修改@root_validator(skip_on_failure=True)解决

其次是类型检测过不去, enabled 和 num_bits未定义类型，在这里补充后解决

```python
class BaseQuantConfig(DeepSpeedConfigModel):
    enabled: bool = True
    num_bits: int = 8
    q_type: QuantTypeEnum = QuantTypeEnum.sym
    q_groups: int = 1


class WeightQuantConfig(BaseQuantConfig):
    enabled: bool = True


class ActivationQuantConfig(BaseQuantConfig):
    enabled: bool = True


class QKVQuantConfig(DeepSpeedConfigModel):
    enabled: bool = True


class QuantizationConfig(DeepSpeedConfigModel):
    enabled: bool = True
    activation: ActivationQuantConfig = ActivationQuantConfig()
    weight: WeightQuantConfig = WeightQuantConfig()
    qkv: QKVQuantConfig = QKVQuantConfig()
```

接着运行代码依旧报错提示`AttributeError: 'FieldInfo' object has no attribute 'field_info'`，似乎是`pydantic`库版本问题，我看到代码上重写了BaseModel，但是这个field_info调用依然报错。尝试了更换旧版`pydantic`库依旧无法解决，请问下正确的版本是什么？或者需要怎么修复这个问题。

**Environment (please complete the following information):**
 - Ubuntu 22.04
 - Python 3.9

**Screenshots**
![image](https://github.com/zjunlp/DeepKE/assets/30100324/6666dea8-a7d5-41da-bdbf-49b776a244f3)

**Additional context**
> Add any other context about the problem here.

**Comment by guihonghao** [comment]
我们的版本是torch==1.13.0
deepspeed==0.8.3
datasets==2.10.1
numpy==1.24.2
transformers==4.26.0

**Comment by aleversn** [comment]
Thank you for your email. I've received your message. If your message requires a reply, I will sooner get in touch with you. Best RegardsPeichao LaiFuzhou University

**Comment by zxlzr** [comment]
请问您的问题是否已解决？

**Comment by aleversn** [comment]
似乎不行 还是提示`AttributeError: 'FieldInfo' object has no attribute 'field_info'`， 请问pydantic版本是多少？

**Comment by guihonghao** [comment]
pydantic版本是1.10.7，
“其次是类型检测过不去, enabled 和 num_bits未定义类型”，我们的mt5并没有实现量化方面的功能，该版本已不一定很适配。
“我看到代码上重写了BaseModel”，我们没有重写BaseModel，用的是AutoModelForSeq2SeqLM。
全量微调大模型你可以参考https://github.com/AetherCortex/Llama-X

**Comment by aleversn** [comment]
好的 1.10.7可以运行了
