### ISSUE TITLE
模型存储地

### ISSUE THREAD

**Issue by whwususu** [zjunlp/DeepKE#341]
您好！我运行了学习，报如下错误：
![image](https://github.com/zjunlp/DeepKE/assets/25104771/01dee720-c737-4114-8378-8feb554c37e2)
现实无法下载谷歌的模型，现在我手动到https://huggingface.co/bert-base-chinese/tree/main，将模型下载下来了，我不知道将其放在项目的何处，或者有配置可以配，谢谢！

**Comment by GoooDte** [comment]
您好，您只需要将配置文件（一般在`conf`文件夹下）中的模型名称参数改为您下载到本地的模型的路径即可

**Comment by whwususu** [comment]
> 您好，您只需要将配置文件（一般在`conf`文件夹下）中的模型名称参数改为您下载到本地的模型的路径即可

嗯，谢谢，弄好了。还请教下，从目前的训练情况看，是LLaMA还是bert效果好啊，现在想搞一个专业领域的知识库
