### ISSUE TITLE
CCKS2023数据下载链接已失效

### ISSUE THREAD

**Issue by ZhouqyCH** [zjunlp/DeepKE#343]
非常感谢作者优秀的工作！
我注意到，Repo中的CCKS2023的数据下载链接：https://github.com/zjunlp/DeepKE/blob/main/example/llm/LLMICL/README_CN.md#%E6%95%B0%E6%8D%AE
已失效，是否可以更新有效的下载链接？
谢谢！

**Comment by guihonghao** [comment]
链接已更新
