### ISSUE TITLE
开箱即用模型运行失败

### ISSUE THREAD

**Issue by Sugaraqua** [zjunlp/DeepKE#346]
**Describe the question**
> A clear and concise description of what the question is.
您好，我在官网下载了cnSchema的开箱即用模型做关系抽取（前因是我使用deepke自行训练模型，训练结果准确率只有57%，因此想用提供的训练好的模型试试），在但是不知是哪里错误，使用示例时抽取出的关系是错误的（2023-10-09 16:51:29,554][__main__][INFO] - "男人的爱" 和 "人生长路" 在句中关系为："毕业院校"，置信度为1.00。），输入“n”自行输入句子的话就会报错无法预测，请问您能想到是哪方面的原因吗？还是说我使用模型的方法有误？

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by xxupiano** [comment]
'输入“n”自行输入句子的话就会报错无法预测'请问报错是什么？

**Comment by Sugaraqua** [comment]
您好。
我使用http://deepke.openkg.cn/CN/cnSchema.html官网的两个测试用例输入
句子一：

抽取出错误结果

句子二：

报错：

各项参数设置：

我是照着文档安装的deepke，但是自己训练出的模型准确率只有0.57，然后发现官网提供了开箱即用模型，准确率较高，但是不知道哪里设置错误，无法正常使用。
希望您指点一二。





&nbsp;


南京の暗鸦
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xin ***@***.***&gt;; 
发送时间: 2023年10月9日(星期一) 晚上8:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zjunlp/DeepKE] 开箱即用模型运行失败 (Issue #346)





 
'输入“n”自行输入句子的话就会报错无法预测'请问报错是什么？

**Comment by zxlzr** [comment]
您好，issue里看不到您的case能再发一下吗？

**Comment by Sugaraqua** [comment]
您好。
我使用[http://deepke.openkg.cn/CN/cnSchema.html官网的两个测试用例输入](http://deepke.openkg.cn/CN/cnSchema.html%E5%AE%98%E7%BD%91%E7%9A%84%E4%B8%A4%E4%B8%AA%E6%B5%8B%E8%AF%95%E7%94%A8%E4%BE%8B%E8%BE%93%E5%85%A5)
句子一：
![image](https://github.com/zjunlp/DeepKE/assets/147385402/9e8a7bfc-cb38-407c-9595-f5483d06a7e5)
抽取出错误结果：
![image](https://github.com/zjunlp/DeepKE/assets/147385402/b0e128fb-10a6-4929-8f96-891b3effb82e)
句子二：
![image](https://github.com/zjunlp/DeepKE/assets/147385402/ae780c79-c5f0-4e2b-ad6a-29d51aadf27c)
报错：
![image](https://github.com/zjunlp/DeepKE/assets/147385402/fb3dad97-25b4-4c95-8552-e369e00ba44c)
各项参数设置：
![image](https://github.com/zjunlp/DeepKE/assets/147385402/cbe123a7-a2d1-42fd-a3a8-8f45dbffd1c9)
我是照着文档安装的deepke，但是自己训练出的模型准确率只有0.57，然后发现官网提供了开箱即用模型，准确率较高，但是不知道哪里设置错误，无法正常使用。
希望您指点一二。

**Comment by zxlzr** [comment]
您好，会有开发同学尽快联系处理

**Comment by tlk1997** [comment]
你好，针对第一个句子，输入头尾实体类型效果最优，因为在训练时对文本进行了处理，将文本中的头尾实体用其头尾实体类型替代，针对第二个句子，可以将rels和y_pred打印出来排查错误。模型准确率和数据集也相关，如果用的不是cnschema的数据集，那么0.57也正常，

**Comment by Sugaraqua** [comment]
我是使用的文档里的数据集，
![image](https://github.com/zjunlp/DeepKE/assets/147385402/654d7e7f-e465-4e51-9ce6-096e9a34a4bd)
训练了两次，第一次30个epoch，从第25轮左右开始训练的准确率就达到1了，验证准确率停留在0.57，第二次训练满了50个epoch（因为我看到代码默认是50），准确率仍然没有什么提升。
像这种可能是过拟合的问题吗？这个框架设置多少epoch比较好呢？

**Comment by tlk1997** [comment]
训练的时候num_relation的值有修改成数据集中relation.csv中关系类型个数嘛

**Comment by Sugaraqua** [comment]
训练时修改了，默认值就是11，文档里的关系类型个数也是11（None加上10个对应关系）。
先前使用re_robert.pth预测出错，发现是关系集文件relation.csv没有修改导致的，照着官网修改关系集后内置用例可以正确预测
![image](https://github.com/zjunlp/DeepKE/assets/147385402/dce33248-4da2-4394-b249-4cd0e570131f)
但是对于官网给出的几个用例预测结果还是不准确
![image](https://github.com/zjunlp/DeepKE/assets/147385402/6d440ff5-fbd1-4e48-9773-92e672a2c93e)
![image](https://github.com/zjunlp/DeepKE/assets/147385402/7728d1e1-1f46-4ed6-a456-1110b6b5eeec)

**Comment by Sugaraqua** [comment]
relation.csv我是按照README_CNSCHEMA_CN.md里的表格排序的
![image](https://github.com/zjunlp/DeepKE/assets/147385402/4ccef0ad-c816-4d8d-91dc-604d8713eaa6)
另外请问训练cnschema使用的是什么数据集？

**Comment by tlk1997** [comment]
cnschema 数据集 https://drive.google.com/drive/folders/1UurqpjePe3zhXxbDDNwLAjVvt7UyUMuQ

**Comment by tlk1997** [comment]
可以自己训练后再预测试试

**Comment by Sugaraqua** [comment]
好的，谢谢

**Comment by Sugaraqua** [comment]
您好，请问这个数据集有国内网盘吗？

**Comment by Sugaraqua** [comment]
1713429049@qq.com，十分感谢！
