### ISSUE TITLE
如何批量预测并保存预测结果？

### ISSUE THREAD

**Issue by pangpangDD** [zjunlp/DeepKE#347]
您好！

当前软件针对NER和RE任务预测方式均为手动输入一句话，控制面板输出预测结果。如果针对大批量成千上万条的数据，请问本软件支持进行批量预测并保存结果至指定文件的功能吗？如果没有，还请点拨一二，感谢！

**Comment by xxupiano** [comment]
抱歉，目前仅支持交互模式。您可以修改predict.py代码，首先读取需要预测的句子文件，然后使用for循环（如果大批量建议并行）进行预测，最后保存结果到指定文件。谢谢

**Comment by pangpangDD** [comment]
好的，谢谢您！
