### ISSUE TITLE
训练结果

### ISSUE THREAD

**Issue by xyh1108** [zjunlp/DeepKE#348]
**Describe the question**
> A clear and concise description of what the question is.
您好，我在使用给定数据集执行完ner文件夹下的run_bert.py之后，出现各项训练指标为0的情况，训练的epoch设置是100

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

![image](https://github.com/zjunlp/DeepKE/assets/119033080/54fa6467-3de1-4404-b9cb-84b454c87787)

**Additional context**
> Add any other context about the problem here.

**Comment by xxupiano** [comment]
从train_loss可以看出训练崩溃了，推测可能因为epoch太大过拟合，一般3-5个即可

**Comment by xyh1108** [comment]
我将epoch设置为5再次进行了训练，训练完成得到的指标依然是0，train_loss变为0.72.请问这是怎么回事

**Comment by zxlzr** [comment]
请问您训练数据量是多少，对于预训练小模型来说一般至少需要几千到几万条标注数据，是否可能数据太少了？

**Comment by xyh1108** [comment]
训练所使用的数据集是下方的这个
<img width="806" alt="2257a4d11cdee206ec93adc2417c43f" src="https://github.com/zjunlp/DeepKE/assets/119033080/efa5725a-4ae7-49df-a468-51fcc71ba278">

**Comment by xxupiano** [comment]
请问使用的是我们提供的默认configuration吗？

**Comment by xyh1108** [comment]
是的 我只修改了其中的一些参数

**Comment by xxupiano** [comment]
修改了哪些参数呢？如果改回默认的还会出现上述问题吗？

**Comment by xyh1108** [comment]
您好 我修改了训练时的batch_size以及将bert.yaml中的bert_model设置为pretrained文件夹下的模型地址

**Comment by xxupiano** [comment]
batch_size是否太小？

**Comment by xyh1108** [comment]
训练时设置的batch_size为32

**Comment by zxlzr** [comment]
请问您问题是否已解决? 建议您用默认参数试一试默认参数我们经过多次测试没有发现问题
