### ISSUE TITLE
DeepKE常规关系抽取模拟训练这一步出错

### ISSUE THREAD

**Issue by Mineminen** [zjunlp/DeepKE#349]
**Describe the question**
> A clear and concise description of what the question is.

你好，我按照README_CN.md安装好环境后，在常规关系抽取运行python run.py出现了以下错误：
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/huggingface/hub/models--bert-base-chinese/refs/main'

**Environment (please complete the following information):**
 - OS: Centos7
 - Python Version 3.8

**Screenshots**
> If applicable, add screenshots to help explain your problem.

![c3bdcae39134ab788397210f8088f60](https://github.com/zjunlp/DeepKE/assets/145844682/17280967-850f-4400-a70e-5a10f48f4683)

**Additional context**
> Add any other context about the problem here.
我开始是创建缺失目录文件
![3af35e187472f1716c88b27b4b66f2f](https://github.com/zjunlp/DeepKE/assets/145844682/6895dc40-7463-4088-8925-40aed79aaebb)
然后又出现了新的问题：
OSError: Can't load tokenizer for 'bert-base-chinese'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-chinese' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer.

**Comment by Sugaraqua** [comment]
我在安装过程中也遇到了这一问题，因为下载模型的huggingface网站国内无法直连，https://zhuanlan.zhihu.com/p/625595604这篇文章有网盘资源，可以尝试。

**Comment by Mineminen** [comment]
我已经解决了，在conf/config.yaml中换个模型就可以了
![25fc188465a8706320d549919370b1a](https://github.com/zjunlp/DeepKE/assets/145844682/7331a6b2-4644-4500-af5c-912be6ba3671)
把lm换成cnn

**Comment by wangchao1980** [comment]
> > 我在安装过程中也遇到了这一问题，因为下载模型的huggingface网站国内无法直连，[https://zhuanlan.zhihu.com/p/625595604这篇文章有网盘资源，可以尝试。](https://zhuanlan.zhihu.com/p/625595604%E8%BF%99%E7%AF%87%E6%96%87%E7%AB%A0%E6%9C%89%E7%BD%91%E7%9B%98%E8%B5%84%E6%BA%90%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%B0%9D%E8%AF%95%E3%80%82)
> > 我已经下载了bert-base-chinese，不换model，怎么设置配置呢

![image](https://github.com/zjunlp/DeepKE/assets/28770548/3eac9d05-8a3f-4753-88ef-e669d566136c)

lm_file设置成模型的目录即可

**Comment by Emily-0203** [comment]
感谢博主，真的弄半天了，稀里糊涂的，改了这个真的可以了
