### ISSUE TITLE
麻烦问一下，我要把自己的数据集改为您提供的csv格式，请问csv中head_offset与tail_offset是什么？

### ISSUE THREAD

**Issue by wangguanhua** [zjunlp/deepke#35]

**Comment by yuwl798180** [comment]
`entity_offset` 是指头实体在句中的位置。

比如： `南京南站位于南京的西南方。` head` 如果是`南京南站`，`tail`是`南京`，则`head_offset`为0，`tail_offset`为6。

offset主要为了保证句中head tail的位置正确，这样在预处理中，将实体信息替换为实体类型（比如南京替换为城市）可以显著提升关系抽取的效果。

当然如果语料中头尾实体在句中只出现1次，不会错误判断位置（或者句中同时出现几次entity但不影响关系判断），这个offset信息不要也可以的。（此时句子为简单句）
