### ISSUE TITLE
提取三元组的性能能达到多少

### ISSUE THREAD

**Issue by LincolnFan** [zjunlp/DeepKE#353]
我只有0.2~0.3左右
训练集是KnowLM-IE.json选5000条，模型是llama7b，超参都是根据readme设置的

**Comment by guihonghao** [comment]
https://drive.google.com/file/d/1vfD4xgToVbCrFP2q-SD7iuRT2KWubIv9/view
你可以从上面的链接获得比赛的训练集。llama7b大概能达到F1 20～30左右。此外在数据了较少的情况下，建议只使用一种指令格式。

**Comment by LincolnFan** [comment]
> https://drive.google.com/file/d/1vfD4xgToVbCrFP2q-SD7iuRT2KWubIv9/view 你可以从上面的链接获得比赛的训练集。llama7b大概能达到F1 20～30左右。此外在数据了较少的情况下，建议只使用一种指令格式。

如果换作其他模型，区别大吗

**Comment by guihonghao** [comment]
baichuan2会更好些，在中文上。

**Comment by LincolnFan** [comment]
好的，谢谢你（回复好快）

**Comment by LincolnFan** [comment]
> Contributor

如果增大数据量会好些吗，现在这样是不是比非llm的都低

**Comment by guihonghao** [comment]
增大数据量会更好，在mt5-base上的fine-tuning结果显示低于llm 7B的lora微调结果。

**Comment by LincolnFan** [comment]
好的，谢谢你
