### ISSUE TITLE
 ERROR:torch.distributed.elastic.multiprocessing.api

### ISSUE THREAD

**Issue by YikunHan42** [zjunlp/DeepKE#354]
**Describe the bug**
> A clear and concise description of what the bug is.
学习这个案例的时候，https://github.com/zjunlp/DeepKE/blob/main/example/llm/InstructKGC/README_CN.md/#lora%E5%BE%AE%E8%B0%83llama，执行`bash scripts/fine_llama.bash`出现或许跟并行处理相关的报错

**Environment (please complete the following information):**
 - OS: Linux
 - Python Version 3.9
 - GPU 4090

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![image](https://github.com/zjunlp/DeepKE/assets/101811299/05ef79d7-506d-4768-ac27-73f301e6ceaf)

**Additional context**
> 感谢帮助

**Comment by guihonghao** [comment]
确保你拥有2块GPU或者将CUDA_VISIBLE_DEVICES="0,1" torchrun --nproc_per_node=2 --master_port=1331 src/finetune.py 换成CUDA_VISIBLE_DEVICES="0" python src/finetune.py 试试

**Comment by zxlzr** [comment]
请问您问题是否已解决

**Comment by YikunHan42** [comment]
> 请问您问题是否已解决



> 确保你拥有2块GPU或者将CUDA_VISIBLE_DEVICES="0,1" torchrun --nproc_per_node=2 --master_port=1331 src/finetune.py 换成CUDA_VISIBLE_DEVICES="0" python src/finetune.py 试试

感谢

**Comment by YikunHan42** [comment]
> 请问您问题是否已解决

可以了，请问后面是只需要把`llama-7b`模型下载到`InstructKGC`下的`models/llama-7b`路径就可以了吧？

**Comment by guihonghao** [comment]
lora微调是只需要把llama-7b模型下载到InstructKGC下的models/llama-7b路径就可以了

**Comment by YikunHan42** [comment]
> lora微调是只需要把llama-7b模型下载到InstructKGC下的models/llama-7b路径就可以了

好的

**Comment by YikunHan42** [comment]
> lora微调是只需要把llama-7b模型下载到InstructKGC下的models/llama-7b路径就可以了

请问把`llama-7b`下载到对应的路径后，执行`fine_llama.bash`后报这个错是为什么呢

![image](https://github.com/zjunlp/DeepKE/assets/101811299/715c68c8-f925-46e7-9ef7-d97e455d7f35)

**Comment by guihonghao** [comment]
确保当前路径是InstructKGC，models在InstructKGC目录下，检查models/llama-7b路径下是否存在tokenizer.json等文件。

**Comment by YikunHan42** [comment]
> 确保当前路径是InstructKGC，models在InstructKGC目录下，检查models/llama-7b路径下是否存在tokenizer.json等文件。

感谢
