### ISSUE TITLE
NotImplementedError: Loading a dataset cached in a LocalFileSystem is not supported.

### ISSUE THREAD

**Issue by 1304150468** [zjunlp/DeepKE#355]
**Describe the question**
> A clear and concise description of what the question is.
您好，我参照example/ner/cross中的README.md进行配置，在进行到[Train]步骤时出现NotImplementedError报错，train.yaml文件与README.md中的一致

**Environment (please complete the following information):**
 - OS: [Linux]
 - Python Version [3.8]

**Screenshots**
![image](https://github.com/zjunlp/DeepKE/assets/106361049/53d9797d-9143-479e-ad62-16f76b092ae2)

**Additional context**

**Comment by flow3rdown** [comment]
麻烦您尝试更新一下`datasets`的版本

**Comment by 1304150468** [comment]
感谢你的回答，在更新完datasets后我得到下面的报错：
![image](https://github.com/zjunlp/DeepKE/assets/106361049/4616227d-a6a7-4fb5-88b4-e92d3a1ae04f)
我现在正在从https://huggingface.co/models上下载对应的模型，但不清楚需要下载哪些文件：
![image](https://github.com/zjunlp/DeepKE/assets/106361049/5812464e-1ae7-47dc-a4b0-219db2c3c0e2)
可以说明一下吗，或者这个报错有其他的解决方法？

**Comment by flow3rdown** [comment]
您可以从hugginface.co上下载模型文件（包括`config.json`, `generation_config.json`, `pytorch_model.bin`, `tokenizer.json`, `spiece.model`）到本地，并修改yaml文件中`model_name_or_path`为本地模型路径；或者是直接将yaml文件中`model_name_or_path`修改为`t5-base`，将会自动下载模型文件（不稳定）。

**Comment by 1304150468** [comment]
好的，文件已经在下载中。另外我想请问一下，在最开始的报错里cached中的dataset uie_json是什么用途？

**Comment by flow3rdown** [comment]
`uie_json.py`用于读取数据文件

**Comment by 1304150468** [comment]
好的，非常感谢，在下载模型后执行`python run.py`后出现以下报错：
![image](https://github.com/zjunlp/DeepKE/assets/106361049/b8a7d143-50d6-4e5e-8c28-7329706e159f)
我没有找到能修改`padding='max_length'`的地方，请问这是什么原因

**Comment by 1304150468** [comment]
好的，非常感谢，在下载模型后执行`python run.py`后出现以下报错：
![image](https://github.com/zjunlp/DeepKE/assets/106361049/b8a7d143-50d6-4e5e-8c28-7329706e159f)
我没有找到能修改`padding='max_length'`的地方，请问这是什么原因

**Comment by flow3rdown** [comment]
这个问题跟`padding='max_length'`没有关系，可能是你cuda有问题，参考这个[issue](https://github.com/pytorch/pytorch/issues/31285)

**Comment by zxlzr** [comment]
请问您问题是否已解决

**Comment by 1304150468** [comment]
感谢您的解答，关于开始的问题已经解决
