### ISSUE TITLE
cnschema未找到'models--hfl--chinese-bert-wwm\\refs\\main'

### ISSUE THREAD

**Issue by WjJjr1** [zjunlp/DeepKE#356]
**Describe the question**
> A clear and concise description of what the question is.
您好,我按照readme_cnschema中的联合三元组抽取步骤,运行predict.py,报出了如下错误FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\LoveLy/.cache\\huggingface\\hub\\models--hfl--chinese-bert-wwm\\refs\\main',我的前面设置ner和re的fp应该都没问题

**Environment (please complete the following information):**
 - OS:  window
 - Python Version 3.8

**Screenshots**
> If applicable, add screenshots to help explain your problem.

![image](https://github.com/zjunlp/DeepKE/assets/139326659/583e1f64-914c-46ee-8f28-409a7948d069)
![image](https://github.com/zjunlp/DeepKE/assets/139326659/a215ee43-f342-47da-ae05-1c87882eedd9)

**Additional context**
> Add any other context about the problem here.

**Comment by tlk1997** [comment]
你好能给出具体报错行数嘛，根据报错大概率是没有从huggingface下载hfl/chinese-bert-wwm模型，可以提前下载后，将https://github.com/zjunlp/DeepKE/blob/main/example/triple/cnschema/conf/model/lm.yaml#L6C10-L6C31修改成模型路径
