### ISSUE TITLE
cnSchema的relation.cvs在哪里下载

### ISSUE THREAD

**Issue by hjnlxuexi** [zjunlp/DeepKE#361]
在使用CNSCHEMA 运行 python predict.py 时
任然需要关系文件   data/origin/relation.csv
请问在哪里下载？

**Comment by GoooDte** [comment]
你好 尝试：
wget 120.27.214.45/Data/re/standard/data.tar.gz
tar -xzvf data.tar.gz

**Comment by hjnlxuexi** [comment]
> 你好 尝试： wget 120.27.214.45/Data/re/standard/data.tar.gz tar -xzvf data.tar.gz

这个relation只有11项，但是文档中指示，CNSCHEMA时把embedding.yaml中num_relations为51（关系个数）

**Comment by xxupiano** [comment]
https://github.com/zjunlp/DeepKE/tree/main/example/triple/cnschema/data 可以在这里或share的模型checpoint链接里找到

**Comment by zxlzr** [comment]
请问您的问题是否解决，还有新的问题吗？

**Comment by hjnlxuexi** [comment]
已经找到了  谢谢解答
