### ISSUE TITLE
RecursionError during inference

### ISSUE THREAD

**Issue by Kkkassini** [zjunlp/DeepKE#362]
**Describe the question**
Getting RecursionError when trying to make inference with 
`CUDA_VISIBLE_DEVICES=1,2 python src/inference.py \
    --model_name_or_path ...xxx/model_weights/knowlm-13b-zhixi \
    --model_name zjunlp/knowlm-13b-zhixi \
    --input_file data/valid.json \
    --output_file results/results_valid.json \
    --fp16 \
    --bits 8 `

valid_json: `{"id": 0, "instruction": "已知候选的实体类型列表：['组织机构', '地理位置', '人物']，请你根据实体类型列表，从以下输入中抽取出可能存在的实体。请按照\"(实体,实体类型)\"的格式回答。", "input": "在这里恕弟不恭之罪，敢在尊前一诤：前人论书，每曰“字字有来历，笔笔有出处”，细读公字，何尝跳出前人藩篱，自隶变而后，直至明季，兄有何新出？"}
{"id": 1, "instruction": "已知候选的实体类型列表：['组织机构', '地理位置', '人物']，请你根据实体类型列表，从以下输入中抽取出可能存在的实体。请按照\"(实体,实体类型)\"的格式回答。", "input": "相比之下，青岛海牛队和广州松日队的雨中之战虽然也是0∶0，但乏善可陈。"}
{"id": 2, "instruction": "已知候选的实体类型列表：['组织机构', '地理位置', '人物']，请你根据实体类型列表，从以下输入中抽取出可能存在的实体。请按照\"(实体,实体类型)\"的格式回答。", "input": "理由多多，最无奈的却是：5月恰逢双重考试，她攻读的博士学位论文要通考；她任教的两所学校，也要在这段时日大考。"}
{"id": 3, "instruction": "已知候选的实体类型列表：['组织机构', '地理位置', '人物']，请你根据实体类型列表，从以下输入中抽取出可能存在的实体。请按照\"(实体,实体类型)\"的格式回答。", "input": "当前国有大中型企业改制中存在的问题。"}
`

**Environment (please complete the following information):**
 - OS: CentOS 8.1
 - Python Version: Python 3.9.16

**Screenshots**
![image](https://github.com/zjunlp/DeepKE/assets/31933415/a2694a2f-1e64-4383-9dc9-1c5d92712bba)

**Additional Info"
First launch returns error : `ImportError: 
LlamaConverter requires the protobuf library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.`

So I then installed missing package `pip install protobuf`
Then it returns 

```
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

I have to downgrade protobuf to 3.20.1. 

Then the inference could be launched but then give `RecursiveError`

**Comment by Kkkassini** [comment]
Issue solved. Things might be useful to improve in Readme:

- Install the requirements.txt in /DeepKE, and then install another requirements.txt in /DeepKE/example/llm/InstructKGC since the protobuf==3.20.1 only exists in the txt from root level. 
- Declare the list of candidates for the `model_name` parameter, which might be from 
- `MODEL_DICT = {
    "llama":["llama", "alpaca", "vicuna", "zhixi"],
    "falcon":["falcon"],
    "baichuan":["baichuan"],
    "chatglm":["chatglm"],
    "moss": ["moss"],
}`
otherwise people will use `zjunlp/knowlm-13b-zhixi` as model_name instead of `zhixi` for example.

**Comment by Kkkassini** [comment]
Also would be glad to know if the inference speed could be improved? currently inferring these 5 samples takes about 3-4 minutes. I'm using 2* Tesla T4. Is the speed normal?

**Comment by guihonghao** [comment]
The inference speed is normal; sorry, we have not yet worked on improving the inference speed.
