### ISSUE TITLE
为什么tutorial中的例子一个都跑不通啊？

### ISSUE THREAD

**Issue by jhj033** [zjunlp/DeepKE#363]
**Describe the bug**
> A clear and concise description of what the bug is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by GoooDte** [comment]
您好，tutorial中的例子只是一般的环境配置和代码运行的流程，可能不够详细和准确，具体还是请您参考对应模块的readme

**Comment by zxlzr** [comment]
您好，请问您跑的是哪个示例，我们会安排工程师协助。

**Comment by jhj033** [comment]
比方说ner/standard/standard_ner_tutorial.ipynb报这样的错，不知道如何下手解决：
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[4], line 29
     26     raise ValueError("At least one of `do_train` or `do_eval` must be True.")
     28 # Checkpoints
---> 29 if os.path.exists(os.path.join(utils.get_original_cwd(), cfg.output_dir)) and os.listdir(os.path.join(utils.get_original_cwd(), cfg.output_dir)) and cfg.do_train:
     30     raise ValueError("Output directory ({}) already exists and is not empty.".format(os.path.join(utils.get_original_cwd(), cfg.output_dir)))
     31 if not os.path.exists(os.path.join(utils.get_original_cwd(), cfg.output_dir)):

File /share/warehouse/anaconda3/envs/deepke/lib/python3.8/site-packages/hydra/utils.py:108, in get_original_cwd()
    104 """
    105 :return: the original working directory the Hydra application was launched from
    106 """
    107 if not HydraConfig.initialized():
--> 108     raise ValueError(
    109         "get_original_cwd() must only be used after HydraConfig is initialized"
    110     )
    111 ret = HydraConfig.get().runtime.cwd
    112 assert ret is not None and isinstance(ret, str)

ValueError: get_original_cwd() must only be used after HydraConfig is initialized

**Comment by jhj033** [comment]
再比如说：ae/standard/standard_ae_tutorial.ipynb的报错，比较古怪：
---------------------------------------------------------------------------
---------------------------++++++++++++++++++++++++++++++++last_hidden_state
TypeError                                 Traceback (most recent call last)
Cell In[10], line 17
     15 logger.info('=' * 10 + ' Start training ' + '=' * 10)
     16 for epoch in range(1, cfg.epoch + 1):
---> 17     train_loss = train(epoch, model, train_dataloader, optimizer, criterion, cfg)
     18     valid_f1, valid_loss = validate(epoch, model, valid_dataloader, criterion)
     19     scheduler.step(valid_loss)

Cell In[8], line 10, in train(epoch, model, dataloader, optimizer, criterion, cfg)
      8 for batch_idx, (x, y) in enumerate(dataloader, 1):
      9     optimizer.zero_grad()
---> 10     y_pred = model(x)
     11     loss = criterion(y_pred, y)
     13     loss.backward()

File /share/warehouse/anaconda3/envs/deepke/lib/python3.8/site-packages/torch/nn/modules/module.py:1194, in Module._call_impl(self, *input, **kwargs)
   1190 # If we don't have any hooks, we want to skip the rest of the logic in
   1191 # this function, and just call forward.
   1192 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194     return forward_call(*input, **kwargs)
   1195 # Do not call functions when jit is used
   1196 full_backward_hooks, non_full_backward_hooks = [], []

Cell In[6], line 16, in PretrainLM.forward(self, x)
     14 output, pooler_output = self.lm(word)
     15 print(f'---------------------------++++++++++++++++++++++++++++++++{output}')
---> 16 output = torch.tensor(output)
     17 output = pack_padded_sequence(output, lens, batch_first=True, enforce_sorted=True)
     18 _, (output,_) = self.bilstm(output)

TypeError: new(): invalid data type 'str'

**Comment by zxlzr** [comment]
> ## 比方说ner/standard/standard_ner_tutorial.ipynb报这样的错，不知道如何下手解决：
> ValueError Traceback (most recent call last) Cell In[4], line 29 26 raise ValueError("At least one of `do_train` or `do_eval` must be True.") 28 # Checkpoints ---> 29 if os.path.exists(os.path.join(utils.get_original_cwd(), cfg.output_dir)) and os.listdir(os.path.join(utils.get_original_cwd(), cfg.output_dir)) and cfg.do_train: 30 raise ValueError("Output directory ({}) already exists and is not empty.".format(os.path.join(utils.get_original_cwd(), cfg.output_dir))) 31 if not os.path.exists(os.path.join(utils.get_original_cwd(), cfg.output_dir)):
> 
> File /share/warehouse/anaconda3/envs/deepke/lib/python3.8/site-packages/hydra/utils.py:108, in get_original_cwd() 104 """ 105 :return: the original working directory the Hydra application was launched from 106 """ 107 if not HydraConfig.initialized(): --> 108 raise ValueError( 109 "get_original_cwd() must only be used after HydraConfig is initialized" 110 ) 111 ret = HydraConfig.get().runtime.cwd 112 assert ret is not None and isinstance(ret, str)
> 
> ValueError: get_original_cwd() must only be used after HydraConfig is initialized

您好这个例子有提示do_train 或do_eval至少一个为True，您需要修改输入。

**Comment by zxlzr** [comment]
> ## 再比如说：ae/standard/standard_ae_tutorial.ipynb的报错，比较古怪：
> ---------------------------++++++++++++++++++++++++++++++++last_hidden_state TypeError Traceback (most recent call last) Cell In[10], line 17 15 logger.info('=' * 10 + ' Start training ' + '=' * 10) 16 for epoch in range(1, cfg.epoch + 1): ---> 17 train_loss = train(epoch, model, train_dataloader, optimizer, criterion, cfg) 18 valid_f1, valid_loss = validate(epoch, model, valid_dataloader, criterion) 19 scheduler.step(valid_loss)
> 
> Cell In[8], line 10, in train(epoch, model, dataloader, optimizer, criterion, cfg) 8 for batch_idx, (x, y) in enumerate(dataloader, 1): 9 optimizer.zero_grad() ---> 10 y_pred = model(x) 11 loss = criterion(y_pred, y) 13 loss.backward()
> 
> File /share/warehouse/anaconda3/envs/deepke/lib/python3.8/site-packages/torch/nn/modules/module.py:1194, in Module._call_impl(self, *input, **kwargs) 1190 # If we don't have any hooks, we want to skip the rest of the logic in 1191 # this function, and just call forward. 1192 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks 1193 or _global_forward_hooks or _global_forward_pre_hooks): -> 1194 return forward_call(*input, **kwargs) 1195 # Do not call functions when jit is used 1196 full_backward_hooks, non_full_backward_hooks = [], []
> 
> Cell In[6], line 16, in PretrainLM.forward(self, x) 14 output, pooler_output = self.lm(word) 15 print(f'---------------------------++++++++++++++++++++++++++++++++{output}') ---> 16 output = torch.tensor(output) 17 output = pack_padded_sequence(output, lens, batch_first=True, enforce_sorted=True) 18 _, (output,_) = self.bilstm(output)
> 
> TypeError: new(): invalid data type 'str'

这个例子可能是因为主模块是2年前开发的，python库版本已经经过了多年迭代，我们计划下线全部tutorial；建议您直接使用readme中的例子是可以直接跑通的。另外deepke 的非大模型版本和大模型版本deepke-llm使用不同的库依赖，这个需要注意下。

**Comment by jhj033** [comment]
> > ## 再比如说：ae/standard/standard_ae_tutorial.ipynb的报错，比较古怪：
> > ---------------------------++++++++++++++++++++++++++++++++last_hidden_state TypeError Traceback (most recent call last) Cell In[10], line 17 15 logger.info('=' * 10 + ' Start training ' + '=' * 10) 16 for epoch in range(1, cfg.epoch + 1): ---> 17 train_loss = train(epoch, model, train_dataloader, optimizer, criterion, cfg) 18 valid_f1, valid_loss = validate(epoch, model, valid_dataloader, criterion) 19 scheduler.step(valid_loss)
> > Cell In[8], line 10, in train(epoch, model, dataloader, optimizer, criterion, cfg) 8 for batch_idx, (x, y) in enumerate(dataloader, 1): 9 optimizer.zero_grad() ---> 10 y_pred = model(x) 11 loss = criterion(y_pred, y) 13 loss.backward()
> > File /share/warehouse/anaconda3/envs/deepke/lib/python3.8/site-packages/torch/nn/modules/module.py:1194, in Module._call_impl(self, *input, **kwargs) 1190 # If we don't have any hooks, we want to skip the rest of the logic in 1191 # this function, and just call forward. 1192 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks 1193 or _global_forward_hooks or _global_forward_pre_hooks): -> 1194 return forward_call(*input, **kwargs) 1195 # Do not call functions when jit is used 1196 full_backward_hooks, non_full_backward_hooks = [], []
> > Cell In[6], line 16, in PretrainLM.forward(self, x) 14 output, pooler_output = self.lm(word) 15 print(f'---------------------------++++++++++++++++++++++++++++++++{output}') ---> 16 output = torch.tensor(output) 17 output = pack_padded_sequence(output, lens, batch_first=True, enforce_sorted=True) 18 _, (output,_) = self.bilstm(output)
> > TypeError: new(): invalid data type 'str'
> 
> 这个例子可能是因为主模块是2年前开发的，python库版本已经经过了多年迭代，我们计划下线全部tutorial；建议您直接使用readme中的例子是可以直接跑通的。另外deepke 的非大模型版本和大模型版本deepke-llm使用不同的库依赖，这个需要注意下。

我区分开deepke和deepke-llm环境的，但是我跑了你们几乎所有非deepke-llm的readme，基本都不能一把跑通，主要是却模型，或者可能是deepke的版本不匹配问题，不容易跑通。

**Comment by zxlzr** [comment]
您好，非常抱歉部分包可能年代久远，python 包发生更新导致了兼容问题，您可以尝试使用早期的版本或者参考下文件夹内requirement写的库版本进行安装。如果有具体问题您可以继续提issue。

**Comment by jhj033** [comment]
> 您好，非常抱歉部分包可能年代久远，python 包发生更新导致了兼容问题，您可以尝试使用早期的版本或者参考下文件夹内requirement写的库版本进行安装。如果有具体问题您可以继续提issue。

好的，谢谢您耐心的讲解！

**Comment by jhj033** [comment]
由于tutorial代码太老而没有更新，请大家忽略tutorial，按照readme的步骤运行都还是ok的。
