### ISSUE TITLE
训练模型时JSON文件为空

### ISSUE THREAD

**Issue by 1304150468** [zjunlp/DeepKE#365]
**Describe the question**
> A clear and concise description of what the question is.

**Environment (please complete the following information):**
 - OS: [Linux]
 - Python Version [3.8]

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![image](https://github.com/zjunlp/DeepKE/assets/106361049/c8c7b5f4-c770-45e9-b7a9-511ad699ce88)

**Additional context**
> Add any other context about the problem here.

**Comment by GoooDte** [comment]
您好，可以尝试把/home/ubuntu/.cache/huggingface中的文件清理一下，如果还是不行，尝试用科学上网的方式下载huggingface数据集

**Comment by 1304150468** [comment]
感谢你的回答，在删除一些文件后以上的报错没有了，但是又出现了如下的报错：
![image](https://github.com/zjunlp/DeepKE/assets/106361049/1e2938f7-f40b-444e-aee1-b8277cde6eb6)
请问这是什么原因呢
