### ISSUE TITLE
执行run.py时检测类型列表为空

### ISSUE THREAD

**Issue by 1304150468** [zjunlp/DeepKE#366]
**Describe the question**
> A clear and concise description of what the question is.
在训练模型时出现type_list和role_list都为空值的情况，应该从何处查找问题

**Environment (please complete the following information):**
 - OS: [Linux]
 - Python Version [3.8]

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![image](https://github.com/zjunlp/DeepKE/assets/106361049/bceb096c-0834-46fa-9137-67d6f0689a51)
![image](https://github.com/zjunlp/DeepKE/assets/106361049/077aba53-02f9-423d-8d83-bc107fab6093)

**Additional context**
> Add any other context about the problem here.

**Comment by GoooDte** [comment]
可以看一下schema参数是否传入成功，从报错来看schema是None

**Comment by 1304150468** [comment]
非常感谢您，检查后是路径问题
