### ISSUE TITLE
chatglm ptuning:ValueError: None is not in list

### ISSUE THREAD

**Issue by www-dayin** [zjunlp/DeepKE#367]
**Describe the bug**
> A clear and concise description of what the bug is.
Traceback (most recent call last):
  File "/root/elton_space/DeepKE/example/llm/InstructKGC/src/finetuning_pt.py", line 191, in <module>
    main()
  File "/root/elton_space/DeepKE/example/llm/InstructKGC/src/finetuning_pt.py", line 155, in main
    train_dataset = Seq2SeqDataSet(args.train_path, tokenizer, args.max_len, args.max_src_len)
  File "/root/elton_space/DeepKE/example/llm/InstructKGC/src/finetuning_pt.py", line 36, in __init__
    context_length = input_ids.index(tokenizer.bos_token_id)
ValueError: None is not in list

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![image](https://github.com/zjunlp/DeepKE/assets/53402493/98083b87-13c0-4f73-b1b0-a5b5df2f2d13)
![image](https://github.com/zjunlp/DeepKE/assets/53402493/d2aea907-34e0-43bb-a0ce-6825c5ad2aa3)

![image](https://github.com/zjunlp/DeepKE/assets/53402493/15d4e3be-4e1c-46a2-91a6-c66d8898c24a)

**Additional context**
> Add any other context about the problem here.

**Comment by guihonghao** [comment]
这似乎是由于ChatGLM在v2、v3版本中去掉了bos_token_id导致的。

**Comment by zxlzr** [comment]
have you solved your issue?
