### ISSUE TITLE
The Hydra package can't be installed in windows environment

### ISSUE THREAD

**Issue by duanzhichen** [zjunlp/DeepKE#368]
When run the run.py file in \example\re\standard, a error of "ModuleNotFoundError: No module named 'hydra'" is reported; however I installed the hydra package by pip install deepke or python setup.py install , an error has occured, the detailed effor is as follows:
<img width="714" alt="8B4787A3-7336-4473-A8FE-20D8559432C7" src="https://github.com/zjunlp/DeepKE/assets/9105991/82cac7f7-5e3b-4447-ab7b-d02ade958f98">

I have tried all the versions of Hydra, the Hydra package don't exist in the requirement.txt file.

**Comment by GoooDte** [comment]
Hi, the package here is `hydra-core` which has been contained in the `requirement.txt` file. You can  clear your environment named `deepke` and try to install deepke by `pip install deepke`.

**Comment by zxlzr** [comment]
have you solved your issue?
