### ISSUE TITLE
IntructIE数据集如何转换为事件抽取指令数据集？

### ISSUE THREAD

**Issue by yfangZhang** [zjunlp/DeepKE#370]
![image](https://github.com/zjunlp/DeepKE/assets/65322222/b25a2e3d-26ae-404b-af1c-071b2f740443)
IntructIE数据集只有entity和relation两项内容，无法通过kg2instruction/convert.py，进行事件抽取数据的转换

**Comment by zxlzr** [comment]
您好，目前InstructionIE数据集里面暂时没有事件类数据，所以无法进行转换，我们计划在未来迭代数据支持更多功能。
