### ISSUE TITLE
PURE训练后进行预测提示错误

### ISSUE THREAD

**Issue by Nydaym** [zjunlp/DeepKE#373]
**训练后进行预测出现问题**
> 找不到这个包，提示报错。

```
Traceback (most recent call last):
  File "predict.py", line 11, in <module>
    from deepke.triple_extraction.PURE.module.data_structures import Dataset, evaluate_predictions
ModuleNotFoundError: No module named 'deepke.triple_extraction.PURE.module'
```

**Environment:**
 - OS: [Linux]
 - Python Version [e.g. 3.7]
 -  deepke                   2.2.7        /root/miniconda3/lib/python3.7/site-packages/deepke-2.2.7-py3.7.egg

**Comment by Nydaym** [comment]
我看了一下好像关于PURE的包都没了，看GITHUB的代码里面也没有，这个库被遗弃了吗？

**Comment by xzwyyd** [comment]
I'm sorry for the inconvenience. It seems that there was a mistake in our code. To fix this issue, you can try adding an 's' after the word 'module', making it 'modules.data_structures'. Please try this solution and let us know if it works. If you encounter any further difficulties, don't hesitate to ask for help. Thank you for your understanding and patience!

**Comment by Nydaym** [comment]
> I'm sorry for the inconvenience. It seems that there was a mistake in our code. To fix this issue, you can try adding an 's' after the word 'module', making it 'modules.data_structures'. Please try this solution and let us know if it works. If you encounter any further difficulties, don't hesitate to ask for help. Thank you for your understanding and patience!

I tried your method, but it may not be the cause of the bug. Upon inspecting the source code, I found that there were corresponding methods for ASP and PRGC in the triple extraction, but the PURE file was empty.

**Comment by xzwyyd** [comment]
Sorry, all the code for PURE has been moved to the Example file before, and that part of the code may need to be modified. The location of the package is in the `DeepKE/example/triple/PURE/models` file.

**Comment by xzwyyd** [comment]
You can try changing `deepke.triple_extraction.PURE.module.data_structures` to `models.data_structures`. If you have any further questions or need further assistance, please feel free to let me know. Thank you for your patience!

**Comment by Nydaym** [comment]
Thanks,I will try it.
