### ISSUE TITLE
DeepKE-cnSchema运行联合三元组抽取出错

### ISSUE THREAD

**Issue by czknotnull** [zjunlp/DeepKE#377]
**Describe the feature**
> A clear and concise description of any features you've considered.
哥哥们好，小弟刚开始学习模型训练方面的技能，想要实现知识图谱抽取
然后按照官网操作手册中[联合三元组抽取](http://deepke.zjukg.cn/CN/cnSchema.html)的步骤，执行python predict.py时，报错图片如下：
![error1](https://github.com/zjunlp/DeepKE/assets/43194009/7041ef5d-1a13-4f03-aabb-00598d5f34b8)
本地环境和conda（python3.8、3.9）都试过了，报错一样的：
![error2](https://github.com/zjunlp/DeepKE/assets/43194009/217b5bf9-e29e-4302-9de2-3944dac28354)
conf\predict.yaml中的内容我更改如下：
text: '此外网易云平台还上架了一系列歌曲，其中包括田馥甄的《小幸运》等'
nerfp: 'D:\czk\work\java_applications\AI\cnSchema-NER\checkpoints\checkpoint_bert'
refp: 'D:\czk\work\java_applications\AI\cnSchema-RE\RE\re_bert.pth'

Environment (please complete the following information):
OS: [window]
Python Version [3.9.13]
麻烦哥哥们给指导一下

**Comment by GoooDte** [comment]
您好 尝试把num_labels改为60

**Comment by czknotnull** [comment]
> 您好 尝试把num_labels改为60

哪个脚本的num_labels

**Comment by GoooDte** [comment]
根据报错信息来看是因为classifier层的维度不匹配，应该是你定义的标签数量与模型预训练的标签数量不匹配

**Comment by zxlzr** [comment]
请问您的问题是否已解决？

**Comment by czknotnull** [comment]
> 根据报错信息来看是因为classifier层的维度不匹配，应该是你定义的标签数量与模型预训练的标签数量不匹配

非常感谢，问题已经解决了，需要加一下模型里面的参数"num_labels": 60,下载下来的模型里面是没有这个参数的
![reply1](https://github.com/zjunlp/DeepKE/assets/43194009/aa1f776a-874f-4a23-8d11-5b1feab39b9b)
![reply2](https://github.com/zjunlp/DeepKE/assets/43194009/45f4ec9d-8662-4c5a-bc6e-0e1ab17865b4)

**Comment by czknotnull** [comment]
> 请问您的问题是否已解决？

已经解决了，非常感谢
