### ISSUE TITLE
InstructKGC对自定义实体类型提取效果不佳

### ISSUE THREAD

**Issue by calvinzhan** [zjunlp/DeepKE#378]
**Describe the bug**
> A clear and concise description of what the bug is.
用example/llm/InstructKGC/src/inference.py进行NER。模型用的是knowlm-13b-ie。类型为"老人旅客"和"孕妇旅客"。

测试数据如下：
{"id": "1e073138ed48eeb6f9726dc34addc6dff821cef502f4ba292c911351d597a8e6", "instruction": "请在所给文本中找出并列举\n['老人旅客', '孕妇旅客']\n提及的实体类型，不存在的类型请注明为NAN。回答应按(实体,实体类型)\n的规范排列。", "input": "特殊服务需求年长旅客，是指70周岁及以上独自出行需要提供无成人陪伴服务，或者身体有障碍、病患，包括身体年迈，短距离（一般在约200米以内）可自行行走，但长距离（约200米以上）行走体力不支，需要轮椅代步的年长旅客。 a）此类旅客服务需求涉及到旅客自身或者航空运输安全，需要在长龙航空直属售票处或拨打我司客服热线（956199）购票，并在购票时提出申请服务。 b）在购买客票时，旅客需填写《特殊旅客乘机申请书A类》（以下简称《乘机申请书》）；若情况特殊，旅客需提交适宜乘机的《医疗诊断证明书》，则填写《特殊旅客乘机申请书B类》，地服人员需告知旅客乘机风险并协助其签署免责，具体要求参见《旅客行李运输手册》病患旅客的相关规定。", "output": "NAN"}

------------------------
预期结果：(特殊服务需求年长旅客, 老人旅客)

实际结果：(老人旅客,实体类型),(孕妇旅客,实体类型)

出现这样的问题，是因为实体类型不常见吗？

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
请问您还有其它问题吗？
