### ISSUE TITLE
执行自定义联合三元组抽取报错：JsonLdError

### ISSUE THREAD

**Issue by czknotnull** [zjunlp/DeepKE#379]
text: '钱学森（英文：Qian Xuesen，1911年12月11日—2009年10月31日），出生于上海，籍贯浙江杭州，中国共产党的优秀党员，忠诚的共产主义战士，享誉海内外的国家杰出贡献科学家和中国航天事业的奠基人，中国科学院、中国工程院资深院士，中国人民政治协商会议第六届、七届、八届全国委员会副主席，两弹一星功勋奖章获得者。钱学森1929—1934年就读于国立交通大学机械工程系；1939年获得美国加州理工学院航空和数学博士学位；1947年任麻省理工学院教授；1956年任中国科学院力学研究所所长；1957年补选为中国科学院学部委员（院士）；1965年任中华人民共和国第七机械工业部副部长；1970年任中国人民解放军国防科学技术委员会副主任；1986年6月任中国科学技术协会主席；1994年当选为中国工程院院士；钱学森主要从事应用力学、工程控制论、航空工程、火箭导弹技术、系统工程和系统科学、思维科学和人体科学以及马克思主义哲学等领域的研究。'
执行predict.py，报一下错误：
![error-1](https://github.com/zjunlp/DeepKE/assets/43194009/c8357518-665c-4e6c-965c-278bff9cd7bd)
![error-2](https://github.com/zjunlp/DeepKE/assets/43194009/dff82c04-355f-4eef-9910-26eb65ed95ba)
，如果按照text: '钱永忠教授毕业于美国加州大学圣迭戈分校，现为美国明尼苏达大学物理与天文系教授，美国物理学会会士，曾任美国国立原子核理论研究所顾问委员会委员，并获美国能源部杰出青年研究者'则执行正确：
![error-3](https://github.com/zjunlp/DeepKE/assets/43194009/d5b6420a-e7ff-4eb9-a5a9-504a93fa6355)

**Comment by GoooDte** [comment]
您好，建议检查一下报错地方的数据格式是否符合要求

**Comment by zxlzr** [comment]
请问您的问题是否已解决?
