### ISSUE TITLE
使用gpt-3.5-turbo API时出现报错You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0

### ISSUE THREAD

**Issue by NSKW22** [zjunlp/DeepKE#380]
**Describe the question**
> A clear and concise description of what the question is.

各位大佬好，本人是初学者，想使用DeepKE-LLM通过gpt-3.5-turbo进行rte任务，在运行run.py时出现了图片中的报错，请问应该如何解决？感激不尽！

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

<img width="611" alt="image" src="https://github.com/zjunlp/DeepKE/assets/102982732/6af3fa7f-986e-4be1-b73d-c8ac6d76f05a">

**Additional context**
> Add any other context about the problem here.

**Comment by GoooDte** [comment]
您好 建议尝试把openai降到0.28版本

**Comment by NSKW22** [comment]
大佬你好，我把openai降到0.28版本后，又出现了新的问题
<img width="498" alt="image" src="https://github.com/zjunlp/DeepKE/assets/102982732/c7d8de92-8333-4745-b2b1-fccfbb06d70c">
请问这个问题是否与openai的版本有关？我该如何解决？感激不尽！

> 您好 建议尝试把openai降到0.28版本

**Comment by GoooDte** [comment]
是的 把openai包的版本降到0.28

**Comment by NSKW22** [comment]
> 是的 把openai包的版本降到0.28 `pip install openai==0.28`

上述服务过载问题就是在把openai的版本降到0.28后出现的

**Comment by GoooDte** [comment]
openai>=1.0.0可能需要改一下调用的代码 具体可以参考报错的指导
<img width="591" alt="image" src="https://github.com/zjunlp/DeepKE/assets/60096298/90ca5e3d-3922-45cb-a722-e62b71c2a9b1">

**Comment by zxlzr** [comment]
请问您的问题是否已解决？

**Comment by NSKW22** [comment]
> 请问您的问题是否已解决？

您好，目前没有解决

**Comment by zxlzr** [comment]
您好，您的报错是openai库的报错，建议您去查一下openai报错指导参考
