### ISSUE TITLE
使用自定义的训练数据集，运行ner/standard下的run_lstmcrf.py，但是无法在checkpoints文件夹下生成对应的model.pth文件，应该怎么解决呢?

### ISSUE THREAD

**Issue by WILSON-TANGWS** [zjunlp/DeepKE#381]
**Describe the question**
> A clear and concise description of what the question is.
各位大佬好，本人是初学者，想使用DeepKE的命名实体识别NER功能对自定义的模型进行训练和预测，在运行run_lstmcrf.py时出现了图片中的报错，貌似是因为f1一直为0，而导致无法在checkpoints文件夹下生成对应的model.pth文件。如果是用官方下载的训练数据集就可以正常运行，怀疑是我的训练集出现了问题？请问应该如何解决？感激不尽！

**Environment (please complete the following information):**
 - OS: [e.g. window 10]
 - Python Version [e.g. 3.8]

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![image](https://github.com/zjunlp/DeepKE/assets/29370692/f0396694-4baf-48e4-9329-a4782c0f1f5d)

**Additional context**
> Add any other context about the problem here.
这是我的数据集文件
![image](https://github.com/zjunlp/DeepKE/assets/29370692/4c7a7531-e1de-4b2f-95bc-69dfddfc8cf6)
这是我的训练数据的内容，用了自定义的标签
![image](https://github.com/zjunlp/DeepKE/assets/29370692/8b1289db-923e-41ac-b94b-8e71b72beed0)
我在对应的配置文件中，也定义了自己的标签
![image](https://github.com/zjunlp/DeepKE/assets/29370692/a722bead-2143-40bc-9654-a3242109a7ce)

**Comment by pengzju** [comment]
您好，既然您在官方下载的训练数据集可以正常运行，说明代码本身应该是没有问题的。
而且我check了你更改的配置文件和数据集格式，都符合要求

唯一我觉得可能出现问题的点在于：您的数据集太小了，你可以参考数据集的文件大小。官方提供的训练集有6.3MB。你自定义的数据集只有296KB。另外你可以观察loss，在3个epoch后loss还有30204.5，说明模型完全没有拟合。因此f1=0或许也正常？应该就是模型没有拟合

**Comment by WILSON-TANGWS** [comment]
谢谢，也就是我还要加大我的训练数据的文件大小对吧？此外您刚刚说的loss这个参数代表的是什么意思呢？正常值应该是在一个什么范围内?

**Comment by pengzju** [comment]
loss：损失函数，越小越好
正常值大概在10^3以下

**Comment by WILSON-TANGWS** [comment]
了解了，此外我看到项目还有一个few_shot低资源训练的功能，如果是同样大小的数据集，它预测的成功率与standard相比较的话，请问哪个更强一些呀?

**Comment by zxlzr** [comment]
少样本情况下用few_shot效果好，样本多了建议用standard效果好
