### ISSUE TITLE
使用LoRA微调ChatGLM出现报错：requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by NSKW22** [zjunlp/DeepKE#382]
使用LoRA微调ChatGLM出现报错：
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-6583f16b-3cc6360c3ecac9a401932079;e9397c0b-0cb6-4a9e-92aa-47717dc5ed7b)
截图如下
<img width="596" alt="image" src="https://github.com/zjunlp/DeepKE/assets/102982732/7022cf20-2457-47e1-abf0-bf2ec831a86c">
<img width="590" alt="image" src="https://github.com/zjunlp/DeepKE/assets/102982732/9948bd0c-d28a-44dd-b35e-151d6197dce9">
网上没有查到相关资料，请问如何解决？感激不尽！

**Comment by GoooDte** [comment]
您好 看起来是huggingface上的模型或数据下载失败了，建议使用科学上网的方式下载到本地再加载

**Comment by guihonghao** [comment]
你可以把模型下载到本地试试。https://hf-mirror.com/    这里也有hugging face镜像网站，不用挂梯子也能下载模型。
