### ISSUE TITLE
关于NER的预测结果

### ISSUE THREAD

**Issue by WILSON-TANGWS** [zjunlp/DeepKE#384]
**Describe the question**
> A clear and concise description of what the question is.

您好，之前看到DeepKE官网上的NER演示效果，如图一，是会显示每个标签及其对应的文本，但是我在运行standard下的predict.py之后，显示的结果如图二，我想问下项目中是否有存在解析NER结果文本为图一那种效果的代码? 谢谢!

**Environment (please complete the following information):**
 - OS: [window]
 - Python Version [3.8]

**Screenshots**
> If applicable, add screenshots to help explain your problem.
图一
![1703210826751_04636C97-AAB7-4f12-8C25-8CF3EE5DF2B6](https://github.com/zjunlp/DeepKE/assets/29370692/f11b4ff0-3738-451c-973f-25e644d61047)
图二
![image](https://github.com/zjunlp/DeepKE/assets/29370692/4bd35f7f-eb2e-49dc-9e5b-1a5739459f9e)

**Additional context**
> Add any other context about the problem here.

**Comment by xxupiano** [comment]
可以去掉这里的注释https://github.com/zjunlp/DeepKE/blob/5de06f0433401c2656f44776719d381b67951fd4/src/deepke/name_entity_re/standard/models/InferBert.py#L167C1-L189并修改成您所需的label，并且返回tag变量，再修改https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/predict.py#L26C2-L36使用tag即可

**Comment by zxlzr** [comment]
请问您还有其它问题吗
