### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by djlwsa** [zjunlp/DeepKE#387]
RuntimeError: Error(s) in loading state_dict for BiLSTM:
        Missing key(s) in state_dict: "bilstm.rnn.weight_ih_l0", "bilstm.rnn.weight_hh_l0", "bilstm.rnn.bias_ih_l0", "bilstm.rnn.bias_hh_l0", "bilstm.rnn.weight_ih_l0_reverse", "bilstm.rnn.weight_hh_l0_reverse", "bilstm.rnn.bias_ih_l0_reverse", "bilstm.rnn.bias_hh_l0_reverse", "bilstm.rnn.weight_ih_l1", "bilstm.rnn.weight_hh_l1", "bilstm.rnn.bias_ih_l1", "bilstm.rnn.bias_hh_l1", "bilstm.rnn.weight_ih_l1_reverse", "bilstm.rnn.weight_hh_l1_reverse", "bilstm.rnn.bias_ih_l1_reverse", "bilstm.rnn.bias_hh_l1_reverse", "fc.weight", "fc.bias".
        Unexpected key(s) in state_dict: "cnn.convs.0.weight", "cnn.convs.1.weight", "cnn.convs.2.weight", "cnn.activations.prelu.weight", "fc1.weight", "fc1.bias", "fc2.weight", "fc2.bias".

**Comment by GoooDte** [comment]
您好，请您提供具体的报错文件和报错代码
