### ISSUE TITLE
关于NER模型的评价指标问题

### ISSUE THREAD

**Issue by 1228660217** [zjunlp/DeepKE#388]
**Describe the question**
> A clear and concise description of what the question is.
您好，我运行BiLSTM-CRF模型的时候，运行完模型输出的评价指标样式如下：
              precision    recall  f1-score   support
      B-CONT     1.0000    1.0000    1.0000        33
       B-EDU     0.9720    0.9811    0.9765       106
       B-LOC     0.6667    1.0000    0.8000         2
      B-NAME     0.9818    0.9818    0.9818       110
       B-ORG     0.9491    0.9618    0.9554       523
       B-PRO     0.7895    0.8333    0.8108        18
      B-RACE     1.0000    0.9333    0.9655        15
     B-TITLE     0.9206    0.9072    0.9139       690
      I-CONT     1.0000    1.0000    1.0000        97
       I-EDU     0.9723    0.9929    0.9825       283
       I-LOC     0.7273    1.0000    0.8421         8
      I-NAME     0.9609    0.9718    0.9663       177
       I-ORG     0.9429    0.9761    0.9592      4146
       I-PRO     0.7143    0.9804    0.8264        51
      I-RACE     1.0000    1.0000    1.0000        14
     I-TITLE     0.9811    0.9065    0.9423      2171
           O     0.9787    0.9769    0.9778      5446
    accuracy                         0.9620     13890
   macro avg     0.9151    0.9649    0.9353     13890
weighted avg     0.9628    0.9620    0.9620     13890

我想问一下，有没有办法直接评价实体的识别准确率而不是每个标签的准确率，类似BERT模型的输出结果，样式如下：
              precision    recall  f1-score   support
        CONT       1.00      1.00      1.00        33
         EDU       0.97      1.00      0.99       106
         LOC       1.00      1.00      1.00         2
        NAME       0.99      0.99      0.99       110
         ORG       0.93      0.95      0.94       521
         PRO       0.86      1.00      0.92        18
        RACE       0.94      1.00      0.97        15
       TITLE       0.95      0.96      0.96       685
   micro avg       0.95      0.97      0.96      1490
   macro avg       0.96      0.99      0.97      1490
weighted avg       0.95      0.97      0.96      1490

在我的理解里这两种方式应该是有区别的，一个实体的所有标签和实体边界都识别准确才算实体识别正确，我不知道有没有理解正确。感谢解答

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by xxupiano** [comment]
最后三行就是整体的，比如micro F1, macro F1, 和weighted F1

**Comment by zxlzr** [comment]
请问您还有其他问题吗

**Comment by 1228660217** [comment]
暂时没有了，谢谢
