### ISSUE TITLE
通过gpt使用fewshot进行rte任务时，程序运行会报错，经过排查发现代码问题

### ISSUE THREAD

**Issue by GUILTYxC** [zjunlp/DeepKE#389]
**报错**
```
{"输入": example["input"], "输出": str(example["output"])}
KeyError: 'input'
```
**原因**
ie_prompt.py文件中第263行：
`for example in self.examples:`
应该更改为
`for example in examples:`
此处的**examples**是入参的示例数据，而**self.examples**此时是空列表，之后的代码才是取**examples**的数据向**self.examples**中填充。
同时第232行的代码确实为：`for example in examples:`，说明263行有误

**Comment by guihonghao** [comment]
你好，ie_prompt.py文件是哪个文件？

**Comment by GUILTYxC** [comment]
文件路径是site-packages/easyinstruct/prompts/ie_prompt.py，是easyinstruct包中的一个文件

**Comment by GUILTYxC** [comment]
我是不是应该在easyinstruct项目中提issue

**Comment by OE-Heart** [comment]
Thanks for the heads up:) We've fixed this typo in the latest [commit](https://github.com/zjunlp/EasyInstruct/commit/2e480d3af4f715cfab795698796143d6a5d32737). Please install the latest version for local development.
