### ISSUE TITLE
请问cnn代码中的mask的作用是？

### ISSUE THREAD

**Issue by flczmsxh** [zjunlp/deepke#39]
**mask**
> 我想问一下在module中的cnn源码里面的mask是作为工程功能吗？因为我在读论文的时候并没有发现类似mask之类的操作

#param mask: [batch_size, max_len], 句长部分为0，padding部分为1。不影响卷积运算，max-pool一定不会pool到pad为0的位置

上面为mask在源码的注释，并不是看的很懂，只是理解为工程中的一个trick，可否帮忙解释一下？谢谢了

**Comment by yuwl798180** [comment]
你好，句子由于在batch时需要padding，那么被padding的句子在经过cnn层后，padding部分由于本身输入为0输出也为0（这里cnn不带bais才可以），所以大多nlp的task使用cnn再接着max pooling，习惯不去管padding的部分了。
mask就是把padding的部分mask掉，不影响pool的正确性。
如果average pooling，就需要mask

**Comment by flczmsxh** [comment]
多谢大佬！
