### ISSUE TITLE
预训练模型加载问题

### ISSUE THREAD

**Issue by litter-bird-big-dream** [zjunlp/DeepKE#390]
**Describe the question**
> A clear and concise description of what the question is.
我是一个新手，希望快速部署预训练模型，熟悉流程，但是在部署过程中，遇到问题。

我下载了https://github.com/zjunlp/DeepKE/blob/main/README_CNSCHEMA_CN.md中提到的5个模型，所有的readme中，都只说了模型放在checkpoints目录下，但是没有具体的介绍说明具体路径，我尝试多次解决不掉。

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]
安装wsl2中 ，使用了conda创建环境

**Screenshots**
> If applicable, add screenshots to help explain your problem.
目前模型放在如下目录：
![image](https://github.com/zjunlp/DeepKE/assets/31815489/b582abae-bda5-4699-a61c-62d5352c70e4)

报错如下：（切换过多个路径，都是报这个错误）
(deepke-llm) vampire@HZYC-maz:~/DeepKE/example/ner/standard$ python predict.py

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/vampire/anaconda3/envs/deepke-llm/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/vampire/anaconda3/envs/deepke-llm/lib/python3.9/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/vampire/anaconda3/envs/deepke-llm/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
CUDA SETUP: Loading binary /home/vampire/anaconda3/envs/deepke-llm/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
/home/vampire/DeepKE/example/ner/standard/predict.py:7: UserWarning:
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="conf", config_name='config')
/home/vampire/anaconda3/envs/deepke-llm/lib/python3.9/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/home/vampire/anaconda3/envs/deepke-llm/lib/python3.9/site-packages/hydra/_internal/defaults_list.py:415: UserWarning: In config: Invalid overriding of hydra/output:
Default list overrides requires 'override' keyword.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/defaults_list_override for more information.

  deprecation_warning(msg)
/home/vampire/anaconda3/envs/deepke-llm/lib/python3.9/site-packages/hydra/_internal/defaults_list.py:415: UserWarning: In config: Invalid overriding of hydra/model:
Default list overrides requires 'override' keyword.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/defaults_list_override for more information.

  deprecation_warning(msg)
In 'config': Could not override 'hydra/model'. No match in the defaults list.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Additional context**
> Add any other context about the problem here.

**Comment by xxupiano** [comment]
看报错是hydra_core版本问题,pip install hydra_core==1.0.6试一下

**Comment by xxupiano** [comment]
checkpoints放在example/ner/standard下

**Comment by litter-bird-big-dream** [comment]
好的，成功了，谢谢！

**Comment by likang123456789** [comment]
我也出现了这个问题，但是将checkpoints放在example/ner/standard下并没有得到解决

**Comment by zxlzr** [comment]
您好，建议您检查下路径是否是绝对路径，如果是windows 系统需要注意\\
