### ISSUE TITLE
使用关系标注工具ds_label_data.py输出结果有问题

### ISSUE THREAD

**Issue by zhousuyu1111** [zjunlp/DeepKE#392]
您好，我尝试使用ds_label_data.py脚本标注数据，
执行python ds_label_data.py --language cn --source_file source_data.json --triple_file triple_file.csv
输出结果如下：

[{"sentence": "\u5982\u4f55\u6f14\u597d\u81ea\u5df1\u7684\u89d2\u8272\uff0c\u8bf7\u8bfb\u300a\u6f14\u5458\u81ea\u6211\u4fee\u517b\u300b\u300a\u559c\u5267\u4e4b\u738b\u300b\u5468\u661f\u9a70\u5d1b\u8d77\u4e8e\u7a77\u56f0\u6f66\u5012\u4e4b\u4e2d\u7684\u72ec\u95e8\u79d8\u7b08", "head": "\u5468\u661f\u9a70", "tail": "\u559c\u5267\u4e4b\u738b", "relation": "None"}, {"sentence": "\u300a\u7a3b\u9999\u300b\u662f\u5468\u6770\u4f26\u6f14\u5531\u7684\u4e00\u9996\u6b4c\u66f2\uff0c\u7531\u5468\u6770\u4f26\u4f5c\u8bcd\u3001\u4f5c\u66f2\uff0c\u9ec4\u96e8\u52cb\u7f16\u66f2\uff0c\u6536\u5f55\u5728\u5468\u6770\u4f262008\u5e7410\u670815\u65e5\u53d1\u884c\u7684\u4e13\u8f91\u300a\u9b54\u6770\u5ea7\u300b\u4e2
d", "head": "\u9b54\u6770\u5ea7", "tail": "\u7a3b\u9999", "relation": "None"}]

请问应该怎么处理

**Comment by GoooDte** [comment]
您好，可以修改一下代码，在输出结果的时候不使用ascii码

**Comment by zhousuyu1111** [comment]
谢谢！
再请问一下，我的结果标签结果中为什么没有提取到关系？

结果如下：
[{"sentence": "如何演好自己的角色，请读《演员自我修养》《喜剧之王》周星驰崛起于穷困潦倒之中的独门秘笈", "head": "周星驰", "tail": "喜剧之王", "relation": "None"}, {"sentence": "《稻香》是周杰伦演唱的一首歌曲，由周杰伦作词、作曲，黄雨勋编曲，收录在周杰伦2008年10月15日发行的专辑《魔杰座》中", "head": "魔杰座", "tail": "稻香", "relation": "None"}]

triple_file.csv如下：
head_type,tail_type,relation
人物,影视作品,导演
音乐专辑,歌曲,所属专辑
人物,影视作品,主演

source_data.json如下：
[
  {
    "sentence": "如何演好自己的角色，请读《演员自我修养》《喜剧之王》周星驰崛起于穷困潦倒之中的独门秘笈",
    "head": "周星驰",
    "tail": "喜剧之王",
    "head_offset": "26",
    "tail_offset": "21" 
},
//……
]

**Comment by zhousuyu1111** [comment]
另外，我的source_data中包含3条数据，脚本处理后，训练json中包含2条，测试包含3条，验证0条，请问这是为什么？

**Comment by GoooDte** [comment]
没有提取到关系是因为您的triple_file.csv里面没有包含您的source_data中的实体，您可以使用我们提供的triple_file: https://drive.google.com/file/d/1YpaMpivodG39p53MM9sMpB41q4EoiQhH/view?usp=sharing

**Comment by zxlzr** [comment]
请问您的问题解决了吗?

**Comment by zhousuyu1111** [comment]
> 请问您的问题解决了吗?

没有解决，依旧没有提取到关系

**Comment by zhousuyu1111** [comment]
谢谢！已经解决了，使用了您提供的triple_file! 
没有提取成功是因为triple_file不包含实体，并且我的source-data中头实体和尾实体反了。

请问一下，有没有办法构造自己的三元组标签数据集？需要将涉及到的每个实体、关系加入自制的triple_file吗? 满足训练条件的数据量是多大?

**Comment by GoooDte** [comment]
您好，我们这里不涉及训练，是一个简易版的远程监督标注，您可以在我们构造的triple_file里添加自己需要的三元组进行标注

**Comment by zxlzr** [comment]
请问您的问题是否已解决？

**Comment by zhousuyu1111** [comment]
已经解决，谢谢！
