### ISSUE TITLE
ValueError: --load_best_model_at_end requires the save and eval strategy to match, but found - Evaluation strategy: no - Save strategy: epoch

### ISSUE THREAD

**Issue by hjmnbnb** [zjunlp/DeepKE#394]
InstructionKGC-指令驱动的自适应知识图谱构建的4.8LoRA微调Baichuan时出现该问题

**Comment by guihonghao** [comment]
--evaluation_strategy "epoch" \
    --save_strategy "epoch" \
    需要保持一致

**Comment by hjmnbnb** [comment]
> --evaluation_strategy "epoch" --save_strategy "epoch" 需要保持一致

会出现，AttributeError: 'BaichuanConfig' object has no attribute 'z_loss_weight'，这或许是readme提到的"目前在evaluation方面存在一些问题, 因此我们使用evaluation_strategy "no""?

**Comment by zxlzr** [comment]
请问您的问题是否已解决？

**Comment by hjmnbnb** [comment]
> 请问您的问题是否已解决？

两个都设为epoch好像确实有问题(损失不下降)，你们可以检查一下，我后面通过手动添加--load_best_model_at_end False，保持昨天之前文档推荐的no、epoch设置，好像稍微正常一点

**Comment by guihonghao** [comment]
需要设置bf16、以及torch版本保持在2.0.0
