### ISSUE TITLE
inference很慢

### ISSUE THREAD

**Issue by hjmnbnb** [zjunlp/DeepKE#397]
在训练结束的eval时，eval_samples_per_second = 9.698，inference代码却要18秒才能跑一条数据，是只有我这样吗？

**Comment by zxlzr** [comment]
请问您使用的是哪一个模型？您是否使用gpu做推理？

**Comment by hjmnbnb** [comment]
baichuan，有用gpu，用的v100

**Comment by hjmnbnb** [comment]
> 您把输出最大token数设置小一点试一试，句子越长输出越慢，长句18秒也是有的。

指的是max_new_tokens这个量吗？

**Comment by GoooDte** [comment]
是的 另外输入的句子太长也会导致推理变慢

**Comment by hjmnbnb** [comment]
> 是的 另外输入的句子太长也会导致推理变慢

OK 谢谢
