### ISSUE TITLE
NER任务执行run_bert.py报错

### ISSUE THREAD

**Issue by zhousuyu1111** [zjunlp/DeepKE#398]
已将bert-base-chinese下载到/DeepKE/example/ner/standard/bert-base-chinese，执行run_bert.py报错如下：ValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/root//PythonProject/DeepKE/example/ner/standard/bert-base-chinese'. Use `repo_type` argument if needed.

请问应该怎么解决

**Comment by xxupiano** [comment]
可以检查下config里模型路径有没有写错

**Comment by zhousuyu1111** [comment]
谢谢！已解决
