### ISSUE TITLE
NER任务执行bert结果全是0

### ISSUE THREAD

**Issue by zhousuyu1111** [zjunlp/DeepKE#399]
你好，我在默认数据集上执行bert，只做了两处参数修改，将num_train_epochs改为5，将train_batch_size改为64，结果如下：

-[2024-01-15 19:59:19,696][__main__][INFO] - 
              precision    recall  f1-score   support
         LOC       0.00      0.00      0.00      1799
         ORG       0.00      0.00      0.00       976
         PER       0.00      0.00      0.00       882
   micro avg       0.00      0.00      0.00      3657
   macro avg       0.00      0.00      0.00      3657
weighted avg       0.00      0.00      0.00      3657

请问是什么原因

**Comment by zhousuyu1111** [comment]
是120.27.214.45/Data/ner/standard/data.tar.gz数据集

**Comment by xxupiano** [comment]
没有改参数的话结果正常吗？

**Comment by zhousuyu1111** [comment]
修改train_batch_size是为了解决我的机器显存不够的问题，从128改为64后能顺利运行

num_train_epochs默认为3，执行结果全是0；查找了一下其他同学的提问，回答中有提到增加epochs，所以改成5，结果依旧全为0

**Comment by xxupiano** [comment]
使用的是否是最新的代码？

**Comment by zxlzr** [comment]
请问您的问题解决了吗，能再描述下您的问题吗

**Comment by zhousuyu1111** [comment]
重新安装了环境，并把epoch改为6，结果依旧全是0，问题还没有解决。

使用bert执行ner任务，结果中precision，recall，f1全为0。使用的是120.27.214.45/Data/ner/standard这里下载的数据，train.yaml做了两处调整，分别是epoch和batchsize。epoch尝试了3，5，6结果都是0。

训练完成后终端警告：undefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月16日 22:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zjunlp/DeepKE] NER任务执行bert结果全是0 (Issue #399) |

请问您的问题解决了吗，能再描述下您的问题吗

**Comment by xxupiano** [comment]
下面是epoch为1，train_batch_size为64的结果。您可以检查下数据集读取或者GPU环境配置等问题
![image](https://github.com/zjunlp/DeepKE/assets/43436958/6367b7d0-4ce4-4fcc-863a-b7148125699f)

**Comment by zxlzr** [comment]
请问您问题解决了吗？

**Comment by zhousuyu1111** [comment]
目前还没有解决，我明天会再试一下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月17日 20:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zjunlp/DeepKE] NER任务执行bert结果全是0 (Issue #399) |

请问您问题解决了吗？

**Comment by zxlzr** [comment]
请问您的问题解决了吗

**Comment by 66246764** [comment]
关于ner standard的这个问题我也遇见了，batchsize参数为64时，epoch为1可以正常有结果，但是epoch为3甚至以上时，就会出现全为0的现象。我在两台服务器上同时进行了测试，一台在epoch为3时没有问题，一台在epoch为3时就会出现全0.不知道问题在哪里
