### ISSUE TITLE
KeyError问题

### ISSUE THREAD

**Issue by ccm120** [zjunlp/deepke#40]
你好，在data中添加了自己的数据集，运行main.py报KeyError 是为什么呢？
是需要在哪个词典添加吗？

**Comment by yuwl798180** [comment]
你好，能具体贴下报错信息吗？

------
数据需要预处理，会先通过`preprocess.py`文件，你可以先看下这个文件，是否需要的`dict[key]`缺失。

**Comment by ccm120** [comment]
![image](https://user-images.githubusercontent.com/45505292/83234641-3817cd00-a1c3-11ea-9c22-106f1405055c.png)

**Comment by yuwl798180** [comment]
你好报错信息是最后一行：`d['rel2idx']`，你的关系文件有放进去吗？
关系文件的格式你可以参考下示例，需要至少有2列：`relation` 和`index`，用来将每个`relation`编码成one-hot token.

**Comment by ccm120** [comment]
已经添加关系放到ralation.csv中了
人物,上任,职务,11
还需要添加别的吗？谢谢回复

**Comment by ccm120** [comment]
谢谢您，我把尾实体和关系添加反了，已解决~感谢
