### ISSUE TITLE
run_bert.py的在训练集、验证集、测试集上的预测结果标签类型都是“O”

### ISSUE THREAD

**Issue by Tubggg** [zjunlp/DeepKE#400]
**Describe the question**
> A clear and concise description of what the question is.
问题如标题所示，请问能推测大概是哪里出了问题吗

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
您可以试试epoch为1，train_batch_size为64看结果是否正常

**Comment by Tubggg** [comment]
由于计算资源限制，我只能设置epoch为1，train_batch_size为32的结果，如下：
[2024-01-19 23:06:14,853][__main__][INFO] - 
              precision    recall  f1-score   support

          好转       0.00      0.00      0.00        69
        无法判断       0.00      0.00      0.00        17
          未愈       0.00      0.00      0.00        22
          痊愈       0.00      0.00      0.00         1

   micro avg       0.00      0.00      0.00       109
   macro avg       0.00      0.00      0.00       109
weighted avg       0.00      0.00      0.00       109

[2024-01-19 23:06:14,854][__main__][INFO] - ***** Eval results *****
[2024-01-19 23:06:14,854][__main__][INFO] - 
              precision    recall  f1-score   support

          好转       0.00      0.00      0.00        69
        无法判断       0.00      0.00      0.00        17
          未愈       0.00      0.00      0.00        22
          痊愈       0.00      0.00      0.00         1

   micro avg       0.00      0.00      0.00       109
   macro avg       0.00      0.00      0.00       109
weighted avg       0.00      0.00      0.00       109

**Comment by Tubggg** [comment]
> 您可以试试epoch为1，train_batch_size为64看结果是否正常

由于计算资源限制，我只能设置epoch为1，train_batch_size为32的结果，如下：
[2024-01-19 23:06:14,854][__main__][INFO] - ***** Eval results *****
[2024-01-19 23:06:14,854][__main__][INFO] - 
              precision    recall  f1-score   support

          好转       0.00      0.00      0.00        69
        无法判断       0.00      0.00      0.00        17
          未愈       0.00      0.00      0.00        22
          痊愈       0.00      0.00      0.00         1

   micro avg       0.00      0.00      0.00       109
   macro avg       0.00      0.00      0.00       109
weighted avg       0.00      0.00      0.00       109

**Comment by xxupiano** [comment]
您好，看结果可能数据量只有100多条，太少了，epoch调大多训练几个epoch（GPU内存限制只会影响batch_size大小）。推荐使用fewshot NER

**Comment by Tubggg** [comment]
> 您好，看结果可能数据量只有100多条，太少了，epoch调大多训练几个epoch（GPU内存限制只会影响batch_size大小）。推荐使用fewshot NER

这个是验证集上的，训练集大概300，然后我epoch设置的是200，我觉得应该是够的，我用另外一个run_lstmcrf.py可以正常跑出结果。

**Comment by zxlzr** [comment]
对于bert来说可能样本有点少了，建议您多收集一些数据样本再试试。

**Comment by zxlzr** [comment]
请问您的问题是否解决？

**Comment by Tubggg** [comment]
> 请问您的问题是否解决？

暂时未解决，令我不解的是在训练集上的f1也都是0，预测出来的都是标签‘O’

**Comment by zxlzr** [comment]
您重新pull最新的代码，数据量扩大一些，多跑几个epoch再测下训练集效果，如果仍未全0请联系我们。

**Comment by zxlzr** [comment]
请问您的问题解决了吗

**Comment by Tubggg** [comment]
> 请问您的问题解决了吗

结果还是全0，我再仔细检查下是否是我数据方面的问题，之后有问题的话再进行咨询，感谢解答！

**Comment by zxlzr** [comment]
好的，您有问题可以随时问
