### ISSUE TITLE
大模型LLMICL知识抽取

### ISSUE THREAD

**Issue by zhousuyu1111** [zjunlp/DeepKE#401]
你好，我在调用大模型进行知识抽取的时候得到的结果和示例不同。
![IMG_export_20240119_112117847](https://github.com/zjunlp/DeepKE/assets/155522302/0dfdb876-7df1-4a95-b095-ea5c86707fd0)
以下是我的样本
![IMG_export_20240119_112253501](https://github.com/zjunlp/DeepKE/assets/155522302/a4e153c9-cec1-4bcd-87bd-4237a0e03c91)

**Comment by guihonghao** [comment]
建议多给几个例子

**Comment by zhousuyu1111** [comment]
你好，抱歉我描述有误，我直接调用大模型，不使用样本增强，进行实体识别，关系抽取或者三元组抽取时得到的结果和https://github.com/zjunlp/DeepKE/blob/main/example/llm/README_CN.md中提供的返回结果不一样。例如我抽取三元组的结果
![IMG_export_20240119_145915754](https://github.com/zjunlp/DeepKE/assets/155522302/abf84026-4771-4e5d-9b8e-1d031ece5737)
样本和配置文件如下：
![IMG_export_20240119_145911888](https://github.com/zjunlp/DeepKE/assets/155522302/02f38ce0-839b-4c1e-b390-9ece3141c021)
![IMG_export_20240119_145909079](https://github.com/zjunlp/DeepKE/assets/155522302/6b4e6c92-a411-4fb7-b65c-edae38ee7a22)
这里已经在rte_check.json中增加了10条。得到的都不是readme中给出具有固定格式的输出，请问这是为什么

**Comment by guihonghao** [comment]
你的zero_shot显示是True，这是0样本设置

**Comment by guihonghao** [comment]
zero_shot=True是0样本，zero_shot=False是少样本。

**Comment by zxlzr** [comment]
请问您的问题是否已解决？
