### ISSUE TITLE
训练step数和样本量的关系对不上

### ISSUE THREAD

**Issue by kuku1128** [zjunlp/DeepKE#402]
pretain model：knowlm-13b-ie

运行脚本：fine_llama.bash

训练样本数：14339
![企业微信截图_ebb48f2a-7215-4527-a96a-802cda9538eb](https://github.com/zjunlp/DeepKE/assets/18701978/2e55281d-2101-4576-bd14-0435655d6c11)
per_device_train_batch_size=8（单卡训练）
epoch=3

但训练的总step=672，和预期差不多差了8倍，这是为何？

![企业微信截图_e6a8d03a-beff-4b8d-ba9d-a6adc929e119](https://github.com/zjunlp/DeepKE/assets/18701978/5529eced-cccf-4e44-bfd1-22e1643b443d)

**Comment by GoooDte** [comment]
您好 可以尝试将gradient_accumulate_step设置为1

**Comment by kuku1128** [comment]
> 您好 可以尝试将gradient_accumulate_step设置为1

感谢回复。所以模型实际上在每个epoch还是训练了14339个样本是吗？我还以为只训练了差不多1/8的样本

**Comment by GoooDte** [comment]
是的，gradient_accumulate_step的目的是梯度累积，适当的梯度累积是有利于训练的

**Comment by GoooDte** [comment]
1000token可能属于比较多的，可以减小beam的大小，也可以使用inference_vllm加速

**Comment by kuku1128** [comment]
> 1000token可能属于比较多的，可以减小beam的大小，也可以使用inference_vllm加速

好的，我试试

**Comment by zxlzr** [comment]
请问您的问题是否已解决？
