### ISSUE TITLE
triple似乎没有一个能用的

### ISSUE THREAD

**Issue by coderyiyang** [zjunlp/DeepKE#403]
按照指引，triple里没有一个是能用的，各种文件名和路径错误。能不能维护一下。

**Comment by zxlzr** [comment]
您好，请问您是哪个模型使用有问题，早期我们经过测试是完全可以正常运行的，可能年代久远有一些库版本过时了。另外建议您直接使用大模型版本。

**Comment by coderyiyang** [comment]
您说的大模型版本是DeepKE-cnSchema吗？

**Comment by zxlzr** [comment]
大模型是https://github.com/zjunlp/DeepKE/tree/main/example/llm  或https://github.com/zjunlp/KnowLM   小模型版本我们陆续就不维护了

**Comment by zxlzr** [comment]
这里有参考教程 https://zhuanlan.zhihu.com/p/666635428    https://zhuanlan.zhihu.com/p/668245670

**Comment by coderyiyang** [comment]
[zjunlp/knowlm-13b-zhixi](https://huggingface.co/zjunlp/knowlm-13b-zhixi)(无需Lora即可直接预测)
这个模型下载之后放在哪里？

**Comment by guihonghao** [comment]
[zjunlp/knowlm-13b-zhixi](https://huggingface.co/zjunlp/knowlm-13b-zhixi)是通用模型，如果专门做信息抽取建议使用https://huggingface.co/zjunlp/knowlm-13b-ie，这里是相应的教程https://github.com/zjunlp/DeepKE/blob/main/example/llm/InstructKGC/README_CN.md

**Comment by guihonghao** [comment]
在InstructKGC目录下面创建一个models目录，模型下到models里面。

**Comment by coderyiyang** [comment]
可以加您一个微信吗？有些地方还是不太明白，想单独咨询。谢谢。

**Comment by guihonghao** [comment]
我的微信是ghh200002

**Comment by vv521** [comment]
> 我的微信是ghh200002

大佬请问，know-13b-IE这个模型可以做微调不？
