### ISSUE TITLE
vllm推理bug

### ISSUE THREAD

**Issue by kuku1128** [zjunlp/DeepKE#404]
vllm_llm.py的LLM没有state_dict，但在inference_vllm的调用方式如下：

llm = LLM(
  model = options.model_name_or_path,
  tokenizer = options.model_name_or_path,
  state_dict = state_dict,
  batch_size = options.batch_size,
)

**Comment by guihonghao** [comment]
是的，目前vllm不支持传入state_dict的方式调用，因此建议使用常规推理方法。后续我们会优化。
