### ISSUE TITLE
请问LightNER需要多大的显存来运行

### ISSUE THREAD

**Issue by haoyumei** [zjunlp/DeepKE#405]
您好，我的GPU是RTX 4090，24GB显存，使用LightNER跑conll2003数据集时会爆内存不足，我的batchsize设置的是8（我看到原文中设置的是16），想问下原文使用的GPU显存是多大呀~

**Comment by coderyiyang** [comment]
我的也爆了，不确定为什么。显示是和bitsandbytes有关。

**Comment by flow3rdown** [comment]
您好，按照README中的环境跑CoNLL2003数据集，`batch size`设置为16时现存占用不到10个G，建议您使用相同的环境尝试下~

**Comment by haoyumei** [comment]
您好，我按照readme配置了环境，还是会显示内存不足o(╥﹏╥)o
![1](https://github.com/zjunlp/DeepKE/assets/59990788/73d4d209-d11d-4754-9fd7-a06d62a74791)
![image](https://github.com/zjunlp/DeepKE/assets/59990788/818a3008-d63d-48bc-881e-037d3bc2565d)

**Comment by coderyiyang** [comment]
一直爆內存，沒法正常運行，期待浙大的大佬們進行一次維護。謝謝！

**Comment by flow3rdown** [comment]
您好，我按照DeepKE要求创建环境并运行是没有出现爆内存或爆显存的情况的，方便的话可以加下微信flow3rdown详细沟通一下
