### ISSUE TITLE
训练过程中epoch训练一半终止（ner standrd）

### ISSUE THREAD

**Issue by 1coke2** [zjunlp/DeepKE#406]
![{29F72087-65B3-48c1-9703-43ACCA0D7544}](https://github.com/zjunlp/DeepKE/assets/129504455/cebe9da2-a3e1-4e8b-be0a-530accdc2078)
![{341AA179-EDA9-4341-9264-F86C71022079}](https://github.com/zjunlp/DeepKE/assets/129504455/405777f5-3c7f-4577-99d5-5750db4a21f4)
![{E4424B9D-E4E5-45d5-AB96-6B0AFA94A4C5}](https://github.com/zjunlp/DeepKE/assets/129504455/5552ac61-ec16-4725-a680-b7f6ed8ef8bc)
我在训练过程中会遇到某一个epoch还没有完成就突然进入了下一个epoch，我查看GPU内存的时候发现并没有占满（我的内存是16，占用的内存是4）

**Comment by xxupiano** [comment]
您好，看您的截图实验并没有一个epoch中突然中止的情况

**Comment by 1coke2** [comment]
作者大大您好，非常感谢您能回复我，也就是说那个epoch训练到一半的截图实际上是那轮训练成功了是吗，可是我看checkpoints在第一轮和第二轮的时候都没有输出，同时我发现我训练结束后，运行predict没有结果






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xin ***@***.***&gt;; 
发送时间: 2024年1月28日(星期天) 上午10:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zjunlp/DeepKE] 训练过程中epoch训练一半终止（ner standrd） (Issue #406)





 
您好，看您的截图实验并没有一个epoch中突然中止的情况

**Comment by 1coke2** [comment]
![{BEE0506C-83DF-4b49-B2AA-F755DAEB7242}](https://github.com/zjunlp/DeepKE/assets/129504455/f8e21fe2-2917-4d07-a1fe-3918a01c46d9)

**Comment by xxupiano** [comment]
1. 每个epoch结束是没有输出，选择eval的话整体训练完有输出
2. 请检查checkpoints文件夹是否为空，或者debug程序查找原因
