### ISSUE TITLE
代码运行

### ISSUE THREAD

**Issue by 66246764** [zjunlp/DeepKE#407]
**Describe the bug**
> A clear and concise description of what the bug is.
当我使用ner的run_bert.py时，报错信息为：（下载环境时提示：DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 24.0 will enforce this behaviour change）

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]
![image](https://github.com/zjunlp/DeepKE/assets/54762477/ea4d38f5-fc2f-4333-a82c-0cc7827dc848)

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![image](https://github.com/zjunlp/DeepKE/assets/54762477/a776bbb5-3b97-4316-8f57-b533a1e139d0)

**Additional context**
> Add any other context about the problem here.

**Comment by 66246764** [comment]
re的run.py时：
![image](https://github.com/zjunlp/DeepKE/assets/54762477/ef34b558-6c99-417b-837c-6b08035b018c)

**Comment by 66246764** [comment]
> 您好，看截图都是因为模型路径有问题，请check一下
您好，请问是需要先自己把对应需要的模型下载好后，放在对应的位置才能run吗

**Comment by xxupiano** [comment]
不需要下载，NER https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/conf/hydra/model/bert.yaml#L2 ，RE https://github.com/zjunlp/DeepKE/blob/main/example/re/standard/conf/model/lm.yaml#L6 已经提供了模型名，from_pretrained会自动下载。
但是两张截图都是from_pretrained找不到模型，我猜您可能改了yaml原有的模型名为自己的模型路径？

**Comment by 66246764** [comment]
> 不需要下载，NER https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/conf/hydra/model/bert.yaml#L2 ，RE https://github.com/zjunlp/DeepKE/blob/main/example/re/standard/conf/model/lm.yaml#L6 已经提供了模型名，from_pretrained会自动下载。 但是两张截图都是from_pretrained找不到模型，我猜您可能改了yaml原有的模型名为自己的模型路径？
谢谢您的解答，但是我下载您的项目后没更改其他配置文件的信息，就直接报错了TAT
