### ISSUE TITLE
MAC环境torch libshm.dylib缺失问题

### ISSUE THREAD

**Issue by hupanfeng** [zjunlp/DeepKE#409]
**Describe the question**
> A clear and concise description of what the question is.

Traceback (most recent call last):
  File "/Users/xxx/work/workspace/bd/DeepKE/example/ae/standard/run.py", line 3, in <module>
    import torch
  File "/Users/xxx/anaconda3/envs/deepke/lib/python3.8/site-packages/torch/__init__.py", line 199, in <module>
    from torch._C import *  # noqa: F403
ImportError: dlopen(/Users/xxx/anaconda3/envs/deepke/lib/python3.8/site-packages/torch/_C.cpython-38-darwin.so, 0x0002): Library not loaded: '@loader_path/libshm.dylib'
  Referenced from: '/Users/xxx/anaconda3/envs/deepke/lib/python3.8/site-packages/torch/lib/libtorch_python.dylib'
  Reason: tried: '/Users/xxx/anaconda3/envs/deepke/lib/python3.8/site-packages/torch/lib/libshm.dylib' (no such file), '/usr/local/lib/libshm.dylib' (no such file), '/usr/lib/libshm.dylib' (no such file)

**Environment (please complete the following information):**
 - OS: mac 
 - Python Version：3.8

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by GoooDte** [comment]
您好，您可以参考这个解决办法 https://blog.csdn.net/weixin_43662044/article/details/135019172
但还是建议您使用linux或者windows环境运行

**Comment by hupanfeng** [comment]
解决了，我重新下了一下依赖就好了
