### ISSUE TITLE
请问GCN中如何得到句法依存树？

### ISSUE THREAD

**Issue by aym871483837** [zjunlp/deepke#41]
您好，在对模型进行训练时，我发现GCN的效果显著低于其他几个模型，查阅代码后在GCN.py中，并没有找到代码关于pyhanlp的相关调用，请问这里是如何通过句法分析构建出词语之间的邻接矩阵来进行关系抽取的呢？如果要添加pyhanlp来做的话，请问应该怎么操作？

**Comment by yuwl798180** [comment]
你好，使用GCN的关键步骤就是：parsing tree 得到的句子token邻接矩阵，之所以gcn效果好也是因为这个外部强烈的依存信息的引入（可以类比为句子token之间有个先验的attention权重了）

因为这个仓库主要集中在中文关系抽取方面，所以目前尝试过几个针对中文的句法解析工具。
比如 [hanlp](https://hanlp.hankcs.com/)。你可以点进去看下演示。
python的接口网址在：[pyhanlp](https://github.com/hankcs/pyhanlp)。
其中[依存句法分析](https://github.com/hankcs/pyhanlp#%E4%BE%9D%E5%AD%98%E5%8F%A5%E6%B3%95%E5%88%86%E6%9E%90)中的第六列就是对应的依存关系。
得到依存关系array后，在文件的[module/GCN](https://github.com/zjunlp/deepke/blob/master/module/GCN.py)中有个api接口为：`head_to_adj`就可以得到对应的邻接矩阵，这里可以控制是否自身与自身相连（就是邻接矩阵对角线为1）。

另外acl2019中有一篇文章，在使用gcn后可以后续的学习过程会动态的更新adj，我尝试过后发现效果不错（后来再深入思考下感觉彻底回到了transformer架构了。。。），所以gcn的效果在我尝试后我是存疑的（相比较于multi-head），而且引入了额外信息（句法解析本身就可能出错）。最近我会重新更新下gcn，把这种动态学习的更新进去。

在回到中文中，目前由于bert的出现，以及acl2019一篇文章的讲解，中文在很多task中不分词可能效果更好。如果不分词，对句法解析的结果就处理起来很麻烦，甚至不如adj直接初始化为相邻token为1其余为0动态学习好了。
所以至少在关系抽取这块，我觉得gcn的使用目前不是充分方法需要修改。

**Comment by aym871483837** [comment]
明白了，非常感谢您的耐心解答！
