### ISSUE TITLE
How to solve the problem that the modle file in re cann't be decoded to utf-8?

### ISSUE THREAD

**Issue by BeimingCharles** [zjunlp/DeepKE#410]
**Describe the question**
> A clear and concise description of what the question is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]
![屏幕截图 2024-02-04 231735](https://github.com/zjunlp/DeepKE/assets/151798892/1a8e1378-6f73-4575-9dd0-3365b9ae7f42)

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by xxupiano** [comment]
According to the figure, `cfg.lm_file` is the path of a HuggingFace-style model, which is not suitable. Did you use your own model? If so, maybe your model file has something wrong.

**Comment by BeimingCharles** [comment]
my model is got from the website given below, which is based on BERT-wwm, Chinese.
website: https://gitcode.com/zjunlp/DeepKE/blob/main/README_CNSCHEMA_CN.md

**Comment by BeasterYong** [comment]
Hello, we have verified and found that this issue does exist. We will fix it as soon as possible, thanks!

**Comment by BeasterYong** [comment]
Hello, we have verified and found that this issue does exist. We will fix it as soon as possible, thanks!

**Comment by BeimingCharles** [comment]
thank you, if the issue was solved, you could tell me as soon as possible.

**Comment by BeasterYong** [comment]
May I ask if you have modified the lm_file in lm.yaml? It is the fp in predict.yaml that needs to be modified not the llm.yaml file, you can check it.

**Comment by zxlzr** [comment]
hi buddy, we are currently on holiday for the Chinese New Year, sorry for the late reply.

It seems you might have used the wrong configuration file. Has your issue been resolved?

**Comment by zxlzr** [comment]
Hi, have you solved the issue？ may i close this issue？

**Comment by BeimingCharles** [comment]
我还有问题，请问哪里需要修改？我的lm.yaml和predict.yaml中的路径都是一样的
![截图1](https://github.com/zjunlp/DeepKE/assets/151798892/dc270bf4-3200-4e84-b6a2-4e061c0fd47d)
![image](https://github.com/zjunlp/DeepKE/assets/151798892/30c6ebc2-bd98-4626-b8e6-50754a9b5a1a)
第一张是lm.yaml；第二张是predict.yaml

**Comment by BeasterYong** [comment]
您好，`lm.yaml`文件是无需修改的，您只需要将其恢复原样即可`lm_file: 'bert-base-chinese`

**Comment by BeasterYong** [comment]
您好，`lm.yaml`文件是无需修改的，您只需要将其恢复原样即可`lm_file: 'bert-base-chinese'`

**Comment by BeimingCharles** [comment]
![image](https://github.com/zjunlp/DeepKE/assets/151798892/58b5754e-3698-4b3d-bc7d-cb1fa64574e0)
那这个问题是什么呢？

**Comment by BeasterYong** [comment]
推测是网络原因造成的。您可以尝试部署网络代理或者设置huggingface镜像网站，或者选择直接从huggingface中下载bert-base-chinese并将`lm_file`改为本地存储目录。

**Comment by BeimingCharles** [comment]
![image](https://github.com/zjunlp/DeepKE/assets/151798892/84a866a1-a897-476e-97de-c1e7b8b73e39)
请问网络代理不能解决的话只能去hugging face 下载了吗？

**Comment by BeasterYong** [comment]
请问您在国内吗？如果在中国地区可以使用下述方法解决：

**Comment by BeasterYong** [comment]
请问您在国内吗？如果在中国地区可以使用下述添加镜像网站的方法下载模型：
```
pip install -U huggingface_hub
export HF_ENDPOINT=https://hf-mirror.com
huggingface-cli download --resume-download --local-dir-use-symlinks False google-bert/bert-base-chinese --local-dir bert-base-chinese
```

**Comment by BeasterYong** [comment]
请问问题解决了吗？

**Comment by BeimingCharles** [comment]
请问哪个是bert-base-chinese的文件地址？

**Comment by BeimingCharles** [comment]
请问哪个是bert-base-chinese的文件地址？

**Comment by zxlzr** [comment]
> 请问您在国内吗？如果在中国地区可以使用下述添加镜像网站的方法下载模型：
> 
> ```
> pip install -U huggingface_hub
> export HF_ENDPOINT=https://hf-mirror.com
> huggingface-cli download --resume-download --local-dir-use-symlinks False google-bert/bert-base-chinese --local-dir bert-base-chinese
> ```

您可以用上述代码下载模型，请问问题解决了吗

**Comment by BeimingCharles** [comment]
下载的那个文件夹里是空的















在 2024-02-27 11:02:33，"Eric" ***@***.***> 写道：

请问您在国内吗？如果在中国地区可以使用下述添加镜像网站的方法下载模型：

pip install -U huggingface_hub
export HF_ENDPOINT=https://hf-mirror.com
huggingface-cli download --resume-download --local-dir-use-symlinks False google-bert/bert-base-chinese --local-dir bert-base-chinese


您可以用上述代码下载模型，请问问题解决了吗

**Comment by zxlzr** [comment]
您好，bert-base-chinese 模型在网上很多地方都可以直接下载到本地使用，比如这里https://github.com/ymcui/Chinese-BERT-wwm

**Comment by BeimingCharles** [comment]
![image](https://github.com/zjunlp/DeepKE/assets/151798892/cefb5575-1380-484c-b2a5-5d78e23ac935)
还是有问题啊

**Comment by zxlzr** [comment]
> ![image](https://private-user-images.githubusercontent.com/151798892/308760743-cefb5575-1380-484c-b2a5-5d78e23ac935.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNzE1NTIsIm5iZiI6MTcwOTE3MTI1MiwicGF0aCI6Ii8xNTE3OTg4OTIvMzA4NzYwNzQzLWNlZmI1NTc1LTEzODAtNDg0Yy1iMmE1LTVkNzhlMjNhYzkzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOVQwMTQ3MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTc4MWY2NWU5N2IwMDhjZTY4MjNlZWJmODk2NWZhMGMzMDI1N2QwOGRiMTY1OWM5ZTE1YTNkNjkwNjBmMGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AMzyZc4qZah4lZ4sVNCieAXSxgc4EGoGscto9ox0_Yc) 还是有问题啊

您好，这是自动调参的wandb的key没输入，如果您不需要使用自动调参，把这行代码注释掉即可运行， wandb使用比较方便您可以参考https://wandb.ai/site

**Comment by BeimingCharles** [comment]
![image](https://github.com/zjunlp/DeepKE/assets/151798892/b4c905b3-c33d-47b8-b299-dc1675089b56)
请问为何加载半天不出结果呢？

**Comment by zxlzr** [comment]
请问您使用的是gpu吗？建议您使用linux环境gpu来运行，cpu下速度非常慢

**Comment by BeimingCharles** [comment]
那这个是在运行吗？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月01日 16:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zjunlp/DeepKE] How to solve the problem that the modle file in re cann't be decoded to utf-8? (Issue #410) |

请问您使用的是gpu吗？建议您使用linux环境gpu来运行，cpu下速度非常慢

**Comment by BeimingCharles** [comment]
![image](https://github.com/zjunlp/DeepKE/assets/151798892/0313b30f-a294-43c2-82b2-f273cda718a8)
请问这是哈情况啊

**Comment by zxlzr** [comment]
建议您安装一个虚拟anaconda 环境再运行，在readme有相关的说明。从报错看可能是python库版本不对，您严格按requirement.txt里面的库版本是可以正常运行的。

**Comment by BeimingCharles** [comment]
有些库的版本都不是最新的，所以要手动下载吗？

**Comment by zxlzr** [comment]
您可以安装一下虚拟环境，然后按readme会自动安装全部的库，不需要手动下载

**Comment by zxlzr** [comment]
https://github.com/zjunlp/DeepKE?tab=readme-ov-file#manual-environment-configuration

**Comment by zxlzr** [comment]
另外建议您使用linux环境安装，linux下安装经过无数次测试都可以正常运行的

**Comment by BeimingCharles** [comment]
![image](https://github.com/zjunlp/DeepKE/assets/151798892/d1892353-6f9c-43af-89d8-13c2f55c0d85)
pip install deepke的时候出问题了

**Comment by zxlzr** [comment]
您好，请您按https://github.com/zjunlp/DeepKE?tab=readme-ov-file#manual-environment-configuration 用anaconda环境安装，不建议在windows使用pip install

**Comment by zxlzr** [comment]
另外windows 环境对python包兼容性很差，建议您用linux安装

**Comment by zxlzr** [comment]
请问您的问题解决了吗

**Comment by BeimingCharles** [comment]
没有啊

**Comment by BeimingCharles** [comment]
肯定可以在Windows上运行的呀

**Comment by zxlzr** [comment]
您好，这个项目非大模型版本是5年前开发的，早期版本对windows兼容性存在问题，非常抱歉，所以建议您使用linux安装，linux对各种环境兼容性都很好，也适合使用gpu训练模型。

另外您也可以使用去年开发的大模型版本deepke-llm（readme有介绍），这个版本的conda和python库版本较高。

计算机领域的发展非常快，很多python库几个月就会更新导致无法适配，非常抱歉。
