### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by kitae0321** [zjunlp/DeepKE#412]
**Describe the question**
I followed the instructions, but as I tried steps 4 and 5, numerous ModuleNotFoundError occurred. How can I resolve this? Thank you.

**Environment (please complete the following information):**
 - OS: mac
 - Python Version 3.9

**Screenshots**
<img width="596" alt="Screenshot 2024-02-07 at 21 14 50" src="https://github.com/zjunlp/DeepKE/assets/67530309/63209497-14e8-4f6a-897e-c2502bee42c4">

**Additional context**
> Add any other context about the problem here.

**Comment by xxupiano** [comment]
pip intall -r requirements.txt

**Comment by zxlzr** [comment]
Have you solved your issue?
