### ISSUE TITLE
LightNER 在 cluener数据集下F1 Score 74%

### ISSUE THREAD

**Issue by zr-icu** [zjunlp/DeepKE#413]
如题，在few-shot代码下使用 bart-large-chinese将 freeze_plm 设置成 True 训练45 epoch。F1 Score 才达到 48.5%

然后将 freeze_plm 设置成 False 训练 45 epoch。F1 Score 达到76%

使用的是全量的 cluener 训练集数量为 1w+。 感觉训练出来的指标好低呀，请问可以帮忙看下么？

**Comment by flow3rdown** [comment]
LightNER主要适用场景为少样本场景，另外LightNER在中文场景下的性能存疑，主要是因为生成式的方式在中文场景下寻找实体边界的能力较弱。您可以尝试调一下参数，例如learning rate, batch size等，参考issue #127
