### ISSUE TITLE
这个问题该如何解决？

### ISSUE THREAD

**Issue by jsh-hit** [zjunlp/DeepKE#414]
**Describe the question**
> A clear and concise description of what the question is.
使用预训练好的模型，对readme中的例子进行测试，但是报错

![QQ截图20240301223803](https://github.com/zjunlp/DeepKE/assets/81158428/8a73b8ee-b9c2-4aad-9323-be03bf69b10a)

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
您好，请问您使用的是哪个具体的代码，我们好帮您定位

**Comment by jsh-hit** [comment]
我是按照DeepKE/example/triple/cnschema/README_CN.md的教程，nerfp修改为ner模型文件夹地址
![DD71A7FF7AB9A04EDB742FF49A7A5F0C](https://github.com/zjunlp/DeepKE/assets/81158428/b46caa76-f957-424e-ac38-209ebba3ab90)
模型文件夹中文件包括
![AB50F73DCC5378024D12826479A32406](https://github.com/zjunlp/DeepKE/assets/81158428/6edcd0c1-91ef-4c19-bb18-4afc8c6b2d7a)
具体报错在cnschema/predict.py的第60行
![111](https://github.com/zjunlp/DeepKE/assets/81158428/9b9b963a-7310-4a38-bdaa-b8f94e9fa3ad)
感谢您的回答！

**Comment by BeasterYong** [comment]
请问您使用的是哪个模型呢

**Comment by BeasterYong** [comment]
您有下载对应的re模型嘛？re模型也是需要下载的，然后更改refp

**Comment by jsh-hit** [comment]
我下载的BERT-wwm, Chinese模型，请问只进行实体识别任务也需要下载re模型吗

**Comment by BeasterYong** [comment]
您好，您可以参考一下readme的内容，re是中间的一个步骤，因此推荐您下载对应的re模型

**Comment by jsh-hit** [comment]
我下载了re模型，但是还是之前那个报错

**Comment by zxlzr** [comment]
请麻烦贴出报错的信息，好帮您排查

**Comment by BeasterYong** [comment]
您好，经我们排查后使用您对应的模型并不会出现上述问题，推荐您使用Linux系统，并且在虚拟环境中安装requirements.txt中所需要的python包
