### ISSUE TITLE
无法安装，有没有大佬救救，错误的地方用**标注出来了

### ISSUE THREAD

**Issue by QAO-O** [zjunlp/DeepKE#415]
(base) PS C:\Users\31401> conda create -n deepke python=3.8
WARNING: A conda environment already exists at 'E:\anaconda\envs\deepke'
Remove existing environment (y/[n])? y

Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: E:\anaconda\envs\deepke

  added / updated specs:
    - python=3.8

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2023.12.12-haa95532_0
  libffi             pkgs/main/win-64::libffi-3.4.4-hd77b12b_0
  openssl            pkgs/main/win-64::openssl-3.0.13-h2bbff1b_0
  pip                pkgs/main/win-64::pip-23.3.1-py38haa95532_0
  python             pkgs/main/win-64::python-3.8.18-h1aa4202_0
  setuptools         pkgs/main/win-64::setuptools-68.2.2-py38haa95532_0
  sqlite             pkgs/main/win-64::sqlite-3.41.2-h2bbff1b_0
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2
  wheel              pkgs/main/win-64::wheel-0.41.2-py38haa95532_0

Proceed ([y]/n)? y

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate deepke
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) PS C:\Users\31401> conda activate deepke
(deepke) PS C:\Users\31401> pip install -r requirements.txt
**_ERROR:_** Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))) - skipping

**Comment by BeasterYong** [comment]
您好，需要进入项目目录之后再执行命令`pip install -r requirements.txt`

**Comment by QAO-O** [comment]
感谢大佬，我现在下载了anaconda，然后直接复制的教程的代码，请问一下还有什么前置工作需要完成的吗

**Comment by BeasterYong** [comment]
下载好您所需要的模型和数据集即可～

**Comment by QAO-O** [comment]
感谢大佬

**Comment by QAO-O** [comment]
大佬 我现在显示 python: can't open file 'setup.py': [Errno 2] No such file or directory 这个错误怎么搞

**Comment by BeasterYong** [comment]
检查一下目录，如果在项目目录下应该没有问题的

**Comment by QAO-O** [comment]
好的 感谢

**Comment by QAO-O** [comment]
我用pip下载了torchcrf，但是运行的时候还是显示我缺少torchcrf怎么办QAQ

(deepke) C:\Users\31401\Desktop\DeepKE-main\DeepKE-main\example\re\standard>python run.py
Traceback (most recent call last):
  File "run.py", line 14, in <module>
    import deepke.relation_extraction.standard.models as models
  File "E:\anaconda\envs\deepke\lib\site-packages\deepke-2.2.7-py3.8.egg\deepke\__init__.py", line 3, in <module>
    from .name_entity_re import *
  File "E:\anaconda\envs\deepke\lib\site-packages\deepke-2.2.7-py3.8.egg\deepke\name_entity_re\__init__.py", line 1, in <module>
    from .standard import *
  File "E:\anaconda\envs\deepke\lib\site-packages\deepke-2.2.7-py3.8.egg\deepke\name_entity_re\standard\__init__.py", line 1, in <module>
    from .models import *
  File "E:\anaconda\envs\deepke\lib\site-packages\deepke-2.2.7-py3.8.egg\deepke\name_entity_re\standard\models\__init__.py", line 1, in <module>
    from .InferBert import *
  File "E:\anaconda\envs\deepke\lib\site-packages\deepke-2.2.7-py3.8.egg\deepke\name_entity_re\standard\models\InferBert.py", line 8, in <module>
    from .BiLSTM_CRF import *
  File "E:\anaconda\envs\deepke\lib\site-packages\deepke-2.2.7-py3.8.egg\deepke\name_entity_re\standard\models\BiLSTM_CRF.py", line 2, in <module>
    from torchcrf import CRF
ModuleNotFoundError: No module named 'torchcrf'

(deepke) C:\Users\31401\Desktop\DeepKE-main\DeepKE-main\example\re\standard>pip install torchcrf
Requirement already satisfied: torchcrf in e:\anaconda\envs\deepke\lib\site-packages (1.1.0)
Requirement already satisfied: numpy in e:\anaconda\envs\deepke\lib\site-packages (from torchcrf) (1.24.2)
Requirement already satisfied: torch>=1.0.0 in e:\anaconda\envs\deepke\lib\site-packages (from torchcrf) (2.2.1)
Requirement already satisfied: filelock in e:\anaconda\envs\deepke\lib\site-packages (from torch>=1.0.0->torchcrf) (3.12.0)
Requirement already satisfied: typing-extensions>=4.8.0 in e:\anaconda\envs\deepke\lib\site-packages (from torch>=1.0.0->torchcrf) (4.10.0)
Requirement already satisfied: sympy in e:\anaconda\envs\deepke\lib\site-packages (from torch>=1.0.0->torchcrf) (1.12)
Requirement already satisfied: networkx in e:\anaconda\envs\deepke\lib\site-packages (from torch>=1.0.0->torchcrf) (3.1)
Requirement already satisfied: jinja2 in e:\anaconda\envs\deepke\lib\site-packages (from torch>=1.0.0->torchcrf) (3.1.3)
Requirement already satisfied: fsspec in e:\anaconda\envs\deepke\lib\site-packages (from torch>=1.0.0->torchcrf) (2024.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in e:\anaconda\envs\deepke\lib\site-packages (from jinja2->torch>=1.0.0->torchcrf) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in e:\anaconda\envs\deepke\lib\site-packages (from sympy->torch>=1.0.0->torchcrf) (1.3.0)

**Comment by zxlzr** [comment]
您好，建议您在linux 环境用anaconda 虚拟环境按readme安装，windows 很多包兼容性不好

**Comment by QAO-O** [comment]
啊，只有Windows怎么办

**Comment by zxlzr** [comment]
建议您网上搜一下windows 下安装包的问题，如果您安装了正确版本的python库后仍有问题请您联系我们

**Comment by QAO-O** [comment]
好的，谢谢

**Comment by liujunshanhelen** [comment]
C:\Users\LiuJunshan\miniconda3\envs\deepke-llm\python.exe C:\Users\LiuJunshan\Desktop\DeepKE-main\DeepKE-main\example\re\standard\run.py 
C:\Users\LiuJunshan\miniconda3\envs\deepke-llm\lib\site-packages\hydra\core\utils.py:207: UserWarning: 
Using config_path to specify the config name is deprecated, specify the config name via config_name
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/config_path_changes
  warnings.warn(category=UserWarning, message=msg)
C:\Users\LiuJunshan\miniconda3\envs\deepke-llm\lib\site-packages\hydra\plugins\config_source.py:190: UserWarning: 
Missing @package directive hydra/output/custom.yaml in file://C:\Users\LiuJunshan\Desktop\DeepKE-main\DeepKE-main\example\re\standard\conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
C:\Users\LiuJunshan\miniconda3\envs\deepke-llm\lib\site-packages\hydra\plugins\config_source.py:190: UserWarning: 
Missing @package directive preprocess.yaml in file://C:\Users\LiuJunshan\Desktop\DeepKE-main\DeepKE-main\example\re\standard\conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
C:\Users\LiuJunshan\miniconda3\envs\deepke-llm\lib\site-packages\hydra\plugins\config_source.py:190: UserWarning: 
Missing @package directive train.yaml in file://C:\Users\LiuJunshan\Desktop\DeepKE-main\DeepKE-main\example\re\standard\conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
C:\Users\LiuJunshan\miniconda3\envs\deepke-llm\lib\site-packages\hydra\plugins\config_source.py:190: UserWarning: 
Missing @package directive embedding.yaml in file://C:\Users\LiuJunshan\Desktop\DeepKE-main\DeepKE-main\example\re\standard\conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
C:\Users\LiuJunshan\miniconda3\envs\deepke-llm\lib\site-packages\hydra\plugins\config_source.py:190: UserWarning: 
Missing @package directive predict.yaml in file://C:\Users\LiuJunshan\Desktop\DeepKE-main\DeepKE-main\example\re\standard\conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
C:\Users\LiuJunshan\miniconda3\envs\deepke-llm\lib\site-packages\hydra\plugins\config_source.py:190: UserWarning: 
Missing @package directive model/lm.yaml in file://C:\Users\LiuJunshan\Desktop\DeepKE-main\DeepKE-main\example\re\standard\conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
[2024-03-04 21:45:30,471][__main__][INFO] - 
cwd: C:\Users\LiuJunshan\Desktop\DeepKE-main\DeepKE-main\example\re\standard
preprocess: true
data_path: data/origin
out_path: data/out
chinese_split: true
replace_entity_with_type: true
replace_entity_with_scope: true
min_freq: 3
pos_limit: 30
seed: 1
use_gpu: true
gpu_id: 0
epoch: 50
batch_size: 32
learning_rate: 0.0003
lr_factor: 0.7
lr_patience: 3
weight_decay: 0.001
early_stopping_patience: 6
train_log: true
log_interval: 10
show_plot: false
only_comparison_plot: false
plot_utils: matplot
predict_plot: false
use_multi_gpu: false
gpu_ids: 0,1
vocab_size: ???
word_dim: 60
pos_size: 62
pos_dim: 10
dim_strategy: sum
num_relations: 11
fp: xxx/checkpoints/2019-12-03_17-35-30/cnn_epoch21.pth
model_name: lm
lm_file: bert-base-chinese
num_hidden_layers: 1
type_rnn: LSTM
input_size: 768
hidden_size: 100
num_layers: 1
dropout: 0.3
bidirectional: true
last_layer_hn: true

[2024-03-04 21:45:30,471][__main__][INFO] - device: cpu
[2024-03-04 21:45:30,472][utils.ioUtils][INFO] - load data from C:\Users\LiuJunshan\Desktop\DeepKE-main\DeepKE-main\example\re\standard\data/out\train.pkl
C:\Users\LiuJunshan\miniconda3\envs\deepke-llm\lib\site-packages\omegaconf\basecontainer.py:225: UserWarning: cfg.pretty() is deprecated and will be removed in a future version.
Use OmegaConf.to_yaml(cfg)

  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\LiuJunshan\Desktop\DeepKE-main\DeepKE-main\example\re\standard\run.py", line 74, in main
    train_dataset = CustomDataset(train_data_path)
  File "C:\Users\LiuJunshan\miniconda3\envs\deepke-llm\lib\site-packages\deepke\relation_extraction\standard\tools\dataset.py", line 64, in __init__
    self.file = load_pkl(fp)
  File "C:\Users\LiuJunshan\miniconda3\envs\deepke-llm\lib\site-packages\deepke\attribution_extraction\standard\utils\ioUtils.py", line 36, in load_pkl
    with open(fp, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\LiuJunshan\\Desktop\\DeepKE-main\\DeepKE-main\\example\\re\\standard\\data/out\\train.pkl'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Process finished with exit code 1
怎么办

**Comment by zxlzr** [comment]
您好，您这个报错是路径找不到，应该是配置文件里路径不太正确导致的，linux和windows的路径写法是不太一样的

**Comment by zxlzr** [comment]
请问您的问题解决了吗

**Comment by liujunshanhelen** [comment]
解决了
