### ISSUE TITLE
人民日报数据集为什么五个标签

### ISSUE THREAD

**Issue by Furyial** [zjunlp/DeepKE#417]
我用人民日报数据集做NER，用的w2ner，按道理他只有人民地名机构名三种标签，BIO标注策略的话，应该只有四种标签输出啊。为什么我用deepke的时候他是按照这个来的{'<pad>': 0, '<suc>': 1, 'loc': 2, 'per': 3, 'org': 4}，请问这个suc代表啥啊

**Comment by pengzju** [comment]
This is an inherent label in the w2ner [source code](https://github.com/ljynlp/W2NER/blob/a34ff841891919001080edefb50e14fa9dc15e1c/data_loader.py#L29) (should be the label of some special tokens). You can ignore this and only count the classification success rate of `{'loc', 'per', 'org'}`.

**Comment by zxlzr** [comment]
Do you have any further questions? 请问您还有其他问题吗？

**Comment by Furyial** [comment]
请问有资料提到过这些特殊的token吗？谢谢哥

**Comment by zxlzr** [comment]
> 请问有资料提到过这些特殊的token吗？谢谢哥

w2ner 论文的代码里有 https://github.com/ljynlp/W2NER/blob/a34ff841891919001080edefb50e14fa9dc15e1c/data_loader.py#L29

**Comment by Furyial** [comment]
卧槽，感谢哥
