### ISSUE TITLE
lightner如何使用cpu训练

### ISSUE THREAD

**Issue by MdcGIt** [zjunlp/DeepKE#420]
**Describe the question**
> A clear and concise description of what the question is.

请问ner的few-shot如何使用cpu进行训练,我把配置文件中的device改为cpu然后允许train,py还是提示我
AssertionError: Torch not compiled with CUDA enabled

**Environment (please complete the following information):**
 - OS: windows
 - Python Version 3,8

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by BeasterYong** [comment]
您好，可以看一下修改后的配置文件和train.py文件的具体路径吗？

**Comment by MdcGIt** [comment]
![image](https://github.com/zjunlp/DeepKE/assets/26782023/29b95e25-a45d-4e5a-bf2e-698bdb77c58c)
重新试了下 然后提示这个错

**Comment by MdcGIt** [comment]
![image](https://github.com/zjunlp/DeepKE/assets/26782023/723e77c9-b843-4814-8669-a04618b317f3)
然后报了这个错, 我把wandb注释掉还有self.writer相关的注释掉就能训练了,但是不注释的话就提示这个错误了

**Comment by MdcGIt** [comment]
![image](https://github.com/zjunlp/DeepKE/assets/26782023/f771a39c-0e35-4483-8d9c-40a629c897d2)
![image](https://github.com/zjunlp/DeepKE/assets/26782023/51097f2f-869b-4526-b7f1-bc702c9de2a0)
我电脑的代理都关了 前面提示已经登录成功了, 但是还是报这个错, 我把wandb调整为offline 也不行，是不是只能不用wandb了

**Comment by zxlzr** [comment]
可以注释掉不使用wandb，用手动调参

**Comment by MdcGIt** [comment]
好的

**Comment by MdcGIt** [comment]
os.environ["WANDB_START_METHOD"] = "thread"  加了一行这个代码解决了wandb的问题
