### ISSUE TITLE
ner的few_shot GPU训练最小需要多大显存

### ISSUE THREAD

**Issue by MdcGIt** [zjunlp/DeepKE#423]
**Describe the question**
> A clear and concise description of what the question is.
我用了一台小米笔记本 有俩个G的显存，训练时提示内存不足，看GPU使用情况是百分之0,batch_size设置成2也还是不行
RuntimeError: CUDA out of memory. Tried to allocate 76.00 MiB (GPU 0; 2.00 GiB total capacity; 1.61 GiB already allocated; 0 bytes free; 1.62 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF 

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

<img width="1078" alt="image" src="https://github.com/zjunlp/DeepKE/assets/26782023/8672937d-472e-4f42-9b08-3c602ced9120">
<img width="634" alt="image" src="https://github.com/zjunlp/DeepKE/assets/26782023/0fc3b261-70e9-4fc4-a207-5d65a2a74633">

**Additional context**
> Add any other context about the problem here.

**Comment by flow3rdown** [comment]
显存的占用与模型占用以及一些训练配置有关，使用`bart-large`，设置`batch size=1`，`prompt_len=10`, `prompt_dim=800`, 显存占用约4.7个G

**Comment by MdcGIt** [comment]
也就是说bart-large这个模型最少也得5个G的显存哈
