### ISSUE TITLE
Lora微调chatglm项目有两个错误不知道怎么解决，有人知道什么情况吗？

### ISSUE THREAD

**Issue by dasaffa** [zjunlp/DeepKE#424]
**用deepke-llm里的项目Lora微调chatglm有两个错误，如图：**
> 一个是参数的问题（很奇怪那个max_memory_MB参数什么情况），还有一个貌似是分布训练导致的，但是弄了两天都没成功运行
![image](https://github.com/zjunlp/DeepKE/assets/75426990/88f802b1-9845-4beb-80ff-bfc915d12b6a)

**下面是我填好的fine_chatglm.bash文件**
![image](https://github.com/zjunlp/DeepKE/assets/75426990/e24e50df-d338-408b-98d2-36f9d6c21918)

**环境：**
 - OS:linux
 - Python Version 3.10

**Comment by zxlzr** [comment]
请问您问题是否已解决

**Comment by dasaffa** [comment]
> 请问您问题是否已解决

暂时还没试

**Comment by dasaffa** [comment]
> > 请问您问题是否已解决
> 
> 暂时还没试

可以了已经
