### ISSUE TITLE
用自己训练出来的ner实体模型进行预测,报错了

### ISSUE THREAD

**Issue by MdcGIt** [zjunlp/DeepKE#425]
**Describe the question**
> A clear and concise description of what the question is.

问题1: 用自己训练出来的ner实体模型进行预测,报错了
问题2: 还有我训练的是中文数据集，为啥dataset_name 设置为cluener2020 不识别呢

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.
问题1截图: 
![image](https://github.com/zjunlp/DeepKE/assets/26782023/e0712e64-810f-4fbb-bd11-20a746644403)
问题2截图 :
![image](https://github.com/zjunlp/DeepKE/assets/26782023/40461277-2d3a-415a-882a-7ff2072b074d)

**Additional context**
> Add any other context about the problem here.

**Comment by flow3rdown** [comment]
抱歉，回复的较晚了。
问题1：您是否使用CoNLL2003训练的模型？如果是用的其他数据集训练的模型，由于数据集的标签不一致会出现维度不匹配的错误。
问题2：需要在`predict.py`中添加映射，可以参考`predict.py`中已经存在的数据集映射关系添加。

**Comment by zxlzr** [comment]
您需要手动添加一下标签映射

**Comment by MdcGIt** [comment]
明白了  谢谢~
