### ISSUE TITLE
setup.py为什么运行不了？

### ISSUE THREAD

**Issue by BeimingCharles** [zjunlp/DeepKE#426]
**Describe the bug**
> A clear and concise description of what the bug is.

![image](https://github.com/zjunlp/DeepKE/assets/151798892/54e69274-0eef-4b32-a678-42711fdbe473)

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]
python3.8

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
请您看一下红色的字，您需要输入命令

请您按readme的要求来执行。

pip install -r requirements.txt

python setup.py install

python setup.py develop

**Comment by zxlzr** [comment]
请问问题是否已解决？
