### ISSUE TITLE
RunBERT问题

### ISSUE THREAD

**Issue by Furyial** [zjunlp/DeepKE#428]
您好，我使用bert做ner时候，采用你们给出的数据集，但是输出结果全部是O，并且最后计算出来的精度也是零。我看之前提出过相同的问题，但是并没有解决。请问有解决方案吗？

**Comment by zxlzr** [comment]
请问您是使用最新的代码吗，是什么模型，数据量有多少，之前的bug很早就修复过了

**Comment by Furyial** [comment]
模型是bert，ner的run_bert

**Comment by zxlzr** [comment]
建议您重新pull下代码再试试吧

**Comment by Furyial** [comment]
您好，我想请问一波，当我下载bert模型之后要把它放到哪里，我下载了新的代码，但是还是全部都O。我把bert_model改为了'G:\\PythonCode\\DeepKE-main\\pretrained\\bert-base-chinese\\'也就是我下载bert后的绝对路径。代码跑出来了全是O，请问是不是这个的问题。我需要把下载的bert模型放到哪里

**Comment by xxupiano** [comment]
请问您跑的是哪个代码文件？

**Comment by Furyial** [comment]
example/ner/standard/run_bert.py

**Comment by zxlzr** [comment]
我们会尽快重跑下看下是否可以复现您遇到的问题。

**Comment by Furyial** [comment]
谢谢哥

**Comment by xxupiano** [comment]
您好，使用我们提供的人民日报数据集wget 120.27.214.45/Data/ner/few_shot/data.tar.gz，训练batch size为64， epoch为1得到结果如下图：
![image](https://github.com/zjunlp/DeepKE/assets/43436958/d6518bfa-3179-43d5-bc3e-013708c46106)

**Comment by xxupiano** [comment]
BERT模型放在哪里都可以，只需要修改hydra/model/bert.yaml中的bert_mode为模型路径即可

**Comment by Furyial** [comment]
老哥，我重新复制了代码，然后设置batchsize为32.还是零
![B~RFFK~D{%0$VUU3{THFS U](https://github.com/zjunlp/DeepKE/assets/118899737/0f2a2892-13c5-4e3a-9f43-490901087119)

**Comment by xxupiano** [comment]
src下的代码是最新的吗？更新src下的代码后重新安装deepke，在DeepKE目录下使用pip install -e .命令

**Comment by Furyial** [comment]
牛逼哥，我把batchsize改成64就出正常结果了.....

**Comment by Furyial** [comment]
谢谢老哥一直耐心解答，祝老哥心想事成万事如意

**Comment by Furyial** [comment]
src下的代码还是原来的，并没有改变
