### ISSUE TITLE
运行ee/standard/时候报错huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/newdisk1/msy/models/bert-base-chinese'. Use `repo_type` argument if needed.

### ISSUE THREAD

**Issue by xiaowang-xuexiji** [zjunlp/DeepKE#429]
这里的模型我该去哪里下载，train.yaml中
model_name_or_path:  /newdisk1/msy/models/bert-base-chinese # [bert-base-uncased, bert-base-chinese] english for ace, chinese for duee
这个字段的模型是什么，从哪里下载。

**Comment by shengyumao** [comment]
你好，这里的字段可以用bert-base-chinese或者bert-base-uncased进行替换，这样会从huggingface自动下载模型。或者可以更改成你本地的bert模型的路径。

**Comment by xiaowang-xuexiji** [comment]
哦哦 我看到了，是因为连接huggingface超时了就没下载，我再试试

**Comment by shengyumao** [comment]
连接huggingface的话可以开代理，没有的话也可以试试看去modelscope上手动下载模型

**Comment by xiaowang-xuexiji** [comment]
开了代理也是连接超时，可以告诉我这个模型的下载地址不啊，或者是我这个代理不能开日本的。

**Comment by zxlzr** [comment]
https://github.com/ymcui/Chinese-BERT-wwm

您也可以在国内的wisemodel 和modelscope 官网搜这个模型下载

**Comment by xiaowang-xuexiji** [comment]
好的 谢谢

**Comment by zxlzr** [comment]
请问您的问题解决了吗
