### ISSUE TITLE
用知识图谱框架完成一门课程的知识梳理

### ISSUE THREAD

**Issue by Pedestrian927** [zjunlp/DeepKE#430]
**Describe the question**
> A clear and concise description of what the question is.
您好，我因学习需要想用这个框架做一个关于数据与计算机网络课程的知识图谱，但因为我对这方面的编程知识涉及不多，不清楚这个项目怎么做，您能提供一些帮助吗？这是我的邮箱
xwavom@qq.com，如果您有空，希望您能联系我

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
建议您可以先学习一些知识图谱构建的在线教程和书籍如下列链接里的项目：

https://github.com/liuhuanyong

https://liuhuanyong.github.io/
