### ISSUE TITLE
InstructIE的环境配置

### ISSUE THREAD

**Issue by 66246764** [zjunlp/DeepKE#432]
**Describe the bug**
> A clear and concise description of what the bug is.
您好，我根据教程配置好环境，下载BaiChuan2-13B-Chat以及zjunlp/baichuan2-13b-iepile-lora后，配置好fine_baichuan.bash里面的路径后，使用您的样例data/Ner的数据进行测试，运行bash ft_scripts/fine_baichuan.bash后出现以下报错信息：
‘keyError：other’

**Environment (please complete the following information):**
关于torch
torch                     2.0.1                    pypi_0    pypi
torchaudio                2.0.0                py39_cu117    pytorch
torchtriton               2.0.0                      py39    pytorch
torchvision               0.15.0               py39_cu117    pytorch

本机cuda信息
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0

**Screenshots**
> If applicable, add screenshots to help explain your problem.
<img width="767" alt="Snipaste_2024-03-17_17-23-44" src="https://github.com/zjunlp/DeepKE/assets/54762477/9ac620af-e609-4eed-8ce5-2c30e79f853c">

keyvalue错误

<img width="858" alt="1" src="https://github.com/zjunlp/DeepKE/assets/54762477/320759d0-b109-4953-adea-67315ef453fb">

**Comment by 66246764** [comment]
<img width="573" alt="2" src="https://github.com/zjunlp/DeepKE/assets/54762477/4976fb08-d43f-4abf-8f1a-2755c594de6b">
这个是bash里面的信息

**Comment by guihonghao** [comment]
你好，需要设置--model_name 'baichuan'

**Comment by 66246764** [comment]
抱歉配置错了- -
我将bash文件更改为：
![image](https://github.com/zjunlp/DeepKE/assets/54762477/c1294088-9f38-4ea3-829b-91f08a695339)
如果想要使用您训练好的[zjunlp/baichuan2-13b-iepile-lora]
是否运行命令bash ft_scripts/fine_baichuan.bash --checkpoint_dir /home/user11/modal/baichuan2-13b-iepile-lora
这个就可以使用您lora微调后的模型了呢

**Comment by guihonghao** [comment]
继续训练是这样的

**Comment by 66246764** [comment]
![image](https://github.com/zjunlp/DeepKE/assets/54762477/1908934f-f679-49be-b9c5-105552ad73a7)
继续训练，出现了这样的错误NotImplementedError: Loading a dataset cached in a LocalFileSystem is not supported.
我搜索一下之前issue有提到过更新一下datasets，但是好像还是不能解决

**Comment by guihonghao** [comment]
pip install datasets==2.18.0

**Comment by 66246764** [comment]
您好，更新到 datasets==2.18.0这个错误解决了。
我现在想要使用这个命令bash ft_scripts/fine_baichuan.bash --checkpoint_dir /home/user11/modal/baichuan2-13b-iepile-lora在您微调后的【baichuan2-13b-iepile-lora】模型下继续训练，数据集根据您下面教程中的描述直接选用了【InstructIE】这个数据集，即直接下载InstructIE后没做任何处理使用里面的train_zh.json
![image](https://github.com/zjunlp/DeepKE/assets/54762477/9ad6a040-9324-43b7-a07b-654ef689cc27)
下面是fine_baichuan.bash文件的配置，将train_file参数更换为了Instruct的train
![image](https://github.com/zjunlp/DeepKE/assets/54762477/196769f3-4092-4159-8668-4321dbec8211)
但是又出现了以下错误“keyerror：prompt”，请问一下这是是哪里理解错了吗- -
![image](https://github.com/zjunlp/DeepKE/assets/54762477/7b7ce012-021c-49d9-b6c6-ed900594c4ed)

**Comment by 66246764** [comment]
这个数据集的使用我是想要测试一下部署情况，后面会更换为垂直领域上的中文数据进行训练

**Comment by guihonghao** [comment]
<img width="725" alt="image" src="https://github.com/zjunlp/DeepKE/assets/53286894/cdb8ca6f-f946-4bd5-9252-88ed1827dbb3">
我们在hugging face的InstructIE上面上传了相应的各个主题的数据，便于处理。你还需要进行下面的数据处理，生成得到的data_processed/InstructIE_人物/train.json文件可以用于训练。
python ie2instruction/convert_func.py \
    --src_path data/InstructIE_人物/train.json \
    --tgt_path data_processed/InstructIE_人物/train.json \
    --schema_path data/InstructIE_人物/schema.json \
    --language zh \
    --task RE \
    --split_num 4 \       
    --random_sort \
    --split train

**Comment by 66246764** [comment]
好的，谢谢！

**Comment by 66246764** [comment]
关于垂直领域微调模型您有建议吗，用基座还是基于lora微调的模型进行二次微调

**Comment by zxlzr** [comment]
您好，看数据，数据量大用基座，目前有更好的基座如baichuan2，通义1.5。数据量小lora 二次微调，一切效果受到数据量和质量影响

**Comment by 66246764** [comment]
明白了，谢谢您！
