### ISSUE TITLE
ner模型预测也是不对

### ISSUE THREAD

**Issue by zjydbj** [zjunlp/DeepKE#434]
我在使用ner部分的时候，也用的是开箱即用特别版DeepKE-cnSchema，也都是按照官方配置的
但是在进行预测的时候，结果也是不对，如下所示：
![image](https://github.com/zjunlp/DeepKE/assets/10933589/0f3258e7-be14-4f8b-9a5a-2c7c4a579989)
结果并不是把所有文字都识别了，而是最后两个字，请问我应该怎么改呢

**Comment by xxupiano** [comment]
https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/conf/train.yaml#L24 请使用L24的labels，注释L23

**Comment by zjydbj** [comment]
我应该是都下载了

**Comment by xxupiano** [comment]
用成了英文模型，LOC是英文标签，中文标签里没有LOC

**Comment by zxlzr** [comment]
请问问题是否已解决？

**Comment by zjydbj** [comment]
麻烦请发一下中文模型的链接呗，就是百度网盘那些chinese吗，我都是运行成LOC了

**Comment by zjydbj** [comment]
还没解决，麻烦请发一下中文模型的链接呗

**Comment by BeasterYong** [comment]
[中文Bert模型链接](https://drive.google.com/drive/folders/1zA8Ichx9nzU3GD92ptdyR_nmARB_7ovg)，请在下载后按照Readme配置即可~
