### ISSUE TITLE
请问cross-ner中的single_transfer中是否Introducing了DAPT，如果是的话在那可以看到这部分代码？

### ISSUE THREAD

**Issue by kkkenshi** [zjunlp/DeepKE#435]

**Comment by njcx-ai** [comment]
您好，感谢您对我们工作的关注。
如论文中图1所示，single_transfer实验中Introducing DAPT那栏引入了DAPT，其具体做法是将底座语言模型按照DAPT的源码在相应的领域数据上预训练，该过程与我们的方法是正交的。因此我们公开的代码中并未涉及这部分代码，您可以参考DAPT的源码了解具体细节。

**Comment by zxlzr** [comment]
请问您还有其他问题吗

**Comment by kkkenshi** [comment]
> 请问您还有其他问题吗

没问题了了谢谢解答
