### ISSUE TITLE
ner的few_shot预测报错

### ISSUE THREAD

**Issue by MdcGIt** [zjunlp/DeepKE#436]
**Describe the question**
> A clear and concise description of what the question is.

在使用ner的few_shot进行训练得到自己的模型之后 然后进行中文预测报错了，predict.py中所需cluener2020的映射都已经添加了,但还是报错了

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![image](https://github.com/zjunlp/DeepKE/assets/26782023/318beda0-3890-4c02-b0d2-55fa987d7928)

![image](https://github.com/zjunlp/DeepKE/assets/26782023/62925726-cf1e-4cfa-863b-9343aaaa7a2c)

![image](https://github.com/zjunlp/DeepKE/assets/26782023/934fff13-e06b-438d-81c4-40f86cf1f9b5)

**Additional context**
> Add any other context about the problem here.

**Comment by MdcGIt** [comment]
![image](https://github.com/zjunlp/DeepKE/assets/26782023/b517ed5a-2a9a-41e8-8cd6-afebdce53f65)

**Comment by flow3rdown** [comment]
您好，`predict.py`中的yaml文件指定存在问题，应改为`@hydra.main(config_path="conf/predict.yaml")`，您可以自行修改或者pull我们更新后的代码再尝试一下。

另外MAPPING中是否正确指定了cluner2020?

**Comment by zxlzr** [comment]
请问您的问题是否可以解决？

**Comment by MdcGIt** [comment]
![image](https://github.com/zjunlp/DeepKE/assets/26782023/cb854123-2399-4318-ae3e-62ad833e9311)
拉取了最新代码之后 提示这个

**Comment by MdcGIt** [comment]
我在data_path中加了test之后上面那个截图的问题修复了，但是预测的时候还是提示之前的错，是不是跟我的模型有关系？
![image](https://github.com/zjunlp/DeepKE/assets/26782023/1d53e7b3-83e7-49ff-9ce1-7b70f5c2c5df)

**Comment by jellin123** [comment]
您好，我也是在使用自己的数据集训练完成后进行预测出现这个问题
![图片](https://github.com/zjunlp/DeepKE/assets/68311969/765ed2e7-d4a0-4917-9f4b-b0df610fba52)

**Comment by MdcGIt** [comment]
@flow3rdown @zxlzr

**Comment by MdcGIt** [comment]
@zxlzr @flow3rdown 帮忙解答一下，卡着好几天了 😭

**Comment by flow3rdown** [comment]
> @zxlzr @flow3rdown 帮忙解答一下，卡着好几天了 😭

麻烦您加一下我的vx: flow3rdown，我用中文模型也没有复现出相应的bug
