### ISSUE TITLE
麻烦提供一下中文的ner模型链接呗，readme上的我用着是英文

### ISSUE THREAD

**Issue by zjydbj** [zjunlp/DeepKE#439]
麻烦提供一下中文的ner模型链接呗，readme上的我用着是英文

**Comment by zjydbj** [comment]
![image](https://github.com/zjunlp/DeepKE/assets/10933589/a5cca0d0-86c6-4476-ae24-871c60a4e62c)
woxiazai我下载的是这个，解析出来是LOC字符，说明还是英文的

**Comment by BeasterYong** [comment]
您好，我们试验过了这个模型没问题
![image](https://github.com/zjunlp/DeepKE/assets/95857885/e654fe59-f2de-49c9-a7fa-6ed8ea2256c3)
请问您是从[链接](https://drive.google.com/drive/folders/1zA8Ichx9nzU3GD92ptdyR_nmARB_7ovg)下载的checkpoint_bert.zip文件吗？

**Comment by zjydbj** [comment]
我下载一下您这个，估计是一样的，再试试

**Comment by BeasterYong** [comment]
麻烦看一下您运行的文件路径和配置文件`config.yaml`的内容吗？

**Comment by BeasterYong** [comment]
可以看一下您运行的文件路径和配置文件config.yaml的内容吗？

**Comment by zjydbj** [comment]
这回OK了，谢谢大佬们的帮助，我是在大佬们的指点下，这么做的，
![image](https://github.com/zjunlp/DeepKE/assets/10933589/8524b2f4-69d2-4e72-9d22-c5b27c4dedc1)
先是zhushid注释掉23行，打开24行
然后这里选择bert
![image](https://github.com/zjunlp/DeepKE/assets/10933589/f2b52117-3762-483a-b196-5d8d3daae5d6)
就好使了，默认值不是bert，我是纯是小白，感谢大家的耐心指导哈
