### ISSUE TITLE
cross-ner中csv问题

### ISSUE THREAD

**Issue by kkkenshi** [zjunlp/DeepKE#440]
**Describe the question**
> 请问如果我想用自己的csv数据做train和single_transfer，可以直接使用csv文件吗？还是得转换成JSON格式，其中csv格式如下：
content        lables
""" your "" covid 19 vaccine . "" YOUR "" ? bruh that shit aint mines"	[{'type': 'Vaccine-related', 'start_index': 3, 'end_index': 6, 'value': 'covid 19 vaccine', 'sentiment': 'Neutral'}]

**Comment by zxlzr** [comment]
您好，您可以自己写脚本把格式转换成统一格式作为输入就可以。

**Comment by kkkenshi** [comment]
您好可以说具体一点吗，谢谢！

**Comment by zxlzr** [comment]
您写脚本转换成和我们提供的数据格式一样的形式即可 120.27.214.45/Data/ner/few_shot/data.tar.gz

**Comment by zxlzr** [comment]
请问是否还有其它问题？

**Comment by kkkenshi** [comment]
没有了谢谢
