### ISSUE TITLE
embedding.yaml中num_relations参数是什么意思

### ISSUE THREAD

**Issue by fuqiang-benz** [zjunlp/DeepKE#441]
example/re/standard/conf/embedding.yaml中num_relations参数是什么意思，是多少种关系种类就写多少吗？ 比如说我有20种关系类型就写20是把， 写1和写51的区别是什么？

**Comment by zxlzr** [comment]
是有多少关系就写多少。

**Comment by zxlzr** [comment]
请问您还有其他问题吗
