### ISSUE TITLE
关于Baichuan-13B-Chat基础模型与提供的IEPile数据集lora微调后的权重的问题

### ISSUE THREAD

**Issue by dasaffa** [zjunlp/DeepKE#442]
**我用Baichuan-13B-Chat基础模型与官方提供的lora微调后的权重时，模型的输出跟训练数据集里的输出不一样**

*我输入的问题是：*
sintruct = "{\"instruction\": \"你是专门进行实体抽取的专家。请从input中抽取出符合schema定义的实体，不存在的实体类型返回空列表。请按照JSON字符串的格式回答。\", \"schema\": [\"姓名\", \"景点\", \"书名\", \"公司\", \"组织机构\", \"电影\"], \"input\": \"在新春佳节期间，游戏天堂联合全国9大城市34家名店进行王牌产品的促销活动，\"}"

*模型的输出却是：*
![image](https://github.com/zjunlp/DeepKE/assets/75426990/0bfab3af-4c4f-4410-a00b-f6fda139930f)

*理想情况下输出不应该是下面那样吗：*
"output": "{\"姓名\": [], \"景点\": [], \"书名\": [], \"公司\": [\"游戏天堂\"], \"组织机构\": [], \"电影\": []}

我用的代码是官方提供的lora权重的使用方法代码。

**Comment by guihonghao** [comment]
看看你inference的命令

**Comment by dasaffa** [comment]
> 看看你inference的命令

我是直接用的提供的代码来使用模型和lora权重的，请问您说的inference命令是哪一部份
![image](https://github.com/zjunlp/DeepKE/assets/75426990/f8b46fb4-5062-4e9a-a743-9455424d3b1e)

**Comment by guihonghao** [comment]
<img width="790" alt="image" src="https://github.com/zjunlp/DeepKE/assets/53286894/0f8266c7-749d-4df6-9887-fd31316addd9">


instruction_mapper = {
    'NERzh': "你是专门进行实体抽取的专家。请从input中抽取出符合schema定义的实体，不存在的实体类型返回空列表。请按照JSON字符串的格式回答。",
    'REzh': "你是专门进行关系抽取的专家。请从input中抽取出符合schema定义的关系三元组，不存在的关系返回空列表。请按照JSON字符串的格式回答。",
    'EEzh': "你是专门进行事件提取的专家。请从input中抽取出符合schema定义的事件，不存在的事件返回空列表，不存在的论元返回NAN，如果论元存在多值请返回列表。请按照JSON字符串的格式回答。",
    'EETzh': "你是专门进行事件提取的专家。请从input中抽取出符合schema定义的事件类型及事件触发词，不存在的事件返回空列表。请按照JSON字符串的格式回答。",
    'EEAzh': "你是专门进行事件论元提取的专家。请从input中抽取出符合schema定义的事件论元及论元角色，不存在的论元返回NAN或空字典，如果论元存在多值请返回列表。请按照JSON字符串的格式回答。",
        
    'NERen': "You are an expert in named entity recognition. Please extract entities that match the schema definition from the input. Return an empty list if the entity type does not exist. Please respond in the format of a JSON string.",
    'REen': "You are an expert in relationship extraction. Please extract relationship triples that match the schema definition from the input. Return an empty list for relationships that do not exist. Please respond in the format of a JSON string.",
    'EEen': "You are an expert in event extraction. Please extract events from the input that conform to the schema definition. Return an empty list for events that do not exist, and return NAN for arguments that do not exist. If an argument has multiple values, please return a list. Respond in the format of a JSON string.",
    'EETen': "You are an expert in event extraction. Please extract event types and event trigger words from the input that conform to the schema definition. Return an empty list for non-existent events. Please respond in the format of a JSON string.",
    'EEAen': "You are an expert in event argument extraction. Please extract event arguments and their roles from the input that conform to the schema definition, which already includes event trigger words. If an argument does not exist, return NAN or an empty dictionary. Please respond in the format of a JSON string.", 
}
split_num_mapper = {'NER':6, 'RE':4, 'EE':4, 'EET':4, 'EEA':4}


import json

task = 'NER'
language = 'en'
schema = ['person', 'organization', 'else', 'location']
split_num = split_num_mapper[task]
split_schemas = [schema[i:i+split_num] for i in range(0, len(schema), split_num)]
input = '284 Robert Allenby ( Australia ) 69 71 71 73 , Miguel Angel Martin ( Spain ) 75 70 71 68 ( Allenby won at first play-off hole )'
sintructs = []
for split_schema in split_schemas:
    sintruct = json.dumps({'instruction':instruction_mapper[task+language], 'schema':split_schema, 'input':input}, ensure_ascii=False)
    sintructs.append(sintruct)


import torch
from transformers import (
    AutoConfig,
    AutoTokenizer,
    AutoModelForCausalLM,
    GenerationConfig
)
from peft import PeftModel

model_path = '/newdisk3/data/guihh/alpaca-lora/models/Baichuan2-13B-Chat'
lora_path = '/newdisk3/data/guihh/alpaca-lora/lora/baichuan2-13b-iepile-lora'
config = AutoConfig.from_pretrained(model_path, trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)

model = AutoModelForCausalLM.from_pretrained(
    model_path,
    config=config,
    device_map="auto",  
    torch_dtype=torch.bfloat16,
    trust_remote_code=True,
)


model = PeftModel.from_pretrained(
    model,
    lora_path,
)
model.eval()

sintruct = "{\"instruction\": \"你是专门进行实体抽取的专家。请从input中抽取出符合schema定义的实体，不存在的实体类型返回空列表。请按照JSON字符串的格式回答。\", \"schema\": [\"姓名\", \"景点\", \"书名\", \"公司\", \"组织机构\", \"电影\"], \"input\": \"在新春佳节期间，游戏天堂联合全国9大城市34家名店进行王牌产品的促销活动，\"}"
sintruct = '<reserved_106>' + sintruct + '<reserved_107>'

input_ids = tokenizer.encode(sintruct, return_tensors="pt")
input_length = input_ids.size(1)
generation_output = model.generate(input_ids=input_ids, generation_config=GenerationConfig(max_length=512, max_new_tokens=256, return_dict_in_generate=True))
generation_output = generation_output.sequences[0]
generation_output = generation_output[input_length:]
output = tokenizer.decode(generation_output, skip_special_tokens=True)

print(output)

你好，我这边测试结果正常。

**Comment by dasaffa** [comment]
> <img alt="image" width="790" src="https://private-user-images.githubusercontent.com/53286894/314916511-0f8266c7-749d-4df6-9887-fd31316addd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5OTA0NTAsIm5iZiI6MTcxMDk5MDE1MCwicGF0aCI6Ii81MzI4Njg5NC8zMTQ5MTY1MTEtMGY4MjY2YzctNzQ5ZC00ZGY2LTk4ODctZmQzMTMxNmFkZGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDAzMDIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMDExNzljZGViNjMzODZhZjdkNDRiZWMzY2I4YjRlZDM4YTBmNjA4MWQzZTc0OTQ3YjAwODRhNjQ0N2JkN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QgrJU0c7z1To9Ggj-zdkYlQJMbRTMeI_l0RkbhAHBIA">
> instruction_mapper = { 'NERzh': "你是专门进行实体抽取的专家。请从input中抽取出符合schema定义的实体，不存在的实体类型返回空列表。请按照JSON字符串的格式回答。", 'REzh': "你是专门进行关系抽取的专家。请从input中抽取出符合schema定义的关系三元组，不存在的关系返回空列表。请按照JSON字符串的格式回答。", 'EEzh': "你是专门进行事件提取的专家。请从input中抽取出符合schema定义的事件，不存在的事件返回空列表，不存在的论元返回NAN，如果论元存在多值请返回列表。请按照JSON字符串的格式回答。", 'EETzh': "你是专门进行事件提取的专家。请从input中抽取出符合schema定义的事件类型及事件触发词，不存在的事件返回空列表。请按照JSON字符串的格式回答。", 'EEAzh': "你是专门进行事件论元提取的专家。请从input中抽取出符合schema定义的事件论元及论元角色，不存在的论元返回NAN或空字典，如果论元存在多值请返回列表。请按照JSON字符串的格式回答。",
> 
> ```
> 'NERen': "You are an expert in named entity recognition. Please extract entities that match the schema definition from the input. Return an empty list if the entity type does not exist. Please respond in the format of a JSON string.",
> 'REen': "You are an expert in relationship extraction. Please extract relationship triples that match the schema definition from the input. Return an empty list for relationships that do not exist. Please respond in the format of a JSON string.",
> 'EEen': "You are an expert in event extraction. Please extract events from the input that conform to the schema definition. Return an empty list for events that do not exist, and return NAN for arguments that do not exist. If an argument has multiple values, please return a list. Respond in the format of a JSON string.",
> 'EETen': "You are an expert in event extraction. Please extract event types and event trigger words from the input that conform to the schema definition. Return an empty list for non-existent events. Please respond in the format of a JSON string.",
> 'EEAen': "You are an expert in event argument extraction. Please extract event arguments and their roles from the input that conform to the schema definition, which already includes event trigger words. If an argument does not exist, return NAN or an empty dictionary. Please respond in the format of a JSON string.", 
> ```
> 
> } split_num_mapper = {'NER':6, 'RE':4, 'EE':4, 'EET':4, 'EEA':4}
> 
> import json
> 
> task = 'NER' language = 'en' schema = ['person', 'organization', 'else', 'location'] split_num = split_num_mapper[task] split_schemas = [schema[i:i+split_num] for i in range(0, len(schema), split_num)] input = '284 Robert Allenby ( Australia ) 69 71 71 73 , Miguel Angel Martin ( Spain ) 75 70 71 68 ( Allenby won at first play-off hole )' sintructs = [] for split_schema in split_schemas: sintruct = json.dumps({'instruction':instruction_mapper[task+language], 'schema':split_schema, 'input':input}, ensure_ascii=False) sintructs.append(sintruct)
> 
> import torch from transformers import ( AutoConfig, AutoTokenizer, AutoModelForCausalLM, GenerationConfig ) from peft import PeftModel
> 
> model_path = '/newdisk3/data/guihh/alpaca-lora/models/Baichuan2-13B-Chat' lora_path = '/newdisk3/data/guihh/alpaca-lora/lora/baichuan2-13b-iepile-lora' config = AutoConfig.from_pretrained(model_path, trust_remote_code=True) tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
> 
> model = AutoModelForCausalLM.from_pretrained( model_path, config=config, device_map="auto", torch_dtype=torch.bfloat16, trust_remote_code=True, )
> 
> model = PeftModel.from_pretrained( model, lora_path, ) model.eval()
> 
> sintruct = "{"instruction": "你是专门进行实体抽取的专家。请从input中抽取出符合schema定义的实体，不存在的实体类型返回空列表。请按照JSON字符串的格式回答。", "schema": ["姓名", "景点", "书名", "公司", "组织机构", "电影"], "input": "在新春佳节期间，游戏天堂联合全国9大城市34家名店进行王牌产品的促销活动，"}" sintruct = '<reserved_106>' + sintruct + '<reserved_107>'
> 
> input_ids = tokenizer.encode(sintruct, return_tensors="pt") input_length = input_ids.size(1) generation_output = model.generate(input_ids=input_ids, generation_config=GenerationConfig(max_length=512, max_new_tokens=256, return_dict_in_generate=True)) generation_output = generation_output.sequences[0] generation_output = generation_output[input_length:] output = tokenizer.decode(generation_output, skip_special_tokens=True)
> 
> print(output)
> 
> 你好，我这边测试结果正常。

好的，我这边再试一下，谢谢

**Comment by dasaffa** [comment]
> <img alt="image" width="790" src="https://private-user-images.githubusercontent.com/53286894/314916511-0f8266c7-749d-4df6-9887-fd31316addd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5OTc5MjAsIm5iZiI6MTcxMDk5NzYyMCwicGF0aCI6Ii81MzI4Njg5NC8zMTQ5MTY1MTEtMGY4MjY2YzctNzQ5ZC00ZGY2LTk4ODctZmQzMTMxNmFkZGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA1MDcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZGYxMmEwMWJhY2JmMGZmYjEyNmI0MTA1MmRhZjZlZWIwMWUzMzc4MzYwZTNlMTIzMGU0NTI4ZGE3YzI4ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.54bdHVfvE2mPPtr_7k2loIiF6xCSUqp7p9GTT_NRF4w">
> instruction_mapper = { 'NERzh': "你是专门进行实体抽取的专家。请从input中抽取出符合schema定义的实体，不存在的实体类型返回空列表。请按照JSON字符串的格式回答。", 'REzh': "你是专门进行关系抽取的专家。请从input中抽取出符合schema定义的关系三元组，不存在的关系返回空列表。请按照JSON字符串的格式回答。", 'EEzh': "你是专门进行事件提取的专家。请从input中抽取出符合schema定义的事件，不存在的事件返回空列表，不存在的论元返回NAN，如果论元存在多值请返回列表。请按照JSON字符串的格式回答。", 'EETzh': "你是专门进行事件提取的专家。请从input中抽取出符合schema定义的事件类型及事件触发词，不存在的事件返回空列表。请按照JSON字符串的格式回答。", 'EEAzh': "你是专门进行事件论元提取的专家。请从input中抽取出符合schema定义的事件论元及论元角色，不存在的论元返回NAN或空字典，如果论元存在多值请返回列表。请按照JSON字符串的格式回答。",
> 
> ```
> 'NERen': "You are an expert in named entity recognition. Please extract entities that match the schema definition from the input. Return an empty list if the entity type does not exist. Please respond in the format of a JSON string.",
> 'REen': "You are an expert in relationship extraction. Please extract relationship triples that match the schema definition from the input. Return an empty list for relationships that do not exist. Please respond in the format of a JSON string.",
> 'EEen': "You are an expert in event extraction. Please extract events from the input that conform to the schema definition. Return an empty list for events that do not exist, and return NAN for arguments that do not exist. If an argument has multiple values, please return a list. Respond in the format of a JSON string.",
> 'EETen': "You are an expert in event extraction. Please extract event types and event trigger words from the input that conform to the schema definition. Return an empty list for non-existent events. Please respond in the format of a JSON string.",
> 'EEAen': "You are an expert in event argument extraction. Please extract event arguments and their roles from the input that conform to the schema definition, which already includes event trigger words. If an argument does not exist, return NAN or an empty dictionary. Please respond in the format of a JSON string.", 
> ```
> 
> } split_num_mapper = {'NER':6, 'RE':4, 'EE':4, 'EET':4, 'EEA':4}
> 
> import json
> 
> task = 'NER' language = 'en' schema = ['person', 'organization', 'else', 'location'] split_num = split_num_mapper[task] split_schemas = [schema[i:i+split_num] for i in range(0, len(schema), split_num)] input = '284 Robert Allenby ( Australia ) 69 71 71 73 , Miguel Angel Martin ( Spain ) 75 70 71 68 ( Allenby won at first play-off hole )' sintructs = [] for split_schema in split_schemas: sintruct = json.dumps({'instruction':instruction_mapper[task+language], 'schema':split_schema, 'input':input}, ensure_ascii=False) sintructs.append(sintruct)
> 
> import torch from transformers import ( AutoConfig, AutoTokenizer, AutoModelForCausalLM, GenerationConfig ) from peft import PeftModel
> 
> model_path = '/newdisk3/data/guihh/alpaca-lora/models/Baichuan2-13B-Chat' lora_path = '/newdisk3/data/guihh/alpaca-lora/lora/baichuan2-13b-iepile-lora' config = AutoConfig.from_pretrained(model_path, trust_remote_code=True) tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
> 
> model = AutoModelForCausalLM.from_pretrained( model_path, config=config, device_map="auto", torch_dtype=torch.bfloat16, trust_remote_code=True, )
> 
> model = PeftModel.from_pretrained( model, lora_path, ) model.eval()
> 
> sintruct = "{"instruction": "你是专门进行实体抽取的专家。请从input中抽取出符合schema定义的实体，不存在的实体类型返回空列表。请按照JSON字符串的格式回答。", "schema": ["姓名", "景点", "书名", "公司", "组织机构", "电影"], "input": "在新春佳节期间，游戏天堂联合全国9大城市34家名店进行王牌产品的促销活动，"}" sintruct = '<reserved_106>' + sintruct + '<reserved_107>'
> 
> input_ids = tokenizer.encode(sintruct, return_tensors="pt") input_length = input_ids.size(1) generation_output = model.generate(input_ids=input_ids, generation_config=GenerationConfig(max_length=512, max_new_tokens=256, return_dict_in_generate=True)) generation_output = generation_output.sequences[0] generation_output = generation_output[input_length:] output = tokenizer.decode(generation_output, skip_special_tokens=True)
> 
> print(output)
> 
> 你好，我这边测试结果正常。

请问一下，你测试运行的完整代码是下面这样吗？还是说只从import  torch那一行开始

```
instruction_mapper = {
'NERzh': "你是专门进行实体抽取的专家。请从input中抽取出符合schema定义的实体，不存在的实体类型返回空列表。请按照JSON字符串的格式回答。",
'REzh': "你是专门进行关系抽取的专家。请从input中抽取出符合schema定义的关系三元组，不存在的关系返回空列表。请按照JSON字符串的格式回答。",
'EEzh': "你是专门进行事件提取的专家。请从input中抽取出符合schema定义的事件，不存在的事件返回空列表，不存在的论元返回NAN，如果论元存在多值请返回列表。请按照JSON字符串的格式回答。",
'EETzh': "你是专门进行事件提取的专家。请从input中抽取出符合schema定义的事件类型及事件触发词，不存在的事件返回空列表。请按照JSON字符串的格式回答。",
'EEAzh': "你是专门进行事件论元提取的专家。请从input中抽取出符合schema定义的事件论元及论元角色，不存在的论元返回NAN或空字典，如果论元存在多值请返回列表。请按照JSON字符串的格式回答。",

'NERen': "You are an expert in named entity recognition. Please extract entities that match the schema definition from the input. Return an empty list if the entity type does not exist. Please respond in the format of a JSON string.",
'REen': "You are an expert in relationship extraction. Please extract relationship triples that match the schema definition from the input. Return an empty list for relationships that do not exist. Please respond in the format of a JSON string.",
'EEen': "You are an expert in event extraction. Please extract events from the input that conform to the schema definition. Return an empty list for events that do not exist, and return NAN for arguments that do not exist. If an argument has multiple values, please return a list. Respond in the format of a JSON string.",
'EETen': "You are an expert in event extraction. Please extract event types and event trigger words from the input that conform to the schema definition. Return an empty list for non-existent events. Please respond in the format of a JSON string.",
'EEAen': "You are an expert in event argument extraction. Please extract event arguments and their roles from the input that conform to the schema definition, which already includes event trigger words. If an argument does not exist, return NAN or an empty dictionary. Please respond in the format of a JSON string.",
}
split_num_mapper = {'NER':6, 'RE':4, 'EE':4, 'EET':4, 'EEA':4}

import json

task = 'NER'
language = 'en'
schema = ['person', 'organization', 'else', 'location']
split_num = split_num_mapper[task]
split_schemas = [schema[i:i+split_num] for i in range(0, len(schema), split_num)]
input = '284 Robert Allenby ( Australia ) 69 71 71 73 , Miguel Angel Martin ( Spain ) 75 70 71 68 ( Allenby won at first play-off hole )'
sintructs = []
for split_schema in split_schemas:
sintruct = json.dumps({'instruction':instruction_mapper[task+language], 'schema':split_schema, 'input':input}, ensure_ascii=False)
sintructs.append(sintruct)

import torch
from transformers import (
AutoConfig,
AutoTokenizer,
AutoModelForCausalLM,
GenerationConfig
)
from peft import PeftModel

model_path = '/home/star/data/hsc/Baichuan-13B-Chat'
lora_path = 'lora/baichuan2-13b-iepile-lora'
config = AutoConfig.from_pretrained(model_path, trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)

model = AutoModelForCausalLM.from_pretrained(
model_path,
config=config,
device_map="auto",
torch_dtype=torch.bfloat16,
trust_remote_code=True,
)

model = PeftModel.from_pretrained(
model,
lora_path,
)
model.eval()

sintruct = "{\"instruction\": \"你是专门进行实体抽取的专家。请从input中抽取出符合schema定义的实体，不存在的实体类型返回空列表。请按照JSON字符串的格式回答。\", \"schema\": [\"姓名\", \"景点\", \"书名\", \"公司\", \"组织机构\", \"电影\"], \"input\": \"在新春佳节期间，游戏天堂联合全国9大城市34家名店进行王牌产品的促销活动，\"}"
sintruct = '<reserved_106>' + sintruct + '<reserved_107>'

input_ids = tokenizer.encode(sintruct, return_tensors="pt")
input_length = input_ids.size(1)
generation_output = model.generate(input_ids=input_ids, generation_config=GenerationConfig(max_length=512, max_new_tokens=256, return_dict_in_generate=True))
generation_output = generation_output.sequences[0]
generation_output = generation_output[input_length:]
output = tokenizer.decode(generation_output, skip_special_tokens=True)

print(output)
```

**Comment by guihonghao** [comment]
import torch前面的是数据处理过程，后面是推理代码
