### ISSUE TITLE
关于InstructionKGC-指令驱动的自适应知识图谱构建的问题

### ISSUE THREAD

**Issue by dasaffa** [zjunlp/DeepKE#443]
**想问一下，关于InstructionKGC-指令驱动的自适应知识图谱构建，第一步lora微调之后，再经过领域内数据训练之后，能够像原来那种使用模型的方式来使用这个微调后模型的功能吗？**

比如说，原来可以加载一个网页端或者命令行方式和本地部署的chatglm-6b对话，经过微调训练chatglm-6b的信息抽取能力之后，还能够加载一个网页端或者命令行的方式使用模型微调后的能力吗？
还是说 InstructionKGC-指令驱动的自适应知识图谱构建 这个项目微调完之后只能用来解决某个特定的信息抽取测试集任务。
![image](https://github.com/zjunlp/DeepKE/assets/75426990/fae5af5a-cd0f-44b5-b7e1-2accc146bb10)

**Comment by guihonghao** [comment]
你的意思是？微调后的模型既有抽取能力又有通用的对话能力？这需要在训练数据中增加通用语料，并且对于抽取数据进行下采样。

**Comment by dasaffa** [comment]
> 你的意思是？微调后的模型既有抽取能力又有通用的对话能力？这需要在训练数据中增加通用语料，并且对于抽取数据进行下采样。

只有抽取能力的话，我能用一个类似下面网页端界面来使用微调后模型抽取能力吗？
![image](https://github.com/zjunlp/DeepKE/assets/75426990/9b7cdd27-5357-4d3a-b85a-92afb1a23328)

**Comment by zxlzr** [comment]
您好，目前模型不具备通用能力，您想要通用能力需要使用通用数据（网上有很多公开的）混合训练。
