### ISSUE TITLE
模型之间的区别

### ISSUE THREAD

**Issue by chenzhongwu** [zjunlp/DeepKE#444]
请问
1. 本网址发布的llama2-13b-iepile-lora和llama-7b-lora-ie的区别只是基座模型不同么？微调的训练集是一致的么？
2. 我在复现llama-7b-lora-ie，进行IE任务时发现性能较差。输出内容基本和输入相同，无法完成任务，请问这是正常的么？
3. 我成功复现了在[https://github.com/zjunlp/KnowLM?tab=readme-ov-file]中发布的knowlm-13b-zhixi。请问knowlm-13b-zhixi和llama2-13b-iepile-lora的区别是什么？如果我想继续微调，knowlm-13b-zhixi和llama2-13b-iepile-lora的微调数据（或者说代码）是一致的么?
谢谢！！

**Comment by zxlzr** [comment]
1  基座和数据都不一样，llama2-13b-iepile-lora基于iepile训练，llama-7b-lora-ie基于处理过的instructie + 部分抽取数据 (使用的是老版本数据经过采样，和目前公开的数据有区别) 
2 请问您是否用了其他数据微调，可能是过拟合了
3 knowlm-13b-zhixi 是最早期的保留了通用能力的抽取大模型，经过了二次预训练 + 抽取指令微调 + 通用指令微调； llama2-13b-iepile-lora 只经过了抽取指令微调，数据是iepile 

我们算力有限，无法支持持续更新和优化大模型，非常抱歉

**Comment by guihonghao** [comment]
llama-7b-lora-ie的底座是llama-7b-base(https://huggingface.co/huggyllama/llama-7b)，使用的训练数据是instructie(https://huggingface.co/datasets/zjunlp/InstructIE中提到的train_zh_old.json)。
llama2-13b-iepile-lora的底座是llama2-13b-chat(https://huggingface.co/meta-llama/Llama-2-13b-chat-hf)，使用的训练数据是IEPile(https://huggingface.co/datasets/zjunlp/iepile)

**Comment by chenzhongwu** [comment]
感谢您的回复。
1. 请问knowlm-13b-zhixi 的pretrain训练的目标函数和目的是什么。
2. 我想在自己的数据上进行专业领域指令微调13b的模型，如果使用8张32GV100，请问一般要多少条数据比较合适，时间大概要多久，训练停止的标志是什么。
3. 本项目所有的抽取模型运行时需要提前指定关系范围，请问这是出于什么考虑？我测试了去掉上述限定，发现性能不佳，是否说明模型的开放抽取能力很一般。作者能否评论一下这一现象。
谢谢！

**Comment by zxlzr** [comment]
1.使用语言模型目标，下一个词预测。目的是加强中文和新知识能力，这个项目在开始启动的时候只有llama，llama中文能力较弱，且不具备2023年新发生的知识。
2. 数据要和通用的混着来训不然会导致通用能力下降，领域数据越大越好，质量要非常高不然反而会导致性能下降，如果算力足够可以一直训下去
3. 本模型不具备开放抽取能力，这个是封闭抽取设定，要指定类型的

**Comment by chenzhongwu** [comment]
我是否可以用开放抽取的语料微调模型，使其有一定的开放抽取能力。

**Comment by chenzhongwu** [comment]
我是否可以用开放抽取的语料微调模型，使其有一定的开放抽取能力。感觉封闭抽取实际用的时候怪怪的

**Comment by zxlzr** [comment]
这个肯定是可以的，您需要考虑下数据配比问题。

**Comment by chenzhongwu** [comment]
试起来成本太高了hh，你这有啥经验么

**Comment by zxlzr** [comment]
没太多经验，没有那么多卡去试验

**Comment by zxlzr** [comment]
您还有其它问题吗

**Comment by chenzhongwu** [comment]
谢谢
