### ISSUE TITLE
RE few-shot的论文复现结果

### ISSUE THREAD

**Issue by XiChen211** [zjunlp/DeepKE#447]
**Describe the question**
想请问一下RE few-shot中，按照所给步骤操作（即下载数据集SEMEVAL，运行run.py训练模型），运行predict.py后，得到的f1分数对应的是KnowPrompt论文哪个部分的结果，不知道复现的有没有问题。

**Environment (please complete the following information):**
 - Linux
 - Python 3.8.10

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![image](https://github.com/zjunlp/DeepKE/assets/129187011/196b7b72-a2f1-4e3a-ad68-9e8d3e307599)
![image](https://github.com/zjunlp/DeepKE/assets/129187011/d1f6955a-2710-46a2-8331-e7f139da0d3b)

**Comment by zxlzr** [comment]
您好，建议您使用knowprompt原始git https://github.com/zjunlp/KnowPrompt来复现，deepke开发这个模块的同学已经毕业了

**Comment by XiChen211** [comment]
> 您好，建议您使用knowprompt原始git https://github.com/zjunlp/KnowPrompt 来复现，deepke开发这个模块的同学已经毕业了
好的，谢谢您
