### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for LM:

### ISSUE THREAD

**Issue by fuqiang-benz** [zjunlp/DeepKE#449]
你好，我用的是DeepKE-cnSchema开箱即用版
python 3.9
torch 1.13.1 cpu版本
![image](https://github.com/zjunlp/DeepKE/assets/64388539/79169562-c9fb-4f9c-9c61-89fddb06d3aa)
![image](https://github.com/zjunlp/DeepKE/assets/64388539/5fb83a7b-5e67-4c7c-bbec-4526d806e89d)
我用的是这里两个模型进行关系抽取然后报错：
RuntimeError: Error(s) in loading state_dict for LM:
	size mismatch for fc.weight: copying a param with shape torch.Size([51, 100]) from checkpoint, the shape in current model is torch.Size([30, 100]).
	size mismatch for fc.bias: copying a param with shape torch.Size([51]) from checkpoint, the shape in current model is torch.Size([30]).
请问有什么解决办法吗？

还有个疑问 conf/embedding.yaml中num_relations 这个参数意义是什么，是关系的类别数吗？比如说我有关系15类，这个参数就要写15吗，写5会怎么样

**Comment by zxlzr** [comment]
您好，这是决定抽取多少关系的个数，数字不对可能会导致报错。

**Comment by fuqiang-benz** [comment]
> 您好，这是决定抽取多少关系的个数，数字不对可能会导致报错。
好的，我是按照你们官网下载的两个模型，现在问题感觉是模型和预训练模型结构不一致导致的，有什么好的解决办法吗，还是我得bert-base-chinese模型下载了

**Comment by xxupiano** [comment]
使用训练好的模型进行推理，不需要修改num_relations

**Comment by xxupiano** [comment]
请问是否将config.yaml中的model改为lm

**Comment by fuqiang-benz** [comment]
> 请问是否将config.yaml中的model改为lm？

已经解决了，感谢感谢
