### ISSUE TITLE
关于deep-llm实现信息抽取（RE）的问题

### ISSUE THREAD

**Issue by dasaffa** [zjunlp/DeepKE#450]
在使用百川模型和官方发布的lora权重基础上，在领域内数据继续训练时，能够去掉schema这个标签吗？也就是说不提供schema标签，也让模型能够从一段话中进行关系抽取。

**Comment by zxlzr** [comment]
您好，可以去掉，但不保证效果（没测试过），目前模型不支持没有schema的抽取。

**Comment by dasaffa** [comment]
> 您好，可以去掉，但不保证效果（没测试过），目前模型不支持没有schema的抽取。

好的谢谢
