### ISSUE TITLE
关于Cross-NER目标域前缀训练

### ISSUE THREAD

**Issue by RoKejk** [zjunlp/DeepKE#451]
**Describe the question**
请问Cross-NER在训练目标域的前缀时，会使用到目标域的正确标签和文本吗？这个模型能在未标注数据集上进行迁移任务吗？谢谢！

**Comment by njcx-ai** [comment]
您好，感谢您对我们DeepKE项目的关注。

因为跨域NER的任务设定就是源域是资源丰富的而目标域是低资源的，本项目的Paper所对应的CP-NER方法在训练目标域的前缀时，会使用到目标域的正确标签和文本。这个生成式模型能在未标注数据集上进行迁移任务，但效果尚未可知，您可以标注个几十条数据即可更好地实现迁移。

祝好！

**Comment by RoKejk** [comment]
感谢回复
请问目标域切分为train，dev，test以后，训练前缀时是只需要用train的数据吗，还是都需要使用？谢谢

**Comment by njcx-ai** [comment]
您好，训练前缀时是只用到train的数据。

**Comment by zxlzr** [comment]
请问您还有其他问题吗

**Comment by RoKejk** [comment]
感谢回复，没有其他问题了
