### ISSUE TITLE
csv转化为JSON问题

### ISSUE THREAD

**Issue by kkkenshi** [zjunlp/DeepKE#452]
**Describe the question**
> A clear and concise description of what the question is.
我想在自己的数据集csv转化为json数据格式训练，目前想写个脚本完成数据转换。
但在json数据格式中，text和token、和entity键好理解，其他的该如何处理呢？
研一小白，谢谢解答！

**Comment by BeasterYong** [comment]
您好，可否看一下原本的csv数据格式和期望转成的json数据格式？

**Comment by BeasterYong** [comment]
relation字段表示实体之间的关系信息，event字段表示文本中描述的事件，asoc字段表示实体附加信息，上述字段一般置为空。record字段使用编码模式记录识别出的实体及其类型，其中<extra_id_0> 为开始标志，<extra_id_1>为结束标志，<extra_id_5> 为实体和标签的分隔符。spot字段代表文本中的各个标签（也就是各个实体所属的类别）；spot_asoc字段则把实体和标签相关联。

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
