### ISSUE TITLE
环境配置与模型量化

### ISSUE THREAD

**Issue by HuiGe88** [zjunlp/DeepKE#454]
您好，我的显存只有12G，关于本项目我有以下几个问题：

1、该项目能否在windows系统上成功运行；
2、对于deepke，我的显存配置能否运行，如果可以，我需要修改哪些参数；
3、对于DeepKE-LLM，我如果想要在12G的显存下运行，是否需要将基础模型更换为量化的模型，例如将llama2-13b-chat更换为4bit量化后的模型，这样能否运行成功，还需要修改哪些参数；

非常感谢您百忙之中抽空回答我的问题，谢谢

**Comment by zxlzr** [comment]
1. 可以windows运行，前提是您可以成功安装所有依赖包，根据先前很多issue发现windows情况下出现有部分包无法正确安装的情况，可能是windows对部分python包存在兼容性问题，我们之前默认测试都是在linux下进行的
2. deepke 非大模型版本12g可以运行，您需要按照非大模型版本readme安装https://github.com/zjunlp/DeepKE?tab=readme-ov-file#manual-environment-configuration 
3. deepke-llm版本显存不太够用，这里一般大模型都是7b的，您需要对模型进行量化后才可以运行，但量化后性能一般都会下降。

**Comment by zxlzr** [comment]
请问您是否还有其他问题？

**Comment by HuiGe88** [comment]
暂时没有了，谢谢您
