### ISSUE TITLE
项目所用算法

### ISSUE THREAD

**Issue by HuiGe88** [zjunlp/DeepKE#455]
您好，我想请问DeepKE中实现NER、RE任务用的是哪些模型或者算法

**Comment by zxlzr** [comment]
您好，deepke实现ner支持bilstm, bert, lightner等, re支持传统的cnn rnn transformer 以及预训练语言模型如bert等； 详细模型在readme里均有介绍。

**Comment by HuiGe88** [comment]
好的，非常感谢您的解答

**Comment by zxlzr** [comment]
请问您是否还有其他问题？

**Comment by HuiGe88** [comment]
暂时没有了，谢谢
