### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by HuiGe88** [zjunlp/DeepKE#456]
您好，我在运行 ner/standard/ 下的run_bert.py文件时出现以下错误，请问这是什么意思？

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by xxupiano** [comment]
您好，请截一下完整的报错截图，谢谢

**Comment by xxupiano** [comment]
您好，请截一下所有报错，不仅是warning

**Comment by xxupiano** [comment]
请问hydra-core版本是1.0.6吗

**Comment by wpx0114** [comment]
> 请问hydra-core版本是1.0.6吗

您好！之前的hydra-core版本是1.3.2，现在换为1.0.6之后已经成功运行了！谢谢
