### ISSUE TITLE
想要在原程序的基础上做成前端VUE界面，请求指导！

### ISSUE THREAD

**Issue by pangpangDD** [zjunlp/DeepKE#457]
您好！
想在原有基础上console输出进度，改造成前端vue界面显示
想请教下原程序的**console界面日志输出方法函数是哪个？**我想针对性的把数据写在接口里，传参给前端进行展示，这种方法可取吗？

**Comment by zxlzr** [comment]
您好，会有开发同学尽快回复您

**Comment by BeasterYong** [comment]
您好，请问您具体想要呈现哪些输出？可以看一下例子吗？

**Comment by pangpangDD** [comment]
您好，非常感谢，需要以下显示输出：
1.运行DeepKE-main\example\ner\standard\run_bert.py文件后，训练过程的实时输出，如：
![image](https://github.com/zjunlp/DeepKE/assets/58252967/4e4261ae-bea4-49d1-8033-73960ffa2aca)
2.运行DeepKE-main\example\ner\standard\predict.py文件后，预测结果的显示，如：
![image](https://github.com/zjunlp/DeepKE/assets/58252967/90b6699f-2439-4111-abf3-1c2650c37043)

**Comment by BeasterYong** [comment]
您好，run_bert.py中的训练输出是tqdm()函数，predict.py中的输出是print()函数，建议您对应具体文件分别定位~

**Comment by pangpangDD** [comment]
> 您好，run_bert.py中的训练输出是tqdm()函数，predict.py中的输出是print()函数，建议您对应具体文件分别定位~
谢谢啦~ DeepKE-main\example\re\standard下 run.py和predict.py函数也是一样吗~

**Comment by BeasterYong** [comment]
> 函数

您好，组织结构类似的代码中的输出函数应该都是一样的

**Comment by pangpangDD** [comment]
好的谢谢您~

**Comment by pangpangDD** [comment]
不好意思！我在 DeepKE-main\example\re\standard下 run.py 中没有找到tqdm()函数，您能帮忙再看看吗？十分感谢！

**Comment by BeasterYong** [comment]
您好，这里的输出是logger和wandb，总体来说没有固定单一的输出函数，建议您阅读代码之后对应具体文件分别定位~如果您只想获取输出可以使用输出重定向操作

**Comment by BeasterYong** [comment]
您好，这里的输出是logger和wandb。项目中没有固定单一的输出函数，建议您阅读代码之后对应具体文件分别定位~ 如果您只想获取输出，可以使用输出重定向操作。

**Comment by BeasterYong** [comment]
> 不好意思！我在 DeepKE-main\example\re\standard下 run.py 中没有找到tqdm()函数，您能帮忙再看看吗？十分感谢！

您好，在run.py文件中是通过logger和wandb输出的。本项目中并没有统一的输出函数，建议您阅读源码并根据具体代码定位输出函数。如果您仅需获取输出，可以通过输出重定向来获取。

**Comment by zxlzr** [comment]
请问还有其他问题吗？
