### ISSUE TITLE
使用 BERT 语言预训练的时候，要如何加载预训练模型呢 

### ISSUE THREAD

**Issue by ly886** [zjunlp/deepke#46]
我使用的是https://github.com/ymcui/Chinese-BERT-wwm#%E4%B8%AD%E6%96%87%E6%A8%A1%E5%9E%8B%E4%B8%8B%E8%BD%BD
上的BERT-wwm, Chinese 放在了 pretrained文件夹下，不知道如何启用，使用LM模型启动时，加载不到其必须的文件。

**Comment by yuwl798180** [comment]
你好，可以看下里面的 readme.md 具体介绍。

**Comment by ly886** [comment]
解决了，需要将下载的文件内容，更名为readme.md中的形式才能被正常读取。
