### ISSUE TITLE
cross-ner Similarity问题

### ISSUE THREAD

**Issue by kkkenshi** [zjunlp/DeepKE#462]
请问代码中哪里可以看到Entity Similarity相关部分呢？

**Comment by flow3rdown** [comment]
您好，Entity Similarity在[此处](https://github.com/zjunlp/DeepKE/blob/785d795807a3ab286955770105bf8f9d4a944537/src/deepke/name_entity_re/cross/seq2seq/models.py#L305-L314)实现

**Comment by kkkenshi** [comment]
没有了谢谢解答
