### ISSUE TITLE
关于三元组SPO的提取问题

### ISSUE THREAD

**Issue by delicate00** [zjunlp/DeepKE#463]
请问下作者llm部分三元组提取也同旧版传统deepke一样是实体和关系的两步提取吗，可以支持上传文档，可以实现对大量文档抽取吗？

**Comment by zxlzr** [comment]
您好大模型llm可以直接一步抽取实体和关系，可以直接输入文档抽取，但文档太长会被截断，目前不支持太长的文档。我们近期会发布新的抽取模型。目前总体上大模型抽取效果仍存在很大的改进空间。

**Comment by delicate00** [comment]
> 您好大模型llm可以直接一步抽取实体和关系，可以直接输入文档抽取，但文档太长会被截断，目前不支持太长的文档。我们近期会发布新的抽取模型。目前总体上大模型抽取效果仍存在很大的改进空间。

之前是打算对比下大模型抽取和deepke-llm的抽取效果的，后续也会继续研究下deepke-llm，感谢您的解答

**Comment by delicate00** [comment]
作者你好，我昨天尝试了一下“example/llm/LLMICL”，run.yaml配置文件如下：
task: "ner"                 # [ner, re, ee, rte, da]
language: "ch"                # ["en", "ch"]
engine: "gpt-3.5-turbo"    # ["text-davinci-003", "text-curie-001", "text-babbage-001", "text-ada-001"]
api_key: "sk-"
#text_input: "历经4小时51分钟的体力、意志力鏖战，北京时间9月9日上午纳达尔在亚瑟·阿什球场，以7比5、6比3、5比7、4比6和6比4击败赛会5号种子俄罗斯球员梅德韦杰夫，夺得了2019年美国网球公开赛男单冠军。"
text_input: "《没有你的夜晚》是歌手欧阳菲菲演唱的歌曲，出自专辑《拥抱》"
zero_shot: True
instruction: None
data_path: ""
domain: ""
labels: None   # ['PER', 'ORG', 'LOC']
head_type: ""
head_entity: ""
tail_type: ""
tail_entity: ""

接着直接运行“example/llm/LLMICL/run.py”，我执行除了“re”以外的任务，显示的结果都如下图所示，是我哪一步操作有误吗？还是说只能执行关系抽取任务呀？
![image](https://github.com/zjunlp/DeepKE/assets/110662274/b916b629-fd21-4869-ad04-71ab4d96b7fc)

**Comment by delicate00** [comment]
还是说是我未使用提示词的原因

**Comment by delicate00** [comment]
已经解决了，是我提示词的原因，之前的提示词模板没有设置
