### ISSUE TITLE
Deepke-LLM是否支持模型并行

### ISSUE THREAD

**Issue by thunderingswolf** [zjunlp/DeepKE#466]
关于deepke-llm，目前验证应该是支持的数据并行方式，请问是否支持模型并行？

问题现状是： 
1. Lora微调chatglm3-6b
2. 单条指令数据平均长度大于8k
3. bitch_size=1 单卡（24G）也装不下模型，提示CUDA分配不足
4. 目前没有更大显存的单卡了

请问是否支持/或者后续是否支持模型并行？  或者有没有其他更好的使用方式？

**Comment by guihonghao** [comment]
你可以尝试使用 --deepspeed configs/ds_config_bf16.json 参数(stage 2)。
stage 3的配置是
```json
{
    "bf16": {
        "enabled": "auto"
    },
    "optimizer": {
    "type": "AdamW",
        "params": {
            "lr": "auto",
            "betas": "auto",
            "eps": "auto",
            "weight_decay": "auto"
        }
    },
    "scheduler": {
        "type": "WarmupDecayLR",
        "params": {
            "total_num_steps": "auto",
            "warmup_min_lr": "auto",
            "warmup_max_lr": "auto",
            "warmup_num_steps": "auto"
        }
    },
    "zero_optimization": {
        "stage": 3,
        "overlap_comm": true,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },
        "contiguous_gradients": true,
        "sub_group_size": 1e9,
        "reduce_bucket_size": 5e8,
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_gather_16bit_weights_on_model_save": true
    },
    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 2000,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
}
```

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by thunderingswolf** [comment]
感谢，已开始按提供方案重新微调

**Comment by zxlzr** [comment]
您要是有任何其他问题欢迎随时提issue

**Comment by thunderingswolf** [comment]
更新master分支，使用--deepspeed configs/ds_config_bf16_stage3.json 出现异常，请帮忙看看

配置如下：
硬件：2片A10

![image](https://github.com/zjunlp/DeepKE/assets/18439007/cafc921e-6941-4722-b0d4-d53ee6753d12)


异常日志：
![image](https://github.com/zjunlp/DeepKE/assets/18439007/63e4a0b5-dc3e-4784-b2af-74cd45c94297)

**Comment by thunderingswolf** [comment]
当配置--deepspeed configs/ds_config_bf16_stage2.json 正常

**Comment by guihonghao** [comment]
去掉ds_config_bf16_stage3.json 里面的"offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },试试

**Comment by thunderingswolf** [comment]
> 去掉ds_config_bf16_stage3.json 里面的"offload_optimizer": { "device": "cpu", "pin_memory": true },试试
 去掉后运行目测没问题了（走过之前报错的阶段）

**Comment by thunderingswolf** [comment]
> 去掉ds_config_bf16_stage3.json 里面的"offload_optimizer": { "device": "cpu", "pin_memory": true },试试
请教： 是因为内存太小？ 去掉后降低GPU占用的效果上，会有什么影响呢？

**Comment by guihonghao** [comment]
优化器卸载到CPU上，可能导致张量在不同的设备上，从而报错

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by thunderingswolf** [comment]
> 请问您还有其他问题吗？

感谢支持
