### ISSUE TITLE
运行之后出现链接超时，但网络正常

### ISSUE THREAD

**Issue by chengmeng0** [zjunlp/DeepKE#468]
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/vocab.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000201FA680610>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/bert-base-uncased/resolve/main/vocab.txt
出现上面的错误，但我没有找到修改url的地方

**Comment by zxlzr** [comment]
您好，您可以手动下载到本地，hf 需要科学上网或使用代理

**Comment by zxlzr** [comment]
请问您的问题解决了吗

**Comment by zxlzr** [comment]
您要是有任何问题欢迎提issue。

**Comment by chengmeng0** [comment]
没有解决，我把config.json、vocab.txt下载到本地还是出现相同的错误

**Comment by chengmeng0** [comment]
> 您要是有任何问题欢迎提issue。
没有解决，我把config.json、vocab.txt下载到本地还是出现相同的错误

**Comment by chengmeng0** [comment]
> 请问您的问题解决了吗

问题已解决
