### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\m1879/.cache\\huggingface\\hub\\models--bert-base-chinese\\refs\\main'

### ISSUE THREAD

**Issue by Fuuto-Joker** [zjunlp/DeepKE#469]
您好，我在按照readme的步骤操作，在运行DeepKE\example\re\standard\run.py时出现错误：
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-chinese/resolve/main/vocab.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002C335994D30>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/bert-base-chinese/resolve/main/vocab.txt
Traceback (most recent call last):
  File "C:\Users\m1879\Desktop\PythonProjects\DeepKE\example\re\standard\run.py", line 63, in main
    preprocess(cfg)
  File "C:\Users\m1879\Desktop\PythonProjects\DeepKE\src\deepke\relation_extraction\standard\tools\preprocess.py", line 208, in preprocess
    _lm_serialize(train_data, cfg)
  File "C:\Users\m1879\Desktop\PythonProjects\DeepKE\src\deepke\relation_extraction\standard\tools\preprocess.py", line 120, in _lm_serialize
    tokenizer = BertTokenizer.from_pretrained(cfg.lm_file)
  File "C:\Users\m1879\anaconda3\envs\deepke\lib\site-packages\transformers\tokenization_utils_base.py", line 1763, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "C:\Users\m1879\anaconda3\envs\deepke\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\m1879\anaconda3\envs\deepke\lib\site-packages\huggingface_hub\utils\_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\m1879\anaconda3\envs\deepke\lib\site-packages\huggingface_hub\file_download.py", line 1148, in hf_hub_download
    with open(ref_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\m1879/.cache\\huggingface\\hub\\models--bert-base-chinese\\refs\\main'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
请问这是否可以通过下载抱抱脸上的bert-base-chinese中的文件解决？如果不行，应该如何操作？

**Comment by zxlzr** [comment]
您好，您可以通过代理https://hf-mirror.com/，或下载到本地解决，注意windows下路径和linux下有区别，您需要check下路径下模型文件是否存在。

**Comment by orangeper** [comment]
> 您好，您可以通过代理https://hf-mirror.com/ ，或下载到本地解决，注意windows下路径和linux下有区别，您需要check下路径下模型文件是否存在。

请问下载后具体怎么操作呢，将config.json、pytorch_model.bin、vocab.txt放入pretrained文件夹下面之后，lm.yaml这个文件中的lm相关路径应该怎么修改呢，多谢

**Comment by xxupiano** [comment]
您好，路径斜杠统一C:\Users\m1879/.cache\huggingface\hub\models--bert-base-chinese\refs\main，存在/和\混用，win环境请使用双斜杠\\

**Comment by orangeper** [comment]
> 您好，路径斜杠统一C:\Users\m1879/.cache\huggingface\hub\models--bert-base-chinese\refs\main，存在/和\混用，win环境请使用双斜杠\\

谢谢您的解答，能具体说明怎么解决这个报错问题吗，我下载了上述三个文件，并放到了pretrained目录下，后续应该修改哪个地方才能解决这个报错呢，麻烦您了

**Comment by orangeper** [comment]
问题已解决，修改lm.yaml文件中的lm_file: '......\\DeepKE\\pretrained'，......替换为DeepKE的存放路径

**Comment by chengmeng0** [comment]
> 问题已解决，修改lm.yaml文件中的lm_file: '......\DeepKE\pretrained'，......替换为DeepKE的存放路径

<img width="383" alt="a1c98ec70176c66ec095e5daf5d7f69d" src="https://github.com/zjunlp/DeepKE/assets/110447206/fa90f7fc-2134-4722-bf79-81dc7e908aee">
您好，我把lm.yaml改为DeepKE的路径，显示无法加载，请问您是怎么操作的呢
<img width="1038" alt="6326831a89425bc61c79716db6869018" src="https://github.com/zjunlp/DeepKE/assets/110447206/2687846e-3cc1-4c82-ba37-f972c45ba1d7">

**Comment by qixiaonan1** [comment]
> 问题已解决，修改lm.yaml文件中的lm_file: '......\DeepKE\pretrained'，......替换为DeepKE的存放路径

您好，我也遇到了这个问题，按照您的方法修改之后仍然报错，请问在下载文件夹之后，您将lm.yaml的内容具体是如何修改的？？

**Comment by orangeper** [comment]
> > 问题已解决，修改lm.yaml文件中的lm_file: '......\DeepKE\pretrained'，......替换为DeepKE的存放路径
> 
> 您好，我也遇到了这个问题，按照您的方法修改之后仍然报错，请问在下载文件夹之后，您将lm.yaml的内容具体是如何修改的？？

只修改lm_file的内容为
lm_file: '......\DeepKE\pretrained'，......替换为DeepKE的存放路径，冒号后有一个空格，lm_file的内容不用修改，去掉前面的注释符号
