### ISSUE TITLE
请问，要做一个接口的话，应该怎么传入数据到predict中呢？

### ISSUE THREAD

**Issue by WHL853087305** [zjunlp/deepke#47]
**Describe the question**
> A clear and concise description of what the question is.
您好，如果我想做一个接口用于测试的话，应该怎么应用呢？因为对hydra不熟，麻烦大神指点指点！

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by yuwl798180** [comment]
你好，模型训练完成后通过保存模型就可以运行测试了。
目前tensorflow有封装比较好的serving服务可以很方便的实现线上调用，pytorch也有serving，不过我没用过，不知道性能如何。
另外之后等写完毕业论文后，会更新下版本，将一些predict/serving功能都完善。
