### ISSUE TITLE
联合三元组抽取编码问题

### ISSUE THREAD

**Issue by chengmeng0** [zjunlp/DeepKE#473]
Traceback (most recent call last):
  File "E:\Python\DeepKE-main\example\triple\cnschema\predict.py", line 42, in main
    data = f.readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa7 in position 15: illegal multibyte sequence

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
运行triple中的predict.py 出现以上报错，请问在哪文件修改编码呢？

**Comment by zxlzr** [comment]
您好，您可以网上搜索上如何修改文件的编码，报错的意思是文件编码和python代码的f.readlines()不一致。

**Comment by chengmeng0** [comment]
好的，已经解决
