### ISSUE TITLE
请问能用vllm或者sglang部署oneke后端么

### ISSUE THREAD

**Issue by EvilCalf** [zjunlp/DeepKE#476]
如题，使用的版本是什么

**Comment by guihonghao** [comment]
你好，可以使用vllm部署oneke，我们使用的是vllm==0.2.1、xformers==0.0.22、flash_attn==2.0.1

**Comment by EvilCalf** [comment]
The conflict is caused by:
    The user requested torch==2.0.0
    accelerate 0.21.0 depends on torch>=1.10.0
    peft 0.4.0 depends on torch>=1.13.0
    vllm 0.2.1 depends on torch==2.0.1
需求的版本不匹配额

**Comment by guihonghao** [comment]
你需要把 torch升级到2.0.1

**Comment by EvilCalf** [comment]
能麻烦提供一个完整的requirements么，因为发现transformer等一系列的都需要升级

**Comment by guihonghao** [comment]
accelerate==0.29.3
bitsandbytes==0.39.0
datasets==2.19.0
deepspeed==0.14.1
flash-attn==0.2.6.post1
numpy==1.23.1
peft==0.4.0
scipy==1.9.1
tiktoken==0.6.0
torch==2.0.1
transformers==4.33.0
transformers-stream-generator==0.0.5
triton==2.0.0
tritonclient==2.44.0
vllm==0.2.1
xformers==0.0.22

**Comment by EvilCalf** [comment]
额不好意思
`
The conflict is caused by:
    The user requested transformers==4.33.0
    peft 0.4.0 depends on transformers
    transformers-stream-generator 0.0.5 depends on transformers>=4.26.1
    vllm 0.2.1 depends on transformers>=4.34.0
`

**Comment by guihonghao** [comment]
你好，我们使用云服务器训练推理，具体为什么会有冲突，我们也不知道。你可以参考vllm官网教程实现vllm的部署。https://github.com/vllm-project/vllm

**Comment by EvilCalf** [comment]
非常感谢，能麻烦提供一个知识图谱提取，使用openai api格式的message 样例么
