### ISSUE TITLE
re类模型中，lm模型处理头实体和尾实体的逻辑是什么？

### ISSUE THREAD

**Issue by thetaaaaa** [zjunlp/DeepKE#479]
**Describe the question**
> A clear and concise description of what the question is.
在关系抽取re类模型中，用例包含lm模型，想请教一下老师这个模型处理头实体和尾实体的逻辑是什么，因为我查看LM源代码时似乎没有找到处理head和tail变量的代码，但是其他几个模型都有。谢谢老师们！

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.
图为我所查看到的LM模型源码，没有找到处理头实体和尾实体的部分。这似乎只是一个文本分类的代码。
![image](https://github.com/zjunlp/DeepKE/assets/66288540/fa605a2c-cb23-44a3-9dbf-3254a0151ecf)

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
您好，关系抽取就是一个分类问题，模型架构没有大的变化，使用bert做关系抽取会在头尾实体加上特殊字符标识实体位置，参见论文https://aclanthology.org/P19-1279.pdf
