### ISSUE TITLE
web demo

### ISSUE THREAD

**Issue by holidaycuki** [zjunlp/DeepKE#481]
**Describe the question**
> A clear and concise description of what the question is.

实体提取的可以在web端运行吗

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by holidaycuki** [comment]
OneKE 实体抽取可以在web端运行吗？

**Comment by zxlzr** [comment]
您好，OneKE是大模型，我们没有计算资源部署在线web服务，抱歉。
