### ISSUE TITLE
ner可以抽哪些类别，可以列举出来吗

### ISSUE THREAD

**Issue by holidaycuki** [zjunlp/DeepKE#482]
**Describe the question**
> A clear and concise description of what the question is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
您好，ner的训练数据里有什么类别（如人名、地名等），就可以抽取这些类别。

**Comment by holidaycuki** [comment]
我想做一个前端的页面，就是把所有的类别就列举出来，按钮点击哪个类别，就抽哪个类别，这个可以实现吗

**Comment by holidaycuki** [comment]
目前我只用推理的脚本

**Comment by zxlzr** [comment]
您可以让模型抽取所有的实体类型，在前端写一个控制逻辑，按一下不同实体类型的按钮来展示不同类型的实体内容就可以。

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by tianchiguaixia** [comment]
> 我想做一个前端的页面，就是把所有的类别就列举出来，按钮点击哪个类别，就抽哪个类别，这个可以实现吗

大模型就行
