### ISSUE TITLE
如何提取所有可能存在的三元组

### ISSUE THREAD

**Issue by qixiaonan1** [zjunlp/DeepKE#483]
**Describe the question**
> A clear and concise description of what the question is.
请问在现有的您提供的代码中，我是否可以给定一段话，但是没有给定的schema，能否实现提取出我给定的段落中所有可能的三元组呢，如果可以我该如何实现呢？

**Comment by zxlzr** [comment]
您好，您说的是开放抽取openie，deepke暂时不支持开放抽取，抱歉。
