### ISSUE TITLE
进行预测时，可以使用多张GPU加载模型吗？

### ISSUE THREAD

**Issue by yjh-Coder** [zjunlp/DeepKE#484]
**Describe the question**
> 想使用多张GPU加载OneKE模型，但是均无效
CUDA_VISIBLE_DEVICES=0,1 或者CUDA_VISIBLE_DEVICES="0,1"  inference.py

**Environment (please complete the following information):**
 - OS: [ubuntu]
 - Python Version [e.g. 3.10]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by guihonghao** [comment]
你好，目前我们的代码不支持多张卡加载模型。

**Comment by MikeDean2367** [comment]
您好，您可以使用[KnowLM](https://github.com/zjunlp/knowlm)的代码在网页上进行推理，执行：
```bash
CUDA_VISIBLE_DEVICES=0,1 python examples/generate_lora_web.py --base_model zjunlp/oneke --multi_gpu --allocate [16,16] --model_tag zhixi
```
其中`--allocate [16,16]`表示两张显卡在加载模型时候的峰值显存位16GB。您可以设置--allocate的值来进行多张卡的推理。

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
