### ISSUE TITLE
cfg配置问题

### ISSUE THREAD

**Issue by XiChen211** [zjunlp/DeepKE#489]
**Describe the question**
> A clear and concise description of what the question is.

这是re-standard中preprocess.py的部分代码，我想更改这里的cfg.lm_file的路径为我本地的，但是我在config.yaml下并没有找到lm_file的配置，我打印cfg内容显示被默认配置成了bert-base-chinese，在config.yaml中加入lm_file路径也没有用，请问要在哪里更改这个配置啊

**Screenshots**
> If applicable, add screenshots to help explain your problem.

![image](https://github.com/zjunlp/DeepKE/assets/129187011/6caa4e06-91e6-4a94-9be0-6b75c8881f79)
![image](https://github.com/zjunlp/DeepKE/assets/129187011/fa5bffa1-d6cb-42c2-af99-6ad4763674a3)
![image](https://github.com/zjunlp/DeepKE/assets/129187011/25e2c830-86f1-48b7-b09b-26b1e3fa18ba)

**Comment by BeasterYong** [comment]
您好，配置路径为`example/re/standard/conf/model/lm.yaml`文件中的`lm_file`，将其修改为本地模型文件存储路径即可

**Comment by zxlzr** [comment]
请问您的问题解决了吗？

**Comment by XiChen211** [comment]
您好非常感谢，已经解决了
