### ISSUE TITLE
您好，请问bert模型为什么没有了，模型里面没找到bert

### ISSUE THREAD

**Issue by zbelieve** [zjunlp/deepke#49]
**Describe the question**
> A clear and concise description of what the question is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by yuwl798180** [comment]
你好，bert模型有的呀，在models/lm.py就是的，lm是language model的缩写

**Comment by zbelieve** [comment]
好的，谢谢您，想再问一个问题，就是bilstm那个原文里面attention，我看代码怎么没有体现呢
