### ISSUE TITLE
cnschema运行问题

### ISSUE THREAD

**Issue by HuiGe88** [zjunlp/DeepKE#491]
您好，我在使用cnschema进行预测时遇到以下报错：
RuntimeError: Error(s) in loading state_dict for BertNer:
	size mismatch for classifier.weight: copying a param with shape torch.Size([60, 768]) from checkpoint, the shape in current model is torch.Size([2, 768]).
	size mismatch for classifier.bias: copying a param with shape torch.Size([60]) from checkpoint, the shape in current model is torch.Size([2]).

我下载了readme中所说的ner模型checkpoint_bert，其中有一个model.json文件中，bert_model我是这样配置的，不知道对不对，
"bert_model": "C:\\Models\\DeepKE\\pretrained\\chinese-bert-wwm"
这是我本地下载的bert模型的路径

**Comment by BeasterYong** [comment]
您好，请参照Readme中的教程，将模型文件夹重命名为checkponits即可

**Comment by zxlzr** [comment]
请问您的问题是否已解决？
