### ISSUE TITLE
有关example中few_shot_cn场景下的NER任务中数据集的问题

### ISSUE THREAD

**Issue by HIT-Rhino** [zjunlp/DeepKE#493]
按照readme中的指示下载的数据集只有conll2003 mit-movie mit-restaurant 和 atis
但是few_shot_cn中代码要求的数据集好像是cluener2020
![屏幕截图 2024-05-06 215422](https://github.com/zjunlp/DeepKE/assets/47494536/d6fc737b-868e-44f5-ba42-276e738492d7)

**Comment by njcx-ai** [comment]
您好，非常感谢您对我们项目的关注。我们代码里对conll2003 mit-movie mit-restaurant 和 atis都是支持的哈，并额外支持了cluener2020，并不会影响您的使用哈。
。

**Comment by HIT-Rhino** [comment]
感谢回复，所以针对few_shot_cn，本项目没有提供相应的数据集吗？

**Comment by zxlzr** [comment]
cluener2020是中文数据集

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by HIT-Rhino** [comment]
能提供一下cluener2020的下载地址吗？不胜感激

**Comment by njcx-ai** [comment]
您可以参考CLUENER2020的官方github项目下载对应数据：https://github.com/CLUEbenchmark/CLUENER2020

**Comment by HIT-Rhino** [comment]
好的，非常感激贵组的帮助！
