### ISSUE TITLE
请问内置的预训练模型具体是什么

### ISSUE THREAD

**Issue by Sugaraqua** [zjunlp/DeepKE#494]
**Describe the question**
> A clear and concise description of what the question is.
您好，请问DeepKE中内置的这几种预训练模型具体是什么模型。我知道lm是谷歌的bert-base-chinese，其他的cnn、rnn等具体是什么模型呢？

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![image](https://github.com/zjunlp/DeepKE/assets/147385402/db6066b6-67dd-468c-99aa-1eb76fc6bf63)

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
您好，cnn具体的模型是卷积神经网络，rnn具体模型是循环神经网络，具体实现在代码里都有的。

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by Sugaraqua** [comment]
谢谢，我已在另一个issue中看到你的回答，这些都是使用的相关标准模型而非改版。
