### ISSUE TITLE
超过512就会报错。

### ISSUE THREAD

**Issue by tianchiguaixia** [zjunlp/DeepKE#495]
使用案例：DeepKE训练关系抽取时候，如果输入文本长度超过512就会报错。这个希望加一个后处理功能，超过512的，进行分段抽取再汇总返回结果。而不是报错。
![image](https://github.com/zjunlp/DeepKE/assets/29837553/26f1085c-8b86-474a-9ec4-d8290039e3af)

**Comment by zxlzr** [comment]
感谢您的建议。

**Comment by tianchiguaixia** [comment]
可以参考阿里的RexUniNLU.因为现实文本，文献很多长度超了。希望添加这个功能，不止文本长度。靠模分段处理，最后合并

**Comment by zxlzr** [comment]
谢谢

**Comment by BeasterYong** [comment]
您好，项目现已支持长文本关系抽取，更新至最新版本即可~

**Comment by BeasterYong** [comment]
如果还遇到其它问题，欢迎继续向我们反馈！

**Comment by tianchiguaixia** [comment]
牛逼，我现在就拿这个去跑标准数据集看看效果
