### ISSUE TITLE
RE standard 是否有论文参考

### ISSUE THREAD

**Issue by Bibaba-King** [zjunlp/DeepKE#496]
CNN
RNN
Capsule
GCN (Based on the paper ["Graph Convolution over Pruned Dependency Trees Improves Relation Extraction"]
Transformer
Pre-trained Model (BERT)

由于只有一个模型给出了参考文献，想问一下别的模型有相关的参考文献吗？

**Comment by zxlzr** [comment]
你好，CNN就是标准CNN，RNN也是标准RNN，您可以理解成直接使用CNN、RNN、Capsule、BERT等模型做分类（关系抽取任务），参考论文有（论文方法一般都会在标准模型上加一些改进的创新改进，因此和deepke的代码不完全一致）：

 Attention-based convolutional neural network for semantic relation extraction

Relation classification via recurrent neural network

Attention-Based Capsule Networks with Dynamic Routing for Relation Extraction

Matching the Blanks: Distributional Similarity for Relation Learning

**Comment by Bibaba-King** [comment]
感谢提供的参考文献！



发自我的iPhone
