### ISSUE TITLE
二次训练数据集

### ISSUE THREAD

**Issue by snowstormer** [zjunlp/DeepKE#498]
**Describe the question**
> A clear and concise description of what the question is.
请问对模型进行二次训练，对数据集格式有什么具体要求吗？我看文档中提到可以用doccano标注数据，可以之间使用不需要预处理吗？

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
您好，您可以按deepke里提供的示例数据进行训练。

**Comment by snowstormer** [comment]
> 您好，您可以按deepke里提供的示例数据进行训练。

哦哦好的，谢谢
