### ISSUE TITLE
OneKE在未来是否考虑推出llama3版本

### ISSUE THREAD

**Issue by ninghairong** [zjunlp/DeepKE#499]
作者您好，请问OneKE在未来是否考虑推出基于llama3训练的版本

**Comment by zxlzr** [comment]
您好 llama3 模型（非chinese版本）的lora权重已开源https://huggingface.co/zjunlp/llama3-8b-iepile-lora   受算力影响，会看情况持续改进发布OneKE新版本

**Comment by ninghairong** [comment]
感谢！
