### ISSUE TITLE
想请教一下作者，bilstm那个原文里面attention，我看代码怎么没有体现呢

### ISSUE THREAD

**Issue by zbelieve** [zjunlp/deepke#50]
**Describe the question**
> A clear and concise description of what the question is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by yuwl798180** [comment]
嗯嗯，是的，没有加attention
如果你需要加的话，可以在模型中引入 module文件里的attention层

ps：当前现在的multi attention效果更好一些，pytorch原生自带的就可以运行，你可以自行添加。

**Comment by zbelieve** [comment]
好的，谢谢您指导
