### ISSUE TITLE
您好，请问关系抽取（全监督）任务采用的是管道模型还是联合模型

### ISSUE THREAD

**Issue by Sugaraqua** [zjunlp/DeepKE#500]
**Describe the question**
> A clear and concise description of what the question is.
您好，请问关系抽取任务（全监督）采用的是管道模型还是联合模型？在常规全监督关系抽取中需要手动输入头尾实体，应该是属于管道模型吧？另外请问该任务解码方式是哪种？基于序列标注、基于指针网络或是基于片段分类？劳烦解惑，不胜感激。

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
1 目前deepke支持管道和联合模型见https://github.com/zjunlp/DeepKE/tree/main/example/triple

2 常规关系抽取是分类任务，不知道您说的解码是什么意思

3 序列标注目前按论文方法实现的，支持基本序列标注如基于bert 和lstm，同时支持Unified Named Entity Recognition as Word-Word Relation Classification论文

如有任何其他问题可随时问

**Comment by zxlzr** [comment]
请问您还有其他问题吗

**Comment by Sugaraqua** [comment]
暂时没有了，感谢您的解答
