### ISSUE TITLE
请问为什么模型生成的json格式包含\和多余的"

### ISSUE THREAD

**Issue by pipiyapi** [zjunlp/DeepKE#504]
模型生成的NER结果不是标准的json格式，无法将其导入excel或其他地方方便地查看结果，请问有什么方法可以将其转为标准json格式，或者有什么方便统计NER详细结果的方法，如统计各个实体类型预测的准确率等等。

![image](https://github.com/zjunlp/DeepKE/assets/169782275/2e61d7e1-237c-427c-8ef3-a5e1081e778d)

**Comment by zxlzr** [comment]
您好，这是不同编码导致的转义符，您可以自行写脚本转换或切换编码。

**Comment by guihonghao** [comment]
output字段可以通过 json.loads() 函数进行解析。NER的提取器可查看 https://github.com/zjunlp/DeepKE/blob/main/example/llm/InstructKGC/ie2instruction/eval/extracter/ner_extracter.py

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
