### ISSUE TITLE
pip安装cnschema出错

### ISSUE THREAD

**Issue by whwususu** [zjunlp/DeepKE#506]
我先安装了 example/llm中的pip install -r requirements.txt，成功后，进入了example\triple\cnschema，更改了模型路径后，我在cnschema目录再次运行了pip install -r requirements.txt，结果报错
![image](https://github.com/zjunlp/DeepKE/assets/25104771/65e5d394-d37b-4286-b351-1c34799d8649)
这个使用方法对吗？谢谢！是不是需要装Rust

**Comment by xxupiano** [comment]
推荐根据主页README，使用setup和requirements.txt安装

**Comment by whwususu** [comment]
谢谢！已经过了那个了
![image](https://github.com/zjunlp/DeepKE/assets/25104771/45a35926-681d-4697-b951-a37762d0ff59)
这个错误的原因是啥啊

**Comment by whwususu** [comment]
> 谢谢！已经过了那个了 ![image](https://private-user-images.githubusercontent.com/25104771/331842275-45a35926-681d-4697-b951-a37762d0ff59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwODQ1MTcsIm5iZiI6MTcxNjA4NDIxNywicGF0aCI6Ii8yNTEwNDc3MS8zMzE4NDIyNzUtNDVhMzU5MjYtNjgxZC00Njk3LWI5NTEtYTM3NzYyZDBmZjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDAyMDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NjA3ZDlkMGY4Y2U4MGFmMzVmNzI4MDFlZmI5Nzc2MDA5OTNiZGVkNWNjYjJiYWE5ZGY0NDljNWY2YTBlMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GnwC98M4eDHRksSsSf76-DAsxyyl3YcIhonkWgLEHmY) 这个错误的原因是啥啊

那个过了，又出了编码问题

**Comment by whwususu** [comment]
![image](https://github.com/zjunlp/DeepKE/assets/25104771/6a5dbcaf-6142-4d0d-b2ef-a95866bc1d6c)
![image](https://github.com/zjunlp/DeepKE/assets/25104771/6c35a82e-474e-4a42-9ea6-1168fca00a1d)
我已经指明了 模型，为啥还会报错啊
![image](https://github.com/zjunlp/DeepKE/assets/25104771/c4de8789-38c2-489e-81fa-5115080c4c20)
谢谢！

**Comment by zxlzr** [comment]
您好，看上去可能是网络原因模型没正确下载？建议您科学上网或先下载到本地再使用。

**Comment by whwususu** [comment]
> 您好，看上去可能是网络原因模型没正确下载？建议您科学上网或先下载到本地再使用。

![image](https://github.com/zjunlp/DeepKE/assets/25104771/44d1bb97-2817-4c91-8463-c178fde71115)
模型已经在这里了啊？不是这两个模型吗？

**Comment by xxupiano** [comment]
根据报错，请将lm_file修改为模型路径

**Comment by whwususu** [comment]
> 根据报错，请将lm_file修改为模型路径

感谢啊，已经跑起来了
![image](https://github.com/zjunlp/DeepKE/assets/25104771/0684a226-2065-448b-a954-01dd8558c650)
![image](https://github.com/zjunlp/DeepKE/assets/25104771/b9c072ed-78d3-4a3f-bc5d-c36720e2fe00)
提取出来的额感觉跑的有点远

**Comment by whwususu** [comment]
> 您好，这个模型是小模型仅支持抽取训练见过的实体关系类型，对于没见过的抽取能力较弱，您可以根据置信度过滤掉这个0.51已经很低了。

我尝试用oneke,按照你们说明的方法，进入example/llm以后，我运行了 pip install -r requirements.txt，并且下载了模型，在你们提供的代码里面，我修改了模型的地址
![image](https://github.com/zjunlp/DeepKE/assets/25104771/dca68f7b-846c-4dae-85a3-6372c091dc62)
出现了这个错误，我还需要做什么？
![image](https://github.com/zjunlp/DeepKE/assets/25104771/33414f03-24d8-4802-a0cf-80121b8ac47a)

**Comment by guihonghao** [comment]
你好，请安装pip install protobuf==3.20.1
oneke所需环境请参照https://github.com/zjunlp/DeepKE/blob/main/example/llm/requirements.txt

**Comment by whwususu** [comment]
> 你好，请安装pip install protobuf==3.20.1 oneke所需环境请参照https://github.com/zjunlp/DeepKE/blob/main/example/llm/requirements.txt
已经安装，非常感谢！
