### ISSUE TITLE
baichuan2-13b-iepile-lora模型预测报错zjunlp/baichuan2-13b-iepile-lora does not appear to have a file named config.json.

### ISSUE THREAD

**Issue by Funnyxiaxia** [zjunlp/DeepKE#508]
在案例：Lora微调Baichuan完成CCKS2023指令驱动的知识图谱构建 中，我尝试使用训练好的baichuan2-13b-iepile-lora模型进行预测，这是我的bash文件：`CUDA_VISIBLE_DEVICES=0 python src/inference.py \
    --stage sft \
    --model_name_or_path 'zjunlp/baichuan2-13b-iepile-lora' \
    --checkpoint_dir 'lora/baichuan2-13b-iepile-lora' \
    --model_name 'baichuan' \
    --template 'baichuan2' \
    --do_predict \
    --input_file 'data/input.json' \
    --output_file 'results/baichuan2-13b-iepile-lora_output.json' \
    --finetuning_type lora \
    --output_dir 'lora/test' \
    --predict_with_generate \
    --cutoff_len 512 \
    --bf16 \
    --max_new_tokens 300 \
    --bits 4`，执行后报错`OSError: zjunlp/baichuan2-13b-iepile-lora does not appear to have a file named config.json. Checkout 'https://huggingface.co/zjunlp/baichuan2-13b-iepile-lora/tree/main' for available files.`

**Comment by guihonghao** [comment]
你好，model_name_or_path 是底座模型即https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat。
另外，我们新发布的信息抽取大模型OneKE在信息抽取方面效果更佳 https://github.com/zjunlp/DeepKE/blob/main/example/llm/OneKE.md

**Comment by Funnyxiaxia** [comment]
我将--model_name_or_path 'baichuan-inc/Baichuan2-13B-Chat' \更换为'baichuan-inc/Baichuan2-13B-Chat'后运行，报错ValueError: You can't pass `load_in_4bit`or `load_in_8bit` as a kwarg when passing `quantization_config` argument at the same time.

**Comment by guihonghao** [comment]
你好，我们采用的环境是
```
accelerate==0.21.0
transformers==4.33.0
bitsandbytes==0.39.1
```

**Comment by zxlzr** [comment]
您好，请问您的问题是否已解决？

**Comment by Funnyxiaxia** [comment]
您好，使用了OneKE。

**Comment by guihonghao** [comment]
1、参考 [data](https://github.com/zjunlp/DeepKE/blob/main/example/llm/InstructKGC/data) 目录下各个任务中sample.json文件格式组织测试文件，schema.json组织schema信息。
2、参考 https://github.com/zjunlp/DeepKE/blob/main/example/llm/InstructKGC/README_CN.md#23%E6%B5%8B%E8%AF%95%E6%95%B0%E6%8D%AE%E8%BD%AC%E6%8D%A2 步骤，按照下面的代码转换sample.json文件为模型可输入的文件test.json
```python
python ie2instruction/convert_func.py \
    --src_path data/NER/sample.json \
    --tgt_path data/NER/test.json \
    --schema_path data/NER/schema.json \
    --language zh \
    --task NER \
    --split_num 6 \
    --split test
```
转换后的每条测试数据将含有id, instruction, label字段。
3、输入模型，模型预测输出output字段。
4、通过下面的代码计算F1分数。
```python
python ie2instruction/eval_func.py \
  --path1 '模型输出文件路径' \
  --task NER 
```

**Comment by Funnyxiaxia** [comment]
在NER任务中，假正例、假负例、真负例如何解释

**Comment by guihonghao** [comment]
参考代码：https://github.com/zjunlp/DeepKE/blob/main/example/llm/InstructKGC/ie2instruction/eval/metric/ner_metric.py

**Comment by Funnyxiaxia** [comment]
pred_num和gold_num是什么意思

**Comment by guihonghao** [comment]
参考资料：https://blog.csdn.net/weixin_45498383/article/details/135740711

**Comment by Funnyxiaxia** [comment]
十分感谢

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
