### ISSUE TITLE
fastchat can use？

### ISSUE THREAD

**Issue by chiyinbao** [zjunlp/DeepKE#509]
**Describe the feature**
> A clear and concise description of any features you've considered.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by guihonghao** [comment]
你好OneKE的底座模型是llama2(中文加强版)，理论上可以适配fastchat框架。注意指令套用prompt模版即可。
```python
system_prompt = '<<SYS>>\nYou are a helpful assistant. 你是一个乐于助人的助手。\n<</SYS>>\n\n'
sintruct = "{\"instruction\": \"You are an expert in named entity recognition. Please extract entities that match the schema definition from the input. Return an empty list if the entity type does not exist. Please respond in the format of a JSON string.\", \"schema\": [\"person\", \"organization\", \"else\", \"location\"], \"input\": \"284 Robert Allenby ( Australia ) 69 71 71 73 , Miguel Angel Martin ( Spain ) 75 70 71 68 ( Allenby won at first play-off hole )\"}"
sintruct = '[INST] ' + system_prompt + sintruct + '[/INST]'
```
不同任务的指令格式可参考  https://github.com/zjunlp/DeepKE/blob/main/example/llm/OneKE.md#oneke%E6%8C%87%E4%BB%A4%E6%A0%BC%E5%BC%8F
