### ISSUE TITLE
请问有kg2instrction使用的data目录的数据吗？

### ISSUE THREAD

**Issue by som-don** [zjunlp/DeepKE#511]
**Describe the question**
> A clear and concise description of what the question is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by som-don** [comment]
仓库中data目录的数据是与ie2instruction对应的，运行kg2instruction会报key error ‘input’的错误，能提供kg2instruction用的data目录中的数据格式吗？谢谢！

**Comment by guihonghao** [comment]
你好，我们更新了代码，请pull最新的代码。kg2instruction用的data目录与ie2instruction的是对应的，在 https://github.com/zjunlp/DeepKE/tree/main/example/llm/InstructKGC/data

**Comment by zxlzr** [comment]
您好，请问您还有其他问题吗

**Comment by som-don** [comment]
感谢！
