### ISSUE TITLE
infer llama3-8B-instruct 报错return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg) TypeError: not a string

### ISSUE THREAD

**Issue by JoshonSmith** [zjunlp/DeepKE#513]
**Describe the bug**
> A clear and concise description of what the bug is.
根据infer_scripts/infer_llama.bash改写 infer_llama3_8B_instruct的测试脚本如下：
CUDA_VISIBLE_DEVICES=3 python src/inference.py \
    --stage sft \
    --model_name_or_path '/data/.cache/Meta-Llama-3-8B-Instruct' \
    --checkpoint_dir '/data/llama3-8b-iepile-lora' \
    --model_name 'llama' \
    --template 'alpaca' \
    --do_predict \
    --input_file 'data/NER/test.json' \
    --output_file 'results/llama3-8b-iepile-lora.json' \
    --finetuning_type lora \
    --output_dir 'lora/test' \
    --predict_with_generate \
    --cutoff_len 512 \
    --bf16 \
    --max_new_tokens 300 \
    --bits 4

**报错**：
>如下：
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /data/condaenvs/deepke-llm/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
05/25/2024 15:09:30 - INFO - __main__ - model_class:<class 'transformers.models.llama.modeling_llama.LlamaForCausalLM'>
tokenizer_class:<class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'PreTrainedTokenizerFast'. 
The class this function is called from is 'LlamaTokenizer'.
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Traceback (most recent call last):
  File "/InstructKGC/src/inference.py", line 122, in <module>
    main()
  File "InstructKGC/src/inference.py", line 116, in main
    inference(model_args, data_args, training_args, finetuning_args, generating_args, inference_args)
  File "/InstructKGC/src/inference.py", line 47, in inference
    model, tokenizer = load_model_and_tokenizer(
  File "InstructKGC/src/model/loader.py", line 53, in load_model_and_tokenizer
    tokenizer = tokenizer_class.from_pretrained(
  File "/data/condaenvs/deepke-llm/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2029, in from_pretrained
    return cls._from_pretrained(
  File "/data/condaenvs/deepke-llm/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2261, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/data/condaenvs/deepke-llm/lib/python3.9/site-packages/transformers/models/llama/tokenization_llama.py", line 178, in __init__
    self.sp_model = self.get_spm_processor(kwargs.pop("from_slow", False))
  File "/data/condaenvs/deepke-llm/lib/python3.9/site-packages/transformers/models/llama/tokenization_llama.py", line 203, in get_spm_processor
    tokenizer.Load(self.vocab_file)
  File "/data/condaenvs/deepke-llm/lib/python3.9/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/data/condaenvs/deepke-llm/lib/python3.9/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    **return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string**

错误原因与这个地方类似：
https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct/discussions/51
修改为：
use AutoTokenizer.from_pretrained(model_path, use_auth_token=token) don not have the error

把 src/utils/general_utils.py的get_model_tokenizer_trainer改为下面这样，可以不报错
```
def get_model_tokenizer_trainer(model_name):
    if model_name == 'llama':
        return LlamaForCausalLM, LlamaTokenizer, Trainer
    elif model_name == 'llama3':
        return LlamaForCausalLM, AutoTokenizer, Trainer
```

**Comment by guihonghao** [comment]
感谢你的提醒，我们将进行响应的修改。
