### ISSUE TITLE
显存不够

### ISSUE THREAD

**Issue by whwususu** [zjunlp/DeepKE#514]
![image](https://github.com/zjunlp/DeepKE/assets/25104771/bcf5ee57-cbd5-429b-8f62-a7af2dbfb746)
显卡是3090，报显存不够， 那么export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:设置为多少比较合适，改了几个数值，依旧报显存不够。谢谢！

**Comment by guihonghao** [comment]
你好，建议增加 `--bits 4` 参数进行量化

**Comment by whwususu** [comment]
> 你好，建议增加 `--bits 4` 参数进行量化

在哪个文件更改啊，我现在没有进行微调，只是用这个模型去进行提取，就报了这个错误，谢谢！

**Comment by guihonghao** [comment]
你已经进行了4bits量化，建议减小输入长度

**Comment by whwususu** [comment]
> 你已经进行了4bits量化，建议减小输入长度 max_length=1024, max_new_tokens=512

已经启动起来了，感谢！
![image](https://github.com/zjunlp/DeepKE/assets/25104771/7ebc8f31-7e59-4595-a949-ba6c24194d27)
![image](https://github.com/zjunlp/DeepKE/assets/25104771/1e3d0ed3-bdab-4816-bab0-cd37f9f973a8)
![image](https://github.com/zjunlp/DeepKE/assets/25104771/45ee793d-88d0-42e8-af83-506f48352522)
怎么抽也只能抽取到第一条，是我问的方式不对吗？
![image](https://github.com/zjunlp/DeepKE/assets/25104771/23487ac9-bc1b-4433-b6c7-bfd88177ad4d)

**Comment by guihonghao** [comment]
我们训练集中文本长度偏短，因此建议实际使用中不要使用过长的文本进行抽取。

**Comment by whwususu** [comment]
> 我们训练集中文本长度偏短，因此建议实际使用中不要使用过长的文本进行抽取。

没办法啊，都是一篇一篇文档过来。我是做了下测试。后面如果真的需要用，那可能真的需要学习了。

**Comment by zxlzr** [comment]
您可以暂时对文档进行划窗口来进行抽取，跑多次抽取模型

**Comment by whwususu** [comment]
> 您可以暂时对文档进行划窗口来进行抽取，跑多次抽取模型

那上下文变化，准确度应该会下降。然后能不能直接读pdf之类，我现在是通过程序读取的pdf，转为了string

**Comment by guihonghao** [comment]
当前阶段的模型可能还无法很好的处理文档级的抽取，我们将在下一个版本的模型中加强这方面的能力。

**Comment by whwususu** [comment]
> 当前阶段的模型可能还无法很好的处理文档级的抽取，我们将在下一个版本的模型中加强这方面的能力。

期待中

**Comment by gangqing** [comment]
@whwususu 请问你是怎么解决的？我也是报这个错，减小了输入输出长度也还是报错。

**Comment by 1223243** [comment]
请问一下，你知道怎么使用vscode调试这个代码吗
