### ISSUE TITLE
LoRA微调大模型时，恢复训练 如何设置？

### ISSUE THREAD

**Issue by JoshonSmith** [zjunlp/DeepKE#515]
你好，我想通过lora方式训练qwen7B，中途中断了，如何设置从checkpoint继续训练
>下面这样设置checkpoint_dir，会导致从0开始重新来训练
CUDA_VISIBLE_DEVICES="3" python src/finetune.py \
    --do_train --do_eval \
    --overwrite_output_dir \
    --stage 'sft' \
    --model_name_or_path '/data/.cache/modelscope/hub/qwen/Qwen1.5-7B-Chat' \
    --checkpoint_dir 'lora/qwen-1.5-7B-chat-devData-lora/checkpoint-17465' \

**Comment by guihonghao** [comment]
增加 `--checkpoint_dir 'lora/qwen-1.5-7B-chat-devData-lora/checkpoint-17465' \` 这行参数，将output_dir设置一个新目录，即可从checkpoint继续训练

**Comment by JoshonSmith** [comment]
> 你好，我想通过lora方式训练qwen7B，中途中断了，如何设置从checkpoint继续训练
> 
> > 下面这样设置checkpoint_dir，会导致从0开始重新来训练
> > CUDA_VISIBLE_DEVICES="3" python src/finetune.py 
> >     --do_train --do_eval 
> >     --overwrite_output_dir 
> >     --stage 'sft' 
> >     --model_name_or_path '/data/.cache/modelscope/hub/qwen/Qwen1.5-7B-Chat' 
> >     --checkpoint_dir 'lora/qwen-1.5-7B-chat-devData-lora/checkpoint-17465' \

设置参数 --resume_from_checkpoint
