### ISSUE TITLE
OneKE指令格式修改

### ISSUE THREAD

**Issue by TTToGAo** [zjunlp/DeepKE#517]
你好，我想请问一下是否能通过修改指令进行一些知识图谱其他相关任务呢？
目前我想通过提供头实体、尾实体、候选的关系集合以及文本，利用OneKE基于文本选择该实体对之间在候选关系中最有可能的关系，想咨询一下是否能通过修改指令的instruction实现？

**Comment by zxlzr** [comment]
您好，您可以通过修改指令来实现，但效果不一定会很好，我们也没试过。

**Comment by TTToGAo** [comment]
> 您好，您可以通过修改指令来实现，但效果不一定会很好，我们也没试过。

好的，感谢你的回复！请问是除了修改指令的instruction还需要修改其他东西吗？是否需要在instruction中描述我设置的schema每个字段的意义呢？

**Comment by zxlzr** [comment]
有描述效果可能会好一些、

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by TTToGAo** [comment]
> 请问您还有其他问题吗？
抱歉没有及时看到，暂时没有问题了，感谢解答！

**Comment by TTToGAo** [comment]
> 请问您还有其他问题吗？

抱歉没有及时看到，暂时没有问题了，感谢解答！
