### ISSUE TITLE
README_CNSCHEMA.md 关系里26 28 是一样的

### ISSUE THREAD

**Issue by zhedoushenmegui** [zjunlp/DeepKE#518]
| 序号  | 头实体类型  | 尾实体类型 | 关系   | 序号  | 头实体类型  | 尾实体类型 | 关系   |
| --- |:------ |:-----:| ---- | --- |:------ |:-----:| ---- |
| 25  | cns:人物     | cns:人物    | cns:丈夫   | 26  | cns:Text   | cns:历史人物  | cns:朝代   |
| 27  | cns:Text   | cns:人物    | cns:民族   | 28  | cns:Text   | cns:历史人物  | cns:朝代   |

**Comment by zxlzr** [comment]
您好，感谢指出问题，已更正readme，这是一个笔误。  28 | cns:Text | cns:历史人物 | cns:号
