### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by gangqing** [zjunlp/DeepKE#520]
根据DeepKE/tree/main/example/llm/OneKE.md的教程的"快速运行"来执行代码，代码是直接复制下来的，报错：显存不足，指写了0号GPU，总显存是32G的，满足教程里的要求，conda环境也是按教程来安装的。麻烦看看是怎么回事。
代码：
<img width="656" alt="image" src="https://github.com/zjunlp/DeepKE/assets/11442825/d9de547b-0f42-40d4-8fde-aab8f8538b50">

显存信息：
<img width="611" alt="image" src="https://github.com/zjunlp/DeepKE/assets/11442825/bebdd9f9-5967-4499-b9a3-5b997e6e0ff4">

报错信息：
<img width="1328" alt="image" src="https://github.com/zjunlp/DeepKE/assets/11442825/4666b02e-3185-4035-9880-a0dfc022db41">

**Comment by guihonghao** [comment]
你好，bf16不支持在V100上执行，请更换机器。

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
