### ISSUE TITLE
多个微调模型在信息抽取的性能比较

### ISSUE THREAD

**Issue by ferry309** [zjunlp/DeepKE#523]
你好，请问贵团队有比较过OneKE，LLama_lora， Qwen_lora，Baichuan_lora这几个模型在通用或者领域场景下的信息抽取效果吗，哪个模型的效果最好呢？另一个想跟您确认的问题是我看 KnowLM是发布的比较早的，相比这几个模型使用了更多的语料进行预训练，在信息抽取任务上，性能相比前面的四个模型又如何呢？

**Comment by ferry309** [comment]
嗯嗯，看到了。感谢回复！我发现在使用长文本作为输入，严格遵循文档指定的Prompt的情况下，oneke有时候会没有输出。应该是和使用短文本训练数据有关，这样一来微调反而限制了模型的实际使用。强烈建议使用长文本再训练下。

**Comment by zxlzr** [comment]
感谢您的建议
