### ISSUE TITLE
关于DeepKE-LLM训练时的数据转换

### ISSUE THREAD

**Issue by hlcle** [zjunlp/DeepKE#524]
https://github.com/zjunlp/DeepKE/blob/main/example/llm/InstructKGC/README_CN.md#22训练数据转换
<img width="2177" alt="image" src="https://github.com/zjunlp/DeepKE/assets/63539519/771845de-9e08-4de3-859d-8be2d7fcae38">
小白来请教大家，请问在这里的KG训练数据的schema中，是否支持多个实体及其属性，如果我想做三元组的抽取任务，应该参考什么样的格式？

**Comment by hlcle** [comment]
> 可以支持多个实体及其属性。 可以采用KG指令模版[{"entity_type": "人物", "attributes": ["出生日期", ...]}, {"entity_type": "XX", ...}] 或者RE指令模版，schema变为[{"subject_type": "人物", "predicate": "出生日期", "object_type": "时间"}, ...] 以及将属性及实体信息包含在schema解释中
> 
> ```
> {
>     "instruction": "你是专门进行关系抽取的专家。请从input中抽取出符合schema定义的关系三元组，不存在的关系返回空列表。请按照JSON字符串的格式回答。",
>     "schema": {
>         "民族": "民族",
>         "毕业院校": "该关系类型描述的是人物和其毕业学院之间的关系，人物是主体，毕业学院是客体。通过识别出文本中的人物名称和学校名称，然后通过词语的组合、上下文情境等信息，分析出人物和学院之间的毕业关系。",
>         "饰演": "这是一个描述电影、电视剧等视听作品中，某个演员扮演某个角色的关系，主体一般为人，客体为他们在作品中扮演的角色。该关系表示了特定人物在特定作品中所扮演角色的情况，以及由此产生的各种演员、角色间的关系。",
>         "父亲": "这个关系类型用来表示人物关系中的父亲和子女之间的亲属关系，即父亲是子女的出生或抚养者。在关系三元组中，'父亲'这个关系类型的主体是子女，客体是父亲。"
>     },
>     "input": "古往今来，能饰演古龙小说人物“楚留香”的，无一不是娱乐圈公认的美男子，2011年，36岁的张智尧在《楚留香新传》里饰演楚留香，依旧帅得让人无法自拔"
> }
> ```
> 
> 具体指令格式可参考：https://github.com/zjunlp/DeepKE/blob/main/example/llm/OneKE.md#oneke%E6%8C%87%E4%BB%A4%E6%A0%BC%E5%BC%8F OneKE指令格式、定制化schema解释指令、定制化example示例指令

明白，感谢指导。最后还想请问一个问题，对于多个实体及其属性的数据，repo中供参考的数据转换程序（https://github.com/zjunlp/DeepKE/blob/main/example/llm/InstructKGC/ie2instruction/convert_func.py）是否支持这样转换，因为我看程序的对应的schema.json(https://github.com/zjunlp/DeepKE/tree/main/example/llm/InstructKGC/data/KG)里没有这样的多实体数据，sample.json里也没有区分各个实体类型的标签。

**Comment by guihonghao** [comment]
我们还未实现多KG数据转换代码，你可以自行构造数据并实现代码。

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
