### ISSUE TITLE
微调oneke

### ISSUE THREAD

**Issue by TTToGAo** [zjunlp/DeepKE#525]
你好，我目前先在deepke上用自己的数据集进行微调，环境是windows系统。以下是我的脚本
output_dir='lora/oneke-continue'
mkdir -p ${output_dir}
CUDA_VISIBLE_DEVICES="0" torchrun --nproc_per_node=1 --master_port=1287 src/finetune.py \
    --do_train \
    --overwrite_output_dir \
    --model_name_or_path '******' \
    --stage 'sft' \
    --model_name 'llama' \
    --template 'llama2' \
    --train_file 'data/RE/processed.json' \
    --output_dir=${output_dir} \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 4 \
    --preprocessing_num_workers 16 \
    --num_train_epochs 10 \
    --learning_rate 5e-5 \
    --max_grad_norm 0.5 \
    --optim "adamw_torch" \
    --max_source_length 400 \
    --cutoff_len 700 \
    --max_target_length 300 \
    --evaluation_strategy "epoch" \
    --save_strategy "epoch" \
    --save_total_limit 10 \
    --lora_r 64 \
    --lora_alpha 64 \
    --lora_dropout 0.05 \
    --bits 4 \
    --language "en"
但目前代码在调用trainer.train()时会返回错误：RuntimeError: Invalid scalar type

**Comment by TTToGAo** [comment]
似乎是尝试调度多张显卡会报错，请问下是否有参数设置其不用多张显卡并行呢

**Comment by guihonghao** [comment]
你好设置成 CUDA_VISIBLE_DEVICES="0" python src/finetune.py ..
即表示单卡运行。
oneke的template应该是 --template 'llama2_zh'
此外参数中没有 --language "en" 改参数

**Comment by TTToGAo** [comment]
> 你好设置成 CUDA_VISIBLE_DEVICES="0" python src/finetune.py .. 即表示单卡运行。 oneke的template应该是 --template 'llama2_zh' 此外参数中没有 --language "en" 改参数

感谢你的回复！请问我目前想利用英文数据进行微调，template仍然选择llama2_zh吗？还有一个问题就是我在用RE任务进行train的过程中labels打印出来有很多NAN值，数据集都是严格按照范例里提供的sample.json格式进行设置的，同时也将schema.json修改为我数据集里的关系，请问NAN这个情况正常吗？

**Comment by guihonghao** [comment]
请提供转换后输入到模型中的instruction、output格式，以及“labels打印出来有很多NAN值”的例子看看。

**Comment by TTToGAo** [comment]
这个是我跑python src/finetune.py后输出的结果，不知道是否符合你说的例子

**Comment by TTToGAo** [comment]
这个是我跑python src/finetune.py后输出的结果，不知道是否符合你说的例子
<img width="1043" alt="1" src="https://github.com/zjunlp/DeepKE/assets/58768751/dc087cfe-2487-4262-bc1f-dc23e9eb7f76">
<img width="1037" alt="2" src="https://github.com/zjunlp/DeepKE/assets/58768751/2ce2d0ad-f54d-441b-8246-2ce3fa364d67">
<img width="587" alt="3" src="https://github.com/zjunlp/DeepKE/assets/58768751/719a625b-321b-4e9d-8809-a375c9cd0406">

**Comment by TTToGAo** [comment]
现在则是一直卡在这个界面，看了GPU的利用率也没上来感觉好像并没有在训练，不知道是什么问题呢？
<img width="1035" alt="4" src="https://github.com/zjunlp/DeepKE/assets/58768751/496e28fe-0e47-4eca-b81f-6ed47dd5b4ec">

**Comment by guihonghao** [comment]
NAN表示给定的关系不存在

**Comment by TTToGAo** [comment]
感谢您的回复，现在则是一直卡在这个界面，进度一直是0%，看了GPU的利用率也没上来感觉好像并没有在训练，不知道是什么问题呢？
<img width="1035" alt="4" src="https://github.com/zjunlp/DeepKE/assets/58768751/6b7b1661-5055-4d2b-87b1-c54dffa594c3">

**Comment by guihonghao** [comment]
检查GPU设备是否可用，最大输入输出长度设置是否合理。
