### ISSUE TITLE
关于利用LoRa微调后调用结果模型

### ISSUE THREAD

**Issue by TTToGAo** [zjunlp/DeepKE#526]
你好！
目前我已经微调好oneke并生成了如下的checkpoint文件
![image](https://github.com/zjunlp/DeepKE/assets/58768751/18cc6f14-2bad-4449-9bc3-923dd93345e0)
想问下是否有什么办法能通过以下类似的代码进行checkpoint模型的加载呢？
<img width="499" alt="3832dc1732f87ec527246ff4ce8723e" src="https://github.com/zjunlp/DeepKE/assets/58768751/1fac5c8b-1b09-470b-9b03-7633af004517">

**Comment by guihonghao** [comment]
参考这块 https://github.com/zjunlp/DeepKE/blob/main/example/llm/InstructKGC/README_CN.md#611%E5%9F%BA%E7%A1%80%E6%A8%A1%E5%9E%8Blora 进行lora推理
参数设置与训练时保持一致，--checkpoint_dir替换成'XXX/checkpoint-XX'

**Comment by zxlzr** [comment]
请问您还有什么问题吗
