### ISSUE TITLE
全量微调权重保存

### ISSUE THREAD

**Issue by hlcle** [zjunlp/DeepKE#527]
`output_dir='lora/oneke-continue'
mkdir -p ${output_dir}
CUDA_VISIBLE_DEVICES="0,1,2,3" torchrun --nproc_per_node=4 --master_port=1287 src/finetune.py \
    --do_train --do_eval \
    --overwrite_output_dir \
    --model_name_or_path 'models/OneKE' \
    --stage 'sft' \
    --finetuning_type 'full' \
    --model_name 'llama' \
    --template 'llama2_zh' \
    --train_file 'data/train.json' \
    --valid_file 'data/dev.json' \
    --output_dir=${output_dir} \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 4 \
    --preprocessing_num_workers 16 \
    --num_train_epochs 10 \
    --learning_rate 5e-5 \
    --max_grad_norm 0.5 \
    --optim "adamw_torch" \
    --max_source_length 400 \
    --cutoff_len 700 \
    --max_target_length 300 \
    --evaluation_strategy "epoch" \
    --save_strategy "epoch" \
    --save_total_limit 10 \
    --lora_dropout 0.05 \
    --bf16 
    --deepspeed 'ds_config_bf16_stage3.json`

为什么保存的checkpoint里没有tokenizer，推理的时候也报错加载不上？求解谢谢

**Comment by guihonghao** [comment]
你好，我们刚刚在finetune.py文件中修复了这一错误。为避免重复训练，你可以从oneke模型目录下拷贝tokenizer相关文件到checkpoint目录下。

**Comment by zxlzr** [comment]
请问您还有什么问题吗
