### ISSUE TITLE
关于数据标注的问题

### ISSUE THREAD

**Issue by Danmo121** [zjunlp/DeepKE#528]
关于BIO标注格式，我的数据中含有一些化学式，例如SiO2、K2O等作为实体，目前我是这样标注的：SiO2 B-ELE，也就是整体标注的，我使用w2ner进行训练，我发现ELE标签的F1值还是可以的，0.96.但在实际预测中，根本预测不到这样的实体，我现在不确定说因为数量不够还是标注的问题，有些数量和这类实体差不多的，还可以预测到。是不是在中英混合的标注应该这样：
S B-ELE
i I-ELE
O I-ELE
2 I-ELE
希望各位大佬指教。

**Comment by xxupiano** [comment]
建议看一下tokenizer对这样的化学物质实体的分词情况，尝试做一下统计，如果大多都按字母分词的话，采用后一种方案，如果大多化学物质没有被分词，则采用目前的标注

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by Danmo121** [comment]
感谢！下午的时候做了尝试，发现使用逐字符标注，即
S B-ELE
i I-ELE
O ELE
2 ELE
的标注方法，模型则能够很好预测这些化学式，估计是因为属于中英文混合的情况所致，可能和泛化性有关，具体我也不得而知，猜想。非常感谢！
shaorqi
***@***.***
---- 回复的原邮件 ----
***@***.***>发送日期2024年6月12日 ***@***.***>***@***.***>,
***@***.***>主题Re: [zjunlp/DeepKE] 关于数据标注的问题 (Issue #528)
请问您还有其他问题吗？
