### ISSUE TITLE
关于re 文档级别抽取预测结果的问题

### ISSUE THREAD

**Issue by Danmo121** [zjunlp/DeepKE#530]
1. 我使用现有的英文数据进行训练，在使用test数据结果预测时，结果中只有：
"title": ，
        "h_idx": ,
        "t_idx": ,
        "r": "",
  但是没有evidence或者sent id，正常应该是得有evidence吧。请赐教，谢谢！
![Snipaste_2024-06-14_00-09-17](https://github.com/zjunlp/DeepKE/assets/129567075/44ffaabb-151d-46c2-a6d6-c7bc2fad4799)
2. 另外还有一个问题请教，在train.yaml文件中，有这两个参数：
num_class: 97
num_labels: 4
其中，num_class代表了关系种类的数量，那么num_labels是什么的数量，有点不太明白，谢谢！

**Comment by zxlzr** [comment]
您好，请问您使用的是deepke中哪个方法？麻烦您提供一些细节便于我们帮助您

**Comment by Danmo121** [comment]
> 您好，请问您使用的是deepke中哪个方法？麻烦您提供一些细节便于我们帮助您
您好，就是使用re中DeepKE\example\re\document 篇章级别的关系抽取方法，就是使用咱们提供的DocRED数据。也是按照现有的代码正常训练和预测的。

**Comment by njcx-ai** [comment]
您好，非常感谢您对我们工作的关注。
1. test数据结果预测的是实体对之间的关系，这里应该不涉及sent_id。
2. num_class代表了关系种类的数量，num_labels表示的应该是论文中公式10-11中的balanced softmax类别，您可以在源码里看一下具体细节。

**Comment by Danmo121** [comment]
感谢解答，关于num_labels我明白了，看了一下h_idx是头实体，t_idx是尾实体，r是关系。h_idx t_idx是指在vertexSet中的索引，之前误认为是pos[]了。再次感谢
