### ISSUE TITLE
这里怎么贴了三个知乎的跳转链接

### ISSUE THREAD

**Issue by zhedoushenmegui** [zjunlp/DeepKE#535]
https://github.com/zjunlp/DeepKE/blob/11c8a09f3891529b31b7bbc9f49a887c87487a66/example/llm/README_CN.md?plain=1#L255

**Comment by zxlzr** [comment]
您好，这是关于p-tuning等方法的中文介绍，您有什么问题吗？

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
