### ISSUE TITLE
关于re  standard预测模型的选择

### ISSUE THREAD

**Issue by pangpangDD** [zjunlp/DeepKE#536]
在re-standard训练过程中，针对每一轮epoch都会在checkpoints文件夹下生成以时间命名的文件夹，文件夹下面是生成对应的训练模型，如epoch为2，就会生成lm_epoch1.pth、lm_epoch2.pth

在预测时候会在predict.yaml中写入fp模型，请问当多个epoch时怎么选择具体的模型呢？是选择lm_epoch1.pth还是lm_epoch2.pth怎么决定的呢？

**Comment by zxlzr** [comment]
您好，根据验证集选择效果最好epoch 的 checkpoint，用效果最好的即可

**Comment by zxlzr** [comment]
请问您有其他问题吗？

**Comment by pangpangDD** [comment]
> 您好，根据验证集选择效果最好epoch 的 checkpoint，用效果最好的即可
效果最好的是不是一般是最后一个？比如3个epoch，第3轮的epoch生成的模型？

**Comment by zxlzr** [comment]
您好，不一定，训久了会过拟合，您需要valid set 调试

**Comment by pangpangDD** [comment]
> 您好，不一定，训久了会过拟合，您需要valid set 调试

请问通过怎样的方式可以查看哪个模型效果最好？小白发问，感谢！

**Comment by zxlzr** [comment]
在验证集上直接测试看效果
