### ISSUE TITLE
where is the fintuing_pt.py in InstructKGC

### ISSUE THREAD

**Issue by BinLingNie** [zjunlp/DeepKE#538]
where is the fintuing_pt.py in InstructKGC

**Comment by XeeKee** [comment]
The previous file restructuring caused the deletion of chatglm by mistake. I have re-uploaded the previous Python code in example/llm/InstructKGC/src/finetuning_chatglm_pt.py. Please note that the chatglm pt script only supports chatglm1. I will be adding the chatglm bash script in the coming days.
