### ISSUE TITLE
直接运行显示错误

### ISSUE THREAD

**Issue by immense8342** [zjunlp/DeepKE#54]
**Describe the bug**
> 直接运行显示错误

**Environment (please complete the following information):**
 - OS:windows
 - Python 3.7

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
>     if torch.cuda.CUDA_ENABLED and use_deterministic_cudnn:
>       torch.backends.cudnn.deterministic = True
>     torch.backends.cudnn.benchmark = False
### 错误信息
 if torch.cuda.CUDA_ENABLED and use_deterministic_cudnn:
AttributeError: module 'torch.cuda' has no attribute 'CUDA_ENABLED'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by mlyzy** [comment]
我也出现这样的问题，请问你解决了吗？

**Comment by mlyzy** [comment]
我换成.is_available()可以跑通

**Comment by touchankawaii** [comment]
我直接把出错的那几行代码注释掉就可以运行了

**Comment by honeysuckcle** [comment]
> 我直接把出错的那几行代码注释掉就可以运行了

请问具体注释掉的是哪几行呢？我也遇到了这个问题，但是是新手也不敢随便改。
