### ISSUE TITLE
llm总是输出重复，有什么参数要改的吗，

### ISSUE THREAD

**Issue by thunder95** [zjunlp/DeepKE#541]
完全参考例子：
https://github.com/zjunlp/DeepKE/blob/main/example/llm/OneKE.md#%E5%BF%AB%E9%80%9F%E8%BF%90%E8%A1%8C

system_prompt = '<<SYS>>\nYou are a helpful assistant. 你是一个乐于助人的助手。\n<</SYS>>\n\n'
sintruct = "{\"instruction\": \"You are an expert in named entity recognition. Please extract entities that match the schema definition from the input. Return an empty list if the entity type does not exist. Please respond in the format of a JSON string.\", \"schema\": [\"person\", \"organization\", \"else\", \"location\"], \"input\": \"284 Robert Allenby ( Australia ) 69 71 71 73 , Miguel Angel Martin ( Spain ) 75 70 71 68 ( Allenby won at first play-off hole )\"}"
sintruct = '[INST] ' + system_prompt + sintruct + '[/INST]'

测试int４和fp１６有相同的问题

输出内容：
{"person": ["Robert Allenby", "Allenby", "Miguel Angel Martin"], "organization": [], "else": [], "location": ["Australia", "Spain"]} "person": ["Robert Allenby", "Allenby", "Miguel Angel Martin"], "organization": [], "else": [], "location": ["Australia", "Spain"]} {"person": ["Robert Allenby", "Allenby", "Miguel Angel Martin"], "organization": [], "else": [], "location": ["Australia", "Spain"]} {"person": ["Robert Allenby", "Allenby", "Miguel Angel Martin"], "organization": [], "else": [], "location": ["Australia", "Spain"]} {"person": ["Robert Allenby", "Allenby", "Miguel Angel Martin"], "organization": [], "else": [], "location": ["Australia", "Spain"]} {"person": ["Robert Allenby", "Allenby", "Miguel Angel Martin"], "organization": [], "else": [], "location": ["Australia", "Spain"]} {"person": ["Robert Allenby", "Allenby", "Miguel Angel Martin"], "organization": [], "else": [], "location": ["Australia", "Spain"]} {"person": ["Robert Allenby", "Allenby", "Miguel Angel Martin"], "organization": [], "else": [], "location": ["Australia", "Spain"]} {"person": ["Robert Allenby", "Allenby", "Miguel Angel Martin"], "organization": [], "else": [], "location": ["Australia", "Spain"]} {"person": ["Robert Allenby", "Allenby", "Miguel Angel Martin"], "organization": [], "else": [], "location": ["Australia", "Spain"]} {"person": ["Robert Allenby", "Allenby", "Miguel Angel Martin"], "organization": [], "else": [], "location": ["Australia", "Spain"]} {"person": ["Robert Allenby", "Allenby", "Miguel Angel Martin"], "organization": []

请问是模型的能力问题还是有什么参数配置不对？

**Comment by guihonghao** [comment]
你可以尝试设置 --repetition_penalty 参数大于1，来抑制模型的重复生成。

**Comment by thunder95** [comment]
@guihonghao 试了不同的penalty，要么乱码要么依旧重复

**Comment by thunder95** [comment]
@guihonghao 　又或者是带出了上下文无关的中文，不能合理的停止，例如：
{"person": ["Robert Allenby", "Allenby", "Miguel Angel Martin"], "organization": [], "else": [], "location": ["Australia", "Spain"]} 《中国》杂志社原刊文：《美国的未来:超级大国或衰败国? 美国总统大选年鉴"} {"人名": []} {"组织": ["《中国》杂志社"], "地点": ["澳大利亚", "美", "美国"], "时间": []} {"个人": []} {"机构": []} {"人物": []} {"主题": ["美国的未来:超级大国 or 衰败国?"]} {"作者": []} {"出版物": []} {"日期": []} {"主体": []} {"其他信息": []} {"结果": []} {"奖项": []} {"国籍": ["澳洲", "西班牙"]} {"职业": []} {"教育程度": []} {"出生地": []} {"所属群体": []} {"配偶": []} {"父母": []} {"宗教信仰": []} {"成就": []} {"作品": []} {"译者": []} {"产地": ["英", "法", "德", "意"]} {"性别": []} {"年龄": []} {"所获荣誉": []} {"所在栏目": []} {"标题": ["罗伯特·艾伦比", "米格尔·安东尼马丁"]} {"内容": ["在第一洞，他击出了一个漂亮的鸟ie；", "他的成绩为75+70=145（ + = ）；", "他在决赛中和巴拿尔一起打出了一对子e；", "这是 his second win on the European Tour this yearf；", "hiscatarinabagrande."]} {"段落主题": ["罗伯特· allenbiy", "米格elangelmartiñon"], "分行结果": ["roberto alencar i", "mig el angelo martínez"]} {"姓名拼写错误": ["罗伯特·allenb ", "米格尔·anegron"]} {"翻译

**Comment by guihonghao** [comment]
不能fp16，我们训练是在bf16上进行的

**Comment by thunder95** [comment]
@guihonghao 大佬　使用bf16会报错，RuntimeError: "triu_tril_cuda_template" not implemented for 'BFloat16'，是要换torch版本吗

**Comment by guihonghao** [comment]
使用推荐的环境
