### ISSUE TITLE
oneKE微调 数据量

### ISSUE THREAD

**Issue by zengtao1978** [zjunlp/DeepKE#544]
对于oneKE 需要RE方面的微调，大约需要多少样本数？
我看example/data/***的中例子训练样本数都比较少，最多100条。
是按照这种规模来准备么？

**Comment by zxlzr** [comment]
如果为了提升抽取能力，数据量越大、质量越高越好，data里的仅仅是例子

**Comment by zengtao1978** [comment]
能提供指导性的数量级么？
通常的pretain模型下，训练样本基本几千就搞定了。
如果要提供IEpile那种量级的数据量，就有点夸张啦。

**Comment by zxlzr** [comment]
您好，数据量和任务本身有关，都是经验数据，比如任务难且和预训练长得不太一样的话，建议多一些，任务简单的话几百数千即可，建议控制数据配比

**Comment by zengtao1978** [comment]
对于新的关系抽取，是否可以利用 “定制化example示例指令 的方式”，来让大模型获得更多泛化能力？

**Comment by zxlzr** [comment]
和基座模型有关，基座模型很强的话，上下文学习能力强，有这个能力，基座模型弱就不太行

**Comment by zengtao1978** [comment]
OK，谢谢。
