### ISSUE TITLE
关于模型训练的公共资源平台

### ISSUE THREAD

**Issue by panhustar** [zjunlp/DeepKE#546]
**Describe the question**
> A clear and concise description of what the question is.
由于受到个人资源设备影响，如果要在公共云平台上训练模型，需要使用GPU 资源，对于从Hugging Face下载的预训练好的模型进行微调，比如bart-large等，建议申请哪个平台的资源进行训练？
非常感谢指教，如果有链接，会更好

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
您好，bart-large 一般3090 4090 机器就可以训练，建议您网上搜一搜，平台非常多。
