### ISSUE TITLE
re功能依赖的bert-base-chinese模型文件缺失

### ISSUE THREAD

**Issue by LSM2525** [zjunlp/DeepKE#548]
**Describe the bug**
> A clear and concise description of what the bug is.
re功能会自动从huggingface上下载bert-base-chinese模型，由于国内无法从huggingface下载模型，手动下载模型上传后报模型中缺少文件的错误。
![QQ_1720517656460](https://github.com/zjunlp/DeepKE/assets/92773729/12d7a067-2e3e-4d9d-8cf1-e2b4e6f265b9)
但是bert-base-chinese模型中本身并没有这个文件，求解答，谢谢！
![1720517726223](https://github.com/zjunlp/DeepKE/assets/92773729/3e922c28-2845-480c-8351-7932e9185d12)

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
您好，windows 下路径需要修改反斜杠

**Comment by zxlzr** [comment]
从报错看deepke还是在调用.cache的下的模型，建议您修改yaml里lm 的路径，改为新的模型地址路径再试试

**Comment by zxlzr** [comment]
请问您的问题解决了吗，建议您检查路径

**Comment by GoooDte** [comment]
您好，您可以参考以下镜像网站直接下载模型，无需手动下载：
https://hf-mirror.com/
