### ISSUE TITLE
泛化的拉普拉斯矩阵(Generalized Laplacian matrix)

### ISSUE THREAD

**Issue by immense8342** [zjunlp/DeepKE#55]
**Describe the question**
> deepke自带的GCN模块好像没有使用泛化的拉普拉斯矩阵(Generalized Laplacian matrix)是吗？还是只是我阅读代码的时候没理解？
>“几何平均受极端值影响较小，因此是GCN中比较常用的归一化方法”
>deepke是使用了算术平均的方法是吗？
[https://blog.csdn.net/July541/article/details/107531735](https://blog.csdn.net/July541/article/details/107531735)
[https://blog.csdn.net/VariableX/article/details/109820684](https://blog.csdn.net/VariableX/article/details/109820684)

**Environment (please complete the following information):**
 - OS: window
 - Python Version 3.7

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
```
 def forward(self, x, adj): #adj是邻接矩阵
        L = x.size(1)
        AxW = self.fc1(torch.bmm(adj, x)) + self.fc1(x)
        AxW = AxW / L
        AxW = F.leaky_relu(AxW)
        AxW = self.dropout(AxW)
        for fc in self.fcs:
            AxW = fc(torch.bmm(adj, AxW)) + fc(AxW)
            AxW = AxW / L
            AxW = F.leaky_relu(AxW)
            AxW = self.dropout(AxW)

        return AxW
```

**Comment by immense8342** [comment]
好像GCN作者还没有完全实现好。。。是吗

**Comment by tlk-dsg** [comment]
GCN已实现，参考的是Attention Guided Graph Convolutional Networks for Relation Extraction这一篇论文中提出的模型

**Comment by tlk-dsg** [comment]
> 好像GCN作者还没有完全实现好。。。是吗

GCN已实现，参考的是Attention Guided Graph Convolutional Networks for Relation Extraction这一篇论文中提出的模型

**Comment by tlk-dsg** [comment]
GCN已实现，参考的是Attention Guided Graph Convolutional Networks for Relation Extraction这一篇论文中提出的模型
