### ISSUE TITLE
使用IEPile微调LLaMA3-8B的训练时间

### ISSUE THREAD

**Issue by Da1zheng** [zjunlp/DeepKE#550]
**Describe the question**
请问使用IEPile微调LLaMA3-8B，显示的训练时间大约是400-500小时是正常的吗？下面是训练的一些参数设置。
GPU = A800 80G
batch_size = 16
bits = 4
其他设置均为默认设置。
谢谢！

**Comment by guihonghao** [comment]
正常，你可以对数据集进行下采样（目前是200多万条数据），增大batch_size

**Comment by Da1zheng** [comment]
感谢您的回复&nbsp;


戴铮
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月11日(星期四) 晚上10:06
收件人: "zjunlp/DeepKE";
抄送: "Author";
主题: Re: [zjunlp/DeepKE] 使用IEPile微调LLaMA3-8B的训练时间 (Issue #550)





 
正常，你可以对数据集进行下采样（目前是200多万条数据），增大batch_size
 
&mdash;

**Comment by zxlzr** [comment]
请问您还有其他问题吗

**Comment by Da1zheng** [comment]
> 请问您还有其他问题吗
没有了，感谢您的回复
