### ISSUE TITLE
Docker调用显卡问题

### ISSUE THREAD

**Issue by diaozeyu115** [zjunlp/DeepKE#551]
您好，我最近尝试用windows下的Docker 运行Deepke，在执行ner/standard中run_bert.py程序的时候，提示显卡（3060，12g）和pytorch版本不兼容（GeForce RTX 3060 with CUDA capability sm_86 is not compatible with the current PyTorch installation），并且给出了CUDA error：Invalid device ordinal。
我想问一下，出现错误是因为容器里没有装cuda吗（不太清楚容器能否直接调用宿主机的CUDA），还是因为pytorch版本太低了？如果想正常调用显卡的话，应该是怎么解决呢，谢谢！

**Comment by zxlzr** [comment]
您好，建议您不使用docker 直接用anaconda安装环境重新试试

**Comment by zxlzr** [comment]
请问您的问题解决了吗？

**Comment by diaozeyu115** [comment]
还没有解决，我在容器内更新了pytorch的版本，运行后没有出现兼容性提示了，但还是会出现cuda error。我打算再找找可能存在的问题，倘若还是无法解决，就装linux虚拟机或者系统



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月20日(周六) 上午9:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zjunlp/DeepKE] Docker调用显卡问题 (Issue #551)




 
请问您的问题解决了吗？

**Comment by diaozeyu115** [comment]
我想问一下跑ner时，先下载Bert模型到本地，再在哪个配置文件中修改路径呀

**Comment by diaozeyu115** [comment]
想问一下，我在windows下安装完依赖，跑run_bert默认用的cpu，查torch的版本1.11.0+cpu，应该怎么解决呀

**Comment by diaozeyu115** [comment]
<img width="421" alt="111" src="https://github.com/user-attachments/assets/a434b5f8-dd03-487b-9b67-39d9b888f5f8">
训练出来结果都是0，batchsize设置的64，请问是咋回事呀

**Comment by GoooDte** [comment]
您好，建议在训练集上测试结果是否正常

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by 1223243** [comment]
请问一下，你知道怎么使用vscode调试这个代码吗
