### ISSUE TITLE
example/llm/InstructKGC/src/finetune.py进行Lora微调报错  KeyError 'response'

### ISSUE THREAD

**Issue by Yumeka999** [zjunlp/DeepKE#552]
使用example/llm/InstructKGC/src/finetune.py + example/llm/InstructKGC/data/RE/train.json
进行Lora微调报错

example/llm/InstructKGC/src/datamodule/preprocess.py中28行报错
query, response = examples["prompt"][i], examples["response"][i]

打印了example的keys只有
id  prompt label 没有response

是preprocess.py有bug 还是训练数据train.json有bug

**Comment by guihonghao** [comment]
你好，example/llm/InstructKGC/data/RE/train.json中的数据格式是 
{"task": "RE", "source": "RE", "instruction": "{\"instruction\": \"你是专门进行关系抽取的专家。请从input中抽取出符合schema定义的关系三元组，不存在的关系返回空列表。请按照JSON字符串的格式回答。\", \"schema\": [\"丈夫\", \"上映时间\", \"专业代码\", \"主持人\"], \"input\": \"如何演好自己的角色，请读《演员自我修养》《喜剧之王》周星驰崛起于穷困潦倒之中的独门秘笈\"}", "output": "{\"丈夫\": [], \"上映时间\": [], \"专业代码\": [], \"主持人\": []}"}
没有问题

**Comment by guihonghao** [comment]
注意，训练数据使用的转换代码是--split train，测试数据使用的是--split test，不要弄混淆
python ie2instruction/convert_func.py \
    --src_path data/NER/sample.json \
    --tgt_path data/NER/train.json \
    --schema_path data/NER/schema.json \
    --language zh \
    --task NER \
    --split_num 6 \       
    --random_sort \
    --split train

**Comment by zxlzr** [comment]
请问您的问题解决了吗？
