### ISSUE TITLE
是否支持跨句多元关系抽取？

### ISSUE THREAD

**Issue by yangguoer** [zjunlp/DeepKE#553]
**Describe the question**
> A clear and concise description of what the question is.
请问是否支持跨句多元关系抽取？

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
您好，暂时不支持。
