### ISSUE TITLE
有计划训练qwen2版本吗

### ISSUE THREAD

**Issue by JoshonSmith** [zjunlp/DeepKE#554]
**Describe the feature**
> A clear and concise description of any features you've considered.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by JoshonSmith** [comment]
此外 智谱最新的大模型也很厉害

**Comment by zxlzr** [comment]
您好，因为我们没有足够的卡，算力资源，暂时无法支持，非常抱歉。
