### ISSUE TITLE
调用训练数据转化脚本时传参报错

### ISSUE THREAD

**Issue by HewenMa** [zjunlp/DeepKE#555]
首先，关于生成训练数据部分有一些小问题想要请教：

1. schema文件的作用是什么？我看到微调时也不会传参到脚本中，个人理解是只有train和test数据才是对最后微调有意义的文件？但每一个任务data文件夹下给的参考都是多个文件，没太理解作用都是什么
2. data文件夹下给的例子中，看起来像是jsonl文件，数据最外部没有[ ]，但下载下来是json文件，那传入文件到脚本时应该是什么格式呢？我们尝试用的是外部有[ ]包裹的json数据但报错

以下是我们实际运行时的小问题：
我所理解的是：src_path是自己准备的预处理的数据集，train和schema都是通过脚本生成的。
报错信息如下：
`root@a51f78e3e7ee:~/DeepKE/example/llm# python InstructKGC/ie2instruction/convert_func.py \
    --src_path OneKE-finetuning-input.json \
    --tgt_path InstructKGC/data/NER/trainOneKE.json \
    --schema_path InstructKGC/data/NER/schemaOneKE.json \
    --language zh \
    --task NER \
    --split_num 6 \       
    --random_sort \
    --split train
usage: convert_func.py [-h] [--src_path SRC_PATH] [--tgt_path TGT_PATH] [--schema_path SCHEMA_PATH] [--hard_negative_path HARD_NEGATIVE_PATH] [--cluster_mode]
                       [--language {zh,en}] [--task {RE,NER,EE,EET,EEA,SPO,KG}] [--split {train,test}] [--split_num SPLIT_NUM] [--neg_schema NEG_SCHEMA] [--random_sort]
convert_func.py: error: unrecognized arguments:  
bash: --random_sort: command not found`
显示--random_sort参数未被识别，请问这是什么原因呢？

**Comment by guihonghao** [comment]
基于schema的抽取，schema文件提供数据集预定义的标签集。
在使用 [convert_func.py](https://github.com/zjunlp/DeepKE/blob/main/example/llm/InstructKGC/ie2instruction/convert_func.py) 脚本之前，请确保参考了 [data](https://github.com/zjunlp/DeepKE/blob/main/example/llm/InstructKGC/data) 目录。该目录详细说明了每种任务所需的数据格式要求。 sample.json 描述了转换前数据的格式，schema.json 展示了 schema 的组织结构， train.json 描述了转换后的数据格式。

**Comment by guihonghao** [comment]
<img width="339" alt="image" src="https://github.com/user-attachments/assets/77117650-7fb0-4cfc-b3c9-202f041192cb">
-random_sort参数未被识别可以是多余的空格导致的

**Comment by zxlzr** [comment]
请问您的问题解决了吗？
