### ISSUE TITLE
Vanilla prompt from CodeKGC paper

### ISSUE THREAD

**Issue by paolo-gajo** [zjunlp/DeepKE#556]
Hello, I wanted to ask if you could please make available the vanilla prompts used for the CodeKGC paper. I am working on reproducing the results and I would like to know what the vanilla prompt looked like exactly. Thank you.

**Comment by bizhen46766** [comment]
Thank you very much for your attention!

 In the paper, the setting of vanilla prompts is very simple and straightforward, without any structured transformations.

For example, the input is:
text:
Gynecomastia in epileptics treated with phenobarbital, phenytoin, and fluoresone: two case reports.

The output is:
triple_list: xxxx

**Comment by bizhen46766** [comment]
Hello, you can modify the parameter value of **ICL_prompt** at this point in the code, replacing the code prompt data with vanilla prompts.

>https://github.com/zjunlp/DeepKE/blob/4c97b1a3f3a57b94face54d6ca7f1f65117420e6/example/llm/CodeKGC/codekgc.py#L36C37-L36C47

` prompt = schema_prompt + '\n' + ICL_prompt +  text
`

**Comment by bizhen46766** [comment]
If you have any further questions, please feel free to contact us via email (**bizhen_zju@zju.edu.cn**)
