### ISSUE TITLE
deepke-llm是否适配GLM4？

### ISSUE THREAD

**Issue by cangyizhou** [zjunlp/DeepKE#558]
**Describe the question**
> A clear and concise description of what the question is.
我想请问一下现有框架是否支持GLM4的训练微调等？

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
您好，目前因为计算资源问题（我们缺卡），暂时未完全支持，抱歉。

**Comment by 1223243** [comment]
请问一下，你知道怎么使用vscode调试这个代码吗
