### ISSUE TITLE
在lora微调oneke时，有两个数据格式未明确

### ISSUE THREAD

**Issue by zhipenglii** [zjunlp/DeepKE#560]
**Describe the question**
> A clear and concise 
![微信图片_20240731112445](https://github.com/user-attachments/assets/1ad6ab57-dc75-444e-846c-97a79d7dbc8f)
![微信图片_20240731112448](https://github.com/user-attachments/assets/a4aac4f7-2f9a-4161-a2fc-b51f5cb5f988)
description of what the question is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.
请问这两个文件的格式分别是什么样子的，在数据准备阶段只说明了训练集和测试集，是一样的吗？

**Comment by guihonghao** [comment]
train.json、dev.json的格式是：
{
    "task": "NER", 
    "source": "CoNLL2003", 
    "instruction": "{\"instruction\": \"You are an expert in named entity recognition. Please extract entities that match the schema definition from the input. Return an empty list if the entity type does not exist. Please respond in the format of a JSON string.\", \"schema\": [\"person\", \"organization\", \"else\", \"location\"], \"input\": \"284 Robert Allenby ( Australia ) 69 71 71 73 , Miguel Angel Martin ( Spain ) 75 70 71 68 ( Allenby won at first play-off hole )\"}", 
    "output": "{\"person\": [\"Robert Allenby\", \"Allenby\", \"Miguel Angel Martin\"], \"organization\": [], \"else\": [], \"location\": [\"Australia\", \"Spain\"]}"
}
其中task、source字段可选非必要

## 🧾 7.评估

我们提供了评估各个任务F1分数的脚本。

```bash
python ie2instruction/eval_func.py \
  --path1 results/llm_output.json \
  --task NER 
```

* `path1` 是模型的输出文件, 其中一条数据样本如下所示, 经测试数据转换脚本转换后的数据具有`id`、`instruction`、`label`字段, `output`字段是经过模型预测脚步后的模型真实输出。

```json
{
  "id": "e88d2b42f8ca14af1b77474fcb18671ed3cacc0c75cf91f63375e966574bd187", 
  "instruction": "{\"instruction\": \"你是专门进行实体抽取的专家。请从input中抽取出符合schema定义的实体，不存在的实体类型返回空列表。请按照JSON字符串的格式回答。\", \"schema\": [\"组织机构\", \"地理位置\", \"人物\"], \"input\": \"相比之下，青岛海牛队和广州松日队的雨中之战虽然也是0∶0，但乏善可陈。\"}", 
  "label": "[{\"entity\": \"广州松日队\", \"entity_type\": \"组织机构\"}, {\"entity\": \"青岛海牛队\", \"entity_type\": \"组织机构\"}]",
  "output": "{\"组织机构\": [\"广州松日队\", \"青岛海牛队\"], \"人物\": [], \"地理位置\": []}"
}
```

* `task`: 目前支持['RE', 'NER', 'EE', 'EET', 'EEA']五类任务。
* 可以设置 `sort_by` 为 `source`, 分别计算每个数据集上的F1分数。

**Comment by zhipenglii** [comment]
谢谢你。我在训练的时候又遇到新的问题，报错keyerro：response，用的是你们的data内样例数据训练的。我用自己的数据也仍然报错。你能帮我看看吗
`KeyError: 'response'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/featurize/work/concept2event/data_construction/ctextraction/example/llm/InstructKGC/src/finetune.py", line 117, in <module>
    main()
  File "/home/featurize/work/concept2event/data_construction/ctextraction/example/llm/InstructKGC/src/finetune.py", line 112, in main
    train(model_args, data_args, training_args, finetuning_args, generating_args)
  File "/home/featurize/work/concept2event/data_construction/ctextraction/example/llm/InstructKGC/src/finetune.py", line 49, in train
    train_data, valid_data = process_datasets(
  File "/home/featurize/work/concept2event/data_construction/ctextraction/example/llm/InstructKGC/src/datamodule/get_datasets.py", line 46, in process_datasets
    valid_data = preprocess_dataset(valid_data, tokenizer, data_args, training_args, stage=finetuning_args.stage)
  File "/home/featurize/work/concept2event/data_construction/ctextraction/example/llm/InstructKGC/src/datamodule/preprocess.py", line 184, in preprocess_dataset
    dataset = dataset.map(
  File "/environment/miniconda3/envs/OneKE/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/environment/miniconda3/envs/OneKE/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/environment/miniconda3/envs/OneKE/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 3185, in map
    for rank, done, content in iflatmap_unordered(
  File "/environment/miniconda3/envs/OneKE/lib/python3.9/site-packages/datasets/utils/py_utils.py", line 654, in iflatmap_unordered
    [async_result.get(timeout=0.05) for async_result in async_results]
  File "/environment/miniconda3/envs/OneKE/lib/python3.9/site-packages/datasets/utils/py_utils.py", line 654, in <listcomp>
    [async_result.get(timeout=0.05) for async_result in async_results]
  File "/environment/miniconda3/envs/OneKE/lib/python3.9/site-packages/multiprocess/pool.py", line 771, in get
    raise self._value
KeyError: 'response'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 22258) of binary: /environment/miniconda3/envs/OneKE/bin/python
Traceback (most recent call last):
  File "/environment/miniconda3/envs/OneKE/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/environment/miniconda3/envs/OneKE/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/environment/miniconda3/envs/OneKE/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/environment/miniconda3/envs/OneKE/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/environment/miniconda3/envs/OneKE/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/environment/miniconda3/envs/OneKE/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================`

**Comment by guihonghao** [comment]
检查train.json和dev.json是否都具有`output`字段，尤其是`dev.json`文件

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by zhipenglii** [comment]
我今天在进行格式转换test的时候模式没有生成
![image](https://github.com/user-attachments/assets/c99d651c-4c2b-48b2-af82-887c0498d3c3)

**Comment by zhipenglii** [comment]
另外训练之后 再使用基础模型和LoRA进行推理的时候 也没有按照最初的设定的那样返回结果
![image](https://github.com/user-attachments/assets/f8cacd9d-812b-4809-868a-0ac9e91fd47a)

**Comment by zhipenglii** [comment]
并且再转换数据的时候 split train 并不会完整的生成schema
![image](https://github.com/user-attachments/assets/d15a54f1-577d-40b5-8354-33f2dd240bea)
而split train 并不会生成schema 是空的

**Comment by zhipenglii** [comment]
![image](https://github.com/user-attachments/assets/25bc1225-5165-43ab-8d79-14641f7b7505)
你好，我推测可能是批量推理的输入文件格式的问题，请问批量推理的时候输入格式应该是什么样子的。我目前是这个样子：
![image](https://github.com/user-attachments/assets/aaae870c-4af2-4fb5-a24f-89602d4d03d4)

**Comment by guihonghao** [comment]
> 我今天在进行格式转换test的时候模式没有生成 ![image](https://private-user-images.githubusercontent.com/81350124/354176399-c99d651c-4c2b-48b2-af82-887c0498d3c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MjQ0MDMsIm5iZiI6MTcyMjUyNDEwMywicGF0aCI6Ii84MTM1MDEyNC8zNTQxNzYzOTktYzk5ZDY1MWMtNGMyYi00OGIyLWFmODItODg3YzA0OThkM2MzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDE0NTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MzRiM2Q0NjkyNTc0YjM0NDg1N2JkM2E4M2U4MGIzYWY1YWMwZjU2MzA0MDA4NmUyNjIzZjFjMTQxMWQ0OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l0IZtCfO-ZzIXzJXsEBZMBpz80xzACGL4vRjDelZYqI)

可能是提供的schema.json文件为空

**Comment by guihonghao** [comment]
> 另外训练之后 再使用基础模型和LoRA进行推理的时候 也没有按照最初的设定的那样返回结果 ![image](https://private-user-images.githubusercontent.com/81350124/354177019-f8cacd9d-812b-4809-868a-0ac9e91fd47a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MjQ0MDMsIm5iZiI6MTcyMjUyNDEwMywicGF0aCI6Ii84MTM1MDEyNC8zNTQxNzcwMTktZjhjYWNkOWQtODEyYi00ODA5LTg2OGEtMGFjOWU5MWZkNDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDE0NTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZDQ4ZTM5YjdjOTg2ODQwYWNiMmZhODU2NmQyNTQxNDQxMGQ1ZTQ3ZTFhYjE3ZDQwNjRjN2QwYzY4YjQ0NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R65MslWQmz3-7VJO3E82tUW_XMsecT3ksMBV2ScwMwI)

要么推理脚本有问题，要么训练的不充分

**Comment by zhipenglii** [comment]
> > 我今天在进行格式转换test的时候模式没有生成 ![image](https://private-user-images.githubusercontent.com/81350124/354176399-c99d651c-4c2b-48b2-af82-887c0498d3c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MjQ0MDMsIm5iZiI6MTcyMjUyNDEwMywicGF0aCI6Ii84MTM1MDEyNC8zNTQxNzYzOTktYzk5ZDY1MWMtNGMyYi00OGIyLWFmODItODg3YzA0OThkM2MzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDE0NTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MzRiM2Q0NjkyNTc0YjM0NDg1N2JkM2E4M2U4MGIzYWY1YWMwZjU2MzA0MDA4NmUyNjIzZjFjMTQxMWQ0OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l0IZtCfO-ZzIXzJXsEBZMBpz80xzACGL4vRjDelZYqI)
> 
> 可能是提供的schema.json文件为空

提供的并不是为空哦，和train的模板路径是一样的

**Comment by guihonghao** [comment]
> > > 我今天在进行格式转换test的时候模式没有生成 ![image](https://private-user-images.githubusercontent.com/81350124/354176399-c99d651c-4c2b-48b2-af82-887c0498d3c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MjQ0MDMsIm5iZiI6MTcyMjUyNDEwMywicGF0aCI6Ii84MTM1MDEyNC8zNTQxNzYzOTktYzk5ZDY1MWMtNGMyYi00OGIyLWFmODItODg3YzA0OThkM2MzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDE0NTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MzRiM2Q0NjkyNTc0YjM0NDg1N2JkM2E4M2U4MGIzYWY1YWMwZjU2MzA0MDA4NmUyNjIzZjFjMTQxMWQ0OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l0IZtCfO-ZzIXzJXsEBZMBpz80xzACGL4vRjDelZYqI)
> > 
> > 
> > 可能是提供的schema.json文件为空
> 
> 提供的并不是为空哦，和train的模板路径是一样的

建议调试代码或print出来，看哪里出了问题

**Comment by zxlzr** [comment]
请问您的问题解决了吗？
