### ISSUE TITLE
执行标准RE示例代码时“UnboundLocalError: local variable 'x' referenced before assignment”

### ISSUE THREAD

**Issue by Kyrie-LiuX** [zjunlp/DeepKE#562]
我发现执行DeepKE/example/re/standard/predict.py 后会报错：

fp: /mnt/data/Psy_KGLLM_LX/DeepKE/example/re/standard/checkpoints/2024-08-05_20-54-21/cnn_epoch50.pth
model_name: cnn
in_channels: ???
out_channels: 100
kernel_sizes:
- 3
- 5
- 7
activation: gelu
pooling_strategy: max
keep_length: true
dropout: 0.3
use_pcnn: false
intermediate: 80

是否使用范例[y/n]，退出请输入: exit .... y
[2024-08-05 21:02:37,822][__main__][INFO] - start sentence preprocess...
[2024-08-05 21:02:37,822][__main__][INFO] - 
sentence: 歌曲《人生长路》出自刘德华国语专辑《男人的爱》，由李泉作词作曲，2001年出行发版
chinese_split: True
replace_entity_with_type:  True
replace_entity_with_scope: True
tokens:    ['歌曲', '《', 'TAIL_歌曲', '》', '出自', '刘德华', '国语专辑', '《', 'HEAD_所属专辑', '》', '，', '由', '李泉', '作词', '作曲', '，', '2001', '年', '出行', '发版']
token2idx: [226, 18, 1, 20, 1983, 476, 1, 18, 1, 20, 13, 202, 4172, 373, 376, 13, 1891, 50, 1, 1]
length:    20
head_idx:  8
tail_idx:  2
[2024-08-05 21:02:37,823][__main__][INFO] - device: cpu
[2024-08-05 21:02:37,857][__main__][INFO] - model name: cnn
[2024-08-05 21:02:37,858][__main__][INFO] - 
 PCNN(
  (embedding): Embedding(
    (wordEmbed): Embedding(4701, 60, padding_idx=0)
    (entityPosEmbed): Embedding(62, 60, padding_idx=0)
    (attribute_keyPosEmbed): Embedding(62, 60, padding_idx=0)
    (layer_norm): LayerNorm((60,), eps=1e-05, elementwise_affine=True)
  )
  (cnn): CNN(
    (convs): ModuleList(
      (0): Conv1d(60, 100, kernel_size=(3,), stride=(1,), padding=(1,), bias=False)
      (1): Conv1d(60, 100, kernel_size=(5,), stride=(1,), padding=(2,), bias=False)
      (2): Conv1d(60, 100, kernel_size=(7,), stride=(1,), padding=(3,), bias=False)
    )
    (activations): ModuleDict(
      (relu): ReLU()
      (lrelu): LeakyReLU(negative_slope=0.01)
      (prelu): PReLU(num_parameters=1)
      (selu): SELU()
      (celu): CELU(alpha=1.0)
      (gelu): GELU()
      (sigmoid): Sigmoid()
      (tanh): Tanh()
    )
    (dropout): Dropout(p=0.3, inplace=False)
  )
  (fc1): Linear(in_features=300, out_features=80, bias=True)
  (fc2): Linear(in_features=80, out_features=11, bias=True)
  (dropout): Dropout(p=0.3, inplace=False)
)
/mnt/data/anaconda3/envs/deepke/lib/python3.8/site-packages/deepke-2.2.7-py3.8.egg/deepke/relation_extraction/standard/models/BasicModule.py:19: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.load_state_dict(torch.load(path, map_location=device))
Traceback (most recent call last):
  File "predict.py", line 135, in main
    x['word'], x['lens'] = torch.tensor([data[0]['token2idx'] + [0] * (512 - len(data[0]['token2idx']))]), torch.tensor([data[0]['seq_len']])
UnboundLocalError: local variable 'x' referenced before assignment

我认为在predict.py第135行代码的x并没有初始化，但是我设置成x = dict()后同样报错：
/mnt/data/anaconda3/envs/deepke/lib/python3.8/site-packages/deepke-2.2.7-py3.8.egg/deepke/relation_extraction/standard/models/BasicModule.py:19: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.load_state_dict(torch.load(path, map_location=device))
Traceback (most recent call last):
  File "predict.py", line 135, in main
    x['word'], x['lens'] = torch.tensor([data[0]['token2idx'] + [0] * (512 - len(data[0]['token2idx']))]), torch.tensor([data[0]['seq_len']])
UnboundLocalError: local variable 'x' referenced before assignment

请问这个问题怎么解决？

**Comment by Kyrie-LiuX** [comment]
解决了，在predict.py第135行代码的x并没有初始化，设置成x = dict()后就成功了，请及时更新代码

**Comment by GoooDte** [comment]
感谢您的指出 我们后续会及时更新
