### ISSUE TITLE
为什么ner/standard/run_bert.py报错

### ISSUE THREAD

**Issue by BeimingCharles** [zjunlp/DeepKE#563]
这个报错怎么解决，其他都按照.md配置好了。
![image](https://github.com/user-attachments/assets/865c8feb-8bbb-4bb9-ba4e-2fdb1393f90b)

**Comment by zxlzr** [comment]
您好，是hydra-core版本的问题，请您安装正确的版本再试试

**Comment by BeimingCharles** [comment]
要不你们帮我远程一下吧，太难配置了😭😭😭



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月06日 23:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zjunlp/DeepKE] 为什么ner/standard/run_bert.py报错 (Issue #563) |

您好，是hydra-core版本的问题，请您安装正确的版本再试试

**Comment by BeimingCharles** [comment]
这个Windows到底能不能配置啊



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月06日 23:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zjunlp/DeepKE] 为什么ner/standard/run_bert.py报错 (Issue #563) |

您好，是hydra-core版本的问题，请您安装正确的版本再试试

**Comment by zxlzr** [comment]
您好，在正确安装python库版本情况下是可以正确允许的，windows可能存在一些python库版本安装兼容问题，建议您再尝试下。

**Comment by zxlzr** [comment]
请问您的问题解决了吗？

**Comment by xxupiano** [comment]
请问hydra-core的版本是1.0.6吗？如果不是去请执行pip install hydra-core==1.0.6

**Comment by zxlzr** [comment]
请问您的问题解决了吗？

**Comment by BeimingCharles** [comment]
多少钱，你教我



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月12日 15:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zjunlp/DeepKE] 为什么ner/standard/run_bert.py报错 (Issue #563) |

请问您的问题解决了吗？

**Comment by zxlzr** [comment]
您好，我们近期其他项目紧张实在抽不出人力时间，过段时间安排人看下这个问题，抱歉。

**Comment by BeimingCharles** [comment]
行



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月13日 01:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zjunlp/DeepKE] 为什么ner/standard/run_bert.py报错 (Issue #563) |

您好，我们近期其他项目紧张实在抽不出人力时间，过段时间安排人看下这个问题，抱歉。

**Comment by xxupiano** [comment]
请问是否仍有报错？请在48小时内回复
