### ISSUE TITLE
运行run_lstmcrf.py时hydra-core老是报错

### ISSUE THREAD

**Issue by BeimingCharles** [zjunlp/DeepKE#564]
![image](https://github.com/user-attachments/assets/25f0c866-b4fa-49c7-b3a9-a8295cfecd9c)

**Comment by zxlzr** [comment]
您好，是hydra-core版本的问题，请您安装正确的版本再试试

**Comment by zxlzr** [comment]
请问您的问题解决了吗？

**Comment by BeimingCharles** [comment]
能不能帮我远程一下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月11日 23:14 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zjunlp/DeepKE] 运行run_lstmcrf.py时hydra-core老是报错 (Issue #564) |

请问您的问题解决了吗？

**Comment by zxlzr** [comment]
非常抱歉，我们是高校小团队，开发这个模块的同学几年前就毕业了，没有足够人力维护，建议您更换hydra-core版本再试一试。给您使用带来不便非常抱歉。

**Comment by xxupiano** [comment]
请问hydra-core的版本是1.0.6吗？如果不是请执行pip install hydra-core==1.0.6

**Comment by zxlzr** [comment]
请问您的问题解决了吗？
