### ISSUE TITLE
hydra/output下custom.yaml和train,yaml的定义（define）顺序问题???

### ISSUE THREAD

**Issue by BeimingCharles** [zjunlp/DeepKE#565]
![image](https://github.com/user-attachments/assets/59570b10-cee0-4503-92bc-43cb7a2e581b)

**Comment by zxlzr** [comment]
您好，烦请按requirement安装正确版本的python库再试一试

**Comment by xxupiano** [comment]
请问hydra-core的版本是1.0.6吗？如果不是请执行pip install hydra-core==1.0.6

**Comment by zxlzr** [comment]
请问您的问题解决了吗？
