### ISSUE TITLE
没用代理，re中输入y后报错

### ISSUE THREAD

**Issue by BeimingCharles** [zjunlp/DeepKE#567]
![image](https://github.com/user-attachments/assets/80534b51-6b8d-4546-ae7b-c5c744fd69a5)

**Comment by zxlzr** [comment]
您好，请您把模型下载到本地然后再使用。

**Comment by BeimingCharles** [comment]
下载之后输入正确的路径还是报错



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月06日 22:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zjunlp/DeepKE] 没用代理，re中输入y后报错 (Issue #567) |

您好，请您把模型下载到本地然后再使用。

**Comment by BeimingCharles** [comment]
这是报错详情
![image](https://github.com/user-attachments/assets/3fbb8d75-a965-46ee-ab13-89f41225132a)

**Comment by GoooDte** [comment]
您好，建议您检查一下路径的格式，看您的第一张图片文件路径中既包含windows斜杠也包含linux斜杠，请您统一

**Comment by zxlzr** [comment]
请问您的问题解决了吗？

**Comment by BeimingCharles** [comment]
解决了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月08日 20:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zjunlp/DeepKE] 没用代理，re中输入y后报错 (Issue #567) |

请问您的问题解决了吗？
