### ISSUE TITLE
max_source_length, max_target_length, cutoff_len含义

### ISSUE THREAD

**Issue by jack9193** [zjunlp/DeepKE#568]
**Describe the question**
> A clear and concise description of what the question is.
请问假设把max_source_length,=500, max_target_length=300,  cutoff_len=800的话，我的数据长度是2000，模型是自动切分成4段进行输入还是直接给我截断前500个字符作为输入，后面1500个字符就丢弃呢？

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by guihonghao** [comment]
直接截断前500个字符作为输入，后面1500个字符就丢弃。

**Comment by guihonghao** [comment]
<img width="1050" alt="image" src="https://github.com/user-attachments/assets/cc44b4a5-ba42-4ec3-aafa-fb2b01cdd81d">

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by jack9193** [comment]
> 请问您还有其他问题吗？

没有了，十分感谢！
