### ISSUE TITLE
wget 120.27.214.45/Data/triple/PRGC/data.tar.gz下载数据的时候 404 not Found

### ISSUE THREAD

**Issue by wangkz2023** [zjunlp/DeepKE#569]
**Describe the question**
> A clear and concise description of what the question is.
wget 120.27.214.45/Data/triple/PRGC/data.tar.gz下载数据的时候 404 not Found
PRGC三元组抽取的数据无法找到

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]
linux
python 3.8

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by GoooDte** [comment]
您好，您要下载哪个数据集就输入对应的zip文件，应该是没有data.zip这个压缩包的

**Comment by zxlzr** [comment]
请问您的问题解决了吗？

**Comment by wangkz2023** [comment]
> 请问您的问题解决了吗？

我从其他项目里下载的数据集
附链接：https://github.com/EduKgs/entity_relation/tree/master

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
