### ISSUE TITLE
lora微调llm是报错

### ISSUE THREAD

**Issue by yjwww** [zjunlp/DeepKE#570]
![WeChatf2bebf175dfaf53bc0dcb8d583aec83d](https://github.com/user-attachments/assets/b7a14601-bc3c-4f96-9444-7c5755592445)
**Describe the question**
> A clear and concise description of what the question is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by guihonghao** [comment]
检查训练集文件是否为空，是否每一行均为一个json字符串，按照教程格式构成`instruction`、`output`。

**Comment by zxlzr** [comment]
请问您的问题解决了吗？
