### ISSUE TITLE
继续lora微调时报错KeyError: 'response'

### ISSUE THREAD

**Issue by cangyizhou** [zjunlp/DeepKE#571]
output_dir='lora/Llama-2-13b-chat-hf-continue'
mkdir -p ${output_dir}
CUDA_VISIBLE_DEVICES="0,1" torchrun --nproc_per_node=2 --master_port=1287 src/finetune.py \
    --do_train --do_eval \
    --overwrite_output_dir \
    --model_name_or_path 'models/Llama-2-13b-chat-hf' \
    --checkpoint_dir 'lora/llama2-13b-iepile-lora' \
    --stage 'sft' \
    --model_name 'llama' \
    --template 'llama2' \
    --train_file 'data/NER/train.json' \
    --valid_file 'data/NER/test.json' \
    --output_dir=${output_dir} \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 4 \
    --preprocessing_num_workers 16 \
    --num_train_epochs 10 \
    --learning_rate 5e-5 \
    --max_grad_norm 0.5 \
    --optim "adamw_torch" \
    --max_source_length 400 \
    --cutoff_len 700 \
    --max_target_length 300 \
    --evaluation_strategy "epoch" \
    --save_strategy "epoch" \
    --save_total_limit 10 \
    --lora_r 64 \
    --lora_alpha 64 \
    --lora_dropout 0.05 \
    --bf16 

运行./ft_scripts/fine_continue.bash后报错KeyError: 'response'，用官方给的示例数据集也是报错，请问是哪里没有注意吗？谢谢解答

**Comment by guihonghao** [comment]
valid_file是验证集不是测试集。test.json是测试集文件，里面没有output字段。

**Comment by guihonghao** [comment]
可以仅使用train_file，通过设置`--val_set_size 100`参数调整从训练集中划分出验证集的大小。

**Comment by zxlzr** [comment]
请问您的问题解决了吗？

**Comment by cangyizhou** [comment]
谢谢解答，问题解决了
