### ISSUE TITLE
中文实体抽取模型选择

### ISSUE THREAD

**Issue by jack9193** [zjunlp/DeepKE#572]
**Describe the question**
> A clear and concise description of what the question is.
请问如果要使用大模型+lora微调来进行中文数据上的实体三元组的抽取的话，建议使用哪个模型呢？
我使用example/llm/InstructKGC下的lora微调OneKE，发现训练集上的F1是88，多训练了10多epoch反而下降成86了。

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
您好，可能是过拟合了，您可以调整下训练的epoch。另外您也可以使用最新的Qwen2模型 + 自定义（或iepile）数据效果可能会更好一些。
