### ISSUE TITLE
使用vscode对多模态命名体进行调试问题

### ISSUE THREAD

**Issue by 1223243** [zjunlp/DeepKE#573]
**Describe the question**
> A clear and concise description of what the question is.

你好，我参考你的这个配置去调试多模态命名体识别predict.py文件，下面是我的调试配置设置
{
"name": "Python: Debug",
"type": "python",
"request": "launch",
"python": "/home/nlp/anaconda3/envs/deepke/bin/python", // 指定python解释器
"program": "${workspaceFolder}/example/ner/multimodal/predict.py",
"cwd": "/home/nlp/xc/NLP/MNRE/DeepKE", //指定运行空间目录，defaults to ${workspaceFolder} (the folder open in VS Code).
"console": "integratedTerminal",
"env": {
"CUDA_VISIBLE_DEVICES":"0",
},
"args": [
"--seed", "1234",
"--bert_name", "/home/nlp/xc/NLP/LLM/openLLM/bert-base-uncased",
"--vit_name", "/home/nlp/xc/NLP/LLM/openLLM/clip-vit-base-patch32",
"--device", "cuda",
"--batch_size", "32",
"--max_seq", "80",
"--aux_size", "128",
"--rcnn_size", "64",
"--ignore_idx", "0",
"--load_path", "/home/nlp/xc/NLP/MNRE/DeepKE/example/ner/multimodal/tw17_bestmodel/best_model.pth",
"--dataset_name", "twitter17",
],
"justMyCode": true
},
项目根目录如下图
[
![1](https://github.com/user-attachments/assets/9812fd48-7984-4932-af22-38652b0eb6e3)
](url)

依旧不能调试，报错信息如下
![微信图片_20240812120137](https://github.com/user-attachments/assets/2010d2d7-b237-41a7-9dd6-f7dde3a75c11)

具体报错内容文字，如下：
(deepke) nlp@med:~/xc/NLP/MNRE/DeepKE$ cd /home/nlp/xc/NLP/MNRE/DeepKE ; /usr/bin/env /home/nlp/anaconda3/envs/deepke/bin/python /home/nlp/.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 57897 -- /home/nlp/xc/NLP/MNRE/DeepKE/example/ner/multimodal/predict.py --seed 3407 --bert_name /home/nlp/xc/NLP/LLM/openLLM/bert-base-uncased --vit_name /home/nlp/xc/NLP/LLM/openLLM/clip-vit-base-patch32 --device cuda --batch_size 32 --max_seq 80 --aux_size 128 --rcnn_size 64 --ignore_idx 0 --load_path /home/nlp/xc/NLP/MNRE/DeepKE/example/ner/multimodal/tw17_bestmodel/best_model.pth --dataset_name twitter17
usage: predict.py [--help] [--hydra-help] [--version] [--cfg {job,hydra,all}] [--package PACKAGE] [--run] [--multirun]
[--shell-completion] [--config-path CONFIG_PATH] [--config-name CONFIG_NAME] [--config-dir CONFIG_DIR]
[--info]
[overrides ...]
predict.py: error: unrecognized arguments: --seed --bert_name /home/nlp/xc/NLP/LLM/openLLM/bert-base-uncased --vit_name /home/nlp/xc/NLP/LLM/openLLM/clip-vit-base-patch32 --device cuda --batch_size 32 --max_seq 80 --aux_size 128 --rcnn_size 64 --ignore_idx 0 --load_path /home/nlp/xc/NLP/MNRE/DeepKE/example/ner/multimodal/tw17_bestmodel/best_model.pth --dataset_name twitter17
**Environment (please complete the following information):**
 - OS: linux
 - Python Version ：3.10.14

**Comment by flow3rdown** [comment]
您好，`predict.py`中已经指定了包含参数配置`yaml`文件，所以可以将`launch.json`中的`args`置为空，并通过修改`conf/predict.yaml`中的参数来进行调试。

**Comment by 1223243** [comment]
> 您好，`predict.py`中已经指定了包含参数配置`yaml`文件，所以可以将`launch.json`中的`args`置为空，并通过修改`conf/predict.yaml`中的参数来进行调试。

您好，
我删去了launch.json中args的内容
{
            "name": "Python: Debug",
            "type": "python",
            "request": "launch",
            "python": "/home/nlp/anaconda3/envs/deepke/bin/python", // 指定python解释器
            "program": "${workspaceFolder}/example/ner/multimodal/predict.py",
            "cwd": "/home/nlp/xc/NLP/MNRE/DeepKE",            //指定运行空间目录，
            // "console": "integratedTerminal",
            "env": {
                "CUDA_VISIBLE_DEVICES":"0",
            },
            "justMyCode": true
        },
  但依旧不能调试呢，具体截图如下
![image](https://github.com/user-attachments/assets/26369b3c-3f5a-4c75-b114-12fd1cc3651b)
直接运行CUDA_VISIBLE_DEVICES=2 python run.py是可以的

**Comment by flow3rdown** [comment]
报错显示没有`/home/nlp/xc/NLP/MNRE/DeepKE/data/twitter2017/test.txt`这个文件，请检查一下是否路径是否正确

**Comment by 1223243** [comment]
> 报错显示没有`/home/nlp/xc/NLP/MNRE/DeepKE/data/twitter2017/test.txt`这个文件，请检查一下是否路径是否正确

是的你这个路径是没有的，2017的test.txt文件路径在`/home/nlp/xc/NLP/MNRE/DeepKE/example/ner/multimodal/data/twitter2017/test.txt`，
问题1：我应该在哪个文件设置相关的参数？
问题2：为啥直接运行CUDA_VISIBLE_DEVICES=2 python run.py是可以的 
问题3：这个框架的train.yaml和predict.yaml能设置哪些参数，怎么查看我能设置的参数有哪些

**Comment by 1223243** [comment]
> 报错显示没有`/home/nlp/xc/NLP/MNRE/DeepKE/data/twitter2017/test.txt`这个文件，请检查一下是否路径是否正确

是的，控制台打印这个路径是没有文件的，
2017的test.txt文件路径在`/home/nlp/xc/NLP/MNRE/DeepKE/example/ner/multimodal/data/twitter2017/test.txt`，
问题1：我应该在哪个文件设置相关的参数？
问题2：为啥直接运行CUDA_VISIBLE_DEVICES=2 python run.py是可以的
问题3：这个框架的train.yaml和predict.yaml能设置哪些参数，怎么查看我能设置的参数有哪些

**Comment by flow3rdown** [comment]
1. 需要在[此处](https://github.com/zjunlp/DeepKE/blob/9a9f8343a1e4f8315f38289c316a47b7b1acf2d9/example/ner/multimodal/predict.py#L30)修改一下`test`文件的位置；
2. `run.py`和`predict.py`中的数据路径都需要进行修改，您应该只修改了`run.py`的配置；
3. `train.yaml`和`predict.yaml`文件中提供了可以修改的参数，可以参考进行修改。

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by 1223243** [comment]
我下午测试一次哈，下午答复



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月19日(周一) 中午11:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zjunlp/DeepKE] 使用vscode对多模态命名体进行调试问题 (Issue #573)




 
请问您还有其他问题吗？

**Comment by 1223243** [comment]
> 1. 需要在[此处](https://github.com/zjunlp/DeepKE/blob/9a9f8343a1e4f8315f38289c316a47b7b1acf2d9/example/ner/multimodal/predict.py#L30)修改一下`test`文件的位置；
> 2. `run.py`和`predict.py`中的数据路径都需要进行修改，您应该只修改了`run.py`的配置；
> 3. `train.yaml`和`predict.yaml`文件中提供了可以修改的参数，可以参考进行修改。

您好，现在可以调试启动没报错了，但是他直接运行完，我打在IFA_model.py文件打的断点，他遇到后并不停止下来，而且完整运行完全部，这是为啥嘞
![微信图片_20240819130926](https://github.com/user-attachments/assets/b8801e0d-f9e9-4766-9c1a-bb2fe97bc5aa)

**Comment by flow3rdown** [comment]
> > 1. 需要在[此处](https://github.com/zjunlp/DeepKE/blob/9a9f8343a1e4f8315f38289c316a47b7b1acf2d9/example/ner/multimodal/predict.py#L30)修改一下`test`文件的位置；
> > 2. `run.py`和`predict.py`中的数据路径都需要进行修改，您应该只修改了`run.py`的配置；
> > 3. `train.yaml`和`predict.yaml`文件中提供了可以修改的参数，可以参考进行修改。
> 
> 您好，现在可以调试启动没报错了，但是他直接运行完，我打在IFA_model.py文件打的断点，他遇到后并不停止下来，而且完整运行完全部，这是为啥嘞 ![微信图片_20240819130926](https://private-user-images.githubusercontent.com/67729727/358986148-b8801e0d-f9e9-4766-9c1a-bb2fe97bc5aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNTQ3NjgsIm5iZiI6MTcyNDE1NDQ2OCwicGF0aCI6Ii82NzcyOTcyNy8zNTg5ODYxNDgtYjg4MDFlMGQtZjllOS00NzY2LTljMWEtYmIyZmU5N2JjNWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDExNDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNzcyYThmNzVjOWVjZWI4ZTEwZTQ0ZDE0MzFmZmMxMDJlNzkwZjIwNjk4ZWYxNjczNzFiNjIxODQzZjQzMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P8Fc7XfjRc_okBfPXj8WFL8ODobI_PJ4raZgZ6pj5Mw)

需要在安装的deepke源码文件中打断点，例如`~/Anaconda/envs/deepke/lib/python3.9/site-packages/deepke/name_entity_re/multimodal/IFA_model.py`

**Comment by 1223243** [comment]
> > > 1. 需要在[此处](https://github.com/zjunlp/DeepKE/blob/9a9f8343a1e4f8315f38289c316a47b7b1acf2d9/example/ner/multimodal/predict.py#L30)修改一下`test`文件的位置；
> > > 2. `run.py`和`predict.py`中的数据路径都需要进行修改，您应该只修改了`run.py`的配置；
> > > 3. `train.yaml`和`predict.yaml`文件中提供了可以修改的参数，可以参考进行修改。
> > 
> > 
> > 您好，现在可以调试启动没报错了，但是他直接运行完，我打在IFA_model.py文件打的断点，他遇到后并不停止下来，而且完整运行完全部，这是为啥嘞 ![微信图片_20240819130926](https://private-user-images.githubusercontent.com/67729727/358986148-b8801e0d-f9e9-4766-9c1a-bb2fe97bc5aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNTQ3NjgsIm5iZiI6MTcyNDE1NDQ2OCwicGF0aCI6Ii82NzcyOTcyNy8zNTg5ODYxNDgtYjg4MDFlMGQtZjllOS00NzY2LTljMWEtYmIyZmU5N2JjNWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDExNDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNzcyYThmNzVjOWVjZWI4ZTEwZTQ0ZDE0MzFmZmMxMDJlNzkwZjIwNjk4ZWYxNjczNzFiNjIxODQzZjQzMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P8Fc7XfjRc_okBfPXj8WFL8ODobI_PJ4raZgZ6pj5Mw)
> 
> 需要在安装的deepke源码文件中打断点，例如`~/Anaconda/envs/deepke/lib/python3.9/site-packages/deepke/name_entity_re/multimodal/IFA_model.py`

我是通过源代码安装的，，我在当前项目文件夹不会给envs的代码打断点，方便加一下qq好友请教大佬一下吗`1625057436`

```
pip install -r requirements.txt
python setup.py install
python setup.py develop
```
不是pip install deepke安装，
我尝试在build里打断点，他也是不停止嘞
![image](https://github.com/user-attachments/assets/ae90a11b-ac59-4528-a88a-4dfbc56139fc)

**Comment by zxlzr** [comment]
您好这个可能是vscode使用问题，建议您搜索引擎搜一下

**Comment by 1223243** [comment]
> 您好这个可能是vscode使用问题，建议您搜索引擎搜一下

您好，基础的vscode调试我会，但没get到，`在安装的deepke源码文件中打断点`，没理解这个，我git clone下来的已经是源码了

**Comment by 1223243** [comment]
> > > 1. 需要在[此处](https://github.com/zjunlp/DeepKE/blob/9a9f8343a1e4f8315f38289c316a47b7b1acf2d9/example/ner/multimodal/predict.py#L30)修改一下`test`文件的位置；
> > > 2. `run.py`和`predict.py`中的数据路径都需要进行修改，您应该只修改了`run.py`的配置；
> > > 3. `train.yaml`和`predict.yaml`文件中提供了可以修改的参数，可以参考进行修改。
> > 
> > 
> > 您好，现在可以调试启动没报错了，但是他直接运行完，我打在IFA_model.py文件打的断点，他遇到后并不停止下来，而且完整运行完全部，这是为啥嘞 ![微信图片_20240819130926](https://private-user-images.githubusercontent.com/67729727/358986148-b8801e0d-f9e9-4766-9c1a-bb2fe97bc5aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNTQ3NjgsIm5iZiI6MTcyNDE1NDQ2OCwicGF0aCI6Ii82NzcyOTcyNy8zNTg5ODYxNDgtYjg4MDFlMGQtZjllOS00NzY2LTljMWEtYmIyZmU5N2JjNWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDExNDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNzcyYThmNzVjOWVjZWI4ZTEwZTQ0ZDE0MzFmZmMxMDJlNzkwZjIwNjk4ZWYxNjczNzFiNjIxODQzZjQzMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P8Fc7XfjRc_okBfPXj8WFL8ODobI_PJ4raZgZ6pj5Mw)
> 
> 需要在安装的deepke源码文件中打断点，例如`~/Anaconda/envs/deepke/lib/python3.9/site-packages/deepke/name_entity_re/multimodal/IFA_model.py`

您好，方便录一个视频教学一下吗

**Comment by flow3rdown** [comment]
你好，加你好友了，麻烦通过下

**Comment by 1223243** [comment]
您好，已通过了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjunlp/DeepKE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月22日(星期四) 上午10:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjunlp/DeepKE] 使用vscode对多模态命名体进行调试问题 (Issue #573)





 
你好，加你好友了，麻烦通过下

**Comment by flow3rdown** [comment]
通过在predict.py加断点，用step into的方式进入deepke源码即可进行调试
