### ISSUE TITLE
关于大模型生成的知识图谱准确性的判断

### ISSUE THREAD

**Issue by Sangs3112** [zjunlp/DeepKE#575]
您好，我现在有一张纯人工做的的质量较高的知识图谱；然后还有用开箱即用的模型生成的一张知识图谱。我想知道有什么方法或者指标可以评价大模型生成出的知识图谱的质量。假设可以把人工生成的知识图谱作为ground truth

**Comment by zxlzr** [comment]
1. 您可以使用一些图匹配算法来匹配2个图谱
2. 您可以从图谱采样出三元组，对三元组进行匹配或人工核验

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
