### ISSUE TITLE
模型选择

### ISSUE THREAD

**Issue by whwususu** [zjunlp/DeepKE#576]
您好！请教您几个问题：
1、我看到了除了bert基础模型，还有基于bert模型训练出来的cnSchema模型外，还有[LightNER(COLING'22)]、 [W2NER(AAAI'22)] 、[KnowPrompt(WWW'22)], [PRGC(ACL'21)], [PURE(NAACL'21)]等模型，作为中文提取，哪个模型最优？或者能否基于cnSchema模型继续训练和微调。从目前看，是基于bert训练后的提取率高，还是大模型oneke较好？
2、对于bert训练的脚本都看到了，实际训练完成后，如果对外提供接口来抽取知识图谱，这个介绍文档是否有？有的话，麻烦告诉我一下，谢谢！

**Comment by zxlzr** [comment]
1 没有最优模型，各个场景下有高质量数据情况下不同模型都可以取得好效果，lightner侧重低资源ner、w2ner是通用ner、knowprompt侧重低资源关系抽取、prgc/pure侧重三元联合抽取

2 您好，我们只提供抽取功能，对外服务接口你可以自行开发开放接口，暂时不支持这个

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by whwususu** [comment]
> 请问您还有其他问题吗？

没有了，谢谢啊，我现在就是苦于到底是用oneke还是用bert这种模型，主要是做一个领域的业务抽取
