### ISSUE TITLE
超参数设置问题

### ISSUE THREAD

**Issue by yccckid** [zjunlp/DeepKE#577]
**Describe the question**
> A clear and concise description of what the question is.

请问LightNER中的hidden state与word embedding融合的超参数在代码中哪个地方设置的？谢谢

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by njcx-ai** [comment]
您好，感谢您对我们项目的关注。请问“hidden state与word embedding融合“具体是指哪一块内容呢？

**Comment by yccckid** [comment]
您好，感谢您拨冗回复。就是encoder部分的输出和encoder编码结果，进行一个element-wise add操作，这里面的一个alpha。论文中的式（6），见附件图片。感谢您的及时回复。
![q](https://github.com/user-attachments/assets/30424067-5083-4041-b77f-78e1dc1c452d)

**Comment by njcx-ai** [comment]
好的，收到您的具体问题，我们最近将回顾一下原始代码来给您具体回复。

**Comment by yccckid** [comment]
非常感谢，期待您的回复

**Comment by njcx-ai** [comment]
您好，公示（6）的具体操作见如下链接的代码位置，其中这里alpha默认为0.5
https://github.com/zjunlp/DeepKE/blob/9a9f8343a1e4f8315f38289c316a47b7b1acf2d9/src/deepke/name_entity_re/few_shot/models/model.py#L195

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
