### ISSUE TITLE
大模型支持千问2.0或者llama3.0么

### ISSUE THREAD

**Issue by whwususu** [zjunlp/DeepKE#578]
您好！除了支持Oneke外，是否还支持千问2.0或者llama3.0呢？使用和训练方式应该是一样的吧？谢谢！

**Comment by BeasterYong** [comment]
您好，我们提供了对于llama模型的支持，对于qwen模型我们会在后续补充相关内容，感谢您的关注~

**Comment by whwususu** [comment]
> 您好，我们提供了对于llama模型的支持，对于qwen模型我们会在后续补充相关内容，感谢您的关注~

嗯，支持llama3么。如果自己想用其它大模型，是不是要训练InstructionKGC指令驱动，谢谢！
