### ISSUE TITLE
不同任务类型选择的schema数量

### ISSUE THREAD

**Issue by yjwww** [zjunlp/DeepKE#579]
**Describe the question**
> A clear and concise description of what the question is.

推荐的任务切分数量依任务而异：NER建议为6，RE、EE、EET、EEA均推荐为4、KG推荐为1，比如在微调和推理时KG任务的schema是否只能使用一个，在数据转化时只生成一个schema，我想抽取多个schema的KG应该怎么操作更合适？谢谢

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by guihonghao** [comment]
KG的schema如下所示
```python
"schema": [
    {
        "entity_type": "人物", 
        "attributes": [ "中文名","英文名","祖籍","出生日期","出生地点","职业", "毕业学校", "作品","奖项"]
    }
    ]
```
如果要抽取多个schema可以把它拆分成多条指令，每条指令只有一个schema。
推荐的切分长度更符合OneKE等模型的训练数据集，如果你做了下游的继续训练，可以设置自定义的长度，训练以后的推理可以按照自定义的长度来。

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by yjwww** [comment]
没有了，谢谢
