### ISSUE TITLE
Schema疑惑

### ISSUE THREAD

**Issue by whwususu** [zjunlp/DeepKE#580]
您好！我在说明文档中看到了InstructIE,里面的schema_zh.json
![image](https://github.com/user-attachments/assets/76ff360f-87ab-4331-9b91-b8bc668421e4)
那么，我是不是可以这样理解，可以自己加类别，现在有12个，自己加的类别必须经过训练和调优后才能有效。
谢谢！

**Comment by guihonghao** [comment]
可以增加类别，OneKE对于新增类别有一定泛化性，但从更好的该新增类别的抽取效果考虑，应该进一步训练调优。

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by whwususu** [comment]
没有了，谢谢
