### ISSUE TITLE
InstructIE schema困惑

### ISSUE THREAD

**Issue by zly0614** [zjunlp/DeepKE#581]
**Describe the bug**
>json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)
在使用
python ie2instruction/convert_func.py \
    --src_path data/InstructIE/train_zh_plus.json \
    --tgt_path data/InstructIE/train.json \
    --schema_path data/InstructIE/schema_zh.json \
    --language zh \
    --task KG \
    --split_num 1 \       
    --random_sort \
    --split train
脚本进行数据格式的转换时出现此类错误

随后使用过KG文件目录下的schema测试，并没有错误。KG目录下的schema中只有一个主题。而InstructIE的schema格式如下
{
    "事件": [
        [
            "事件_参与者_人物/组织",
            "事件_发生地点_地理地区",
            "事件_发生时间_时间",
            "事件_别名_事件",
            "事件_赞助者_人物/组织",
            "事件_伤亡人数_度量",
            "事件_起因_文本",
            "事件_导致_文本",
            "事件_主办方_组织",
            "事件_所获奖项_专业",
            "事件_获胜者_人物/组织"
        ],
        [
            "参与者",
            "发生地点",
            "发生时间",
            "别名",
            "赞助者",
            "伤亡人数",
            "起因",
            "导致",
            "主办方",
            "所获奖项",
            "获胜者"
        ]
    ],
    "自然科学": [
        [
            "产品_别名_产品",
            "产品_组成_产品",
            "产品_生成物_产品",
            "产品_产地_地理地区",
            "产品_发现者或发明者_人物/组织",
            "产品_名称由来_文本",
            "产品_用途_文本"
        ],
        [
            "别名",
            "组成",
            "生成物",
            "产地",
            "发现者或发明者",
            "名称由来",
            "用途"
        ]
    ]}
InstructIE不能多个主题一起转换吗？

**Comment by guihonghao** [comment]
KG指令的schema文件应该是下面这种格式，目前仅支持单个领域
```
["人物_别名_人物", "人物_出生地点_地理地区", "人物_出生日期_时间", "人物_死亡地点_地理地区", "人物_国籍_地理地区", "人物_职业_专业", "人物_作品_产品", "人物_成就_专业", "人物_籍贯_地理地区", "人物_职务_专业", "人物_配偶_人物", "人物_父母_人物", "人物_所属组织_组织", "人物_死亡日期_时间", "人物_兄弟姊妹_人物"]
["别名", "出生地点", "出生日期", "死亡地点", "国籍", "职业", "作品", "成就", "籍贯", "职务", "配偶", "父母", "所属组织", "死亡日期", "兄弟姊妹"]
{"人物": ["别名", "出生地点", "出生日期", "死亡地点", "国籍", "职业", "作品", "成就", "籍贯", "职务", "配偶", "父母", "所属组织", "死亡日期", "兄弟姊妹"]}
```
多个主题转换你可以修改我们的代码https://github.com/zjunlp/DeepKE/blob/main/example/llm/InstructKGC/ie2instruction/convert/processer/kg_processer.py、https://github.com/zjunlp/DeepKE/blob/main/example/llm/InstructKGC/ie2instruction/convert/converter/kg_converter.py，或者自己写一个数据转换代码，很容易的。

**Comment by guihonghao** [comment]
["头实体类型_属性_尾实体类型", ]
["属性", ]
{"主题/领域/实体类型": ["属性", ]}
仅第二、三行是必须的，第一行可以为空列表[]

**Comment by zly0614** [comment]
好的，谢谢
