### ISSUE TITLE
knowlm-13b-ie模型直接推理遇到bug，楼主昨天的fix_tokenizer还存在bug

### ISSUE THREAD

**Issue by shenshaowei** [zjunlp/DeepKE#582]
Hi，我按照modelscore教程，处理process.json数据，然后下载knowlm-13b-ie模型直接推理
CUDA_VISIBLE_DEVICES="5" **python src/inference.py** --model_name_or_path 'model/knowlm-13b-ie' --model_name 'llama' --input_file 'data/NER/processed.json' --output_file 'results/ner_test.json' --output_dir 'results' --fp16 --bits 4
错误1，需要添加参数--output_dir 'results'
错误2，**如果不在loader的tokenizer的参数加特殊符号，直接报错**，报错信息：
  File "/data/miniconda3/envs/deepke/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 349, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
  File "/data/miniconda3/envs/deepke/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 356, in _convert_token_to_id_with_added_voc
    return self.unk_token_id
  File "/data/miniconda3/envs/deepke/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1206, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
  File "/data/miniconda3/envs/deepke/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1072, in unk_token
    return str(self._unk_token)
RecursionError: maximum recursion depth exceeded while getting the str of an object
但如果自己尝试添加：
    tokenizer = tokenizer_class.from_pretrained(
        model_args.model_name_or_path,
        use_fast=model_args.use_fast_tokenizer,
        split_special_tokens=model_args.split_special_tokens,
        padding_side="left",
        `unk_token = "<unk>",`
        `bos_token = "<s>",`
        `eos_token = "</s>",`
        **config_kwargs  # 将 config_kwargs 放在最后
    )
    但是输出是乱七八糟的，好像跟输入完全没任何关系，我不知道特殊字符需要什么，求楼主告知，可见代码里的fix_tokenizer没起任何作用：
以下是楼主你昨天的更新，我直接放进tokenizer也是报错，求更新代码完善特殊字符部分
        # Fix tokenizer
    if tokenizer.bos_token_id is None:
        tokenizer.bos_token = "<|beginoftext|>"
    
    if tokenizer.eos_token_id is None:
        tokenizer.eos_token = "<|endoftext|>"
        logger.info("Add eos token: {}".format(tokenizer.eos_token))

    if tokenizer.pad_token_id is None:
        tokenizer.pad_token = tokenizer.eos_token
        logger.info("Add pad token: {}".format(tokenizer.pad_token))
     求更新代码，十分感谢

**Comment by guihonghao** [comment]
```bash
CUDA_VISIBLE_DEVICES=0 python src/inference.py \
    --stage sft \
    --model_name_or_path '/nature/ghh/alpaca-lora/models/knowlm-13b-ie' \
    --model_name 'llama' \
    --template 'alpaca' \
    --do_predict \
    --input_file 'data/NER/processed.json' \
    --output_file '/nature/ghh/alpaca-lora/llama2-7b-chat-lora.json' \
    --finetuning_type lora \
    --output_dir 'lora/test' \
    --predict_with_generate \
    --cutoff_len 512 \
    --bf16 \
    --max_new_tokens 300 \
    --bits 4
```
使用上述配置输出正常。
<img width="616" alt="image" src="https://github.com/user-attachments/assets/22f56ec2-47a2-4c43-a475-1954b00ff318">
参考InstructKGC/kg2instruction目录进行knowlm-13b-ie模型输入数据的转换。knowlm-13b-ie目前已不再维护，建议使用我们最新的模型OneKE https://huggingface.co/zjunlp/OneKE

**Comment by shenshaowei** [comment]
我在tokenizer加了        'unk_token = "<unk>"',        
    即tokenizer = tokenizer_class.from_pretrained(
        model_args.model_name_or_path,
        use_fast=model_args.use_fast_tokenizer,
        split_special_tokens=model_args.split_special_tokens,
        padding_side="left",
        'unk_token = "<unk>"',        
        **config_kwargs  # 将 config_kwargs 放在最后
    )
    可以运行了，运行还是# 运行Python脚本
python src/inference.py \
    --model_name_or_path '/data3/shensw/knowlm-13b-ie' \
    --model_name 'llama' \
    --input_file 'data/NER/processed.json' \
    --output_file 'results/ner_test.json' \
    --output_dir 'results' \
    --fp16 \
    --bits 4
    这样可以么，需要补充 'unk_token = "<unk>"',

**Comment by shenshaowei** [comment]
谢谢，我会参考新的模型的

**Comment by shenshaowei** [comment]
如果tokenizer里的unk_token不赋值，楼主给的代码还是报错，能否告知unk_token需要赋什么值，我给的<unk>

**Comment by guihonghao** [comment]
unk_token没有赋值为tokenizer.pad_token即可

**Comment by shenshaowei** [comment]
请问要继续微调OneKE模型的话用这条命令就可以吗？可以自己根据需求建立新的数据集继续训练OneKE吗，训练和推理假如要做NER，是训练数据外的实体，是不是要在schema_path data/NER/schema.json添加？另外，OneKE是什么底座？ 
output_dir='lora/oneke-continue'
mkdir -p ${output_dir}
CUDA_VISIBLE_DEVICES="0,1,2,3" torchrun --nproc_per_node=4 --master_port=1287 src/finetune.py \
    --do_train --do_eval \
    --overwrite_output_dir \
    --model_name_or_path 'models/OneKE' \
    --stage 'sft' \
    --model_name 'llama' \
    --template 'llama2_zh' \
    --train_file 'data/train.json' \
    --valid_file 'data/dev.json' \
    --output_dir=${output_dir} \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 4 \
    --preprocessing_num_workers 16 \
    --num_train_epochs 10 \
    --learning_rate 5e-5 \
    --max_grad_norm 0.5 \
    --optim "adamw_torch" \
    --max_source_length 400 \
    --cutoff_len 700 \
    --max_target_length 300 \
    --evaluation_strategy "epoch" \
    --save_strategy "epoch" \
    --save_total_limit 10 \
    --lora_r 64 \
    --lora_alpha 64 \
    --lora_dropout 0.05 \
    --bf16 \
    --bits 4

**Comment by guihonghao** [comment]
你好，OneKE的底座采用的是 https://huggingface.co/hfl/chinese-alpaca-2-13b
可以自己根据需求建立新的数据集，数据格式及处理参考https://github.com/zjunlp/DeepKE/tree/main/example/llm/InstructKGC#-2data
data/NER/schema.json中是训练指令中需要的schema，根据抽取需求调整

**Comment by guihonghao** [comment]
ZJUNLP/OneKE使用的微调数据比ZJUNLP/knowlm-13b-ie更多，性能更好（远好于）。具体使用方法参考https://github.com/zjunlp/DeepKE/blob/main/example/llm/OneKE_old.md。

**Comment by guihonghao** [comment]
“NER任务推荐的schema是6对吧？”是推荐的schema切分长度，建议一条指令中的schema数量不超过6。如果一个数据集的schema数量是18，建议分成3条指令询问LLM，每条指令包含6个schema，最后把3条指令的答案汇总成最终答案。
训练数据转换代码，split_num参数可设置schema切分长度。
<img width="1082" alt="image" src="https://github.com/user-attachments/assets/d7809a04-1b84-4cc5-82dc-6d62e5f1acb1">

**Comment by shenshaowei** [comment]
大佬。我统计了我想微调的NER数据集的Entity类型，一共有18个label，请问一下大佬之前训练那么多不同数据集的时候，split_num是不是都是取6，那比如我有两个数据，Entity各有6个label，一是编号、时间、疾病、药物、身体、地点；二是医学检验项目、年龄、地址、人名、价格、科室，这样我训练时的schema是按顺序统一设置成所有Entity的总和：编号、时间、疾病、药物、身体、地点、医学检验项目、年龄、地址、人名、价格、科室，是这样吗？
这样一来每次训练预测都不一样，比如我schema设置编号、时间、疾病、药物、身体、地点、医学检验项目、年龄、地址、人名、价格、科室，按照代码会被切分成了两次识别，一是预测前6个，二是预测后6个，这样的话，是最后把三次的预测结果合成一个数据，再拿来跟数据的groundtruth做一次计算损失？还是计算三次？
在训练上的策略需要大佬指点下

**Comment by guihonghao** [comment]
计算三次

**Comment by guihonghao** [comment]
切分只是在数据处理做了优化，即18个schema会被切分成3条指令，每条包含6个scheme。训练上没有优化，3条指令分别与其ground truth计算损失。

**Comment by shenshaowei** [comment]
你好大佬，请问要继续微调OneKE模型的话支持单卡吗，我改为
output_dir='lora/oneke-continue'
mkdir -p ${output_dir}
CUDA_VISIBLE_DEVICES="0" torchrun --nproc_per_node=1 --master_port=1287 src/finetune.py
--do_train --do_eval
--overwrite_output_dir
--model_name_or_path 'models/OneKE'
--stage 'sft'
--model_name 'llama'
--template 'llama2_zh'
--train_file 'data/train.json'
--valid_file 'data/dev.json'
--output_dir=${output_dir}
--per_device_train_batch_size 2
--per_device_eval_batch_size 2
--gradient_accumulation_steps 4
--preprocessing_num_workers 16
--num_train_epochs 10
--learning_rate 5e-5
--max_grad_norm 0.5
--optim "adamw_torch"
--max_source_length 400
--cutoff_len 700
--max_target_length 300
--evaluation_strategy "epoch"
--save_strategy "epoch"
--save_total_limit 10
--lora_r 64
--lora_alpha 64
--lora_dropout 0.05
--bf16
--bits 4
爆了分布式训练的错误，lora和全量的单卡训练命令分别是什么

**Comment by zxlzr** [comment]
抱歉 目前暂时还没有

**Comment by shenshaowei** [comment]
大佬。目前我已用训练下面的代码训练完lora，我有几处疑问？
output_dir='lora/oneke-continue'
mkdir -p ${output_dir}
CUDA_VISIBLE_DEVICES=4 torchrun --nproc_per_node=1 --master_port=1287 src/finetune.py \
    --do_train --do_eval \
    --overwrite_output_dir \
    --model_name_or_path '/data3/shensw/model/OneKE' \
    --stage 'sft' \
    --model_name 'llama' \
    --template 'llama2_zh' \
    --train_file '/data3/shensw/DeepKE/example/llm/InstructKGC/data/NER/oneke_train_change.json' \
    --valid_file '/data3/shensw/DeepKE/example/llm/InstructKGC/data/NER/oneke_dev_change.json' \
    --output_dir=${output_dir} \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 16 \
    --gradient_accumulation_steps 4 \
    --preprocessing_num_workers 16 \
    --num_train_epochs 10 \
    --learning_rate 5e-5 \
    --max_grad_norm 0.5 \
    --optim "adamw_torch" \
    --max_source_length 400 \
    --cutoff_len 700 \
    --max_target_length 300 \
    --evaluation_strategy "epoch" \
    --save_strategy "epoch" \
    --save_total_limit 10 \
    --lora_r 64 \
    --lora_alpha 64 \
    --lora_dropout 0.05 \
    --bf16 \
    --bits 4
    ①训练时我设置--bits 4，这一步应该是量化处理，最后我在推理时使用--bits 16/32影响精度吗？
    ②训练完查看checkpoints的文件，checkpoints模型怎么和之前的结构不一样，难道要先执行那一步什么**合并基础模型+Lora导出**？但是我没看懂这一步，而且用下面代码时报错：
  python src/export_model.py \
 --model_name_or_path '/data3/shensw/model/OneKE' \
 --checkpoint_dir '/data3/shensw/DeepKE/example/llm/InstructKGC/lora/oneke-continue/checkpoint-18170' \
--export_dir '/data3/shensw/DeepKE/example/llm/InstructKGC/lora_results/oneke-lora' \
--stage 'sft' \
--model_name 'llama' \
--template 'llama3' \
--output_dir 'lora_results/test'
报错信息：AssertionError: Template llama3 does not exist.
这是我执行的训练好的LoRA模型代码：
CUDA_VISIBLE_DEVICES=4 python src/inference.py \
    --stage sft \
    --model_name_or_path '/data3/shensw/model/OneKE' \
    --checkpoint_dir 'lora/oneke-continue' \
    --model_name 'llama' \
    --template 'llama2' \
    --do_predict \
    --input_file 'data/NER/oneke_test_change.json' \
    --output_file 'results/oneke_train_change_lora_output.json' \
    --finetuning_type lora \
    --output_dir 'lora/test' \
    --predict_with_generate \
    --cutoff_len 512 \
    --bf16 \
    --max_new_tokens 300 \
    --bits 16
    训练完出来的模型文件好像还需要合成？和如何用训练好的模型推理这个过程感觉十分复杂，看了文档好久有点摸不着头脑，希望大佬能指导一下

**Comment by guihonghao** [comment]
①训练时我设置--bits 4，这一步应该是量化处理，最后我在推理时使用--bits 16/32影响精度吗？应该会有影响。
②训练完查看checkpoints的文件，checkpoints模型怎么和之前的结构不一样，难道要先执行那一步什么合并基础模型+Lora导出？--model_name 'llama'
--template 'llama3'需要与训练时保持一致。--model_name 'llama'
--template 'llama2_zh'
这样推理
```bash
CUDA_VISIBLE_DEVICES=4 python src/inference.py
--stage sft
--model_name_or_path '/data3/shensw/model/OneKE'
--checkpoint_dir 'data3/shensw/DeepKE/example/llm/InstructKGC/lora/oneke-continue/checkpoint-18170'
--model_name 'llama'
--template 'llama2'
--do_predict
--input_file 'data/NER/oneke_test_change.json'
--output_file 'results/oneke_train_change_lora_output.json'
--finetuning_type lora
--output_dir 'lora/test'
--predict_with_generate
--cutoff_len 512
--bf16
--max_new_tokens 300
--bits 16
```

**Comment by shenshaowei** [comment]
十分感谢，大佬帮了我很多，这个项目鲁棒性和泛化性很强，刚刚看run.py的def train，我发现我的每个checkpoints都有optimizer.pt 和 scheduler.pt，这应该是是与训练过程中相关的状态文件，pytorch_model.bin: 这是微调后的模型权重文件，但我没看到有pytorch_model.bin，分析了下代码，模型权重保存的逻辑是在评估过程中（if results['f1'] > best_dev_f1）才执行的，只有当当前的评估结果 F1-score 超过之前的最佳 F1-score 时，才会触发保存操作，但是每个checkpoints我都没看到pytorch_model.bin，我有完整执行完训练代码了，但跑了大佬刚给的命令，却可以运行？好神奇，可以解释一下吗，有点好奇

**Comment by guihonghao** [comment]
bits设置为4，为什么推理的输出速度反而还没有原本bits设置为16的OneKe快了？速度很慢，这是为何？量化以后推理速度变慢是正常的。
导出时--model_name 'llama'
--template 'llama3'需要与训练时保持一致。--model_name 'llama'
--template 'llama2_zh'
训练设置为bits 4，推理只能用bits 4

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
