### ISSUE TITLE
linux 安裝 conda环境报错Please use pip<24.1 if you need to use this version. INFO: 

### ISSUE THREAD

**Issue by yihanxiaoxiao** [zjunlp/DeepKE#583]
Please use pip<24.1 if you need to use this version.
INFO: pip is looking at multiple versions of hydra-core to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following yanked versions: 1.0.0, 1.0.1, 1.0.2, 2.0.0rc1, 2.0.0rc2, 2.0.0rc22, 2.0.0rc23, 2.0.0rc24, 2.0.0rc25, 2.0.0rc26, 2.0.0rc27, 2.0.0rc28, 2.0.0rc29, 2.0.1rc1, 2.0.1rc2, 2.0.1rc3, 2.0.1rc4, 2.0.1rc5, 2.2.0

最新的conda环境 安装 pip版本是24.2 安装deepke报错。deepke安装pip 版本24.0可以安装成功。官方有时间可以更新下安装文档了。

**Comment by zxlzr** [comment]
非常感谢指出问题，我们尽快更新文档
