### ISSUE TITLE
模型评估

### ISSUE THREAD

**Issue by thahhaa** [zjunlp/DeepKE#586]
> 
你好，我使用自己标注的数据进行RE任务，通过eval_func.py进行评估，总样本数，错误数都有，但其他结果一直为0，请问要怎么解决呢？

**Comment by zxlzr** [comment]
建议您看下case，模型是否预测正确，如果模型预测不正确建议您调试下超参数或使用更多数据训练看看。

**Comment by thahhaa** [comment]
我是训练前后都进行了评估，使用训练之后的权重可以出来数值，但是训练之前的一直结果都是0，请问这个是什么原因？

**Comment by zxlzr** [comment]
训练前您做过预测吗，如果训练前模型预测失败说明 训练前模型不具备您提供的数据的抽取能力，训练后具备了

**Comment by thahhaa** [comment]
我用的是RE任务，根据data里的格式生成的test数据，然后使用原模型进行了预测，label和output都有

**Comment by shenshaowei** [comment]
考察下数据转换的代码任务有没有选错

**Comment by guihonghao** [comment]
请贴出模型预测结果

**Comment by thahhaa** [comment]
已经解决了，感谢
