### ISSUE TITLE
OneKE使用流程

### ISSUE THREAD

**Issue by Bat-Reality** [zjunlp/DeepKE#588]
您好。

我目前想用OneKE大模型做关系抽取，想**从大量文档中自动构建知识图谱**。

由于我是第一次使用本项目，看了许久仍不太清楚使用流程，可否请您稍微描述一下**使用流程**呢？如果能附上代码或者调用代码流程，就太感谢了。

然后还想问一下，目前通过OneKE大模型做端到端的构建知识图谱效果如何，和小模型相比推荐哪个呢？

**Comment by guihonghao** [comment]
你好，参考 https://github.com/zjunlp/DeepKE/blob/main/example/llm/OneKE_old.md 这个文档教程。

**Comment by guihonghao** [comment]
> 请问您有使用该项目里面的模型成功构建知识图谱吗？如果有的话使用的哪个模型，具体流程是怎么样的？
使用OneKE模型 https://huggingface.co/zjunlp/OneKE
教程参考 https://github.com/zjunlp/DeepKE/blob/main/example/llm/OneKE_old.md

**Comment by Lcberggg** [comment]
能否对文档级别的数据集使用呢？
