### ISSUE TITLE
为什么在docker里部署，再进行第三步时说没有该文件夹呢

### ISSUE THREAD

**Issue by lfy2023** [zjunlp/DeepKE#589]
**Describe the question**
> A clear and concise description of what the question is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

![29367611_f90c649a-be73-41fc-fda6-0f5011c8fa02](https://github.com/user-attachments/assets/8d2779a7-ec95-48dd-b90e-148f84a26c5f)

**Additional context**
> Add any other context about the problem here.

**Comment by BeasterYong** [comment]
您好，看路径您现在已经在DeepKE目录下了，直接`cd example/re/standard` 就好

**Comment by zxlzr** [comment]
请问您的问题解决了吗？
