### ISSUE TITLE
模型推理至少需要多少显存，4bit量化后需要多少显存，文中提到的训练和推理至少需要20G是量化前还是量化后

### ISSUE THREAD

**Issue by litao321321** [zjunlp/DeepKE#590]
**Describe the question**
> A clear and concise description of what the question is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by guihonghao** [comment]
量化后
