### ISSUE TITLE
关于模型评估

### ISSUE THREAD

**Issue by Da1zheng** [zjunlp/DeepKE#593]
作者您好，我使用IEPile数据集切分出来部分数据作为测试集，测试结果经过推理脚本保存在results目录。

现在我想对这些测试结果（格式包含task，source，instruction，output字段）使用评估脚本eval_func.py进行评估，但是数据格式不正确（缺少id字段）导致评估脚本不能正常运行。请问怎么对IEPile切分出来的测试集进行评估呢

![image](https://github.com/user-attachments/assets/832b0189-4513-4b52-b8e2-afb93d0c5c48)

**Comment by guihonghao** [comment]
正常使用下面代码生成的测试指令数据带有`id`字段。`--split test`
```
python ie2instruction/convert_func.py \
    --src_path data/NER/sample.json \
    --tgt_path data/NER/test.json \
    --schema_path data/NER/schema.json \
    --language zh \
    --task NER \
    --split_num 6 \
    --split test
```

**Comment by zxlzr** [comment]
请问您的问题解决了吗？
