### ISSUE TITLE
使用llama3-8b-Instruct-iepile和chatglm3-6b在特定领域EE数据集进行继续微调，使用vllm进行infer结果全部为0

### ISSUE THREAD

**Issue by Azzz123** [zjunlp/DeepKE#596]
**Describe the question**
> A clear and concise description of what the question is.
chatglm：
![image](https://github.com/user-attachments/assets/4730704f-f693-47b2-a7a4-541769269f96)
![image](https://github.com/user-attachments/assets/b56c9937-055d-496b-801a-71bd2cfb0010)

llama：
![image](https://github.com/user-attachments/assets/a098d465-02e6-479c-acff-e865573387d2)
![image](https://github.com/user-attachments/assets/31bcb421-07a6-4dee-b709-a11e2f82fd35)

这是部分的vllm推理过程和全部推理结果

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]
llama的训练参数设置：
![image](https://github.com/user-attachments/assets/da5b9004-e91f-4a50-a6af-2abd0263a48d)

chatglm的训练参数设置：
![image](https://github.com/user-attachments/assets/38a6e739-7fdc-46cd-a473-8de106f6b2e3)

**Comment by Azzz123** [comment]
![image](https://github.com/user-attachments/assets/f10d0b68-8a6c-43c3-85a8-f1617c03281f)
这是chatglm的推理脚本，llama的除了路径不同，model_name设置为llama，template设置为aplaca，其他一致

**Comment by guihonghao** [comment]
尝试一下非vllm推理方式 https://github.com/zjunlp/DeepKE/blob/main/example/llm/InstructKGC/README_CN.md#611%E5%9F%BA%E7%A1%80%E6%A8%A1%E5%9E%8Blora

**Comment by Azzz123** [comment]
![image](https://github.com/user-attachments/assets/01c357b3-5766-40a1-844b-c62e098e52f3)
运行非vllm推理时查看日志有json decode报错 是这个原因吗？

**Comment by Azzz123** [comment]
非vllm大概推理了30条数据后还是全错
![image](https://github.com/user-attachments/assets/6d4f560b-5c65-4806-a5c9-a580973cd0ad)

**Comment by guihonghao** [comment]
检查train.json、valid.json中指令格式是否正确。鉴于训练脚步是从头训练，训练样本数量是否足够？是否应该混合别的数据集增加训练数据。且schema未中文化。

**Comment by Azzz123** [comment]
train.json和valid.json格式如下共12000+3000条数据，应该是和您代码的InstructKGC\data\EE\train.json中格式是一致的，您可以查看一下
我的：
![image](https://github.com/user-attachments/assets/d774eaaa-7d41-4f3a-bd27-75d15605ae74)

示例中：
![image](https://github.com/user-attachments/assets/0031d7b4-0f51-40eb-a5e1-48fbd32b6959)

我会将schema中文化后再尝试进行训练，期待您的回复

**Comment by guihonghao** [comment]
可能因为llama3和chatglm3架构模版问题，可以尝试其他开源训练框架用同一份数据训练。oneke训练脚本是怎样的？是否测过直接不训练oneke进行推理的结果？

**Comment by Azzz123** [comment]
没有直接推理试过，请问还有什么开源训练框架推荐吗？

**Comment by guihonghao** [comment]
> 没有直接推理试过，请问还有什么开源训练框架推荐吗？

LLM-Factory 、ms-swift

**Comment by Azzz123** [comment]
谢谢，另外我在合并导出qwen2.5-32B模型时失败了，终端输出信息如下
![image](https://github.com/user-attachments/assets/63f0340a-ebef-451a-950f-6f93abb88422)

**Comment by Azzz123** [comment]
直接不训练oneke进行推理的结果
![image](https://github.com/user-attachments/assets/212d3dc0-8834-46af-b202-7adbed7c316e)

**Comment by guihonghao** [comment]
> 谢谢，另外我在合并导出qwen2.5-32B模型时失败了，终端输出信息如下 ![image](https://private-user-images.githubusercontent.com/65334828/379665631-63f0340a-ebef-451a-950f-6f93abb88422.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTgwMjMsIm5iZiI6MTcyOTc1NzcyMywicGF0aCI6Ii82NTMzNDgyOC8zNzk2NjU2MzEtNjNmMDM0MGEtZWJlZi00NTFhLTk1MGYtNmY5M2FiYjg4NDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA4MTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ODY0NTg0MjE5MzNkZGJjOGRlZWQ5ZTRhM2ZjZTg0ZDA3Y2YzMzU4MmQwNmM3MTI4MTcxZTljOTI0ZDk3MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZBqZnyUb9YaH7HA9Ba_DA4QHROcDP5emwVVvADbMXH8)

可能空间不够

**Comment by Azzz123** [comment]
内存不足了是吗 磁盘空间应该是够得
