### ISSUE TITLE
关于关系抽取中关系类型与实体类型对应的问题

### ISSUE THREAD

**Issue by Danmo121** [zjunlp/DeepKE#597]
**Describe the question**
> 这里有一个简单的问题想咨询一下，在关系抽取中，从relation.csv来看，当前的数据格式时每2个实体类之间的关系是确定的只有一类，同时在README中指出也提示到“如果您使用的同一个关系存在多种实体类型，可以采取对实体类型加关系前缀的方式构造输入”，这应该也是为了保证不同种实体类型之间只包含特定的关系。在训练后，预测阶段需要还需要输入头实体和尾实体的类型，这样的话即使不需要训练，只要知道头实体和尾实体的类型，关系自然是明确的。我不太确定是我理解的那个环节有问题，所以想请教一下。

**Comment by zxlzr** [comment]
您好，句子里有2个实体及其类型，这两个实体不一定存在这个关系。例如  e1 和 e2 一同出游 ; e1 携夫人e2  一同出游，都出现e1 e2 人物实体，但只有第二句可以抽取关系  夫妻，第一句 关系是NA(无法识别关系)   请问您还有其他问题吗？

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
