### ISSUE TITLE
pip install -r requirements.txt gives an error 

### ISSUE THREAD

**Issue by ProphetMo** [zjunlp/DeepKE#599]
**Describe the question**
> A clear and concise description of what the question is.
环境是新的，然后给deepke安装依赖的时候，疑似版本好像有冲突，安装matplotlib的时候会报错，

![image](https://github.com/user-attachments/assets/a4e39537-127a-400b-bf54-560931a8aeac)

requirements.txt如下
torch==2.2.0
hydra-core==1.0.6
tensorboard==2.4.1
matplotlib==3.4.1
transformers==4.26.0
jieba==0.42.1
scikit-learn==0.24.1
seqeval==1.2.2
opt-einsum==3.3.0
wandb==0.12.7
ujson==5.6.0
huggingface_hub==0.11.0
tensorboardX==2.5.1
nltk==3.8
protobuf==3.20.1
numpy==1.21.0
ipdb==0.13.11
pytorch-crf==0.7.2
tqdm==4.66.1
openai==0.28.0
Jinja2==3.1.2
datasets==2.13.2
pyhocon==0.3.60

**Comment by BeasterYong** [comment]
您好，经过验证，我们安装上述版本的python包并没有遇到问题，您可以尝试更换pip代理或者更新pip版本后重试~

**Comment by zxlzr** [comment]
请问您的问题解决了吗？
