### ISSUE TITLE
你好，能不能提供数据

### ISSUE THREAD

**Issue by chenyangjun45** [zjunlp/deepke#6]
你好，能不能提供相应的数据，主要是为了跑通模型试一试，小规模的也行

**Comment by yuwl798180** [comment]
你好，中文抽取数据集目前比较少。
 [ccks2019](ccks2019.cn) 有关系抽取评测任务，贡献了一批数据集。
另外百度上半年有个相关比赛，也贡献了一批数据集，网址为：[baidu broad](http://ai.baidu.com/broad/download)。

如有需要，可以自行下载。

**Comment by yuwl798180** [comment]
稍后我会上传5000条采样的数据，方便跑模型。

**Comment by mrbulb** [comment]
@yuwl798180 您好，不好意思打扰一下，我想要获取《CCKS 2019 人物关系抽取》的数据集进行训练来着，但是上[相关网页](https://biendata.com/competition/ccks_2019_ipre/rules/?next_url=/competition/ccks_2019_ipre/data/)看了一下，貌似报名日期截止后就不能再查看数据了。所以想冒昧的问一下，您那边还有这个数据集的备份吗？是否方便分享一下呢？

**Comment by yuwl798180** [comment]
> @yuwl798180 您好，不好意思打扰一下，我想要获取《CCKS 2019 人物关系抽取》的数据集进行训练来着，但是上[相关网页](https://biendata.com/competition/ccks_2019_ipre/rules/?next_url=/competition/ccks_2019_ipre/data/)看了一下，貌似报名日期截止后就不能再查看数据了。所以想冒昧的问一下，您那边还有这个数据集的备份吗？是否方便分享一下呢？

你好，他们的数据集已经公开在[github](https://github.com/SUDA-HLT/IPRE)，使用时注意引用。

**Comment by mrbulb** [comment]
> > @yuwl798180 您好，不好意思打扰一下，我想要获取《CCKS 2019 人物关系抽取》的数据集进行训练来着，但是上[相关网页](https://biendata.com/competition/ccks_2019_ipre/rules/?next_url=/competition/ccks_2019_ipre/data/)看了一下，貌似报名日期截止后就不能再查看数据了。所以想冒昧的问一下，您那边还有这个数据集的备份吗？是否方便分享一下呢？
> 
> 你好，他们的数据集已经公开在[github](https://github.com/SUDA-HLT/IPRE)，使用时注意引用。

嗯嗯，好的好的，十分感谢
