### ISSUE TITLE
运行predict.py时报错No such file or directory: 'xxx/checkpoints/2019-12-03_17-35-30/cnn_epoch21.pth'

### ISSUE THREAD

**Issue by touchankawaii** [zjunlp/deepke#60]
**Describe the question**
> A clear and concise description of what the question is.

如题，请问如何解决呢

**Environment (please complete the following information):**
 - OS: windows10
 - Python Version 3.7

**Screenshots**
> If applicable, add screenshots to help explain your problem.

****
![image](https://user-images.githubusercontent.com/52189146/115183314-1f334580-a10e-11eb-8f21-892cfa45a35f.png)

**Additional context**
> Add any other context about the problem here.

**Comment by touchankawaii** [comment]
修改predict.py中的自定义路径即可

**Comment by lelechallc** [comment]
> 



> 修改predict.py中的自定义路径即可

你好，请问具体是哪个路径错误了

**Comment by lelechallc** [comment]
> 修改[https://github.com/zjunlp/DeepKE/blob/main/example/re/standard/conf/predict.yaml中的路径为训练后模型保存的路径。]

感谢！！
