### ISSUE TITLE
使用OneKE时，关于schema的问题

### ISSUE THREAD

**Issue by fzb0316** [zjunlp/DeepKE#600]
我现在想用使用OneKE生成一份知识图谱，但是我一定要定义一个schema吗？我需要首先进行NER任务，使用OneKE识别出来歧义的实体以消除歧义，然后在原文本中标记识别的实体，接下来使用OneKE输出相应的三元组。这一个流程需要定义两个schema，并且由于我的文本语料比较大，手动定义这个schema也是一个巨大的人工过程，请问有什么方法解决吗。

**Comment by fzb0316** [comment]
http://deepke.zjukg.cn/CN/re_doc_show.html请问在这个网站展示的技术中，标注文本时使用什么技术实现的，并且生成三元组序列的技术是OneKE吗，那schema是怎么定义的呢

**Comment by fzb0316** [comment]
[http://deepke.zjukg.cn/CN/re_doc_show.html 请问在这个网站展示的技术中，标注文本时使用什么技术实现的，并且生成三元组序列的技术是OneKE吗，那schema是怎么定义的呢]

**Comment by fzb0316** [comment]
好的好的，我了解了。 http://deepke.zjukg.cn/CN/re_doc_show.html 我还有一个问题，请问在这个网站展示的技术中，标注文本时使用什么技术实现的，并且生成三元组序列的技术是OneKE吗，那schema是怎么定义的呢

**Comment by zxlzr** [comment]
您好，标注文本是对数据中已有实体的可视化，识别实体可以使用ner技术，生成序列使用的是文档级关系抽取（如Document-level Relation Extraction as Semantic Segmentation），这个demo展示开发的时候大模型还没有出来。

**Comment by zxlzr** [comment]
请问您还有其他问题吗

**Comment by fzb0316** [comment]
感谢回复，我没有问题了
