### ISSUE TITLE
关于ner的standard方法评价指标

### ISSUE THREAD

**Issue by goldenblack2** [zjunlp/DeepKE#603]
请问standard下的ner方法bert和lstmcrf 是不是没写获得metrics的代码 ，别的任务tools文件夹下都有metrics文件

**Comment by BeasterYong** [comment]
您好，ner部分计算Metric的代码并没有列为一个单独文件，而是并入了训练的代码中，您可以查阅[相关代码](https://github.com/zjunlp/DeepKE/blob/af051b58c62e4b0a7e99793d24ecbd76484dd6ba/example/ner/standard/run_bert.py#L218)

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
