### ISSUE TITLE
国内网络一直报错无法访问bert模型资源

### ISSUE THREAD

**Issue by QWQyyy** [zjunlp/DeepKE#604]
你好，国内网络使用deepKE的任何功能，在默认情况下都是报错网络问题，
![image](https://github.com/user-attachments/assets/4328f82d-eb95-43d6-b507-4a3e458cc7e7)
我认为需要公布一下怎么对yaml文件做配置，不然我们根本不知道怎么通过yaml配置本地路径
我可以通过浏览器下载bert等模型到本地路径下，但是pycharm的网络访问一直不行
个人建议补充一下yaml中相关参数的设置，谢谢

**Comment by guihonghao** [comment]
推荐使用hugging face镜像网站，下载模型到本地
https://hf-mirror.com/

**Comment by fuzaizai666** [comment]
执行关系抽取中的低资源抽取模块时，也出现预训练模型bert下载不了的问题，下载模型存储在本地后，修改yaml文件中的model_name_or_path: 'bert-base-uncased'为本地存放路径后，出现了一个报错，报错的具体位置是DeepKE\src\deepke\relation_extraction\few_shot 中的get_label_word程序中的get_label_word函数，    with open(f"data/{model_name_or_path}.pt", "wb") as file:
        torch.save(t, file)
请问这个问题要怎么解决呀~

**Comment by zxlzr** [comment]
您好，在/DeepKE/example/ner/standard/conf/hydra/model/bert.yaml文件中的bert_model: 'bert-base-uncased'，修改模型名为本地模型存储路径即可。
Windows示例  bert_model: "D:\\models\\bert-base-chinese"
Linux示例         bert_model: "/home/user/models/bert-base-chinese"
建议根据您的具体环境使用 绝对路径，避免因工作目录的变化导致模型加载失败。
