### ISSUE TITLE
使用自己数据运行standard ner报错问题

### ISSUE THREAD

**Issue by Toblame** [zjunlp/DeepKE#605]
请教下为何使用自己的预料用bert模型按照步骤抽取实体时会报如下错误，用仓库给的兵马俑例子可以跑通
![image](https://github.com/user-attachments/assets/009fecf4-0364-4a57-b7ed-cd3136e9d0c8)

**Comment by zxlzr** [comment]
报错信息为assert 即token个数和label个数不一致，建议检查是否输入有特殊字符、空格等，换一句话试一试，如果换一句是可以正常运行的，建议您优化输入文本。

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by Toblame** [comment]
谢谢你的回复，暂时没有其他问题啦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月21日(周四) 下午2:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zjunlp/DeepKE] 使用自己数据运行standard ner报错问题 (Issue #605)




 
请问您还有其他问题吗？
