### ISSUE TITLE
请问那个document级别的关系抽取，如果是用在中文任务上，可以用什么预训练模型呢？

### ISSUE THREAD

**Issue by Timmy-love-you** [zjunlp/DeepKE#606]
请问那个document级别的关系抽取，如果是用在中文任务上，可以用什么预训练模型呢？
原指定的roberta-base好像只能用在英文任务上。

**Comment by zxlzr** [comment]
您可以使用https://github.com/ymcui/Chinese-BERT-wwm  上面的中文bert或roberta等模型

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
