### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'length'

### ISSUE THREAD

**Issue by HeYuLi123** [zjunlp/DeepKE#607]
**Describe the bug**
> 在利用OneKE模型进行“4.10领域内数据继续训练”的过程中，出现了如下的问题：
![image](https://github.com/user-attachments/assets/58c181c9-a88b-49a3-ac33-ae05c3c72940)

**Environment (please complete the following information):**
 - OS: Windows 10 家庭版
 - Python Version 3.9.20
- require：完全按照 example/llm文件夹下的requirements.txt 的版本要求
- NVIDIA： GeForce RTX 3060

**Screenshots**
> 

**Additional context**
> 训练的指令如下：
`python src/finetune.py --do_train --do_eval --model_name_or_path models/OneKE --stage sft --model_name llama --template llama2_zh --train_file data/NER/train.json --val_set_size 100 --output_dir result --per_device_train_batch_size 2 --per_device_eval_batch_size 2 --gradient_accumulation_steps 4 --preprocessing_num_workers 16 --num_train_epochs 10 --learning_rate 5e-5 --max_grad_norm 0.5 --optim adamw_torch --max_source_length 400 --cutoff_len 700 --max_target_length 300 --evaluation_strategy epoch --save_strategy epoch --save_total_limit 10 --lora_r 64 --lora_alpha 64 --lora_dropout 0.05 --bf16 --bits 4`

我尝试了移除length字段，确保传递给inputs没有这个参数，能够正常进行训练，但这样会不会这样逻辑上有啥错误？
期待大神能够指点一下~

**Comment by guihonghao** [comment]
你好，我们最新的代码中不会传入length字段。不传入length给inputs不会有逻辑错误。

**Comment by HeYuLi123** [comment]
好的好的，非常感谢~
