### ISSUE TITLE
缺少dict文件？

### ISSUE THREAD

**Issue by 963603132** [zjunlp/DeepKE#609]
**Describe the bug**
> A clear and concise description of what the bug is.
看起来似乎是在这个文件夹下缺少对应的文件。在DUEE里只有readme，在ACE里有trigger_tag，但是为json格式，是不是代码修改了但是对应的文件没有上传？请帮助解决，非常感谢！！

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]
 - python 3.8
 - OS:WINDOWS

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![微信图片_20241205100548](https://github.com/user-attachments/assets/4ac8752d-61b6-4300-8b3d-d5543f659282)

**Additional context**
> Add any other context about the problem here.

**Comment by 963603132** [comment]
DeepKE-main\DeepKE-main\example\ee\standard\data\ACE\schema这个文件夹里面有trigger_tag.json，但DeepKE-main\DeepKE-main\example\ee\standard\data\DUEE只有readme文件

**Comment by shengyumao** [comment]
你好～
你需要在DeepKE-main\DeepKE-main\example\ee\standard\data\DUEE目录下，执行一下README.md文件中的命令去下载一下DuEE数据集，即执行下面的命令
```bash
wget 120.27.214.45/Data/ee/DuEE.zip
unzip DuEE.zip
```
下载完后就可以运行DUEE相应代码了

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
