### ISSUE TITLE
Bert模型存放位置

### ISSUE THREAD

**Issue by fuzaizai666** [zjunlp/DeepKE#611]
您好哇，请问ner standard 任务中本地下载的bert-base-chinese模型要放在哪里？

**Comment by LiamLYYY** [comment]
您好，在/DeepKE/example/ner/standard/conf/hydra/model/bert.yaml文件中的bert_model: 'bert-base-uncased'，修改模型名为本地模型存储路径即可

**Comment by LiamLYYY** [comment]
您好，在/DeepKE/example/ner/standard/conf/hydra/model/bert.yaml文件中的bert_model: 'bert-base-uncased'，修改模型名为本地模型存储路径即可

**Comment by zxlzr** [comment]
请问您的问题解决了吗
