### ISSUE TITLE
dacoco跨段落标记问题

### ISSUE THREAD

**Issue by whwususu** [zjunlp/DeepKE#612]
你好，dacoco打标的时候，垮了段落，比如实体1在段落1，客体在段落5。我们直接识别实体，然后根据预设的schema，去引导组合实体，形成关系，除了这种方式，还有不有其它好办法啊，谢谢！

**Comment by zxlzr** [comment]
您好，感谢关注deepke，我也没有其他好的想法。

**Comment by whwususu** [comment]
> 您好，感谢关注deepke，我也没有其他好的想法。

好的，谢谢，也不知道大家是怎么做的
