### ISSUE TITLE
模型权重参数不匹配问题

### ISSUE THREAD

**Issue by likang123456789** [zjunlp/DeepKE#614]
**Describe the bug**
> A clear and concise description of what the bug is.
Traceback (most recent call last):
  File "run_bert.py", line 118, in main
    model = TrainNer.from_pretrained(cfg.bert_model,from_tf = False,config = config)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2478, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2844, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for TrainNer:
        size mismatch for classifier.weight: copying a param with shape torch.Size([60, 768]) from checkpoint, the shape in current model is torch.Size([10, 768]).
        size mismatch for classifier.bias: copying a param with shape torch.Size([60]) from checkpoint, the shape in current model is torch.Size([10]).
        You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.
当我运行ner任务中run_bert.py文件，试图加载RoBERTa-wwm-extChinese预训练模型时，提示该报错，运行predict.py文件无影响

**Comment by likang123456789** [comment]
非常感谢官方给出了回答，目前已经排查到了问题出现的原因
大致原因如下：
官方提供的RoBERTa-wwm-ext模型识别的实体类型数量为28个，对classifier.weight的sahpe要求出现  28*2+4=60
因为我采用了自己的数据集，需要的识别的实体类型为3个，对classifier.weight的sahpe要求出现  3*2+4=10，导致了与RoBERTa-wwm-ext模型要求不匹配的问题。对于该问题，不知官方是否有解决方案。
目前我思考如下：
1.无视不匹配的问题，考虑添加 ignore_mismatched_sizes=True 参数来忽略尺寸不匹配的问题
2.修改我的labels，添加无意义实体类型，将实体类型进行扩充至28个
3.修改模型结构，使其接受的实体类型改为3

**Comment by zxlzr** [comment]
https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/conf/train.yaml  可以试试修改下labels: ['LOC','ORG','PER']

**Comment by zxlzr** [comment]
请问您的问题解决了吗？

**Comment by likang123456789** [comment]
> Have you solved your problem?

Hello, for your proposal to modify the labels scheme, and can not change the occurrence of the error, at present, I added ignore_mismatched_sizes=True parameter, ignoring the mismatch problem, so that the code can run normally

Also I took your initial advice and tried to train my data using the [bert-base-chinese] pre-trained model and encountered the same problem as isssues4, fi, and recall were both 0,> 请问您的问题解决了吗？

您好，对于您提出的修改labels方案，并不能改变该错误的发生，目前，我添加了ignore_mismatched_sizes=True 参数，无视了不匹配的问题，使得代码可以正常运行，并且训练数据

此外我接受了您最初的建议，还尝试了使用[bert-base-chinese]预训练模型训练自己数据，但遇到了和isssues4一样的问题，fi，和召回率均为0，     现在我正在按照issues4问题的提出者说的方案，改变学习率和epoch，尝试训练数据及使用wandb检测loss变化。

希望官方能早日优化代码，更好的适配bert模型

**Comment by zxlzr** [comment]
抱歉，我们会尽快优化。

**Comment by zxlzr** [comment]
https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/README_CN.md   我们已更新readme便于大家使用bert训练ner模型，如有任何问题欢迎提issue
