### ISSUE TITLE
关系抽取data里relation.csv

### ISSUE THREAD

**Issue by woshifln** [zjunlp/DeepKE#617]
**Describe the question**
> A clear and concise description of what the question is.
你好，想询问一些问题：
①：relation.csv原本有一些关系数据，如果需要的关系 不包含在这个文件里，怎么添加需要的关系？可以直接手动在文件里添加吗？如果可以手动添加，需要重现训练模型吗？
②：进行关系抽取，只能抽取出relation.csv所含有的关系吗
③：ae下data里的attribute.csv也是跟relation.csv同样的原理吗

**Environment (please complete the following information):**
 - OS: Linux-Ubuntu20.04
 - Python Version:3.8.20

**Comment by zxlzr** [comment]
感谢关注deepke 

1 可以加 需要重训
2 是的
3 是的

**Comment by woshifln** [comment]
你好，还有一个问题，我在进行实体识别时，使用bert,运行run_bert.py时显示已杀死ion是什么原因

**Comment by zxlzr** [comment]
请打出完整信息

**Comment by woshifln** [comment]
![1](https://github.com/user-attachments/assets/cc0cce2d-3501-4523-863e-c77a96b27bb2)

**Comment by zxlzr** [comment]
请换个机器或gpu 试试，感觉是本地环境问题

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by woshifln** [comment]
暂时没有了，谢谢

**Comment by woshifln** [comment]
关于运行run_bert.py会显示已杀死ion我重新建了个环境还是会这样报错哎，运行ee里的进行事件抽取也会报这样的错。关于运行run_bert.py进行实体识别我前天有运行训练一次但由于太慢，中途我给它停掉了，没运行完，然后昨天我又重新运行它就不行了。这该怎么办啊

**Comment by zxlzr** [comment]
我们没有遇到过类似的情况，建议您换个机器试试，您用的是gpu吗？

**Comment by woshifln** [comment]
换台电脑吗？我试试吧。不是gpu，我用的是VMware+ubuntu22.04，它这个显卡是虚拟出来的，VMware基于主机的显卡虚拟映射出了一个供uhuntu系统使用的显卡，这个显卡没有合适的驱动去实现基于GPU的深度学习环境搭建

**Comment by zxlzr** [comment]
建议您直接用cpu 试试 配置文件里改cpu就可以

**Comment by woshifln** [comment]
![2](https://github.com/user-attachments/assets/cb6197a4-1ee3-45bf-8282-8be792ca4e09)
不好意思，这个我不太懂，该成cpu是直接在train.yaml这个地方把gpu改成cpu吗

**Comment by zxlzr** [comment]
是的 改False  cpu会比gpu慢一些

**Comment by woshifln** [comment]
![3](https://github.com/user-attachments/assets/cb4b9449-29d1-49d1-b09d-8428d1017a97)
完了，改了也不行☹
![4](https://github.com/user-attachments/assets/06c64c20-27d1-4c0b-870d-818064711886)

**Comment by zxlzr** [comment]
可能是您环境问题吧  我们多次尝试没有遇到这种情况
