### ISSUE TITLE
想问下关于NER训练相关问题

### ISSUE THREAD

**Issue by zokgo** [zjunlp/DeepKE#618]
您好，首先非常感谢DeepKE团队做出的成果，于我们而言非常有用，有一些关于NER模型训练的细节问题想请教下：
1.开箱即用的基于bert的NER使用的训练数据是[https://drive.google.com/drive/folders/1zA8Ichx9nzU3GD92ptdyR_nmARB_7ovg](url)这里的数据嘛？我在使用提供的训练数据训练时发现，训练数据中有LOC的类型，而type.txt中没有。
![image](https://github.com/user-attachments/assets/8deaa804-3b0d-418e-94b0-8c37de37346a)
2.如果不是，可否提供使用的训练数据及标签组？
期待您的回复

**Comment by zxlzr** [comment]
您好，数据在readme上有提到的

wget 120.27.214.45/Data/ner/standard/data.tar.gz
tar -xzvf data.tar.gz

不知道您发的google drive 是哪个

**Comment by zxlzr** [comment]
https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/README_CN.md

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
