### ISSUE TITLE
请问预测时，能否不指定head和tail直接输出{实体A，实体B，关系}呢

### ISSUE THREAD

**Issue by touchankawaii** [zjunlp/DeepKE#62]
**Describe the question**
> A clear and concise description of what the question is.

如题

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by tlk-dsg** [comment]
deepke不行，另一个工具openue可以，https://github.com/zjunlp/OpenUE

**Comment by Brodong** [comment]
> deepke不行，另一个工具openue可以，https://github.com/zjunlp/OpenUE

感谢，正好要找该工具
