### ISSUE TITLE
bi_lstm.py中没有attention部分

### ISSUE THREAD

**Issue by ZJL0111** [zjunlp/DeepKE#64]
**Describe the question**
> A clear and concise description of what the question is.

bi_lstm.py中没有找到attention部分，但您的介绍里写的是用了Attention-Based Bidirectional Long Short-Term Memory Networks for Relation Classification中的网络结构的。

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/19632448/116212048-04e51180-a777-11eb-88e0-4af8ce1015c6.png)

**Additional context**
> Add any other context about the problem here.

**Comment by tlk-dsg** [comment]
具体以所给代码为准
