### ISSUE TITLE
如何使用该框架进行混合精度训练？

### ISSUE THREAD

**Issue by LiXuanming** [zjunlp/DeepKE#66]
**Describe the question**
> A clear and concise description of what the question is.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by tlk-dsg** [comment]
暂时还没这方面的研究，您可以自己尝试一下
