### ISSUE TITLE
缺少bert_vocab.txt文件

### ISSUE THREAD

**Issue by idleuncle** [zjunlp/deepke#7]
<img width="594" alt="Screen Shot 2019-09-11 at 3 27 31 PM" src="https://user-images.githubusercontent.com/23009769/64676762-e0a4c600-d4a8-11e9-9ddf-cdfa13240225.png">
缺少main.py中定义的bert_vocab.txt文件

**Comment by yuwl798180** [comment]
你好，之前调用bert使用的是 pytorch-transoformer 的文件。这个程序有个bug就是本地使用Bert无法正确读取文件。已经提交pr，现在最新版（1.2.0）以修改bug。
稍后会重构下这块代码。
另外更建议使用哈工大最近发布的Chinese-BERT-wwm，效果更好一些，而且模型上传到了讯飞云，下载速度也快很多。稍后也会写在备注中。

**Comment by Naplues** [comment]
你好，更新的代码里是不是把bert模型的代码忘了呢

**Comment by StCross** [comment]
> 你好，更新的代码里是不是把bert模型的代码忘了呢

你好，请问你本地跑bert遇到问题了吗，我是无法读取bert_config.json
