### ISSUE TITLE
关于实体类型的问题咨询

### ISSUE THREAD

**Issue by UserJTZhang** [zjunlp/DeepKE#70]
你好，非常感谢在项目上的付出与努力，目前我正在研究关系抽取的决定因素，发现识别的准确率和输入的实体类别（head_type和tail_type）也有很大的关系，可是我在抽取的时候并不能提前知道类型的列表，以至于无法准确的输入实体的类别，因此会造成模型误差。找了很久没有找到，希望可以得到完整的类型列表（人物，地点等）。另外如果能够提供完整的关系列表将感激不尽。

PS：我现在正在进行SpaCy实体识别后将识别的实体作为输入实现全流程实体识别和关系抽取，如有所进展愿意分享。

**Comment by tlk-dsg** [comment]
后续会改进，感谢提出宝贵意见
