### ISSUE TITLE
输出的精确率召回率f1值是所有关系的平均效果吗？可以输出每种关系的抽取效果吗？

### ISSUE THREAD

**Issue by touchankawaii** [zjunlp/DeepKE#72]
可不可以对每种关系都输出一个抽取的效果呢
另外还想问一下为什么f1值会出现比P和r都低的情况呢？不应该是P和r的平均值吗？

**Comment by tlk-dsg** [comment]
可修改代码，实现每种关系的效果
f1 = 2*p*r/(p+r)
