### ISSUE TITLE
hydra包报错

### ISSUE THREAD

**Issue by Brodong** [zjunlp/DeepKE#74]
hydra好像不能使用config_path形式了。
报错：
Traceback (most recent call last):
  File "D:/KnowGraph/DeepKE/tools/main.py", line 144, in <module>
    **main()**
  File "D:\Software\conda\envs\KnowGraph3.6\lib\site-packages\hydra\main.py", line 53, in decorated_main
    **config_name=config_name,**
  File "D:\Software\conda\envs\KnowGraph3.6\lib\site-packages\hydra\_internal\utils.py", line 312, in _run_hydra
    **validate_config_path(config_path)**
  File "D:\Software\conda\envs\KnowGraph3.6\lib\site-packages\hydra\core\utils.py", line 266, in validate_config_path
    **raise ValueError(msg)**
ValueError: Using config_path to specify the config name is not supported, specify the config name via config_name.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/config_path_changes

**Comment by Echo0117** [comment]
> hydra好像不能使用config_path形式了。
> 报错：
> Traceback (most recent call last):
> File "D:/KnowGraph/DeepKE/tools/main.py", line 144, in
> **main()**
> File "D:\Software\conda\envs\KnowGraph3.6\lib\site-packages\hydra\main.py", line 53, in decorated_main
> **config_name=config_name,**
> File "D:\Software\conda\envs\KnowGraph3.6\lib\site-packages\hydra_internal\utils.py", line 312, in _run_hydra
> **validate_config_path(config_path)**
> File "D:\Software\conda\envs\KnowGraph3.6\lib\site-packages\hydra\core\utils.py", line 266, in validate_config_path
> **raise ValueError(msg)**
> ValueError: Using config_path to specify the config name is not supported, specify the config name via config_name.
> See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/config_path_changes

我也是一样的问题，后来把版本降到 hydra-core==0.11.3 就好啦

**Comment by Brodong** [comment]
嗯嗯，你的方法也可以。
我将代码改为：
`@hydra.main(config_path="../conf/", config_name="config.yaml")`
然后就可以啦！
