### ISSUE TITLE
error

### ISSUE THREAD

**Issue by misska1** [zjunlp/DeepKE#76]
**Describe the question**
> A clear and concise description of what the question is.

**Environment (please complete the following information):**
 - OS:  mac 
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.
<img width="1115" alt="截屏2021-08-16 下午2 39 13" src="https://user-images.githubusercontent.com/22286006/129521517-9db3f981-a3c0-4223-846b-8f023ba284b4.png">

**Additional context**
> Add any other context about the problem here.

**Comment by misska1** [comment]
so where is your main.py

**Comment by tlk-dsg** [comment]
The problem you meet is not where the main.py is . The real problem is that the hydra-core 's version is too high . You should  reduce the hydra-core 's version to 1.0.6 and then you can run the program.

**Comment by wangcccchen** [comment]
> 

I reduce the hydra-core's version to 1.0.6,but it's still not work. 
![image](https://user-images.githubusercontent.com/70743874/147197210-4141c047-04a6-4de2-8cea-922c5c4f1cd7.png)
![image](https://user-images.githubusercontent.com/70743874/147197257-fdb1ae58-dc16-4e02-8acb-129368834660.png)
![image](https://user-images.githubusercontent.com/70743874/147197308-6e0cc26d-ef60-4595-8ee7-ea8b954d62f5.png)

**Comment by xxupiano** [comment]
Please check if there is the 'hydra-core' or not in your environment by running 'import hydra'. If not, please check if the codes is being run in the correct DeepKE environment.
And we sincerely recommend to run 'pip install deepke' to create the environment.

**Comment by wangcccchen** [comment]
> Please check if there is the 'hydra-core' or not in your environment by running 'import hydra'. If not, please check if the codes is being run in the correct DeepKE environment. And we sincerely recommend to run 'pip install deepke' to create the environment.

1. 我想请问文档中的 pip install deepke和代码readme中的pip install -r requirements.txt是什么关系？两个都需要执行吗？有先后顺序吗？
2. 运行了 pip install deepke，环境中的torch版本是1.10.0，但是在  requirements.txt中 torch版本说的是 1.5,请问torch版本是哪个？还是两个都可以？
期待回复！谢谢！

**Comment by tlk1997** [comment]
> > Please check if there is the 'hydra-core' or not in your environment by running 'import hydra'. If not, please check if the codes is being run in the correct DeepKE environment. And we sincerely recommend to run 'pip install deepke' to create the environment.
> 
> 1. 我想请问文档中的 pip install deepke和代码readme中的pip install -r requirements.txt是什么关系？两个都需要执行吗？有先后顺序吗？
> 2. 运行了 pip install deepke，环境中的torch版本是1.10.0，但是在  requirements.txt中 torch版本说的是 1.5,请问torch版本是哪个？还是两个都可以？
>    期待回复！谢谢！

两个都是可以的
