### ISSUE TITLE
在M1 mac上可以成功运行这个项目吗？

### ISSUE THREAD

**Issue by moon2610** [zjunlp/DeepKE#81]
**Describe the question**
>  在example/re/standar这个例子中，运行run.py，在model(x)处，程序异常中止。

**Environment (please complete the following information):**
 - OS: m1 mac
 - Python Version 3.8

**Comment by tlk1997** [comment]
感谢使用DeepKE，M1 mac不支持低版本pytorch，建议升级pytorch版本使用，可升级至1.8版本。

**Comment by moon2610** [comment]
请问，transformers的哪个版本支持mac m1，谢谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjunlp/DeepKE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月16日(星期二) 晚上9:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjunlp/DeepKE] 在M1 mac上可以成功运行这个项目吗？ (Issue #81)





 
感谢使用DeepKE，M1 mac不支持低版本pytorch，建议升级pytorch版本使用，可升级至1.8版本。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tlk1997** [comment]
> 

现在的DeepKE可能对transformers版本要求比较严苛，需要此固定版本，后续会对代码进行升级，届时将适配更多版本transformers，请后续持续关注

**Comment by moon2610** [comment]
谢谢您的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjunlp/DeepKE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月28日(星期天) 晚上9:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjunlp/DeepKE] 在M1 mac上可以成功运行这个项目吗？ (Issue #81)





   
现在的DeepKE可能对transformers版本要求比较严苛，需要此固定版本，后续会对代码进行升级，届时将适配更多版本transformers，请后续持续关注
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
