### ISSUE TITLE
name 'add_start_docstrings' is not defined

### ISSUE THREAD

**Issue by onechinstu** [zjunlp/DeepKE#82]
**Describe the question**
> A clear and concise description of what the question is.

How can I solve this?

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by Flow3rDown** [comment]
Hello, please check if your transformers version is 3.4.0.

**Comment by onechinstu** [comment]
Ok, thank you very much for your reply




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjunlp/DeepKE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月22日(星期一) 晚上9:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjunlp/DeepKE] name 'add_start_docstrings' is not defined (Issue #82)





 
Hello, please check if your transformers version is 3.4.0.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
