### ISSUE TITLE
您好，请问在nre任务中想要增加实体的类型应该怎么做呢？

### ISSUE THREAD

**Issue by GLORYFeonix** [zjunlp/DeepKE#86]
我尝试将train.txt、valid.txt、test.txt换成自己标注的文件，里面包含了除PER、LOC等示例里的类型之外的一种类型nz。如下图：
![image](https://user-images.githubusercontent.com/50977527/150797528-eda2bcbc-95ab-4a6a-abb8-c4743a93f825.png)
然后我在deepke\name_entity_re\standard\tools\preprocess.py里修改get_labels函数，增加了nz类型。如下图：
![image](https://user-images.githubusercontent.com/50977527/150797776-3242f550-74d2-4e83-a509-e89d08a77380.png)
然后尝试运行Notebook Tutorial中的NER ````Notebook的代码。结果在Evaluate中的`temp_1.append(label_map[label_ids[i][j]])`一步卡住了。因为`label_ids[i][j]`的值为0，而label_map中没有0这个key。

 - OS: windows10
 - Python Version 3.9.9

![image](https://user-images.githubusercontent.com/50977527/150799359-43ce2c6b-dd02-429d-9fd9-9255ec7571be.png)

十分感谢拨冗相助！

**Comment by tlk1997** [comment]
你好，你可以在报错前输出一下label_map看一下这个map里有哪些内容
还有就是在本地修改源码内容的话，notebook里导入包的话，是不会生效的，你得通过python setup.py install的方式在运行example文件夹中run.py才能生效

**Comment by GLORYFeonix** [comment]
> 你好，你可以在报错前输出一下label_map看一下这个map里有哪些内容 还有就是在本地修改源码内容的话，notebook里导入包的话，是不会生效的，你得通过python setup.py install的方式在运行example文件夹中run.py才能生效

 您好，关于label_map我之前已经看过，是一个dictionary，如下：
![image](https://user-images.githubusercontent.com/50977527/150812565-85117a7a-ffa0-42e4-b122-5fdeb283acb0.png)

然后关于本地修改源码的我不是很明白您的意思。我之前没有在preprocess.py的get_labels函数中添加我自己的nz类型时，是会在这之前的train阶段就会报错，错误大概就是没法找到匹配的label。添加了该类型之后这个错误就被修复了。所以按我的理解，这应该是生效了？我看了下该错误前后的代码，大意是调用该路径的preprocess.py中的函数。那我认为直接在本地修改该文件内的函数应该也是会生效的吧？
我的python并不是十分熟练，如果有错，请您不吝赐教。
