### ISSUE TITLE
Fine-tune a model trained on conll2003 for mit-movie/mit-restaurant/other dataset?

### ISSUE THREAD

**Issue by ezflow97** [zjunlp/DeepKE#87]
**Describe the question**

Hi I'm using DeepKE/tutorial-notebooks/ner/few-shot/fewshot_ner_tutorial.ipynb on google colab.

colab notebook link - https://colab.research.google.com/drive/1MVEX1hxciD6803FcbuA1ec8SKj2oXUd_?usp=sharing

I'm training model on coNLL2003 dataset ( step name - Train on CoNLL2003 ) and trying to use this trained model (stored in directory - /content/savemodel)  to fine-tune on few-shots mit-movie dataset.  

Basically I'm trying to reproduce below findings mentioned in LightNER paper. By setting cfg.load_path = '/content/savemodel/conll2003_16_2e-05/best_model.pth'  in Train on few-shot datasets section of the notebook

finds from paper - 
[https://imgur.com/l3zVkcz](url)
[https://imgur.com/Vd2aprP](url)

I'm getting this error after doing above steps  - 
RuntimeError: Error(s) in loading state_dict for PromptGeneratorModel:
	Missing key(s) in state_dict: "prompt_model.prompt_decoder.averge_weights.0", "decoder.averge_weights.0". 
	size mismatch for prompt_model.prompt_decoder.mapping: copying a param with shape torch.Size([6]) from checkpoint, the shape in current model is torch.Size([14]).
	size mismatch for decoder.mapping: copying a param with shape torch.Size([6]) from checkpoint, the shape in current model is torch.Size([14]).

**Environment (please complete the following information):**
 - Python Version  3.7.12

Thank you.

**Comment by Flow3rDown** [comment]
Hi, sorry for bringing you inconvenience, we have updated `fewshot_ner_tutorial.ipynb`, you can try again.
