### ISSUE TITLE
怎么做预测啊？

### ISSUE THREAD

**Issue by huangj268** [zjunlp/deepke#9]
好像只有训练，训练好怎么做预测呢？

**Comment by yuwl798180** [comment]
预测过程和验证过程一样的呀。

你是说单独输入个句子预测的结果吗？
稍后添加个predict文件

**Comment by Lanme** [comment]
这个能一对实体多关系预测的么？

**Comment by yuwl798180** [comment]
暂时不支持多分类，因为上传的采样数据是单类别的。

稍后找下多分类的数据集，采样一批样本，添加多分类的预测代码
