### ISSUE TITLE
vocab文件

### ISSUE THREAD

**Issue by wangcccchen** [zjunlp/DeepKE#91]
您好，在关系抽取任务中，加载数据时根据word2idx等生成了vocab文件，想请问这个文件在后续关系抽取任务中起了什么作用？

**Comment by tlk1997** [comment]
您好，vocab文件为根据所提供数据集所产生的词典，在后续进行预测的时候会再次用到。

**Comment by wangcccchen** [comment]
> 您好，vocab文件为根据所提供数据集所产生的词典，在后续进行预测的时候会再次用到。

谢谢回复，我还想问一下，在应用时，使用胶囊网络进行关系抽取的任务之前，需要先进行命名实体识别吗？

**Comment by tlk1997** [comment]
> > 您好，vocab文件为根据所提供数据集所产生的词典，在后续进行预测的时候会再次用到。
> 
> 谢谢回复，我还想问一下，在应用时，使用胶囊网络进行关系抽取的任务之前，需要先进行命名实体识别吗？

是的，实体都得在进行训练前标注出来
