### ISSUE TITLE
怎么得到每一类别的precision、recall、f1值，而不仅仅是最佳迭代的那次总体训练评分呢？

### ISSUE THREAD

**Issue by zhanghaoxuan1999** [zjunlp/DeepKE#93]
例如做属性抽取，得到的结果是最佳的一次迭代结果的p、r、f1值，我想获得该最佳结果中 每一种属性 的具体得分(p、r、f1和混淆矩阵)，可以添加相关代码吗？

**Comment by tlk1997** [comment]
感谢提议，如需得到你想要的结果，可在https://github.com/zjunlp/DeepKE/blob/main/src/deepke/attribution_extraction/standard/tools/trainer.py中增加代码来计算每一种属性的得分
