### ISSUE TITLE
Why  Toturial Notebook run always wrong !!!

### ISSUE THREAD

**Issue by DingZhaohai** [zjunlp/DeepKE#94]
**Describe the bug**
> A clear and concise description of what the bug is.

ner run wrong: i think i canot run OK.
re run wrong: i think i canot run OK.
……

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by tlk1997** [comment]
What is wrong? And you can try to use source code .
