### ISSUE TITLE
LightNER Datasets not k-shot per entity

### ISSUE THREAD

**Issue by vasilisvyth** [zjunlp/DeepKE#95]
MIT RESTAURANT does not have 10-shot per entity 
for example Location has 23 named entities, for other named entities I see this problem as well and for other datasets.
![image](https://user-images.githubusercontent.com/72560545/158666806-1702a101-b39c-403d-92f4-8062b38a379f.png)

**Comment by Flow3rDown** [comment]
Hi,
First, there are usually multiple entities in a sentence, it's hard to sample precision k-shot data, so we control the total number of samples. The distribution of entity tags in the sample results is the same as the complete original data. The Mit-Restaurant dataset contains most 'location' entity tags, so the sample result as same. Second, note that DeepKE is an open toolkit for knowledge base population, we provide some data for example and you can sample data by yourself. Last, we will update more balanced k-shot data for examples.
Thank you!
