### ISSUE TITLE
python setup.py install过程中遇到的问题

### ISSUE THREAD

**Issue by lelechallc** [zjunlp/DeepKE#99]
**Describe the bug**
> A clear and concise description of what the bug is.
Installed /home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/tqdm-4.60.0-py3.8.egg
Searching for seqeval==1.2.2
Reading https://pypi.org/simple/seqeval/
Downloading https://files.pythonhosted.org/packages/9d/2d/233c79d5b4e5ab1dbf111242299153f3caddddbb691219f363ad55ce783d/seqeval-1.2.2.tar.gz#sha256=f28e97c3ab96d6fcd32b648f6438ff2e09cfba87f05939da9b3970713ec56e6f
Best match: seqeval 1.2.2
Processing seqeval-1.2.2.tar.gz
Writing /tmp/easy_install-o6yke2n9/seqeval-1.2.2/setup.cfg
Running seqeval-1.2.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-o6yke2n9/seqeval-1.2.2/egg-dist-tmp-9u9ef_oj
WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
ERROR: Could not find a version that satisfies the requirement setuptools_scm (from versions: none)
ERROR: No matching distribution found for setuptools_scm
error: Command '['/home/luocheng_lin/anaconda3/envs/deepke/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/easy_install-o6yke2n9/seqeval-1.2.2/temp/tmp0im4dlat', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.

在按照readme安装时候，运行python setup.py install所报的错，请问如何解决

**Comment by tlk1997** [comment]
重新试试，或者pip换一个镜像源

**Comment by zxlzr** [comment]
建个虚拟python 或者anaconda 环境重新试试，可能是python环境问题

**Comment by lelechallc** [comment]
> 重新试试，或者pip换一个镜像源

已尝试用pip install deepke安装了，谢谢

**Comment by lelechallc** [comment]
> 建个虚拟python 或者anaconda 环境重新试试，可能是python环境问题

是在虚拟环境下安装的
